### PR TITLE
rebalances ecom a bit + a score fix

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Fixes LSS score, if this dosnt get merged ill just make a new pr with the singular fix
Drastically increases starter funds of every department
Removes most drip feed free money to help incentives departments paying one a other and using the credit
Marshals/Blackshield still get 1.5k an hour to try and not drain the most played department 
Adds account balance terminal to Preimer room, this allows them to monitor against fraud, see payments and termitate dead accounts and deal with det better

### CODE REVIEW

**Comment by MSieghardt** [comment]
Looks good, both code-wise and change-wise. Departments have no excuse now to say they can't pay for materials/parts.

**Comment by Kazkin** [comment]
I'll have to think about this one.

**Comment by Dopiotl** [comment]
Since trading on Sojourn remains entirely around materials and salvage, even with a miner, you still can't quite convert credits into the nanoforge or into the protolath. 

Lonestar players will always prioritize exclusive departemental items when trading ; they will always goal to use the endless nature of their furnished export shuttle :

As it stands right now, Lonestar will always vastly prefer to trade 18 industrial autolaths and a shovel-type item like nightvisions, ergo grips, water blood bags, the church vendor with weapon blueprints since church items export for so much. Or break in and copy designs from the church factory disk, you only need your PDA for it, just delete the crew records program at 14Go to get a lot more storage space on your PDA, then put all those copied blueprints on an empty data disk obtained at any lonestar print-mat vendor.
Because the export shuttle has no upper limit, and a 4500c for a crate of materials at SI, that's sterile and boring.

If dealing with money, any departments already have to essentially, talk itself out of a hostage situation, when dealing with lonestar, since there are strictly no competitors, and since credits are a meaningless ressource to try and work with.
This pr kinda doesn't do much but reinforces that tenfold, or that is, it's really just the guild and SI since marshals and blackshield won't lose their money drip-feed. If dealing with money.

It's still kinda meaningless to force Si/guild with having to grind for credits, especially if you're not going to remove the income from their blackshield/marshal customers. Since it turns out, trading with marshal/blackshield also is going to be mostly done with items and batteries and meds and ressources. Rather than credits.

Legitimately, whats the difference between lonestar having 200k vs 4 million credits?
Outside of making numbers go up and occasionally providing infinite materials to a department in exchange for making numbers go up, what does lonestar do?
There's a reason why almost every cargo tech / miner goes prospector after a week, they don't do anything.
Turns out, the solution is to legitimately not give a shit that Lonestar makes bank.

I'd like to go on detail about this ; this is just like not giving a shit that "the research is done in under an hour".
Because, in general, not just this pr, worsening the grind over time is toxic and does the opposite of solving anything, it reinforces the problem(s) and pushes players to leave.
As it stands right now, you need autism powers to play guild or SI-
Well, used to. Because right now, the 50% change to SI recently breathed a wide influx of players there. So I can only recommend more of that instead.

**Comment by cdb-is-not-good** [comment]
I do like this change, personally. Though i'd argue for reducing the Marshal/shield hourly income drastically(1500? 2000?). If the funds are already there to pay for their entire daily pay, and anything extra is just there for say ammo, materials, etc - it gives a bit more incentive to get that extra cash that we collect through various means. 
If the account can pay for our hourly, then anything else we collect might go towards something else - extra toys, new gear, etc. 

I'd also add that i don't think this will 'increase grind', really. It will just necessitate consideration - if the Shield want new toys from the guild they might have to go scrounge up some cash by doing stuff for others. If SI wants more materials than they can afford(while still paying hourly) they might just have to sell some design disks or such.

**Pull request merged**
