### PR TITLE
psion sleepy time powers return

### PR DESCRIPTION
**Pull request by ChefDoggo**
## About The Pull Request
<details>
<summary>
	considering the upcoming possible removal of crayon time for psions i wanted to readd a funky power to the cultured organ
</summary>
<hr>

readds peace of mind
changes cost to 4 from 2
	
<hr>
</details>

## Changelog
:cl:

add: readded peace of mind
balance: doubled psion point cost of peace of mind 2 > 4
:cl:

### CODE REVIEW

**Comment by ChefDoggo** [comment]
power to the cancermen

**Comment by cdb-is-not-good** [comment]
Salt pr

**Comment by ChefDoggo** [comment]
> Salt pr

all prs are salt, at least i have the balls to admit it

**Comment by cdb-is-not-good** [comment]
I'm not a huge fan of returning that power in its current state. Fact that you could just passive grab someone and instantly put them to sleep for an extended period was maybe a little too strong- admittedly it is limited to two roles but idk

**Comment by ChefDoggo** [comment]
> I'm not a huge fan of returning that power in its current state. Fact that you could just passive grab someone and instantly put them to sleep for an extended period was maybe a little too strong- admittedly it is limited to two roles but idk

if i knew how i would change it to aggro

**Comment by ChefDoggo** [comment]
hence why i left on maintainers can edit

**Comment by ChefDoggo** [comment]
psiblocking stuff updated at cat request

**Comment by cdb-is-not-good** [comment]
> > I'm not a huge fan of returning that power in its current state. Fact that you could just passive grab someone and instantly put them to sleep for an extended period was maybe a little too strong- admittedly it is limited to two roles but idk
> 
> if i knew how i would change it to aggro

This is a learning experience, then. Look at how other grab-moves check grab level.

**Comment by cdb-is-not-good** [comment]
With that I see no reason to not bring this back. It was a handy power and if the CBO/Therapist is shredded(or drugged up) enough to get you to an aggressive grab you deserve to enter a coma.

**Pull request merged**
