### PR TITLE
RE-removes cargo shuttle

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
removes cargo shuttle
lowers all beacons by 20% as the above shuttle is no longer around

Testing: ran a tester server for runtimes
Performance: Better it has less things now!

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I unironically dont support this as its a church nerf thank you for your time.

**Review by hex37 — APPROVED** [review]

**Comment by Trilbyspaceclone** [comment]
(still waiting on lich for approval)

**Comment by Dongels** [comment]
I also do not approve of this change since it lacks the "Possum seal of approval" like rebel's prs do.

**Comment by cdb-is-not-good** [comment]
> I also do not approve of this change since it lacks the "Possum seal of approval" like rebel's prs do.

image

**Comment by cdb-is-not-good** [comment]
rest in piece shuttle you won't be missed

**Pull request merged**
