### PR TITLE
Payment increase to the people

### PR DESCRIPTION
**Pull request by Rayfod**
We can now finally get more than 2 packs of cigs for 2 hours of work with latency.
Increased the amount that people get paid by 2
This is honestly the most requested change that was made to date.

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Rayfod** [comment]
It was summed up pretty well why this is a good change by Shirumic
> Increase job wages to eris equivilants, make more money available per hour so people are more inclined to actually spend it, and thus people more inclined to actually charge for it.
> https://wiki.cev-eris.com/Roles_ErisEn
> 300 at maximum for nearly all jobs is unfeasible and encourages people to never spend any money ever that they don't make through maint dungeon trawling, meaning less time spent on RP and more time spent grinding for PvE gameplay.

**Comment by cdb-is-not-good** [comment]
Few issues with doing this, right off the bat. Many of the prices are pretty low and account for lowered base wages. Accounts also only have so much money in them. This is a rather sweeping change that lacks consideration for other things. Should a doctor really be able to buy a shotgun every hour? Should a trooper be able to buy four packs of smokes an hour? Should the WO be able to purchase an entire void-wolf mod crate an hour?

**Comment by cdb-is-not-good** [comment]
To clarify, i'm not against raising wages. But a lot more work needs to go into such a change than just straight up raising the wages.

**Comment by IrkallaEpsilon** [comment]
Reminder that hourly pay is paid every 2-2.5 hours depending on latency and some things in the vendors are VASTLY overpriced. . Many Beacon import prices are still beyond good and evil. 3k for a crate of steel comes to mind amongst other things. SI charges up to 800 or even more for revival surgery if they choose so and often deliberately half ass first treatment and do minimal work there. Things get more expensive one would think people would barter more and have more InTerNAl ConFlIcTs but in reality they just game the system harder tbf

**Comment by Rayfod** [comment]
> Few issues with doing this, right off the bat. Many of the prices are pretty low and account for lowered base wages. Accounts also only have so much money in them. This is a rather sweeping change that lacks consideration for other things. Should a doctor really be able to buy a shotgun every hour? Should a trooper be able to buy four packs of smokes an hour? Should the WO be able to purchase an entire void-wolf mod crate an hour?

Also, we get paid every 1-2 hours with the latency we have most of the time on the server.
The answer is YES to all of these questions
A doctor is a very low-action job most of the time, with a limited amount of ways to earn money. I do not see any reason why we should not reward them with payment to take care of themselves.
Troopers...Should be paid enough for 4 packs of smokes
And the WO already have access to the marshal account, so them getting enough for a void wolf mod is not something special.

The negative: Money might be worth a little less, so people might be more willing to charge more
The positive: People will be more likely to charge people for services since it does not cost them their ENTIRE wage for a dinner set.

**Comment by cdb-is-not-good** [comment]
> > Few issues with doing this, right off the bat. Many of the prices are pretty low and account for lowered base wages. Accounts also only have so much money in them. This is a rather sweeping change that lacks consideration for other things. Should a doctor really be able to buy a shotgun every hour? Should a trooper be able to buy four packs of smokes an hour? Should the WO be able to purchase an entire void-wolf mod crate an hour?
> 
> Also, we get paid every 1-2 hours with the latency we have most of the time on the server. The answer is YES to all of these questions A doctor is a very low-action job most of the time, with a limited amount of ways to earn money. I do not see any reason why we should not reward them with payment to take care of themselves. Troopers...Should be paid enough for 4 packs of smokes And the WO already have access to the marshal account, so them getting enough for a void wolf mod is not something special. And it's a good step in the right direction.
> 
> The negative: Money might be worth a little less, so people might be more willing to charge more The positive: People will be more likely to charge people for services since it does not cost them their entire wage for a dinner set.

Ten packs of smokes, actually. An actual gameplay concern at that point, since smoking gives inspiration - but that's not the topic at hand. If you are going to raise EVERYONES wages then I need you to at least go over the prices of assorted things and make an effort to bring them into line. Some stuff will need to be more - some may be less. But I don't personally approve of just giving everyone more money without other considerations. If the other dev staff chime in to the opposite, then I might change my mind - but i'm not a fan of this change on the whole.

**Comment by ThePainkiller** [comment]
Hello, local medic cat man here. Thought I'd chime in with my opinion.

Some points raised in this post are quite valid, when it comes to how much of your own salary it costs for some stuff:

> some things in the vendors are VASTLY overpriced

Insuls being at 600 is a good example, not to mention even the most basic of firearms is an hourly salary as well.

> Many Beacon import prices are still beyond good and evil. 3k for a crate of steel comes to mind amongst other things.

tbh **just considering the mats adressed** this is mostly a non issue considering cargo techs should be racking up profits, and this is balanced in a way that doesn't completely nullifies miner gameplay, making mining a better alternative to straight out importing mats. On the other side, beacon prices are all assuming cargo techs start exporting some stuff as well to unlock better trades and rack up a lot of money, so it's not something you should take your own salary into account on, unless we're talking about /selling/ mats to the usual market rate to anything that isn't Soteria/Guild.

> SI charges up to 800 or even more for revival surgery if they choose so and often deliberately half ass first treatment and do minimal work there.

This is where I wanted to chime in the most. Yes, IrkallaEpsilon's right. Medical treatment in Soteria is **very** expensive when you take Sleepers/Surgery into account as per SOP, not to mention ATK and chems use, which even if taken into the bare minimum of 2 credits per unit still adds up to around 800 to 1200 for most revival surgeries. Even with the grace of the _"first time free"_ treatment for most colonists, there have been various, numerous times in which colonists have been unable to pay entirely their fees. Sum that up with the 800 credit fee for Medevac you have to pay Blackshield if they have to drag you back from the forest/deep maint (which honestly is a literal "stupidity tax" punishment, since you kind of assumed the risks of going there lol), and a person that isn't actively selling things (only possible IF there's cargo present, or if you sell to a specific department that has access to their own budget, like mats you found scavenging to Soteria). There has been times in which, for the sake of the poor dumbass colonist getting into debt for repeatedly dying, I'd discount small things like ATK uses or chemicals used out of the full price for treatment, and I had never charged for a stomach pump/dyalisis before as the price for sleeper use is stupidly high for the sake of a doctor not using the chems they have in hand, which as a doctor is something you should do for the sake of practicality (e.g why use your limited 60u dylo on your belt if you can slap on a sleeper and click a button twice? Save that for when someone arrives dying of toxic shock and you have to stabilize them), but conflicts with the oath of the _"twin traps of **overtreatment** and nihilism"_ since the most practical use **is** the most expensive one (for the patient). ~~But eh, not many medical players are dedicated to the oath anyways so who cares about that~~

> 300 at maximum for nearly all jobs is unfeasible and encourages people to never spend any money ever that they don't make through maint dungeon trawling, meaning less time spent on RP and more time spent grinding for PvE gameplay.

The fairest of points so far, a severe lack of money encourages most, if not all players, being prospector plus as a side job to make meets end, considering examples like Doctors and Roboticists not actually benefitting from cuts from sales as everything they sell must go to the departamental funds rather than their own pocket money. While we **aren't Eris and aren't as focused on every single colonist packing heat for the sake of it**, this is still a valid point nonetheless as it curves the RP factor of the game in lieu of pure mechanical combat/looting for the sake of obtaining credits.

While this does address serious issues concerning colony economy in general and the incentive for spending one's hard earned money, I agree that this will need further testing and balancing **taking every single money spending aspect of the game into account** before merely bumping pay by like 50% just because 250 credits every hour (and half with dilation) isn't enough for you to spend your salary on personal benefits. Perhaps price adjustment on certain things would be fairer balance in terms of colony economy, or perhaps the bumped salary isn't as big of an issue as possible if it's toned down enough. I'd like to hear what others have to say on this too.

**Comment by ThatGuyFromThatPlace** [comment]
2.5x increase? Really? 250%?
My personal suggestion would be a considerably lower increase. This is a really big change to just suddenly WHOMP onto the server without any adjustment to anything aside from the wages.

**Pull request closed without merging**
