### PR TITLE
It's time to get RIIIIIIIIIIIIIIIIIIIPPPPPPPPPPPPPED!

### PR DESCRIPTION
**Pull request by ThePainkiller**
## [WORK HARDER, NOT SMARTER!](https://www.youtube.com/watch?v=ckZlj2p8W9M)

- Refactors waistcoats and sleeveless sweater vests into attachable accessories for jumpsuits (except the Helltaker waistcoat), they can still be worn on the suit slot but no longer have pockets.
- Moves waistcoats and sweater vests into accessory category of loadout, with proper gear selection
- Replaces "laced jackboots" with Duty boots that come in three variants. Sprites originally made by Lamasmaster.

image

- ACOG scope added to basic security disk
- ACOG scope is now craftable on the Guns tab of crafting menu, costs double the materials to make as an incentive to print it through lathe.
- Fixes Corpsman and Trooper half capes being available on capes selection for everyone regardless of job
- Refactors "alurane" body marking icon state into its proper spelling, "Alraune"
- Minor typo fixes on admin messages for players loading/saving characters' messages

- Properly adds the toned body/musculature as a body marking, both female and male versions. [It's time to get **RIIIIIIIIIIIIIIIPPPPPPED!**](https://user-images.githubusercontent.com/1294508/163295817-eface35e-8914-4bff-ae0f-e9cfb5a48d17.png)
### **Don't forget this marking has to have the same skin color as your base body for it to work properly.**

**Male version:**
image

**Female version:**
image

<hr>

This pr closes #3070 as they're effectively one and the same thing, just that it had become too stale so I took my own hands into making it work.

## Changelog
:cl:
add: Added toned muscles as a body marking, both male and female versions. Don't forget to use the same skin color as your character when using it! **IT'S TIME TO GET RIIIIIIIIIIIIIIIPPPPPPPPPPPED!**
add: Replaces laced jackboots with Duty boots, come in three variants: Normal, Long, and Long with Heels! Sprites by Lammaster, original creator of the laced jackboots (so it's an intended change by the original creator)
tweak: ACOG scopes added to basic security disk. ACOG scopes are now manually craftable under Guns tab too.
fix: Fixed everyone being able to take Corpsman and Trooper half capes through cape selection.
imageadd: Added muscular overlays, duty boots sprites.
spellcheck: fixed a few typos on admin messages when a player saves/loads a character or spams these functions.
refactor: Refactors waistcoats and sleeveless sweater vests into accessories, while still being able to be equipped on the suit slot (albeit with no pockets).
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
I'll solve the conflicts as soon as I'm done fetching from master.

**Comment by cdb-is-not-good** [comment]
Not a fan of putting the scope in the sec disk, the original plan was for it to be placed in the H&S station for purchase at a relatively low price.

**Comment by ThePainkiller** [comment]
> Not a fan of putting the scope in the sec disk, the original plan was for it to be placed in the H&S station for purchase at a relatively low price.

I could argue as well that the heavy focus on cargo import/export system has made it an almost relative catch-all replacement for most departments when it comes to obtainability of anything, considering with enough investment cargo can dish out unmakers, Greyson AI's, void wolf gauss coil barrels, and guns in general, making marshal's armory, prospector jobs, and even Soteria having a direct competition over goods, so I'd honestly rather not crowd it more than it already is for the sake of balance.

I also went by the spirit of the [description](https://github.com/sojourn-13/sojourn-station/blob/b64bbce671105082a53b0faefe88b1f5cc664700/code/modules/projectiles/guns/mods/mods.dm#L611) of the item: _"Mass produced, **lathe machined**"_...I thought then that it was meant to be available to be printed at a lathe, eventually, rather than added to a cargo trade station...and since it's a cheap, basic scope with no other detriments nor buffs for guns, I thought the sec disc was at least a decent alternative for its availability outside of the Mosin kit as a basic, generic scope.

**Comment by cdb-is-not-good** [comment]
> > Not a fan of putting the scope in the sec disk, the original plan was for it to be placed in the H&S station for purchase at a relatively low price.
> 
> I could argue as well that the heavy focus on cargo import/export system has made it an almost relative catch-all replacement for most departments when it comes to obtainability of anything, considering with enough investment cargo can dish out unmakers, Greyson AI's, void wolf gauss coil barrels, and guns in general, making marshal's armory, prospector jobs, and even Soteria having a direct competition over goods, so I'd honestly rather not crowd it more than it already is for the sake of balance.
> 
> I also went by the spirit of the [description](https://github.com/sojourn-13/sojourn-station/blob/b64bbce671105082a53b0faefe88b1f5cc664700/code/modules/projectiles/guns/mods/mods.dm#L611) of the item: _"Mass produced, **lathe machined**"_...I thought then that it was meant to be available to be printed at a lathe, eventually, rather than added to a cargo trade station...and since it's a cheap, basic scope with no other detriments nor buffs for guns, I thought the sec disc was at least a decent alternative for its availability outside of the Mosin kit as a basic, generic scope.

My counter is thusly; Just because it's lathe machined doesn't mean they sell the designs for a workhorse scope. I could live with putting it on a disk - but hand crafting? hard no. Remove that and i suppose that's fine.

**Pull request merged**
