### PR TITLE
Add projectile tag to rpg

### PR DESCRIPTION
**Pull request by Chevalt**
Does what it says on the tin, this adds a projectile firing tag to the RPG allowing it to be modded like other projectile guns.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
😨

Won't this allow for silliness like putting a gauss on the RPG?

**Comment by cdb-is-not-good** [comment]
actually, more import and real question. Why? Even if we ignore potentially busted additions won't most mods on the thing be....worthless? It gets 1 shot, it's DEFINITELY not going to be allowed to have an overshooter, and each shot has FAT recoil IIRC?

**Comment by Chevalt** [comment]
> actually, more import and real question. Why? Even if we ignore potentially busted additions won't most mods on the thing be....worthless? It gets 1 shot, it's DEFINITELY not going to be allowed to have an overshooter, and each shot has FAT recoil IIRC?

overshooter uses internal mag so that won't fit

**Comment by benj8560** [comment]
personally against this. You don't need to mod a damn RPG up your already pretty much guaranteeing you win the fight if you land your shot as is. It's also wildly strange for modifications intended for small to medium caliber weapons to fit on one.

**Comment by cdb-is-not-good** [comment]
> > actually, more import and real question. Why? Even if we ignore potentially busted additions won't most mods on the thing be....worthless? It gets 1 shot, it's DEFINITELY not going to be allowed to have an overshooter, and each shot has FAT recoil IIRC?
> 
> overshooter uses internal mag so that won't fit

Still waiting to hear what the point is of this change. Why is allowing an RPG to take mods a desired outcome? what benefit does this have?

**Comment by cdb-is-not-good** [comment]
If I don't get a decent answer to the question i'll be denying this PR.

**Pull request closed without merging**
