### PR TITLE
smoking nerfs?

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Smoking around no smoking signs no longer restores sanity or rest - Unless you have the chainsmoker perk, in that case you dont care
Smoking around smoking area sings give you an additional sanity, as well as a task

### CODE REVIEW

**Comment by Dissentbay** [comment]
there is so many more important things to work on, I can't just not consider this pr a meme

**Comment by faaaay** [comment]
> there is so many more important things to work on, I can't just not consider this pr a meme

the work is already done, it's too late now

but also: yeah, this is weird. what if my character just doesn't care about smoking rules?

**Comment by AysheDaArtist** [comment]
"Smoking around no smoking signs no longer restores sanity or rest"

**based**

**Comment by AysheDaArtist** [comment]
> Also, if my character for example tends to disrespect authority, why should they give a shit if it's a smoking area or not? This is the kind of thing that should be enforced in RP, not dumb mechanical changes that don't make sense. Do the signs project some kind of fucking psionic aura or something??

Same reason *everyone* gets inspiration when they get hurt.  Everyone is just a masochist :V  
Slippery slop to start thinking that everything mechanical has to be tied to RP and vice-versa, I can just as easily write this out as "Your character acknowledges they're smoking in a non-smoking area, badass sure, but you still feel the creeping notion you're doing something wrong." so it balances it out to 0, that simple.

Mechanically speaking, sanity just got added, everyone is smoking everywhere, so mechanically, making it harder to just passively smoke 24/7 is ideal rather than expecting players to just roleplay on a RP server, because no one points out "Hey, you're smoking like ten packs a day to battle your stress, that's pretty bad." or "Hey, this is a non-smoking area."

Now it's mechanical, now it's in the back of your heads "Oh, I don't get anything for smoking here, so I'm going to leave", simple

**Comment by king5327** [comment]
This should be the other way around. Smoking in no-smoking areas should be more insightful.

In any case, I don't think this should be merged.

**Pull request merged**
