### PR TITLE
huntermap redone

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Hunter map redone! - By Guidesa#7987
with tweaks by Trilby
image
image

Testing: Walked around made sure everything at a glance worked
Performance:Smaller map so maybe better

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
This was approved by lich

**Comment by TheSleepyCatmom** [comment]
Is this just the map? Or was this also the changes to jobs or whatever.

**Comment by TheSleepyCatmom** [comment]
I'm too tired. It's just the map. Yeah this is fine.

**Comment by TheSleepyCatmom** [comment]
Actually, did we make sure to turn the announce off on those elevators?

**Comment by Churro55** [comment]
The overall layout goes against our prime map design rule: Dividing the players.
This is even worse for a faction that already gets a low player count, dividing them even further won't be helpful.
In my opinion, this map doesn't look too good and doesn't have the feeling the current one has; it seems more like a vague campsite/shanty town than a Lodge community in the forest for hunting.
The rooms seem to be divided very arbitrarily without convenience in mind at all. The 'security' is non-existant as well.

It has a lot of work put into it and I don't want to sound like tearing away at it but I also really don't think this only not improves but degrades the experience.

**Comment by cdb-is-not-good** [comment]
Im mostly fine on the map, it's definitely more compact but isn't that the entire thing Lich is always on about? Making things closer together so there's more opportunity to actually see people? The current lodge is neat, but it's a LOT of wasted space that players never use. They go between the animals, lodge itself and the exit.

**Comment by Dongels** [comment]
:v trilby did say it was Approved by Lich. So he seems fine with it...based on your arguments.

**Comment by Memedoktor** [comment]
So this is my full look through and talk about it in one go, praise and dislike laid as i work from my way top down.

- Power: I like having the power be extensive though i have concern how fucking out of the way it could be for any lodge that spawns in the commons area to the south unless the solars are already turned on which i doubt. The new power sources could be nice especially with greater consumption though it feels like we could turn into a logging camp depending on the power requirements

- Trash area: Given if my understanding is correct that we're being moved to the east of the colony away from our plains then this is a fucking god send since having to run to the scrap haven was the only way we got any levels of materials that weren't directly grown or ripped out of carcasses its a bit annoying being so far from the armory but beyond that no complaints

- Huntmaster: I fuck with the new design of the office a fair bit though its kinda hard to see in any real resolution. I do wish it guaranteed the privacy of a vault door or the like  and perhaps a bit more room could be spared with all that rock to the south but hey a pr for that can be done after a while of getting to feel it out.

- Bookroom: small and cozy we could use a bit bigger of a table for us to play cards or d20 in. I feel like its location is super fucking out of the way though and honestly would be better served being swapped with faith.

- Cryo: So it looks alright:tm: but i can't really see to clearly on a bit of it so i don't have a ton to say.

- Faith: So i feel like this spot here is a bit unneeded honestly, not to say that hunters can't be of the faith or anything but with our relocation and access to the colony being made easier i feel like a quick run to the colony for any religious hunter to handle their absolutionist needs. And any religious matters they have beyond that i feel could be done within the privacy of their own rooms.

- Medical: By far an up and improvement directly across from the gate means it isn't a fucking Olympic run when you're pulling a hunter that got to friendly with a render. It seems we have some new things to work with which i'm thankful for beyond that i don't have much to say i'd defer to herbalist mains on their opinions. (ps give us a bottle of prosurgeon for self surgery jk jk)

- Garden: Huge W for herbalist mains a ton of space to work with and water crops including some indoor areas is super nice, i swear im gonna learn how to make a pill press and put one in here you mark my words.

- Crafting armory: Again kinda hard to see what all is in it but it looks like we have access to a grip of the tools we normally would have to go out of our way to craft and i fuck with that especially as someone who enjoys some bow use from time to time. Possible big W would need better resolution for further comments.

- Upper commons: I feel like this bit here is a bit way to fucking far and out the way, its aesthetically beautiful and real work has clearly been put into it but it feels so out of the way that no one would want to be there for much any reason other than that might be where spawned in if there are even spawns there. It feels like it was put there cause there was just a ton of negative space between cryo and power.

- Lower commons: By far one of the biggest stars of this rework its a bit hard to see parts here and there but as a whole from what i can see it looks like a fucking dnd Ranger's commune and i love it, it gives the feel of some hunters having cleared some forest and erected some cabins for lodging till they move off to their next prowling area. Though i wish we were given those multiple personals cabins that there had been talk of in the past i think that would be really nice.

**Comment by Guidesu** [comment]
> 
> I supposed you never played as church but anyone who spawns who are an Absolutism that is not vector or prime can't do any rituals that is required to be on the clergy. So that means even if you are a churchie and is not a factorial or whatsoever you cannot do anything with it at all and you are still totally dependent at the colony current working clergy. So that is there to fill a RPing purpose and aswell if a hunter manages to get a devout upgrade actually manage to do their little church things like fixing other members of faith cruciform if there's more than one in there. But that requires to interact with the colony first.

But aside that I will make a PR later if this gets approved to spare the poor soul of trilby. And will do further changes

**Comment by Memedoktor** [comment]
> > I supposed you never played as church but anyone who spawns who are an Absolutism that is not vector or prime can't do any rituals that is required to be on the clergy. So that means even if you are a churchie and is not a factorial or whatsoever you cannot do anything with it at all and you are still totally dependent at the colony current working clergy. So that is there to fill a RPing purpose and aswell if a hunter manages to get a devout upgrade actually manage to do their little church things like fixing other members of faith cruciform if there's more than one in there. But that requires to interact with the colony first.
> 
> But aside that I will make a PR later if this gets approved to spare the poor soul of trilby. And will do further changes

Fair enough i suppose though yeah i've not touched the church once nor any real plans too i just feel as if its space that had been put to something that isn't super important to the lodge and its identity and especially in a place that feels like it could be used for something else, even more so with the fact it is right next to medical and the armory.

**Comment by TheSleepyCatmom** [comment]
> Actually, did we make sure to turn the announce off on those elevators?

Still need an answer to this.

**Comment by Memedoktor** [comment]
SO after having gone in to look at it in game. New gripes just dropped.

1. why do we have lonestar lockers with headsets in them with the encryption keys. Including the chef lockers which give us 2 sharpening blocks that feels like an oversight and 3 miles.
2. why do we have so much free shit for no reason? we have toolboxes with advanced tools in them as well as disk for literally anything we could ever want
3. I really am not to big a fan of just giving like 12 copies of the armor out as it feels like it takes away from the crafting of your own gear what i feel gives it personality of you preparing for the hunt. Instead its now just grab premade guns grab armor and run for loot spots. A lot of the spirit feels taken out with that.
4. I **really** dislike the Hunt master having no way to secure their office. the fallen empress shotgun can literally just get speedrushed at by anyone and taken to get lost or whatnot without any protection.
5. the tatonka pen feels really cramped for how much we breed them in comparison to the absolutely massive Cerberus pen.

**Comment by Guidesu** [comment]
> > Actually, did we make sure to turn the announce off on those elevators?
> 
> Still need an answer to this.

Yes trilby did

**Comment by TheSleepyCatmom** [comment]
> SO after having gone in to look at it in game. New gripes just dropped.
> 
> 1. why do we have lonestar lockers with headsets in them with the encryption keys. Including the chef lockers which give us 2 sharpening blocks that feels like an oversight and 3 miles.
> 2. why do we have so much free shit for no reason? we have toolboxes with advanced tools in them as well as disk for literally anything we could ever want
> 3. I really am not to big a fan of just giving like 12 copies of the armor out as it feels like it takes away from the crafting of your own gear what i feel gives it personality of you preparing for the hunt. Instead its now just grab premade guns grab armor and run for loot spots. A lot of the spirit feels taken out with that.
> 4. I **really** dislike the Hunt master having no way to secure their office. the fallen empress shotgun can literally just get speedrushed at by anyone and taken to get lost or whatnot without any protection.
> 5. the tatonka pen feels really cramped for how much we breed them in comparison to the absolutely massive Cerberus pen.

All of this will need changed generally. I don't mind the pens that's whatever. Having a ton of guns and armor is a no. Having no way for the Huntmaster to secure their equipment is no. Lonestar lockers are especially a no. Advanced tools are *doubly* no.

Also, the Absolutism altar will need to be removed.

**Comment by Guidesu** [comment]
> SO after having gone in to look at it in game. New gripes just dropped.
> 
> 1. why do we have lonestar lockers with headsets in them with the encryption keys. Including the chef lockers which give us 2 sharpening blocks that feels like an oversight and 3 miles.
> 2. why do we have so much free shit for no reason? we have toolboxes with advanced tools in them as well as disk for literally anything we could ever want
> 3. I really am not to big a fan of just giving like 12 copies of the armor out as it feels like it takes away from the crafting of your own gear what i feel gives it personality of you preparing for the hunt. Instead its now just grab premade guns grab armor and run for loot spots. A lot of the spirit feels taken out with that.
> 4. I **really** dislike the Hunt master having no way to secure their office. the fallen empress shotgun can literally just get speedrushed at by anyone and taken to get lost or whatnot without any protection.
> 5. the tatonka pen feels really cramped for how much we breed them in comparison to the absolutely massive Cerberus pen.



> > SO after having gone in to look at it in game. New gripes just dropped.
> > 
> > 1. why do we have lonestar lockers with headsets in them with the encryption keys. Including the chef lockers which give us 2 sharpening blocks that feels like an oversight and 3 miles.
> > 2. why do we have so much free shit for no reason? we have toolboxes with advanced tools in them as well as disk for literally anything we could ever want
> > 3. I really am not to big a fan of just giving like 12 copies of the armor out as it feels like it takes away from the crafting of your own gear what i feel gives it personality of you preparing for the hunt. Instead its now just grab premade guns grab armor and run for loot spots. A lot of the spirit feels taken out with that.
> > 4. I **really** dislike the Hunt master having no way to secure their office. the fallen empress shotgun can literally just get speedrushed at by anyone and taken to get lost or whatnot without any protection.
> > 5. the tatonka pen feels really cramped for how much we breed them in comparison to the absolutely massive Cerberus pen.
> 
> All of this will need changed generally. I don't mind the pens that's whatever. Having a ton of guns and armor is a no. Having no way for the Huntmaster to secure their equipment is no. Lonestar lockers are especially a no. Advanced tools are _doubly_ no.
> 
> Also, the Absolutism altar will need to be removed.

I gave huntmaster an airlock with his perms but I think trilby removed it on her version

Oh that? Shit I forgot to remove it lmao. I was just messing around trying to have idea how to fill the empty shelfs.

Also... where..? I don't recall giving them a Lonestar chef locker or whatever?

The guns and armors are fair I was just trying to have a general idea of what put what

**Comment by WatermelonsEverywhere** [comment]
- Currently the Laser Boltgun keeps the map offset permanently, always making it look like it's one tile higher than it really is.

- Regular farm animals like pigs and cows can open doors whereas lodge animals like tatonkas, cluckers and so on cannot, so the regular animals can escape their pens and wander around freely.

- There's a double-wall separating the regular animal pen and the Tatonka pen, it feels like it could be cut a bit so the Tatonka pen can be expanded slightly, right now it's the most cramped pen of all and it could get annoying if trying to farm for Tangu.

**Comment by WatermelonsEverywhere** [comment]
To illustrate what I mean with the Laser Boltgun:

- Standing
image
- Dropped item
image
- Can't grab it from here, it's actually another tile down.
image

**Comment by WatermelonsEverywhere** [comment]
As a final comment, I ran this map on a local server and turned on the solars, they tracked the sun, but the console showed 0W generated even after giving it time to update, I'm not sure if this was caused by my local server being set up wrong or if it'll persist on a live server, something worth looking into.

**Comment by Trilbyspaceclone** [comment]
Power is tested to work its just soloars dont get perfect power based on the sun and its intracting

**Review by hex37 — APPROVED** [review]

**Review by TheSleepyCatmom — CHANGES_REQUESTED** [review]
> > SO after having gone in to look at it in game. New gripes just dropped.
> > 
> > 1. why do we have lonestar lockers with headsets in them with the encryption keys. Including the chef lockers which give us 2 sharpening blocks that feels like an oversight and 3 miles.
> > 2. why do we have so much free shit for no reason? we have toolboxes with advanced tools in them as well as disk for literally anything we could ever want
> > 3. I really am not to big a fan of just giving like 12 copies of the armor out as it feels like it takes away from the crafting of your own gear what i feel gives it personality of you preparing for the hunt. Instead its now just grab premade guns grab armor and run for loot spots. A lot of the spirit feels taken out with that.
> > 4. I **really** dislike the Hunt master having no way to secure their office. the fallen empress shotgun can literally just get speedrushed at by anyone and taken to get lost or whatnot without any protection.
> > 5. the tatonka pen feels really cramped for how much we breed them in comparison to the absolutely massive Cerberus pen.
> 
> All of this will need changed generally. I don't mind the pens that's whatever. Having a ton of guns and armor is a no. Having no way for the Huntmaster to secure their equipment is no. Lonestar lockers are especially a no. Advanced tools are _doubly_ no.
> 
> Also, the Absolutism altar will need to be removed.

I still need these things done before this gets merged.

**Comment by TheSleepyCatmom** [comment]
And also, addendum, to fix the pixel shifted items. Don't pixel shift objects you intend to move around, it will break them.

**Comment by Guidesu** [comment]
> And also, addendum, to fix the pixel shifted items. Don't pixel shift objects you intend to move around, it will break them.

image
Can in a next PR replace the farm bot with this little fellaw?

**Comment by Trilbyspaceclone** [comment]
image

**Review by TheSleepyCatmom — COMMENTED** [review]
On a glance this looks better. Please get someone to test it in play to make sure it functions right and that the advanced tools are poof and we're good.

**Comment by cdb-is-not-good** [comment]
I'll be testing this myself when I get home to make sure there's no more erroneous placements or mapping errors. So long as its clear it aught to be good to merge

**Comment by cdb-is-not-good** [comment]
Did a review. 



image

 mapping issue, no reason to have a door here if it's going to go right into a rack. Additional issue - why is the lodge getting a handmade bullet crafter? we gave that to the prospectors because they had a reason to have it, but for the lodge this only trivializes their ability to create ammo for their bone rifles - which is already FAIRLY easy, I dont think this should stay.  

Their starting materials also  seem to be higher which I am- ambivalent about, personally.

image

fewer bolt lances is- not the end of the world, but I don't know how many people will ACTUALLY use these handmade weapons when they compare so poorly to their actual - fairly high end gear. Seems wasteful, but fluff is fine.

image

I know this is a standing issue but - but wood....wood walls...for a gate, they are so ridiculously easy to defeat.

Small other thoughts; the star striker on the wall looks cool and all but is....i mean you can't put it back, why not place it in a storage case a la the Premiers gun? 

image

Medical area...why are they getting an organ printer? I know it's a small thing that makes relatively little difference but Im not a huge fan of putting one here, i get that the idea is to allow them access to such a thing in the event they need to replace an organ without going to the colony but....ehhhh- there's a REASON no one in the lodge has the surgery talent. 

Herbalism area, mostly good - I dont like giving them plant genetics stuff though, that seems like another little thing that's unnecessary for them to receive and that will only trivialize an already fairly....small, and easy part of their setup.  Additionally, why the xenoflorists lockers? That gives them some stuff they aught not to have, these should be replaced with crates with the necessary stuff. 
image


cooking area, amazing. Love it, love the inclusion of oil. Good change.

Trash area- ehhhhhhhh....primary smelter....why.....recycler? BIG why They don't need refined scrap, it's basically worthless for them to be able to produce, I'll concede to the smelter because they already have access to an industrial fab so this is just a small QoL thing, but still.


Overall, I personally think these above points NEED to be addressed as some of them are rather problematic, but given all the approvals are in place I'll merge this now and recommend that adjustment be done at a later date @Guidesu

**Pull request merged**
