### PR TITLE
Revert "Makes the Akula tail fit non-Akula bodies." because Sojourn doesn't have a functioning layer system.

### PR DESCRIPTION
**Pull request by LiteralMushroom**
Reverts sojourn-13/sojourn-station#3920

the tail fucking goes over clothes
why do we not have a functioning layer system???

Why did I not realize this before the original PR got merged? Because I was dumb and only looked at the naked sprite.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
there's a switch tail layer verb. Did you try that first?

**Comment by LiteralMushroom** [comment]
> there's a switch tail layer verb. Did you try that first?

it
goes over clothes in character setup

**Comment by cdb-is-not-good** [comment]
> > there's a switch tail layer verb. Did you try that first?
> 
> it goes over clothes in character setup

That doesn't really answer my question. Got a picture of the thing?

**Comment by ThePainkiller** [comment]
> there's a switch tail layer verb. Did you try that first?

The switch tail layer verb does not work as it was poorly ported without taking into consideration that it applies to ORGANS and not character markings, which are two different things. I can attest to it never having worked, ever.

**Comment by cdb-is-not-good** [comment]
> > there's a switch tail layer verb. Did you try that first?
> 
> The switch tail layer verb does not work as it was poorly ported without taking into consideration that it applies to ORGANS and not character markings, which are two different things. I can attest to it never having worked, ever.

weird- it works for me but admittedly it does very little other than make the tail appear over the backpack layer which ...barely matters.

**Comment by LiteralMushroom** [comment]
> > > there's a switch tail layer verb. Did you try that first?
> > 
> > 
> > it goes over clothes in character setup
> 
> That doesn't really answer my question. Got a picture of the thing?

Capture

significantly less noticeable if you're naked
which is why I didn't realize it was a Problem until now

**Review by Trilbyspaceclone — APPROVED** [review]

**Pull request merged**
