### PR TITLE
Adds new mini-room at the lowest maints

### PR DESCRIPTION
**Pull request by CactusMouth**
] Adds a Xeno Storage room in lower maints for all those non-prospies to have a go at.

image
 
Requested earlier by the many legends that don't play Prospector.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
you should use rng spawners rather then hard spawn xeno types

**Comment by CactusMouth** [comment]
> you should use rng spawners rather then hard spawn xeno types

Plan to do so tomorrow, then should be mostly fine. Cheers/

**Comment by cdb-is-not-good** [comment]
completely blanked on this, will test rq and get it in if there's no issues.

**Comment by cdb-is-not-good** [comment]
seems fine. I might suggest adding something more to encourage folks to care about this potentially very dangerous room but other than that it seems fine .

**Pull request merged**
