### PR TITLE
The cooking rework, PART 1

### PR DESCRIPTION
**Pull request by hex37**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Small PR- reworks all of cooking, no big deal.

All sprite work and logos done courtesy of @Rimruler (Discord: Rimruler#4104)

Sound design courtesy of Emi (Discord: OorthianEmissary#3201) and @Rimruler 
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
holy shit thats a lot of commits

**Comment by hex37** [comment]
> holy shit thats a lot of commits

And it's not going to get any better!

**Comment by Memedoktor** [comment]
Just want to say keep up the good work i look forward greatly to how this goes

**Comment by hex37** [comment]
I got the basic code out for making reagents (like frosting) from the cooking process

The Oven has been added, and is currently getting tested

All cooking appliances now periodically run a cooking check while the food is cooking. It reduces the quality manually if left on too long.

All current appliances now run scans on themselves and people around them

**Pull request merged**
