### PR TITLE
Renames and adds back numerical garbs

### PR DESCRIPTION
**Pull request by Noobetski**
## About The Pull Request
<details>
<summary>
	Renames numerical hat to absolute leather hat and numerical garbs to surtout
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

add: Added ex-numerical clothes back
tweak: Renamed numerical garbs and hat
:cl:

### CODE REVIEW

**Comment by Noobetski** [comment]
hol' on, 2 last commits didn't save for some reason

**Comment by du-top** [comment]
What's wrong?

**Comment by Noobetski** [comment]
yes

**Comment by Noobetski** [comment]
wait can i just

**Pull request closed without merging**
