### PR TITLE
Carpediem buff, recommended by Rain Chule

### PR DESCRIPTION
**Pull request by Noobetski**
## About The Pull Request
<details>
<summary>
	Buffed damage and reduced fire delay
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

balance: buffed carpediem

/:cl:

### CODE REVIEW

**Comment by Noobetski** [comment]
i did an error

**Comment by Noobetski** [comment]
alright, should be good now

**Comment by cdb-is-not-good** [comment]
+5 damage, +10 AP, 50% firerate increase - in total. Not a huge buff, imho will need actual gameplay testing to know if it's worth keeping. Recommend a testmerge on it.

**Comment by cdb-is-not-good** [comment]
Also when  making these kinds of actual balance changes please put the exact changes in an easy to read form. Not everyone is going to read the files changed and understand exactly what is changed.

**Pull request merged**
