### PR TITLE
Rebalances nanogate inspiration

### PR DESCRIPTION
**Pull request by Legate-Maxson**
Correctly changes inspiration gain to 50% from 25% like it is labelled in the tool tip for the nanogate perk.

### CODE REVIEW

**Comment by Stutternov** [comment]
hhrmn........ technically this _does_ make the wording correct.........

**Comment by Trilbyspaceclone** [comment]
`Those with a nanogate find it far more difficult to become inspired`
 im failing to see were it says 25% or 50%

**Comment by Legate-Maxson** [comment]
> 

This dude went and changed the wiki

**Comment by Trilbyspaceclone** [comment]
What?

**Comment by Dissentbay** [comment]
huh, I always thought it was 30% since nanogates were added

**Comment by Trilbyspaceclone** [comment]
I do not think that raising the amount of inspriation for nanogates without other drawbacks is good for balance.
Sorry

**Pull request merged**
