### PR TITLE
I HATE THE VOX I HATE THE VOX

### PR DESCRIPTION
**Pull request by Yawet330**
YOU SHOULD SPEEDMERGE THIS, NOW

For real, this fixes several critical bugs that Niko's AI changes brought

Like them shooting 3x per second.

And attacking. 3x per second.

And moving faster than they should.

## Changelog
:cl:
fix: Birbs fixed. And nerfed
/:cl:

### CODE REVIEW

**Comment by Yawet330** [comment]
If you need more evidence of this, go to dev general or issue reports.

Mobs overall are VERY fucked and having them process 3x faster with no safeguards was a POOR mistake.

T. greyson bots doing la funny again...

**Comment by BurpleBineapple** [comment]
This doesn't actually fix the issue of ranged mobs attacking too frequently, to note. Just decreases the health of birds in particular.

The current issue is a much larger issue that applies to all ranged mobs. Greyson mobs, Void Wolf mobs, Forest Birds, etc.

**Comment by cdb-is-not-good** [comment]
Changelog not detailed and the actual changes are different than what you did describe.

**Comment by Yawet330** [comment]
> Changelog not detailed and the actual changes are different than what you did describe.

This was fixed in the discord anyway. This was just a stop-gap for prospectors.

**Pull request closed without merging**
