### PR TITLE
Some untested and unfinished event stuff

### PR DESCRIPTION
**Pull request by Kazkin**
-Add a potential check for excelsior turrets that now check if you are excelsior faction. This should prevent the turrets from shooting excelsior npcs.
-Excelsior turrets buffed to 300 hp and added a preloaded version with 160 bullets loaded in.
-Added Gloria.
-Modified the space fortress map into an excelsior fortress, the mechanics and visual aspect is finished, but requires extensive testing.
--Verify all turrets are working.
--Verify lighting is working.
--Verify the anti-matter engine can be built and doesn't give off weird alarms when exploded.
--Verify all visual aspects look nice.
--Verify all shields can be powered on and work as required.
--Verify the land mine in the depot can be picked up and used without exploding.
--Verify turrets do not shoot excelsior npcs.
--Verify the lockers in dorms have the appropiate clothes.
--Modify map code to make the map the correct size.
--Verify the base is auto powered through map variables.

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
This approved by lich?

**Comment by r4d6** [comment]
I just did a PR to change some tiny stuff to the map here : https://github.com/Kazkin/sojourn-station/pull/1

**Comment by r4d6** [comment]
I can verify that, at least on my end, lighting was _**fucked**_ and that the antimatter engine worked just fine.
Also the excelsior shields don't start anchored.

**Comment by r4d6** [comment]
I managed to fix the lighting issues and updated [the PR](https://github.com/Kazkin/sojourn-station/pull/1) with the fixes.

**Comment by r4d6** [comment]
Also the turret work fine.

**Pull request merged**
