### PR TITLE
Fembots and Femboybots

### PR DESCRIPTION
**Pull request by MSieghardt**
From Skyrat. Started as a joke, became a reality.

Adds fembots and femboybots. 

Tested on my server, things work just fine (not that much can break here)

https://github.com/Skyrat-SS13/Skyrat13/pull/2709 This is what I pulled them from. Flynn requested them.

### CODE REVIEW

**Comment by Kazkin** [comment]
Funny as this is, its a bit too sexual for a general purpose bot. Gonna have to decline on it for now but I'll leave it open in case changes wanna be made.

**Comment by benj8560** [comment]
I'd like to point out legit Polaris a none ERP sever has ported these kek. Also on that note polairs has a hole pile of bot sprites they have ported/made over the years might be a better place to start also some that are cute robit girls without being overly sexual.

**Comment by MSieghardt** [comment]
Yes, this is *very* sexual. I could turn them into new cyborgs but that's more work than I'm willing to slap into a joke. Flynn requested them, I PR-ed them. Feel free to close it, I'll fix the cyborgs a bit more in the future before I actually port some good sprites.

**Comment by Trilbyspaceclone** [comment]
I wish I could close it

**Pull request closed without merging**
