### PR TITLE
mining update part 2 (point vendor + ore stacking fixes)

### PR DESCRIPTION
**Pull request by lolman360**
minor stack refactor
large trashbags hold 25% more since bluespace trashbags exist
adds mining points and point vendor (not mapped in)
ore boxes now pick up ore when dragged over it, like fat satchels
better mining tools give increased yield from hitting rocks 
mining tool power adjustments (greyson jackhammer digging 60 >> 75)

## Changelog
:cl:
refactor: minor stack refactor
balance: large trashbags hold 25% more since bluespace trashbags exist
balance: mining satchels can now hold up to 120 ore (1 full stack)
add: adds mining points and point vendor (not mapped in)
fix: ore boxes now pick up ore when dragged over it, like fat satchels
balance: better mining tools give increased yield from hitting rocks 
balance: mining tool power adjustments (greyson jackhammer digging 60 >> 75)
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
How significant is the increased yield?

**Comment by r4d6** [comment]
Why add mining points and a mining point vendor, when miners already get like a 10-20% cut on everything they mine?

**Comment by cdb-is-not-good** [comment]
I would suppose it's to reward miners for their work especially when they go, mine - and promptly get told "lol" when no one is around to actually purchase the materials. More of a departmental commissary?

**Comment by cdb-is-not-good** [comment]
Gonna merge this for now, but we may tweak the values for balance reasons as we move forward.

**Comment by lolman360** [comment]
> How significant is the increased yield?

roughly 12-15% per tool upgrade, capping out at around 60-75% at G-P jackhammer tier

**Pull request merged**
