### PR TITLE
Career Tweak: Intelligensia Cannot be Hunters + Buff

### PR DESCRIPTION
**Pull request by OliOliOnsiPree**
## About The Pull Request

What this PR does is makes Intelligensia not allowed to be Hunters or Hunt Master.
Due to Moon saids it might need a buff in the future I added ten instead of five for the gains.

## Changelog
:cl:
Tweak: Intelligensia is not hunters/hunt master
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Whats the reasoning for this?

**Comment by OliOliOnsiPree** [comment]
> Whats the reasoning for this?

so in the code it states: 
	"You lack of physically capability also makes you ineligible for the colony security forces or as a prospector (except salvager), further locking you into your role as an intellectual."
Which a hunter / hunt master is a physically capability job.

**Comment by cdb-is-not-good** [comment]
I suppose that's fair, we may perhaps want to buff intelligensia in the future due to all the ....jobs it locks you outta, but hey this is probably fine.

**Comment by OliOliOnsiPree** [comment]
> I suppose that's fair, we may perhaps want to buff intelligensia in the future due to all the ....jobs it locks you outta, but hey this is probably fine.

Yeah they have alot of jobs they get locked out of more then naramad I think. But it's the thinking tank "origin" so it slightly makes sense.

**Comment by cdb-is-not-good** [comment]
Yea this is fine as it stands. +1

**Pull request merged**
