### PR TITLE
Adds in the clothing for the Matriarch + update skinning knife icon

### PR DESCRIPTION
**Pull request by intense-skies**
Adds in a a Matriarch cape, admin spawn only. Fits in the hat slot since Jea normally doesn't wear one
Also provides new icon and updates the skinning knife to use it (old one still in files).
**Sprites done by BladeburstNINJA#9500**

### CODE REVIEW

**Comment by intense-skies** [comment]
Finally did it right this time thank you god.

**Comment by ThePainkiller** [comment]
Woah those are some nice stats for a "headgear". Have you thought about making it an actual attachable accessory so you can wear it over a normal suit instead?

**Comment by r4d6** [comment]
> Woah those are some nice stats for a "headgear". Have you thought about making it an actual attachable accessory so you can wear it over a normal suit instead?

Well, can accessories even **give**armor ?
And in any case, this is an admin-only item designed for the leader of a faction.

**Comment by Kazkin** [comment]
Given it only armors the head, I'm  fine with it.

**Pull request merged**
