### PR TITLE
Replaces the Spider Outpost with an underground Spider Cave

### PR DESCRIPTION
**Pull request by SingingSpock**
## About The Pull Request
<details>
<summary>
	Spider Outpost collapses into the ground, exposing the spider cave that was beneath it!
</summary>
<hr>

Screenshot 2024-02-01 152941

Screenshot 2024-02-01 152956

Replaces the spider outpost with a spider cave, which had sometimes been said to be beneath it in the past. This cave is on the Underground 1 level, and has some mineable rock that leads to the colony's maintenances. This gives the colony a second entry point via mining into maints, which is good for allowing hostile outsiders to actually do something other than die in the meadow as they fail to get into the colony proper.

I tried to balance the loot and loot types against the amount of mobs, but it might be a bit off. I tried to err on the side of less rather than the side of more.
<hr>
</details>

## Changelog
:cl:
map: Replaces the Spider Outpost with an underground Spider Cave
/:cl:

### CODE REVIEW

**Comment by SingingSpock** [comment]
Accidentally undid someone else's changes, let me see if I can fix that. Don't merge yet.

**Comment by SingingSpock** [comment]
There we go

**Comment by cdb-is-not-good** [comment]
Giving until Monday for Chev and co to properly resolve the event they did halfway, if they dont by then i'll merge this.

**Review by Support-hells-angels-bitch — CHANGES_REQUESTED** [review]
Listen linda

**Comment by Support-hells-angels-bitch** [comment]
Listen Linda Reddog wants to talk with Tracy, checkmate!!

**Comment by cdb-is-not-good** [comment]
I may ask you to make some tweaks to this, but i wanna see it in play first. With this new, fairly larger breach now present I might suggest bolting the doors and stapling a 'DO NOT TRESSPASS' sign on the outside as well as  either offering better camera coverage of the east/west mountain soft spots or simply removing those entryways since there's now a far better way in/out(illegal style). Mostly just so the colony isn't a hilarious sieve in terms of security holes

**Comment by cdb-is-not-good** [comment]
Right off the bat, those rare gun spawns are a BIT much for an area that's just got a few spiders in :p

**Comment by SingingSpock** [comment]
> Right off the bat, those rare gun spawns are a BIT much for an area that's just got a few spiders in :p Specifically, the energy_weapon spawn at the south-east corner, the dungeon_energy_gun spawn at the north east. AFAIK the spider outpost didn't have any spawns that weren't cheap spawners.

I'll get on that in the morning. I don't actually know what guns are in each spawn, it isn't really well labeled how good each one is.

**Comment by cdb-is-not-good** [comment]
Think this is good for now, I've a few tweaks I wanna make but that's probably better suited to its own PR due to *what* i wanna do. In the future for these kinds of over-hanging thiings I'd probably suggest using latice+catwalk(after all, it's cheaper to produce :p)

**Pull request merged**
