### PR TITLE
Fixes perk-based damage mods, adds ablative subdermal armor

### PR DESCRIPTION
**Pull request by Xaytan**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Fixes brute and burn damage modifiers from perks. 

Adds an alternative version of subdermal armor that reduces burn damage.

Full list of things that were nonfunctional prior to this change

Cow Skin Mutation
Gigantism Mutation
Thick Fur Mutation
Dwarfism Mutation
Revival Sickness
Aulvae Decohesion Syndrome
Nanofiber Muscle Therapy
Natural Armor
Thin Skin
Ra Cht'mant
Monomial Bulwark of Harmony
Ironskin draught

	
<hr>
</details>

## Changelog
:cl:
fix: Perk based damage modifiers will now properly apply to damage taken.
fix: Adds ablative subdermal armor.

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
This adds in additional issues
Subdermal armor *does infact work*

**Comment by cdb-is-not-good** [comment]
Don't close PRs for "having issues" without specifying what issues

**Comment by benj8560** [comment]
I can quote trilby on subdermal armor working just fine as is. Its handled limb by limb making it fully body protection like this from a single implant slot is pretty massive balance wise. It's already quite good.

**Comment by Xaytan** [comment]
> I can quote trilby on subdermal armor working just fine as is. Its handled limb by limb making it fully body protection like this from a single implant slot is pretty massive balance wise. It's already quite good.

We've already discussed it and tested it. Trilby had told me it wasn't working the other day, but apparently that was a joke.

The other change in this PR still needs to happen.

**Comment by cdb-is-not-good** [comment]
> > I can quote trilby on subdermal armor working just fine as is. Its handled limb by limb making it fully body protection like this from a single implant slot is pretty massive balance wise. It's already quite good.
> 
> We've already discussed it and tested it. Trilby had told me it wasn't working the other day, but apparently Trilby thinks it's funny to say bugs exist that she knows don't.
> 
> The other change in this PR still needs to happen.

Amazing, simply fantastic.

**Pull request merged**
