### PR TITLE
Perk Icons

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Readds perk icons that were commented out alongside the updated stats and perks tab from actual Eris.
shork
While most of these are still just base Eris icons I made a lot of my own for the races and what else have you we have over them (granted of varying quality)
E10
Also new shark pool safety poster which is well located in the pool near lockers.
shark

<hr>
</details>

## Changelog
:cl:
add: Shark poster to pool
imageadd: Perk icons from races to nanogate
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Some of these are a lil....eh- Make the  Naramad one not a meme and work on the Kriosan/Sablekyne/Mar'Qua ones. Mar'Qua aren't going to be frog people pretty soon here and the Kriosan/Sable ones don't exactly match the race in question

**Comment by Lamasmaster** [comment]
perk
Something something, naramad still prob placeholder because I got no clue what to put there

**Comment by Lamasmaster** [comment]
And now even that is replaced thanks to PurplePineapple
merp

**Comment by cdb-is-not-good** [comment]
> perk Something something, naramad still prob placeholder because I got no clue what to put there

Again, make them something that isn't a meme :V

**Comment by Lamasmaster** [comment]
guuuuh

**Comment by AysheDaArtist** [comment]
This is a good design pathway, representing the races by their race faction.  If we don't want to do flags, we can represent the features of the skill in abstract art, such as having Razor Girl/Boy showing sharp angles in three slashes.  If you're open to having me help, I could take on some icons and assist, you'll be project lead on it.

**Comment by cdb-is-not-good** [comment]
Drafting this till the sprites that do need touching up are fixed.

**Comment by AysheDaArtist** [comment]
icons
weneedtodo64sprites
Lamasmaster coded in room for 64x64 sprites, but HD scaled down even with CSS looks bleh, we're going to have to go full sprites but we do have the space for nice 64x64 designs

**Pull request closed without merging**
