### PR TITLE
Rework of mob-AI activation checks.

### PR DESCRIPTION
**Pull request by Yatiyaya**
## About The Pull Request
<details>
<summary>
	Because it seems, after a brief check on the sojourn discord, that people test-merged incomplete and broken code.
	Deeming it not working (Because, I was still working on it) I've decided to upload the actually finished product here.
	
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

del: Removed old things

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Please name your PR correctly.

Also, I do believe we already testmerged these changes and ultimately decided not to keep them- there wasnt a significant appreciable effect on performance and it causes issues with certain mobs(pets and cattle particularly)

**Comment by du-top** [comment]
It seems you are referring to the PR #4697

**Comment by cdb-is-not-good** [comment]
So are you telling us this PR *doesn't* have the issues with farm animals and pets ceasing to process? 

Do you have any profiler results to indicate any performance increases over stock?

**Comment by Yatiyaya** [comment]
https://i.gyazo.com/49f650e12e2d2d208a8dc8743be233f9.png

I do, infact. It's called private server testing. Apologies for the high numbers as I use an 8-core CPU which isn't designed to handle server processing.
But as you can see, after the PR, it's lightning and machinery causing your lag because they are no longer waiting on the mob subsystem to fire/finish processing.

**Comment by cdb-is-not-good** [comment]
Excellent. Though regarding the issues with farm animals that's sorta the core issue we had that needs to be addressed before I think we'd want to merge this. So was it?

**Comment by Yatiyaya** [comment]
I would need articulatable issue other than "They stop processing"
Because, realistically, that would not happen due to them not being tied to superior_animal life() processing, not Ai sleep/activation.

**Comment by cdb-is-not-good** [comment]
>I would need articulatable issue other than"They stop processing"

???
They're farm animals/pets, they stop moving(minor) and particularly stop serving as a source of milk, eggs, etc. 

I didn't bother asking about it after porting the other because, well - you were not here and I had only done the porting at headmin request and with minimal info other than "pls port these two PRs". As you might note, we didn't see a huge boost from the "incomplete and broken" code we had ported, not a huge reason to fuss over it at that point, hm?

**Comment by Yatiyaya** [comment]
Time taken 15 seconds.
mob/living/life.dm was modified and didn't account for simple_animals exclusively using it while carbons(superior_animals and humans) using their own activate_AI code.

https://gyazo.com/2fde8062b93a993267996812b53118ba
https://gyazo.com/2b3a13a5287769d870f39c6de191f786
https://i.gyazo.com/2d5d565cf9a486d3f96d404751b69605.png

**Comment by Yatiyaya** [comment]
Lodge animals are classified as a superior_animal.
Meaning their AI is being put to sleep and because mob activation only works on !faction, they stay sleeping.

**Pull request closed without merging**
