### PR TITLE
fire fighting buff for borgs

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Gives borgs a new fire-b-gone that holds 3x the reagents, refills in a recharger and is faster at spraying. - This only applies to borgs that had fire-b-gone present in their kit rather then every borg type

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Maybe just for engi borgs instead of all of wm

**Comment by cdb-is-not-good** [comment]
Maybe just for engi borgs instead of all of em

**Comment by Trilbyspaceclone** [comment]
standerd is underpowed
drones are engi
engi are engi
and RnD borgs could use it for xenobio

**Comment by cdb-is-not-good** [comment]
Hrmmhmmh that works too just so long as it's reasonably distributed instead of all of em

**Comment by cdb-is-not-good** [comment]
Not that it makes a huge difference imo

**Comment by Trilbyspaceclone** [comment]
This pr simply improves the ones already given not giving them to every borg sorry for this confusion in the pr desc

**Comment by cdb-is-not-good** [comment]
Oh, are those the only borgs with extinguishers? If so that's fine.

**Comment by Trilbyspaceclone** [comment]
> Oh, are those the only borgs with extinguishers? If so that's fine.

mhm

**Pull request merged**
