### PR TITLE
3 new guns from Mojave

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Eckler - Heavy assault SMG, 9mm drum or stick for Marshal officers.

Aktion - Single action 10mm revolver for Rangers, FAT damage FAT AP a BIT unwieldy.

Nina - 9mm assault pistol for scavs and those who find it in the GARBAGE(spawn weight slightly lower than mac higher than croon.)

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Remove the nocode and exta :)

Also they should be in loot tables/have gun parts

**Comment by cdb-is-not-good** [comment]
Not every gun needs to have gun parts imo. Also the nocode stuff is nice references for someone who might want them later- I will add the two of the ones i diidn't to the loot pool tho.

**Comment by Trilbyspaceclone** [comment]
sprite bloat bad

**Comment by cdb-is-not-good** [comment]
the sprites don't leave the file and it doesn't affect anything too seriously.

**Comment by benj8560** [comment]
not on the specs disks? I see something in the desc about these being ''rare'' or whatever but. Just add a decent license point cost or something idk. That disk already has the marshal sniper on it one of the best DMRs in the game so printing anything off it that's not that is already a sizeable cost.

**Comment by cdb-is-not-good** [comment]
grahhh totally forgot

**Comment by benj8560** [comment]
The ranger revolver kinda blows chunks as well. Compaired to the deckard its just...a no brainer. I'd suggest switching it to 12mm or dramaticly upping the stats to put its raw damage a step above it to make up for single shell unloading/single action. Those are some MASSIVE drawbacks compaired to a deckard that you can instantly unload and fire semi-auto

**Comment by benj8560** [comment]
Nina turns invis when loaded with a highcap pistol mag. Apparently also missing wielded icons

**Comment by ChefDoggo** [comment]
can this get unTMed somewhat soonish? even the Eckler lacks sprites/isn't pathed properly, an actual SMG mag makes it go invis

**Comment by cdb-is-not-good** [comment]
Probably for the best, I don't got the time rn to get this functional.

**Pull request closed without merging**
