### PR TITLE
Nanogate & Psionic Aboose Fix

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
<details>
<summary>
	Stops FBPs from getting Nanogates since there's been recorded complaints about FBPs power-gaming it. Also stops psionic abuse by limiting TK range further.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
balance: Limits psionic range.
balance: Stops FBPs from taking Nanogates due to reported aboose of mechanics. (FBPs have no downsides to taking nanogates)
/:cl:

### CODE REVIEW

**Comment by ApplePlastic** [comment]
blessed

**Comment by cdb-is-not-good** [comment]
ehhhhh, i feel like this is a half measure that doesn't address the core issue that the nanogate doesn't have significant downsides

**Comment by Dimasw99** [comment]
I am going to cry because I am using long range telekinesis to pull multiple canisters. If people are abusing long range telekinesis on mobs then why not just make mobs chase people. I thought Niko just made a long range fix too

**Comment by cdb-is-not-good** [comment]
> I am going to cry because I am using long range telekinesis to pull multiple canisters. If people are abusing long range telekinesis on mobs then why not just make mobs chase people. I thought Niko just made a long range fix too

we reduced the range a few times but for whatever reason never reduced the range down to view range- till now, i suppose

**Comment by nikothedude** [comment]
> I am going to cry because I am using long range telekinesis to pull multiple canisters. If people are abusing long range telekinesis on mobs then why not just make mobs chase people. I thought Niko just made a long range fix too

mobs do target you if you whack them now but that doesnt mean other shit cant be cheesed like turrets

**Comment by cdb-is-not-good** [comment]
actually it not working on them is intentional i believe, Possum was just...weird and didn't take it away from them

**Comment by faaaay** [comment]
> actually it not working on them is intentional i believe, Possum was just...weird and didn't take it away from them

From a quick look at the perk, and how it references "natural healing", it does seem intentional.


But more on the main point: Synths **do** have their own downsides. I can _understand_ the argument of "If you don't have insight anyway, why wouldn't you take a core implant?" but at the same time - how many people _don't_ take a core implant at this point?

**Comment by Jul-Jul** [comment]
I'm all for the psionic fix, but the Nanogate change ain't required as health regeneration, and chems power...don't even work with synths. Also a synth having a little bot helper is cool. Honestly seems like a unrequired change.

**Comment by Stutternov** [comment]
> lmfao what?
> 
> Restricting FBPs from nanogates?
> 
> actual kneejerk, go away.

‘Go away’ - the power gamer who avoids bans by the heel of his seat. 

Synths have 0 downside from using nanogates due to lacking nutrition, as nutrition is their balance. I’ve directly seen people myself abuse the nanogate including its speed increase, omnitool spawns and everything else it sports with no downsides.

Inspiration decrease doesn’t exist because you are an FBP. Nutrition usage does not affect FBPs. The entire way the implant was balanced was around humans.

**Comment by r4d6** [comment]
> Synths have 0 downside from using nanogates due to lacking nutrition, as nutrition is their balance. I’ve directly seen people myself abuse the nanogate including its speed increase, omnitool spawns and everything else it sports with no downsides.

No offense, but what the fuck are you talking about?
Nutrition was _**never**_ a balance factor for the nanogate.
NONE of the powers even mention nutrition. The only additional nutrition cost would come from the fact that you have yet another organ in your body. That's it.
Any increase in nutrition usage was never considered a downside of the nanogate.

It's the cruciforms that actively use nutrition & blood as fuel.



> actually it not working on them is intentional i believe, Possum was just...weird and didn't take it away from them

Due to the way the nanogate work, there isn't any current support to lock/unlock access to certain powers based on the species.
And the reason the Regeneration doesn't work on FBPs is because FBPs and other synths do not process. At all.
IIRC processing was turned off due to causing problem with "nutrition" and inspiration.

**Comment by Stutternov** [comment]
> > Synths have 0 downside from using nanogates due to lacking nutrition, as nutrition is their balance. I’ve directly seen people myself abuse the nanogate including its speed increase, omnitool spawns and everything else it sports with no downsides.
> 
> No offense, but what the fuck are you talking about? Nutrition was _**never**_ a balance factor for the nanogate. NONE of the powers even mention nutrition. The only additional nutrition cost would come from the fact that you have yet another organ in your body. That's it. Any increase in nutrition usage was never considered a downside of the nanogate.
> 
> It's the cruciforms that actively use nutrition & blood as fuel.
> 
> > actually it not working on them is intentional i believe, Possum was just...weird and didn't take it away from them
> 
> Due to the way the nanogate work, there isn't any current support to lock/unlock access to certain powers based on the species. And the reason the Regeneration doesn't work on FBPs is because FBPs and other synths do not process. At all. IIRC processing was turned off due to causing problem with "nutrition" and inspiration.

The speed-up nanogate stuff, that you or Possum coded with 0 downsides to using, actually only had the unitended downside of nutrition usage due to the movement speed. Why? I can't tell, but it does increase nutrition usage - I'm guessing by tiles traveled. 

"No offense" doesn't work when you act like a prick instantly.

**Pull request closed without merging**
