### PR TITLE
Blackshield drip buff

### PR DESCRIPTION
**Pull request by ThePainkiller**
## About The Pull Request

- Refactors the Blackshield Radio Hat into a functional headset worn in the head
- Modifies `say` code to allow for the helmet to function
- Blackshield Radio Hat now available on loadout under Security tab
- Blackshield Longcoat in three different variants, added longcoat selection to loadout under security tab
- Fixes descriptions of Ablative and Bulletproof armors, as well as their icon states
- Fixes bad icon state for the brown beret
- Adds sprites for Sergeant beret, with a drab olive version
- Adds the Sergeant's pilotka (side cap) with an alternate drab olive style, to the Sergeant's locker and security loadout
- Refactors the Grey Utility Cover into being the parent for fatigue covers, so that loadout gear selection for the item gets fixed without a parent "head" item
- Adds alt styles for Blackshield Berets
- Adds proper Corspman beret variant, with alt style
- Minor typo fixes to "pants" selection of utility uniforms

This also corrects a missing pixel that was making armor clip out of the coat. Full flak vests, however, still clip above this coat as they're incredibly bulky.

<hr>

image

image

<hr>

### **EDIT:** The Blackshield Radio Hat works properly as a headset when talking on common channel, but currently does not work for Blackshield frequency despite coming with the proper encryption key. Any help on how to solve this is more than welcome.

<hr>

## Changelog
:cl:
add: Adds the following drip for Blackshield:
- Blackshield Longcoat in three different variants, added longcoat selection to loadout under security tab, two of each spawn on the accesory locker in the barracks
- Blackshield Radio Hat now available on loadout under Security tab, functions like a headset and is worn on the head
- Separate Sergeant beret sprites, with a drab olive version
- Corpsmen Beret sprites, with drab olive alt
- Drab olive alt style for Trooper berets
- Sergeant's pilotka (side cap) with an alternate olive style, on the Sergeant locker and security tab on loadout, available only for Supply Spec and Sergeant
fix: Fixes bad icon state of brown beret, fixes icon states of ablative and bulletproof helmets
refactor: Refactors Blackshield Radio Hat from a mere hat into a proper and functional headset
code: Edits say.dm code to accomodate for items worn on the head to be used as headset (for the Radio Hat)
spellcheck: Fixed typos on most clothings
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Is this fully tested? Historically I've noticed issues with alternate styles for accessories when using the current code but I might be out of date on that.

**Comment by ThePainkiller** [comment]
> Is this fully tested? Historically I've noticed issues with alternate styles for accessories when using the current code but I might be out of date on that.

You just reminded me that since it's an item that fits both suit slot and accessory slot, it should also get a state on the suits.dmi

However, you're right, after changing styles this just defaults back to the base one when attached to a plate carrier as accessory. I'll see if there's a way I can fix that.

**Comment by ThePainkiller** [comment]
> Generally not a fan of the radio hat, either. Especially considering it doesn't work properly.

Radio hat was already present in code, introduced by Rebel0 on another PR, just unobtainable before this PR. It **IS** working properly, except for the encryption keys which I have no idea why it doesn't parse departamental messages as it should, despite passing all of the checks for a message to be parsed (emotes transmit through commons properly, just not departamental radio)

> Olive drab also isn't part of the coloring aesthetic we have for forest-green Blackshield equipment.

image

The hats alt styles **literally** follow specifically the color palette of green equipment. I invite you to confirm it with Eyedropper, Aseprite, or your tool of choice. I had also made brown versions following the "tan" pattern of utility uniforms, but testing with in game lightning made me realize there's barely a noticeable difference when 1-2 pixels are concerned (in the case of berets, at least), so I went with the olive choice to work for both colors of utility uniforms + longcoat combos. Which is the main goal of this PR, have stuff that combines in color with the alternate uniforms that spawn on the blackshield lockers on the barracks.

The "pilotka", side cap, garrison cap whoever you want to call it,[ is already a thing that the Steward gets access to](https://github.com/sojourn-13/sojourn-station/blob/28f2ce744c5b35646a2964d238098094924c0744/code/modules/clothing/head/jobs.dm#L32), and it naturally [spawns on their locker](https://github.com/sojourn-13/sojourn-station/blob/28f2ce744c5b35646a2964d238098094924c0744/code/game/objects/structures/crates_lockers/closets/secure/security.dm#L36). If a Steward can have it for drip purposes, then why not? I even discussed it with CDB and agreed that giving it to Sergeants and Supply Specs was better than having the average HURRAH SIR YES SIR Trooper/Cadet have access to it, so it's not going to be used/obtained by the average freshman but by someone who advanced enough to be in the position of Sergeant/Supply Specialist. Hence the loadout/locker restrictions.

**Comment by cdb-is-not-good** [comment]
I agreed that it's already in use but was ultimately on the fence given that we /are/ trying to move away from the shield military stuff. I don't personally think giving them olive drab is the end of the world but for now let's nix the Pilotka

**Pull request merged**
