### PR TITLE
Lodge Solar Array Revamp

### PR DESCRIPTION
**Pull request by Pawoverlord**
## Solar Array Adjustments
<details>
<summary>
	In short, this is changing the solar array of the lodge from the Guidesu version to one that looks more cohesive and has additional solar panels (about 10 more). It removes the mass amount of generators and replaces it with a single generator, as that is all that is required to power the entire lodge. This PR also adds a recycler in a new 'maintenance' room that has the solar setup, SMES, and recycler. Lastly, this PR has the additions of trash bins about the lodge to allow lodgers to throw things away instead of dropping items on the ground like a discarded Woody doll.
Lodge members will now have to insert wood into the generator found in the 'maintenance' room and toggle SMES and solars at the start of every shift to ensure power for the entire shift.

</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
add: Recycler for scrapping trash.
add: Trash bins throughout the Lodge.
remove: Excessive amounts of generators.
fix: Solar array for the Lodge.

/:cl:

image

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Weres the outside APC for the outside areas?

**Comment by Pawoverlord** [comment]
> Weres the outside APC for the outside areas?

I might have forgotten to add it, as it doesn't power any devices currently. When I get home I can adjust the PR with the exterior APC. Just in case the colony shuttle doesn't play nice with it.

**Comment by Pawoverlord** [comment]
After re-reviewing this upload, I will be adjusting the wiring again. I attached the new external APC to the wrong wire by accident.

**Comment by Pawoverlord** [comment]
Much better, no longer a crime against engineering design. Image uploaded to show the hot new external APC.

image

**Comment by Trilbyspaceclone** [comment]
please add a catwalk to the apc and a wire just in case + top right corner needs an extra bit of green impassable rock so its in non-darkness

**Comment by Pawoverlord** [comment]
I am unsure what you mean by your comment. As there is no darkness in game in that corner, and the APC does indeed have a wire under the catwalk that it's on.
image
image

**Comment by Medizeal22** [comment]
Approved provided no conflicts.

**Pull request merged**
