### PR TITLE
Blockshield 2.0

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Remake of this https://github.com/sojourn-13/sojourn-station/pull/4564
Conflicts for whatever reason were unfixable so now on current branch
	
<hr>
</details>

## Changelog
:cl:
add: Blackshield as it's own department
/:cl:

### CODE REVIEW

**Comment by Lamasmaster** [comment]
Note this PR just seperates them code wise so they can be interacted without affecting eachother like Soteria Medical and Research, outside of the account change this changes pretty much nothing user or lore wise.

**Comment by Trilbyspaceclone** [comment]
Waiting on moon to also take a peek at this

**Comment by cdb-is-not-good** [comment]
I see no reason why not. We aren't splitting anything lore wise and this is necessary for some code stuff like BS unique backpacks. Plus one

**Comment by cdb-is-not-good** [comment]
This can be test merged, if that wasn't clear

**Comment by Lamasmaster** [comment]
So far only the manifest is bugged otherwise seems to work, need to fix that tommorow.

**Comment by cdb-is-not-good** [comment]
Why not just make green backpack an alt skin of the base bag

**Comment by cdb-is-not-good** [comment]
Is this done being worked on and ready to be merged?

**Pull request merged**
