### PR TITLE
Remaps the Vassily (by Lamasmaster)

### PR DESCRIPTION
**Pull request by Ryan180602**
## About The Pull Request
Squashes the Vasily. Any questions, direct to Lamasmaster, he's the PR's author.
<summary>
	Remaps the Vassily to look a bit better.
</summary>
</details>

## Changelog
:cl:Lamasmaster
tweak: Remaps the Vassily
:cl:

### CODE REVIEW

**Comment by Lamasmaster** [comment]
Hangar

**Comment by benj8560** [comment]
while your touching this. It had some problems with the lodge landing zone it would tear the ship apart apon takeoff I've no idea whats causing it I assumed maybe it was using some odd turfs under it at a guess but never looked into it.

**Comment by benj8560** [comment]
I personally feel like at minimum it should have at least one jail cell of sorts as well? does not NEED it but it is for a police force to use.

**Comment by Lamasmaster** [comment]
It didn't tear apart in my test or in most cases that we used it on server so legitimetly no idea what causes that to happen.
As for the cell it's not really required since you can tie people to the chairs themselves.

**Comment by benj8560** [comment]
the moment you get into the high toughness chair/cuff is pretty much useless. As this is now anyone being arrested with this shuttle would need constant supervision and that's okay just not ideal. Kinda defeats the point of having a police shuttle. They don't just buckle you in in a police car they lock you in the back.

**Comment by benj8560** [comment]
but i guess just shoving them in that back seating room would mostly accomplish that just...not very professional looking

**Comment by Lamasmaster** [comment]
I could remove the equipment room I guess but then I'd shove those things into the actual tactical armory for marshals to make room for a cell but otherwise don't see where it could fit.

**Comment by benj8560** [comment]
could scrap the extra airlock? I'm not sure what its for aside from making a tremendous amount more sense. Why....was this shuttle setup in such a way you need to walk all the way around it to get in anyways...very silly. 

The old airlock would honestly be the best fit for a cell but I imagine thats gonna be a lot more work with how these eris style shuttles are built.

**Comment by benj8560** [comment]
does really nail putting them in the backseat if you put them in that back back airlock part tho

**Comment by cdb-is-not-good** [comment]
Can we make it even smaller

**Comment by Lamasmaster** [comment]
I wanted to but it screws the up sprites for the shuttle itself

**Comment by Lamasmaster** [comment]
image

**Comment by Lamasmaster** [comment]
Somehow this causes the hangar to start depressurized, gotta love it

**Comment by Trilbyspaceclone** [comment]
you accidently renamed the map it seems

**Comment by Lamasmaster** [comment]
I didn't touch the map name so no clue how that happened 🤔 I love github sometimes

**Comment by cdb-is-not-good** [comment]
Test your PRs

**Comment by Ryan180602** [comment]
fixed now (smh @Lamasmaster)

**Comment by Ryan180602** [comment]
and fixed

**Comment by Lamasmaster** [comment]
we live in a post git client society tbh

**Comment by benj8560** [comment]
space tile located here REALLY needs a fix by next round https://i.imgur.com/eOuj7Bf.png

**Comment by Lamasmaster** [comment]
Should be spaceless now

**Comment by cdb-is-not-good** [comment]
Merge this already goddammit

**Comment by Trilbyspaceclone** [comment]
> Merge this already goddammit

It has fixes pending

**Pull request merged**
