### PR TITLE
Adding Winter Cape

### PR DESCRIPTION
**Pull request by YuiJaguar**
Adds a cute Red and white 'Orsi' style cape for those cold nights.
This is available in both the loadout AND the vendor! Snuggle up!
This is my first contribution to the server plz no flame :)
I'll be trying my best to add more 'cute' clothing options that fit the style as well as I can make it.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Post pics, silly

**Comment by YuiJaguar** [comment]
> Post pics, silly

Oh right!. Let me just add these....
Screenshot 2024-02-25 001932
Screenshot 2024-02-25 002037
Screenshot 2024-02-25 002100
Screenshot 2024-02-25 002118

**Comment by YuiJaguar** [comment]
It's off by a pixel, I'm fixing it and reposting. I thought I had it correct but when I put my scratchboard in it It was not right. I'll post what it looks like 'equipped' in a moment.

**Comment by YuiJaguar** [comment]
Right! Now that the pixel is fixed. Here's what it looks like on my scratch board 
EDIT: OH MY GOD I SWEAR IM NOT THIS SLOPPY BUT I FOUND ONE MORE ARTIFACT TO FIX. PLEASE BELIEVE ME IM GOOD AT SPRITING IM FIXING IT AND POSTING AGAIN. Please forgive me I checked this like 8 times last night and didn't notice these 2 things. Here's the picture!

Screenshot 2024-02-25 004711

**Comment by YuiJaguar** [comment]
Screenshot 2024-02-25 005535
Screenshot 2024-02-25 005659

Last two for you to look at 'posed' on the dum dum

**Comment by YuiJaguar** [comment]
The name of my scratchboard is dum dum, by the way. Be nice to him.

**Comment by cdb-is-not-good** [comment]
Neat

**Pull request merged**
