### PR TITLE
Makes female specific sprites work

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Ports Eris system for female specific sprites, if they have them why don't we, currently uses their own sprites only.
	
<hr>
</details>

## Changelog
:cl:
add: Female specific sprite system
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
The `uniform/mob_fem.dmi` has a **very** limited range of options (156 icons down from a current total of **553**), if code-wise this will only ever draw from a specific pool on `mob_fem.dmi` to `get_gender_icon()` on female character overlays, wouldn't this render most of the current clothing invisible on women if they decide to wear an item whose `icon_state` is not present in there?

**Comment by Trilbyspaceclone** [comment]
i hate this

**Comment by BigBadPossum** [comment]
Mob_fem was not used for this specific reason, as it would require either duplicating all clothing sprites or making a female version for all existing sprites that don't have _fem addition. Not a good idea for spriters work loads.

**Comment by Lamasmaster** [comment]
I know at least few spriters are interested in this in some capacity and not every sprite has to have a female version entirely.
So either I can make it into a draft until I do have the sprites which is going to take a while or maybe I can come up with a way where it reverts to the male sprite if it doesn't find one in the female folder.

**Pull request closed without merging**
