### PR TITLE
SLT sidearm options

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Gives SLTs the option to choose between the Abnegate, soteria version of the Zeus and Spider Rose.
Spider Rose doesn't see much use neither does Zeus with Zeus being an orderly weapon at one point so it makes sense.
	
<hr>
</details>

## Changelog
:cl:
balance: Sidearm options for SLTs
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Not that I really care much but why would one ever pick Zeus over the spider rose which has hitscan and a lethal mode

**Comment by SingingSpock** [comment]
With its current cell, the Hera will get 5 shots per cell. With a posi, it gets 8.

**Comment by cdb-is-not-good** [comment]
Hum, well im not a huge fan of giving them a sidearm that *is* potentially lethal. They don't need that kind of versatility.

**Comment by Lamasmaster** [comment]
I could just remove the spider doesn't really matter just seemed like it would fit, Zeus has enough shots to down a single person reliably as long as they aren't on oxy.

**Comment by Lamasmaster** [comment]
Removed spider

**Pull request merged**
