### PR TITLE
Update firstaid.dm

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Fixes trama kits desc to be less wrong
## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Lilly, the Guild didn't design these...**I** did, and that's how I rolled with it ICly even :/
The "bluespace infusion" is a fancy way to explain the reason they're "bigger on the inside" despite being the same size as normal treatment kits.

**Comment by Kazkin** [comment]
Given bluespace creates entropy and these don't, it makes more sense for them to be a guild design, because engineers are good at efficiency.

**Comment by Kazkin** [comment]
Not gonna merge this until I see a rebuttal or it sits for awhile tho.

**Comment by Trilbyspaceclone** [comment]
how would bluespace make something bigger on the inside?

**Comment by AysheDaArtist** [comment]
Are there any other tools inside Soteria that also have guild affiliation?  I agree with the bluespace being odd since it doesn't actually cause bluespace entropy, but if it's lore Guild has built some stuff for Soteria that will be brought up ICly and could even be used as leverage, or even for future tools/tech.

"Yea, well why don't you hand over all the toys we've made you over the years Soteria"

It's a cool idea, but even something small can be dragged out a mile.  I'd consider maybe just having "This one is larger in capacity thanks to Soteria ingenuity"

**Comment by ThePainkiller** [comment]
> I agree with the bluespace being odd since it doesn't actually cause bluespace entropy[...]

Fair point on that one, I wanted to explain the bs reason on why it has higher capacity than normal medkits and, as usual, BlueSpace takes the blame, but if for lore reasons (and entropy ones since it's an actual thing here) doesn't fit, then you're right

> It's a cool idea, but even something small can be dragged out a mile. I'd consider maybe just having "This one is larger in capacity thanks to Soteria ingenuity"

I like this one! This is an acceptable middle ground if anything because it doesn't take away from the fact that I designed these, instead of straight out defaulting to the Guild and breaking the spirit of the original item. This is a Soteria creation, not a Guild one, and should be still labeled as such.

**Comment by Trilbyspaceclone** [comment]
the idea was that guild helps Cargo with their tools to make them better see Jolly-co but ill swap it

**Pull request merged**
