### PR TITLE
Crayolo Antaginism

### PR DESCRIPTION
**Pull request by LongSleeves**
Adds Trap runes to crayon magic that use a small assortment of spells and scrolls.
Adds punishments for church goers using crayon magic.
Fixes crayon magic balancing. You weren't supposed to be able to skip casing Babel. The language requirements are back.
Adds new spell that coverts runes to trap runes.
Adds Joke scroll spell that tells a joke. Will it fall flat or make people laugh?
Adds Entangle scroll that creates a web of fairy lights. They vanish after 3 minutes.
Adds Charger scroll that releases ball lightning! Its not friendly to the scroll burner.
Adds Reveal scroll that gives a quick flicker of thermal vision to the caster and those around them.
Moves Mightier to knife rituals. It didn't make as much sense to have to craft a scroll for each throwing crayon.
Adds DEEP LORE to crayon magic, what could the author intended by this?!?
unknown ooOOOooO
Deepmaints mobs when blocked by holy tiles have a 5% odds to be permanently killed, as a different power steps from the 
Fixes some bugs with Escape and Life To Cards
Fixes some of the comments in code being lies or having typos.
Crayon spells should now be colorful! Smoke in particular will be any color of crayon.
Pen is no longer mightier then the dagger thus requires it
Crayon Basin is no longer the admin only version. It was added without giving it any debuffs. It will now tank sanity both from being around it and using it.
Psi Inhalers now need you to be able to huff them
Psi Inhalers now lower psi_blocking. Just in case you stepped on a trap rune as a psionic.
New tweaks to how oddities work, only used for crayon magic

Is flame now properly works. You can burn scrolls with more then welders now.

### CODE REVIEW

**Comment by LongSleeves** [comment]
Things to do:
Fix up the trap rune spawning so its in maints and deep maints only.
Fix up the color scheme of trap runes so they are funner.
See how trilby makes it more "playful".
Add way for crayon mages to make trap runes themselves.

**Comment by cdb-is-not-good** [comment]
I'm not a huge fan of making these spawn completely randomly

**Comment by ChefDoggo** [comment]
> I'm not a huge fan of making these spawn completely randomly

same
also making it so crayon magic is completely barred by two groups is pretty fucking lame, as it is the church already banned the use and the psionic ban doesn't really make sense, overall L PR imo

**Comment by SingingSpock** [comment]
I agree with a punishment for Churchies, something originating from their Cruciform, but not for psions for the reasons Chef said: it just makes little sense.

**Comment by LongSleeves** [comment]
-The punishments for touching runes will be adjusted to only on book use for churchies and removed completely for psionics.
This was heavily requested by multiple people which I found surprising on the psionics part. But its a easy change.

-The runes have been requested to only be placed in places where you would normally find crayon activity so we will be hard mapping in a few spots instead of randomized.

-Cerebrix will be buffed to lower psi_blocking. This is so you don't perma get fucked by ignorance and lose your psionics.

-The health loss on the trap rune however will remain. Its literally a 5hp loss IF it picks that spell. And there will be checks in place so if you have less then 80 max hp the rune will no longer target you at all.

**Comment by ChefDoggo** [comment]
excited to step on a rune, it proc the scribe spell and i go fucking blind

**Comment by LongSleeves** [comment]
its vary specific spells that it can do. Its not the ENTIRE list. Otherwise we would be risking people paradoxing and blowing up large sections of colony.

**Comment by cdb-is-not-good** [comment]
I'm satisfied with the changes. That said, given the contention I'm gonna air on the side of caution and we'll testmerge this for a bit

**Comment by Trilbyspaceclone** [comment]
Scope creep do to inspriation (and bug fixes/balance)

**Comment by LongSleeves** [comment]
added in a few more things and did the balance tweak that much of it needed. The ability to cast later rituals without first doing Babel was never intended and allowed people to get some snazzy equipment like crayon pouches without permanent debuffs.

**Comment by cdb-is-not-good** [comment]
Conflicts

**Pull request merged**
