### PR TITLE
linked box nerf 

### PR DESCRIPTION
**Pull request by ApplePlastic**
i hate this codebase

## About The Pull Request
<details>
<summary>
	Linked box ammunition is a normal-sized item. They can be stored in belts. This is not good, so I fixed it. 
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Tweak: Changed the size of linked box ammunition form Normal to Bulky. 
/:cl:

### CODE REVIEW

**Comment by ApplePlastic** [comment]
https://tenor.com/view/transitions-kinemaster-black-guy-suit-tiktok-gif-25279479

**Comment by ApplePlastic** [comment]
shoebill invasion

**Comment by cdb-is-not-good** [comment]
Do extra bulk -2 so that it takes up the same amount of space in the bag, but can't in anything smaller than a satchel

**Comment by ApplePlastic** [comment]
sure

**Comment by ApplePlastic** [comment]
just another PR- staging it for now.

**Pull request merged**
