### PR TITLE
Makes possible to dowload the trading program at NTnet.

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
Well, it's just of a general issue.
 Lonestar is the only department who has access to it, even if in a way does not make much sense.
Most of the time, lonestar can't even sell most of the time specific items. For example, the CAV Hope that only accepts Church Items. The other trading station that only accepts things that only Guild is capable off. And such is also others trading stations such the medical one that buys organs.
So by this not only Medical, Guild… hell even church or Marshal can build a receiving and sending beacon by asking guild or buying a disk and build their own little market. 
And thus this also leads to another fun thing to deal.
Market competition.
Which leads to every department fighting for a way to gain more pretense on the trading market.

This is the first part of my trading market that will gives in some sorta of way medbay/guild/marshal/blackshields/church/lonestar/prospectors/lonestar service/soteria hell even colonist a way to gain money and participate on the trading market.

If this goes to code, my next step is to give way more trading markets with its own niches, more things to interact and in a way. A fun monetary battle between departments.

Plus, if you lose the program or if someone deletes it… Or the computer breaks, you will permanently lose it for the entire round.

	
<hr>
</details>

## Changelog
:cl:
add: After a code breach of hackers, the Lonestar Trading program has become public.

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
This was already denied in #2279 but i still like the idea!

**Comment by Kazkin** [comment]
The problem that I have with this, primarily, is that it would allow people to circumvent cargo entirely for items they need, making it so they can neither get a mark up value when selling or basically do anything required of cargo techs for anything not directly related to the shuttle, which would become far less useful if the trade shuttles were freely available. I'm not closing this outright, but I'm not really convinced its a good idea for the game.

**Comment by Guidesu** [comment]
> The problem that I have with this, primarily, is that it would allow people to circumvent cargo entirely for items they need, making it so they can neither get a mark up value when selling or basically do anything required of cargo techs for anything not directly related to the shuttle, which would become far less useful if the trade shuttles were freely available. I'm not closing this outright, but I'm not really convinced its a good idea for the game.

So heres my solution:
Creates an public market that has far less items.
But still has the ability to people sell theirs stuffs

**Comment by Kazkin** [comment]
After giving it some consideration, I've decided to deny this. I do not wish to remove a unique quality to cargo and spread it around, so that the faction that is relatively underplayed retains its more unique qualities. This is equal to lending out job specific access/abilities to the point of making it a non-thing for those who are concerned with it.

**Pull request closed without merging**
