### PR TITLE
Slower spiders

### PR DESCRIPTION
**Pull request by Dissentbay**
## About The Pull Request
<details>
<summary>
	Makes spiders move slower, the more likely of a bite to be the end of you, the slower they are (Emperor/Reaper unchanged)
	
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
tweak: changed move_to_delay in most spiders, Emperor and Reaver left untouched.

balance: made it so spiders that have the potential to kill/severely maim with one bite can be avoided by most 
characters not using any slowing armor and opting to run away

Dev note: The objective of this PR is to make such encounters optional as they were previously, making blitzing/kiting a viable strategy, instead of a guaranteed stop to buy meds/get treated by a doctor.
     Colony maintenance should not be a real challenge (do not cherry pick emperors walking or a random stalker, they are not the rule, they are the exception), while at the same time not be comparable to skeet shooting. Difficulty should be progressive, in the outward direction of the colony, goign against that serves no purpose but to cause players who come to the server for other reasons than PVE to have difficulty to start enjoying this aspect of the server in a gradual way, and spiders are there to remind you that threats will do more than beat you up, like most roaches do, but to poison you with various reagents, teaching you about using range to your advantage or preparing better for the most likely threat you are to find, while roaches will most likely swarm you and teach you about handling various threats at the same time, prioritizing the ones most likely to make you unwillingly horizontal faster. 
     Just so you may choose to risk more for better rewards and go outside, or to deep maint, those challenges should make you bring better equipment. Alone or as a group? Harder or easier? That would be outside the scope of this PR, I just hope everyone enjoys their slice of PVE, whatever they choose.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
What made you choise these values that are 3-5x slower then pre-buff?

**Comment by Stutternov** [comment]
While I can say some spiders are still a little bit too fast in my experience on server, some of these feel like _hard_ nerfs (ex from 3 -> 5, 4 -> 7) which may be a bit too much.

**Comment by Dissentbay** [comment]
I used the old values as a base in this pr
https://github.com/sojourn-13/sojourn-station/pull/3477
some spiders got nerfed harder based on the direct threat a bite of them are, given the changes to the rate they inject you, recluse being the most nerfed due to being able to end you in one bite.
Also I'm okay with not nerfing that hard certain spiders, respecting the objective of this PR, that is to make spiders as avoidable as they were before the buffs.

**Comment by Trilbyspaceclone** [comment]
You do relise that if they are 5x slower then a person, anyone in any armor combo in the game can out *walk* a spider?

**Comment by Stutternov** [comment]
> 

In that case it's kind of just a hard revert. Personally I'd just suggest finding values through testing, just find better values rather than hard-revert since they got changed due to spiders being really not that threatening despite their instant agro before.

**Comment by Dissentbay** [comment]
> You do relise that if they are 5x slower then a person, anyone in any armor combo in the game can out _walk_ a spider?

no, because my local speed and in the server are not comparable, you're most welcome to tell me values that would mostly achieve the objective of this PR and satisfy your concerns, because current values (while better than at the buff) are not managing to make spiders an avoidable threat
 
> In that case it's kind of just a hard revert. Personally I'd just suggest finding values through testing, just find better values rather than hard-revert since they got changed due to spiders being really not that threatening despite their instant agro before.

I would be okay with a hard revert, just in speed, I am completely okay with the changes in the danger they are when you get bit

**Comment by nikothedude** [comment]
> > You do relise that if they are 5x slower then a person, anyone in any armor combo in the game can out _walk_ a spider?
> 
> no, because my local speed and in the server are not comparable, you're most welcome to tell me values that would mostly achieve the objective of this PR and satisfy your concerns, because current values (while better than at the buff) are not managing to make spiders an avoidable threat

The speed on local and on server are the exact same, unless your local server itself is slower for some reason|

Mobtick, AKA targetting is slower for the first 30 or so mins, but that doesnt affect movespeed

**Comment by Dissentbay** [comment]
>The speed on local and on server are the exact same, unless your local server itself is slower for some reason|
Mobtick, AKA targetting is slower for the first 30 or so mins, but that doesnt affect movespeed

I'm not talking about aggression or damage, my point is making spiders avoidable, as in you can just run away if you turn a corner and there is a number of them you're aware you won't be able to handle. But at the same time, not go back to spider standing motionless while you shoot at it freely

**Comment by cdb-is-not-good** [comment]
>Dev note: The objective of this PR is to make such encounters optional as they were previously, making blitzing/kiting a viable strategy, instead of a guaranteed stop to buy meds/get treated by a doctor.

First thing to note is that these...encounters are not meant to be 'optional' - if you are in an area with spiders the chances are good that you are there on purpose, and by choice. A threat that you can easily and effortlessly kite is not a threat - and thus may as well not exist.

**Comment by Dissentbay** [comment]
>First thing to note is that these...encounters are not meant to be 'optional' - if you are in an area with spiders the chances are good that you are there on purpose, and by choice. A threat that you can easily and effortlessly kite is not a threat - and thus may as well not exist.

So turning a corner should result in your death? Or can you see the three spiders around it?
A spider falling onto the public lathe should result in your death?
An open maintenance door, either opened by someone or by the spiders themselves, should result in someone death?

In those situations the person is not "looking for trouble" and still getting it, making so you can outrun the spiders solves this issue
Kiting the spiders will only detract from your own experience, the decision to engage them in melee is still there, by making the spiders unavoidable you're removing player agency to tackle an issue, forcing them to handle it one way only, which is with one or multiple spiders glued to them.
And again, progressive threat, why spiders have to be such a threat from a rp and game design standpoint? Because someone felt like it? I am unable to see any issue with how maintenance was "difficult" before, so much so I had to learn make a PR in attempt to revert what I believe is a poor decision. That should tell how much I believe buffs to maintenance critters are a bad decision.

**Comment by Dissentbay** [comment]
>They need not, if one only prepares. A flash, some soap, a gun - etc. These are all ways to beat and survive just fine.

Guess I should make a pr that gives everyone a flash when they spawn them, or maybe make the spiders avoidable? so you can press in a direction and escape the threat? Running away also does not require you to be in close contact with the threat, a soap will make you escape one spider at best and a gun is also not given to you when you spawn, meanwhile running away is something every colonist who just arrived can do

>It also introduces new issues that you have not offered a meaningful solution to. It trivializes these mobs rather significantly

list the issues, please. In my opinion the mob won't be trivialized in the slightest, you will only have one more option to engage it, which is not engaging at all by running away, are more options bad? If so, enlighten me

**Comment by cdb-is-not-good** [comment]
>In my opinion

Seems to be the summary of this PR - i disagree, and don't really feel like you've made your point in a very convincing fashion. In its current state, this PR isn't going to be accepted - I'm open to making these changes less extreme but a full revert just...doesn't seem necessary, even if some of the numbers do need tweaking.

**Comment by Dissentbay** [comment]
>Seems to be the summary of this PR - i disagree, and don't really feel like you've made your point in a very convincing fashion. In its current state, this PR isn't going to be accepted - I'm open to making these changes less extreme but a full revert just...doesn't seem necessary, even if some of the numbers do need tweaking.

Again, are you able to explain you points without expressing your opinions? Also can you engage the entirety of my point or you plan to only pick parts that you can express a disagreeing opinion?
Because I fail to see any argument from your part, only your beliefs, and they are opposite to mine
Perhaps you should ask more people what they think about the maintenance buff, because your sample seems to be VERY different from mine, while you may want to paint me as lone opinion, I saw several discussions from players in general chat, dsay and OOC, mostly unfavorable to the increased risk without any reward. If you are deaf to different opinions, I am unable to discuss with you anything, plus the PR to nerf spiders is here, it is this one, and we are taking more time to discuss it than many other big changes, time that could be used to actually merge this PR, see the reaction of the community and further adjust it, if necessary

**Comment by cdb-is-not-good** [comment]
I'm mostly just disinterested in arguing my opinion vs yours? It's not really worthwhile because we clearly stand in very different places on the matter.  I've given my call about this PR, and if you don't want to change it further then that's fine, but i won't be merging it.

**Pull request closed without merging**
