### PR TITLE
[IDB IGNORE] [MDB IGNORE] Moves non-weapons from /obj/weapon to just /obj

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
its an optimation i sware!
Tots no hidden code in all these changes, im a cool cat!!

### CODE REVIEW

**Comment by r4d6** [comment]
Ah, porting https://github.com/discordia-space/CEV-Eris/pull/6357 ?

**Comment by Trilbyspaceclone** [comment]
ye

**Comment by ThePainkiller** [comment]
**OH GOD OH NO**

**Comment by AffectedArc07** [comment]
Plaese put `[IDB IGNORE] [MDB IGNORE]` in your PR title or this repo will be blacklisted from MapDiffBot.

**Comment by MSieghardt** [comment]
Under sojourn-station/code/modules/projectiles/guns/projectile.dm
add 
hitsound = "swing_hit"

Tested this and that is the only issue I found. Everything works as it should, at least when tested. We'll find bugs out if they come up when we merge, but so far it shouldn't crash.

**Comment by Kazkin** [comment]
May the Absolute have mercy. Merged.

**Pull request merged**
