### PR TITLE
Dylo OD + Mech Refining

### PR DESCRIPTION
**Pull request by DiscordWizard**
## About The Pull Request
<details>
<summary>
	Gives dylovene a harsher OD than just some toxins
	Makes it so mech ranged weapons properly melee things
        Cleans mecha code a little
</summary>
<hr>

Fixes me being dumb with the ranged weapon melee check on my earlier commit, I forgot to test hitting another mech in melee with a ranged weapon and it's most likely borked.

Changes Dylovene OD from mild toxins to a proper amount of toxic buildup and kidney damage, because organs that aren't the liver should receive some love too! And some gasping, it's always a good indicator
	
<hr>
</details>

## Changelog
:cl:
add: dylo OD limit at 30 units
balance: harsher dylo OD
fix: mech ranged melee fix
code: removed duplicated code from mecha
/:cl:

### CODE REVIEW

**Comment by DiscordWizard** [comment]
Forgot to test this at home, so putting it up for review to see if anyone spots any errors or wants to comment and argue about the new dylo OD for balance before I work back on it in 12 hours

**Comment by ThePainkiller** [comment]
Dylovene never had, **nor should it ever have**, any kind of overdose. What's the reason behind this?

**Comment by DiscordWizard** [comment]
It was on the to-do list that dylovene needed a different OD than the basic one. Every single chemical has a base OD that gives mild toxins when surpassed, the problem with dylovene is that it simply out-heals any damage its OD can give so people can go around with as much dylo in them as they please. It's already pretty hard to OD on dylo with the 30 unit cap and extremely good toxin removal, if you go over that it's honestly on you.

**Comment by cdb-is-not-good** [comment]
> Dylovene never had, **nor should it ever have**, any kind of overdose. What's the reason behind this?

why would it not have an overdose?

**Comment by DiscordWizard** [comment]
The parent /reagent overdose is set to 0 and /reagent/medicine doesn't change it, you have to specify the overdose level on the specific chem if I understand the code correctly

**Comment by Dongels** [comment]
I've been *for* giving Dylo an OD that was not just the current base tox...since it's a nothing thing that gets cured by the dylo. This would just help diversify the use of other tox chems.

**Comment by cdb-is-not-good** [comment]
> I don't think it's necessary to include it since it should inherit from parent, as every other reagent that doesn't have it specified :B

*Insert stephan-molyneux meme about arguments here*
That's not really a proper response and you know it.

**Comment by ThePainkiller** [comment]
> Insert stephan-molyneux meme about arguments here
That's not really a proper response and you know it.

...W-what kind of response? I just thought it redundant to add something that I assumed the code handled for itself by inheriting from parent, I didn't even say it in a rude way, I think...?

**Comment by DiscordWizard** [comment]
You're fine, it's a valid concern. I just feel like we do need a little more damage variety and dylovene can be very easily abused since you just have an infinite amount of it in sleepers.
And hey, sleepers don't even let you add Dylovene to 30u by default! You're physically unable to OD someone unless you purposefully jab three syringes in them

**Pull request merged**
