### PR TITLE
 Geiger counters to the people

### PR DESCRIPTION
**Pull request by benj8560**
Adds Geiger counters to adept, GM, rad suit closets and rad gear crates. Why where these lonestar exclusive exactly? Who knows.

Note: dont merge for now theres some problems with these counters I'll see about resolving and including in this PR. Currently pre-set spires do not produce rads and the SM is using old code for rads not detected by the counters.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Do miners already get one?

**Comment by benj8560** [comment]
Miners can get them in their vender and lonestar can import them. These prior to this PR are the only 2 ways in the game of obtaining them

**Comment by cdb-is-not-good** [comment]
also a small note these apparently don't really work all that well and need work.

**Comment by benj8560** [comment]
gonna scrap this for now. Ran into troubles trying to figure out why pre-set spires refuse to make rads. Maybe come back to it some day.

**Pull request closed without merging**
