### PR TITLE
Resprites

### PR DESCRIPTION
**Pull request by Legate-Maxson**
Changed sprite for church saint armor. Adds NT Cerberus FBP head, Adds NT Evening Dress by Undard.

### CODE REVIEW

**Comment by Smokingsquirrel** [comment]
Don’t do anything to the paladin sprite next I hope. I got something in the works for that

**Comment by Legate-Maxson** [comment]
> Don’t do anything to the paladin sprite next I hope. I got something in the works for that

Didn't touch it. Was told to remove the Saint sprite since it didn't work with the armor code and the sprite was just stolen from another code base anyway. That sprite was the only one changed

**Comment by Smokingsquirrel** [comment]
> > Don’t do anything to the paladin sprite next I hope. I got something in the works for that
> 
> Didn't touch it. Was told to remove the Saint sprite since it didn't work with the armor code and the sprite was just stolen from another code base anyway. That sprite was the only one changed

Yeah saint needed a due rework which we also had in the make but I will cancel that and there will be a paladin and royal respite instead

**Comment by Legate-Maxson** [comment]
Alright PR is good to go now fully tested

**Pull request merged**
