### PR TITLE
Head Office upgrades and other things

### PR DESCRIPTION
**Pull request by SingingSpock**
## About The Pull Request
<details>
<summary>
	Updates the Heads Offices, and a few smaller supporting changes
</summary>
<hr>

Updates each Head office to have 1) A command console and a console for their department if their department has one, 2) A command tablet, 3)Buttons to open and bolt their door on their desk (except Prime because holy doors work on prayers), 4) A Filing Cabinet, 5) A request console, and 6) some kind of bedroom or private space.

Warrant Officer office got a full remap, removing the old unused elevator and moving the WO office down, adding a small bedroom. The newly freed space got converted to a smaller briefing space for Marshals.
image

Redid a few areas: the main Bridge room is now one area (whose idea was it for it to be two?), the bridge hallway is its own area, and the security firing range now uses the firing range area rather than a renamed version of the base area.

Additionally, made a few changes to command tablets and consoles, and added coded subtypes for Request Consoles rather than relying on setting the variables in the map itself.

CRO Office:
image
CBO Office:
image
BC Office (They have actual window tints now rather than shutters. There's still shutters for the door to the ladder):
image
Premier's Office:
image
Control Room and Bridge Hallway:
image
image
CEO's Office:
image
GM's Office:
image
Foreman's Office: 
image
Prime's Office: 
image
<hr>
</details>

## Changelog
:cl:
map: Head offices got some extra things for them to do their work better
map: Warrant Officer office got completely redone
tweak: Some components in some preset tablets and computers got upgraded
/:cl:

### CODE REVIEW

**Comment by du-top** [comment]
Kinda liked the couch in the WO office, as sometimes more than one "guest" was "invited" there. Guess it is a good sign if I don't have something more substential to nag about.

**Comment by SingingSpock** [comment]
> Kinda liked the couch in the WO office, as sometimes more than one "guest" was "invited" there. Guess it is a good sign if I don't have something more substential to nag about.

Couch was moved into the bedroom portion, it's not gone.

**Comment by du-top** [comment]
Yeah, I saw that,  I am not concerned about wasting Marshals' furniture budget. It's just ... if I and another person (or more) get invited into the WO's _bedroom_, it ... hits different. Admittedly, more chairs across the WO's desk would work, too. It's just an impulse, don't want to start a discussion, I just wanted to hint that the last times I used this office as a "guest", the couch was the first (and only?) thing that got used.

**Comment by SingingSpock** [comment]
Tests pointed out a couple things, don't merge until I've had time to fix them in the morning

**Comment by SingingSpock** [comment]
Okay, this should be good to go now.

**Comment by Trilbyspaceclone** [comment]
Why is CRO losing the chem implant controler and tracker console?

**Comment by Trilbyspaceclone** [comment]
image

What do these 2 new buttons do?
image

**Comment by Trilbyspaceclone** [comment]
image
Their should not be a massive open space right their 
I dont get why your removing the decoration lift
No head of staff should get their own bedroom, side rooms are fine but bedroom isnt
the new office is tile for tile the biggest and has little reason to be

**Comment by cdb-is-not-good** [comment]
pls post pics of all changes in the PR desc

**Comment by cdb-is-not-good** [comment]
pls post pics of *all* changes to PR desc

**Comment by AysheDaArtist** [comment]
We removed bedrooms to discourage "guests" while in head positions
It's generally accepted that heads go home, in the lower colony, they don't just live on surface

Why are we returning bedrooms?  The CEO even has a little secret bedroom that shouldn't be there.

**Comment by SingingSpock** [comment]
> Why is CRO losing the chem implant controler and tracker console?

Because 1) they don't need it, those implants are security tools. If the WO gives a parolee a tracker/sleepy implant, the CRO shouldn't be touching that. 2) If for some reason they do need it, they can use the one on the bridge or I think even make their own (on mobile so can't double check). 3) the space you say to move the filing cabinet to has a table with important stuff on it.

**Comment by SingingSpock** [comment]
> image
> 
> What do these 2 new buttons do? image

Bolt/unbolt and open/close the door. Every Head office now has these

**Comment by SingingSpock** [comment]
> image Their should not be a massive open space right their I dont get why your removing the decoration lift No head of staff should get their own bedroom, side rooms are fine but bedroom isnt the new office is tile for tile the biggest head of staff room (preimer dosnt count) and has little reason to be

The open space is a briefing zone similar to the (much larger) open space a level down for Blackshield briefings. The decorative lift serves no purpose but to confuse new players, making functional use of the limited in-colony space will always take precedence over massive "decorations" to me. The reason it's the biggest (maybe excluding CEO, who also gets a full bedroom with attached bathroom) is simply because that's the space I had. It needed to be bigger, and the side room (even if I make it not a bedroom) needed to be below the bathroom. This put constraints on how the rest needed to be shaped.

**Comment by SingingSpock** [comment]
> pls post pics of _all_ changes to PR desc

Will do when I get home

**Comment by SingingSpock** [comment]
Images of all Head offices posted

**Comment by cdb-is-not-good** [comment]
This is fine, will testmerge to make sure this doesn't nuke the map as Bams Pr was unmerged.

**Comment by Trilbyspaceclone** [comment]
> This is fine, will testmerge to make sure this doesn't nuke the map as Bams Pr was unmerged.

theirs still a cat walked grass tile

**Comment by cdb-is-not-good** [comment]
> image Their should not be a massive open space right their I dont get why your removing the decoration lift No head of staff should get their own bedroom, side rooms are fine but bedroom isnt the new office is tile for tile the biggest head of staff room (preimer dosnt count) and has little reason to be

Do agree that this lil meeting area is a bit....weird? And a bit too sparse. Please fix the grass tile when you get a chance as well.

**Comment by SingingSpock** [comment]
> > image Their should not be a massive open space right their I dont get why your removing the decoration lift No head of staff should get their own bedroom, side rooms are fine but bedroom isnt the new office is tile for tile the biggest head of staff room (preimer dosnt count) and has little reason to be
> 
> Do agree that this lil meeting area is a bit....weird? And a bit too sparse. Please fix the grass tile when you get a chance as well.

What I can put there is constrained by the need to keep the sightlines from the WO office, so it can't be a room or anything opaque. I could maybe move/put a couple vendors in the area, but it wouldn't really help that much with it feeling empty. I went with a briefing room because it works for Blackshield to fill a big, empty space, figured it'd work here too. Eventually I'd like to remap Marshals wholesale to fix the workflow issues with it, but this at least fixes one of the issues.

**Comment by SkinkHunt** [comment]
Apologies for a late reply. The bedrooms were being added back due to popular demand. When Rebel made the new map, all the private quarters for HoS's were removed. Except the WO and CBO, I think. I re-added the guild and LS rooms, when I added the pool and dorms back into the map. 

If you want to punish head of staff who are not doing their job, don't remove things from maps. That's horrible game design philosophy. So what if they have a place to chill when they want. Ultimately they have to do their job or get demoted.

**Comment by cdb-is-not-good** [comment]
>I've never found the "but they'll avoid doing their jobs" as a valid argument for removing the bedrooms or private quarters. The presence of the LS room has yet to even cause that issue since I added it. Not one complaint about a CEO not doing their job because they were in that room.

Because it never was a valid argument. Rebel would point to an event happening 1 round out of a hundred as a valid cause to remove this or change that.

**Pull request merged**
