### PR TITLE
Add Crinos + Allow for species-specific speak-only languages

### PR DESCRIPTION
**Pull request by Ryan180602**
## About The Pull Request
<details>
<summary>
	Adds in Crinos, Sablekyne language. Current lore bracket idea is as follows, and is subject to change pending lorepeople.

"The native language of the Sablekyne, Crinos, is nearly unintelligible to humans, a flowing language consisting of rolling r's, chrips, and other assorted sounds. Once thought to have died out due to extensive SolFed efforts- but later rejuvenated via re-use by Sablekyne (and even Human) linguists, travelers, traders and pilgrims.
Reforms in education systems across northern Onkarth in particular has made it mandatory for a local dialect of Crinos to be taught to elementary sections of the structure; an effort made to reinvigorate their language post-occupation."

Also, species-specific speak-only languages can be added. A bit jank, and can be done better. But this should work

</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
add: Adds Sablekyne language, Crinos.
/:cl:

### CODE REVIEW

**Comment by Ryan180602** [comment]
No language similarities were added since it's supposed to be a born-on-home pure Sablekyne tongue. but if we want a more bastardised, Sol-mixed lingo per lore, minor similarities can be added

**Comment by cdb-is-not-good** [comment]
Thematically I have no objections. I want to do a lore review and if you would, please get Risikio to give this a review(he's one of the most familiar)

**Comment by Ryan180602** [comment]
PR needs a quick commit. will do in a little while. DNM till then

**Comment by Ryan180602** [comment]
Added exception to language code to allow for people to add species-specific speak-only languages. So this is not just a `Add Crinos` PR, it's also a `Add Crinos + Do a bit of language changes` PR

beware. should be ready for check and approve provided tests dont fail

**Pull request merged**
