### PR TITLE
Makes low blood more lethal.

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Bloodloss damage values significantly raised.

Low blood warnings for players given some slight differentiation to better allow for guessing at overall bloodloss level

In summary, damage(real damage.) now starts at 'blood_okay' levels of bloodloss, causing 5 oxyloss(up from 1.5).

Damage ramps up from there, from blood_bad to 10 oxyloss, and then to blood volume < 1 at which point it is 20 damage, as current.

This *should* hopefuly fix the issue where someone could walk around with 40% blood capacity and suffer no ill effects.

Some slight testing, oxy-loss is generally still pretty negligible until you hit critical bloodloss(about 60% percent blood volume) at which point it will rapidly kill you. If quick enough, innaprov/dex will severely slow said death.

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by DerFlammenwerfer** [comment]
I can confirm from experience in-game that blood loss is extremely lethal, and that inaprovaline, dex, and dex+ all are very helpful. I was able to keep someone who was at 50% blood with dead heart, lungs, and blood vessels alive long enough to surgically replace all organs, before giving them a dose of Sanguinium and Iron to restore their blood levels.

**Comment by DustanHache** [comment]
I feel like it's currently overtuned, as even dropping to 70% blood (which is something i do frequently, especially when swarmed by termites or spiders) is basically a death sentence unironically. this is hugely painful to deal with as anti-bloodloss meds and dexalin are not readily available outside of medical. inapprovaline *does help*, but is usually a stall for anyone who isn't medical.

**Comment by cdb-is-not-good** [comment]
That may just mean we need to slow down bleeding a bit.

**Comment by SkinkHunt** [comment]
Testing with quickclot also yielded the result of not stopping bleeding before bleeding out

**Comment by cdb-is-not-good** [comment]
unrelated to this PR quick-clot appears broken.

**Comment by king5327** [comment]
I'm gonna leave a good-to-merge on this, since it works as intended. That said, having some fixes to the peripheral issues would be nice.

**Pull request merged**
