### PR TITLE
Change the code reference of the Cog from 'Retro' to Cog

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
Change the internal code name of the Cog from 'retro' to 'cog' so that it make more sense.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Please do not do this, as its to keep in line eris

**Comment by hex37** [comment]
Don't listen to Trilby- do it

**Comment by Trilbyspaceclone** [comment]
No!
Must be cryptic must be coder lingo! CODER SPEAK!

**Comment by Kazkin** [comment]
Normally I prefer to keep things inline with eris but this is more clear and its pretty obvious what the retro to cog is here.

**Pull request merged**
