### PR TITLE
Webvest Sprite

### PR DESCRIPTION
**Pull request by Churro55**
replace: The ancient webvest icon sprite. Made a new one months ago but forgot to add it, so there it is.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Kicking the bots to work

**Comment by Trilbyspaceclone** [comment]
Odd guess githib has some tools degenration to not do the icon bot

**Comment by Kazkin** [comment]
Conflicts but good to merge once fixed.

**Comment by Trilbyspaceclone** [comment]
Putting this in a bug fix pr

**Pull request closed without merging**
