### PR TITLE
Power to the guild

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Removes most generators and ways to get them from the map except the 3 from spider with 2 of them being moved around, logistics no longer can produce generator boards so you are stuck with what guild has or can make from their nanoforge. Yes this means soteria can get atoms with 1 less research so like eh.
Diesel
Prepper

Removes church solars as they don't really generate much power for the tickrate they devour
churchsolar

Also fixes faulty wiring in soteria outpost (but I hate it either way)
	
<hr>
</details>

## Changelog
:cl:
del: Generator Acquisition
del: Church Solars
fix: Faulty Wire
/:cl:

### CODE REVIEW

**Comment by DorfGuy1** [comment]
hey uh. This kind of screws up RND's progression. Soteria science doesn't need an L like this. Plus there've been times where soteria has to fix power when there's no guild.

**Comment by ActuallyALovelyGrave** [comment]
@DorfGuy1 Yes, Trilby and Lamasmaster both ignore all other factors regarding of such harsh changes. I don't know what happens right now in the community, but i would love to see that somebody else points out some weird stuff that being merged without any compains, or otherwise we will see another boring 'high-RP' bay build.

**Comment by du-top** [comment]
Great, who needs power in lowpop anyway.

**Comment by Nep993** [comment]
genuinely a kind of dumb change

**Pull request merged**
