### PR TITLE
gatehouse tweaks + glass buffs

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
## About The Pull Request
<details>
<summary>
Reworks the checkpoint a bit. Mostly, it's been made a bit bigger and a bit more secure. While the perimeter on the whole remains made of tissue paper, the main port of entry is now slightly harder to smash through in a slugout(The main doors are unchanged so if no one is there you can still get through in like....seconds.).

Also makes it a bit bigger, adds  some more storage space(including secure lockers with security access requirements for throwing contraband, weapons from outsiders, etc), a couple of wall lockers for troopers to leave their guns/helmets when not actively in use, a coffee/smoke vendiing machine and an exosuit charger).

Adds some granularity to more areas. 'Main Gate is now split into main, east and west.

Finally,  buffs windows/Glass shutters, they've received a 'bit' more health and toughness such that sneezing on them won't instant cause them to explode.  These buffs apply more resistance/health to various windows. Maybe this will result in the guild having to do less glasswork(lol)
image

</summary>
<hr>

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
the linters found errors

**Comment by cdb-is-not-good** [comment]
...oh, right. I suppose i shouldn't be too surprised.

**Comment by cdb-is-not-good** [comment]
why tf every area needs a vent+scrubber 😭

**Comment by du-top** [comment]
If you want sturdier glass at the gatehouse... use sturdier glass instead of changing all the glass in the world? It's glass! It's supposed to break!

**Comment by cdb-is-not-good** [comment]
I don't just want sturdier glass at the gatehouse :p I want all glass to be slightly less silly easy to break. Thick glass is infact quite strong - not that that matters much. But it felt a bit TOO easy to break.

**Comment by du-top** [comment]
how many hits with a crowbar do _your_ windows withstand?

**Comment by cdb-is-not-good** [comment]
how many windows do _I_ have that're videogame windows? They're still significantly easier to break than a wall as they should be but the idea was to make them less comically weak, it's a fairly minor buff.

**Pull request merged**
