### PR TITLE
The Great Air Alarm Fix of 2024

### PR DESCRIPTION
**Pull request by AMcilraith**
## About The Pull Request
<details>
<summary>
	Turns on the air alarms and optimises map alarms.
</summary>
<hr>

It turns the air alarms on by default, allowing them to scrub out contaminants without being unlocked every time.
Optimizes air processing by removing unnecessary air alarms, replaced with fire alarms.
	
<hr>
</details>

## Changelog
:cl:
tweak: turns air alarms by default
tweak: removes over 180 uneccessary air alarms, replaces most with fire alarms
/:cl:

### CODE REVIEW

**Comment by AMcilraith** [comment]
> This pr conflicts with other current ones and with preposed redo of bridge area will make this unable to be merged You also make the suna and hottube areas unable to be overheated as you had removed those ones.
> 
> Air Alarms act like space heaters/coolers when temp is outside the set number, and are blocked by walls/doors thats why theirs so many.

Is it possible to add some kind of temepreature detection to the fire alarms, and have them feed back this information to the air alarms, or no?

**Comment by AMcilraith** [comment]
from what i see, they already check temperature, it it's above 200C they trigger

this wouldn't be hard, I don't think.

**Comment by Trilbyspaceclone** [comment]
Id suggest making high risk areas that more commonly would need air treatment be mapped in with the vent/on or scrubber/on and then an air-alarm that is set to scrubbing
Rather then all the events ever

Again replacing many of the air alarms means a lot of areas no longer cool down as fast or at all if heated by lets say a welder fuel fire.

**Comment by AMcilraith** [comment]
> Id suggest making high risk areas that more commonly would need air treatment be mapped in with the vent/on or scrubber/on and then an air-alarm that is set to scrubbing Rather then all the events ever
> 
> Again replacing many of the air alarms means a lot of areas no longer cool down as fast or at all if heated by lets say a welder fuel fire.

i can do this, and it'd probably be able to be done after the latest map pr

closing Pr, to be updated map-side when able.

**Pull request closed without merging**
