### PR TITLE
Cuts down on avable slots

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Colonist are no longer endless slots
Most departments now have less maxium staff

### CODE REVIEW

**Comment by lolman360** [comment]
>6 colonist slots

wat

**Comment by cdb-is-not-good** [comment]
:squint:

**Comment by IrkallaEpsilon** [comment]
> Firstly there is absolutely no reason for this to be spawning, secondly it will screw up loot and make all these items more common, thirdly, this is possibly a direct violation to contributing guidelines, I should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by Dopiotl** [comment]
This should be subject to a very important discord vote.

**Comment by Dopiotl** [comment]
And, shouldn't the focus be on the amount of people online but not actually playing. Please

**Comment by cdb-is-not-good** [comment]
Gonna deny this for now, other headmins are in agreement that this is a no go. If compelling arguments can be made for this PR or more players/devs rallied behind it then soft maybe, but I can't stand by this change at this time.

**Pull request closed without merging**
