### PR TITLE
Laser tag vendor

### PR DESCRIPTION
**Pull request by LongSleeves**
Adds all 4 colors of laser tag guns and accessories to the Toys 4 Us vendor in the lonestar lobby.

*Tested on personal server.*
Each gun was given 25 credit price
Armors were 25 credits
Headsets were 10 credits.

Vender has 5 of each item for 5 man teams. (didn't think most teams would have more then 5)
Has all 4 colors in case your doing a 4 man free for all.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Cool change, only slight concern- don't these items have actually a not small amount of materials in them? Hence why they would always get deconstructed. Maybe we'll want to switch them to just have a lil bit of steel/plastic each so this can't be gamed

**Comment by cdb-is-not-good** [comment]
also i assume they aren't mapped in for a reason?

**Comment by Trilbyspaceclone** [comment]
that means we can get rid of the lockers so people have to pay a price!

**Comment by Trilbyspaceclone** [comment]
They are mapped in to the toy venders

**Comment by SingingSpock** [comment]
> Cool change, only slight concern- don't these items have actually a not small amount of materials in them? Hence why they would always get deconstructed. Maybe we'll want to switch them to just have a lil bit of steel/plastic each so this can't be gamed

Just checked, it's already miniscule amounts of plastic for the guns and a normal-for-suit amount of biomatter for the vest

**Comment by cdb-is-not-good** [comment]
ah okay based, I stand corrected then.

**Pull request merged**
