### PR TITLE
Changes the absolute's pronouns

### PR DESCRIPTION
**Pull request by elgeonmb**
## About The Pull Request
<details>
<summary>
	Changes the Absolute's pronouns
</summary>
<hr>
It uses it/its now.

	
<hr>
</details>

## Changelog
:cl:
tweak: The Absolute now uses it/its

/:cl:

### CODE REVIEW

**Comment by BigBadPossum** [comment]
Cringe.

**Comment by MSieghardt** [comment]
Cringe.

**Comment by elgeonmb** [comment]
Get bent :)

**Comment by Legate-Maxson** [comment]
cringe

**Pull request merged**
