### PR TITLE
Add a new tail

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
<details>
<summary>
	About The Pull Request

Adds in a new tail
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
supper odd its not showing icon bot

**Comment by TheSleepyCatmom** [comment]
Checked through it too. Also too reminiscent of the old Xeno tails for me to +1 it. Not into the idea that people are going to try RPing Xeno-splices like they try to do with Renders every so often after we added those tails. Rather just avoid the fuck out of it.

**Comment by Guidesu** [comment]
> Checked through it too. Also too reminiscent of the old Xeno tails for me to +1 it. Not into the idea that people are going to try RPing Xeno-splices like they try to do with Renders every so often after we added those tails. Rather just avoid the fuck out of it.

I don't see harm on it. TBH. Its more for person who needs an tail like that i just put xeno on the name because i was out of ideas

**Comment by cdb-is-not-good** [comment]
Looking closer it's - okay. I suppose. Though don't call it that in code or it'll be taken for it ;v

**Comment by Guidesu** [comment]
> Looking closer it's - okay. I suppose. Though don't call it that in code or it'll be taken for it ;v

Alright

**Pull request merged**
