### PR TITLE
Better names

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Redoes many alt tiles adding in more better descripting what that person does 
Removes all cases of lower ranking Alt titles as people thought a lower pick was a lower rank, should clear up that confusion

### CODE REVIEW

**Comment by ThePainkiller** [comment]
I was gonna say the same as Kavric, specifically on the cases of _"Marshal Junior Officer"_, _"Research Assistant"_ and _"Soteria Medical Intern"_, these are jobs that **DEFINITELY** need these alt titles to distinguish someone that's new to the profession and is still learning the ropes of processing / medical / general science
Also "Guild Tinkerer" would be way better than _"Fabricator"_, and _"Junior roboticist"_ never made much sense either.

**Comment by Spoopy11** [comment]
We need junior titles to show that people are _juniors/in-experienced in their field._  This is a removal and needs a replacement if you want this to be a thing IMO.

**Comment by cdb-is-not-good** [comment]
The reason this PR exists is due to an issue where certain morons would treat 'juniors' like lower ranked staff and either push them out of doing work or otherwise treat them poorly. Which 'is' a tiny bit of an issue, but one i would prefer to have handled IC/OOC rather than via code.

**Comment by Trilbyspaceclone** [comment]
The IC fix is only a bandaid to an issue that will always bleed through untill its standard notion. The only fix is to correct its titles as is

**Comment by cdb-is-not-good** [comment]
Not willing to merge this without other dev-staff approval of some kind. While the concerns you raise are valid i feel like there's better ways to handle them than outright removing these alt-titles that are widely used.

**Comment by elgeonmb** [comment]
Hot Take: I play a research assistant because I want to play someone who is lower-ranked, inexperienced, and not really seen as as capable their colleagues :P

Obviously sometimes people can be a dick about it, but I feel like if you're playing a junior title for more than a handful of rounds that this is an experience you've basically signed up for, and if you don't like it you can just... change your alt title. This kind of a fix would make sense if the problem we were seeing was people eating up job slots as junior titles and then refusing to do their job using a lack of experience or training as an excuse, but I don't think that's happening and as it stands this is just closing off an entirely opt-in experience of play because some people opted in and didn't like it!

**Pull request merged**
