### PR TITLE
Enable space fortress again with some minor map changes.

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
image
the bluespace shards should be removed do to entropy - im aware im the one that mapped it, for the event but now that its over it should be removed

Theirs also a half of the scrapper ship seemly in the middle of space not sure if thats intented
image

**Comment by Guidesu** [comment]
should be ready

**Comment by Trilbyspaceclone** [comment]
Skink requested this to be untest merged do propis shuttle error, and performance

**Comment by cdb-is-not-good** [comment]
This has been dead in the water for some time now. If you can resolve the issues with the PR feel free to remake it

**Pull request closed without merging**
