### PR TITLE
Use role's alt title instead of assigned role when cryoing

### PR DESCRIPTION
**Pull request by du-top**
## About The Pull Request
<details>
<summary>
	Use role's alt title instead of assigned role when cryoing
</summary>
<hr>
This way the titles used in the announcement are the same in joining and leaving. So I won't join as nurse and leave as doctor.

	
<hr>
</details>

## Changelog
:cl:
fix: Use role's alt title instead of assigned role when cryoing

/:cl:

### CODE REVIEW

**Comment by du-top** [comment]
Untested, thus draft.

**Comment by king5327** [comment]
I mean, given the scarcity of the changes, I can see this being testmerged.

**Comment by du-top** [comment]
"Cryogenic Oversight states, "Meryl Roberts, , has entered long-term storage."
... shit.

**Comment by king5327** [comment]
> "Cryogenic Oversight states, "Meryl Roberts, , has entered long-term storage." ... shit.

I already resolved it with the pr just above your comment.

**Pull request merged**
