### PR TITLE
Makes the subtle verb hidden to ghosts

### PR DESCRIPTION
**Pull request by wb13**
## About The Pull Request
<details>
<summary>
Conceals the content of the subtle verb from ghosts - for when players really only want those close by to see.
Logs are still created as appropriate.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
Whispers hidden to ghost - No.
Subtle hidden to ghost - Yes.

**Review by KathyRyals — CHANGES_REQUESTED** [review]
Whispers hidden to ghosts - No.
Subtle hidden to ghosts - Why not.

**Review by KathyRyals — APPROVED** [review]
Looks very okay. Did you test this ?

**Comment by wb13** [comment]
> 
> 
> Looks very okay. Did you test this ?

Yep, double-checked locally with another player.
Cleaned up a couple lines though, so might need another approval.

**Comment by KathyRyals** [comment]
Can you change the Subtle verb to Subtle(anti-ghosts) in the verb list ? So it accurately reflects the new behaviour.

**Comment by wb13** [comment]
> 
> 
> Can you change the Subtle verb to Subtle(anti-ghosts) in the verb list ? So it accurately reflects the new behaviour.

Sure, done.

**Pull request merged**
