### PR TITLE
Swaps out "advanced laser turrets" Lasercore to a lasercannon

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Titiania laser cannon is a better lore fit for the preppers and void wolf base

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Awww, I'm gonna miss the Laser Core energy guns, they were pretty neat

**Comment by Trilbyspaceclone** [comment]
Still can be found in disks @ThePainkiller and the like

**Comment by ThePainkiller** [comment]
> Still can be found in disks and the like

Well, yeah! But no longer a **guaranteed** drop will make it rarer, a shame. Think that wolves can have laser cores instead of cogs, and let only Greyson bots have cogs?

**Comment by Trilbyspaceclone** [comment]
Cogs are so plentiful that they are used these days by Voids as its cheap and still powerful for its age

**Pull request merged**
