### PR TITLE
[MDB IGNORE] [IDB IGNORE] mapping

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Properly coverts all maps to proper formats
Adds 3 new mini junkfield ruins
1 is an atmos setup were you can get some more air and jectpacks
1 is a over-filled room with a combat drone and some goodies
1 is a glass box with some weapons and a combat drone

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by r4d6** [comment]
What are proper formats and why isn't BYOND's native map format enough?

**Comment by r4d6** [comment]
This PR change the native BYOND format to the TGM Map Format.

This new format doesn't improve performance, the only thing that it does is reduce conflict when two coder work on the same map, which we don't have a problem with thanks to the low amount of coder.
As a downside this will require *all* coders to run the converter after every map edit.

To summarize, changing the format will increase the workload on the coders & mappers for no significant benefits.

**Comment by Trilbyspaceclone** [comment]
when we get the CI changes in it will help with that running more smoothly

**Comment by Kazkin** [comment]
Conflicts.

**Pull request merged**
