### PR TITLE
Makes the bar and exterior more stylish

### PR DESCRIPTION
**Pull request by Chevalt**
new coded bar
New Exterior
Bar change! This makes the bar into a more stylish modern chic city bar, with better floors, more table for the bartender's convenience, separations between the restaurant and the bar, and more style. This change is purely aesthetic and QOL, no critical areas have been changed.
Screenshot in map dev

This PR also changes the colony exterior by adding a spaceport along with a new social area, being a sand pit (which was requested by players, since it was present before) and a pond.

Duplicate APC present on screenshot not present anymore after fix

### CODE REVIEW

**Comment by SkinkHunt** [comment]
Yes, please. :)

**Comment by ZoeTwinscythe** [comment]
The cited changes look like improvements to me. Ship it!

**Comment by cdb-is-not-good** [comment]
put the screenshots in ur actual PR .........

**Comment by Dogorb** [comment]
I like it, seems like a good change to the bar.

**Comment by cdb-is-not-good** [comment]
Amazing & perfect. Merge asap

**Comment by cdb-is-not-good** [comment]
As a general rule, once a PR is marked good to merge don't keep making changes to it without notifying someone. Im not going to be merging this for now till A. that little issue with the dupl.icate APC is fixed and B. I hear back about what these changes are

**Pull request merged**
