### PR TITLE
Matrix transformation refactor, among other misc fixes and changes

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
Reasoning for this PR: Previously, whenever we applied a change to a transformation, we /completely replaced it/. This is because we had no way to make sure that things like resting (which rotates the transform by 90 degrees) wouldn't apply themselves over and over, since we couldn't track it.

My system doesn't track it, but makes sure that the transform isn't applied repeatedly, by returning if the flag given to this transform is already in the list of transforms.

What it does: Adds a new system for transforming matrixes. All procs are stored within transform_types.dm and all specific types are in types.dm. For what the procs do, what the vars do, read the code documentation.

What it fixes: Baby cerberuses not having their .5 scale applied. Yes. This is actually what this was made for.

Misc changes: Removes the bullet resize as it was inconsistantly applied, and I personally like big bullets more.

Testing steps: 
Spawn as human with 120% scaling and rest, unrest, matrixes work. Change size factor to 90%. Punch self to update icons, I resize back down to 90% size. Spawn baby cerberuses. They have the correct transformation and they fall over if I stun them. The same goes for all mobs.

Ghost and watch as the multi-z shadow of myself properly updates my transforms as they copy them. Watch ameridian crystals grow. Spawn ameridian golems, their initial transform works. Fuck with the spatial cutter, the slices are properly rotated. Call the procs manually, such as removing or adding certain transforms. It all works. 

IC impact: None at all lmao

## Changelog
:cl:
refactor: A new system for handling transforms, transform_types, contained in transform_types.dm. All instances of atom-based transform fuckery should be migrated to this.
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Tested?

**Comment by nikothedude** [comment]
> Tested?

i have testing steps you fool

**Comment by nikothedude** [comment]
also i noticed a few mistakes

**Comment by nikothedude** [comment]
agh that doesnt fix the issue

**Comment by cdb-is-not-good** [comment]
> > Tested?
> 
> i have testing steps you fool
Oh I see



> also i noticed a few mistakes

>:T

**Comment by nikothedude** [comment]
> > > Tested?
> > 
> > 
> > i have testing steps you fool
> > Oh I see
> 
> > also i noticed a few mistakes
> 
> T:<

its a big pr....... sowwy....

**Comment by cdb-is-not-good** [comment]
It's okay that's why I always ask, measure twice cut once and all that

**Comment by nikothedude** [comment]
image
new bullet sizes

**Comment by nikothedude** [comment]
the big ones are anti-material bullets aka tank shells

**Comment by nikothedude** [comment]
FUCK BAD ARGUMENTS

**Pull request merged**
