### PR TITLE
Marshal vendor actually marshal

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Makes it so the marshal vendor sells marshal equipment, that is one that they no longer use (Ladon, Minotaur, Zeus etc.) but did at one point in time, it was weird to me that majority of weapons in that vendor weren't ever even used and don't even belong to the brands associated with them (a church revolver, seriously ?), some price adjustements too so that you won't get utterly ripped off by rest of the stock.
Clarissa is also back since it exists, does in loadout too just yeah got axed from vendor.
Changed the structuring of the vendor so you get LTL and regular magazines seperated to make it bit less obnoxious to scroll (boxes still aren't)
	
<hr>
</details>

## Changelog
:cl:
tweak: Marshal Vendor
balance: Marshal Vendor
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Only took a brief peek but I'm a bit concerned about the prices. Vendors historically are on the pricier side to discourage sidestepping the actual department/players who can provide the goods

**Comment by Lamasmaster** [comment]
Yeah dunno about the prices either honestly kinda just put something down to make sense not much else

**Comment by Trilbyspaceclone** [comment]
conflicts with blackshield pr thing

**Comment by cdb-is-not-good** [comment]
Bump the prices just a bit and this will probably be good to go.

**Comment by cdb-is-not-good** [comment]
Trilby was correct. This conflicts.

**Comment by Lamasmaster** [comment]
Screaming

**Comment by cdb-is-not-good** [comment]
Good for testmerges if @Trilbyspaceclone has no complaints

**Comment by cdb-is-not-good** [comment]
Criminy.

**Comment by cdb-is-not-good** [comment]
@Lamasmaster I assume this is done being worked on and doesn't need any more tweaks>

**Pull request merged**
