### PR TITLE
new utility hardsuit modules

### PR DESCRIPTION
**Pull request by lolman360**
hardsuit cargo clamp, lets you load structures. prevents you from mounting mounted or held weapons (eblade/eshield/lasers)

hardsuit grappler, lets you throw yourself at things/throw things at yourself. hooking in mobs has a long cooldown (10x)

no longer wip, tested, works fine

## Changelog
:cl:
add: hardsuit grappler and hardsuit cargo clamp. grappler is soteria/trade beacon exclusive for now, cargo clamps start on select hardsuits (industrial preloaded, techno preloaded, CE preloaded)
iconadd: new sprites from tg for the new modules 
/:cl:

### CODE REVIEW

**Comment by BigBadPossum** [comment]
Not sure on this one, I'd like a full break down on what it can fully do.

**Comment by lolman360** [comment]
> Not sure on this one, I'd like a full break down on what it can fully do.

grappler works like a gun: you fire it at something. if it hits a turf, it pulls you towards the turf. if it hits a unanchored structure or unanchored mob, it pulls it to right next to you. if it hits a anchored mob or structure, it pulls you in towards it.

the projectile does no damage. It has a decent charge cost (1000) and has a 10s cooldown on hitting mobs, so you can't stunlock people with it. It has a 1s cooldown on hitting other things, but this combined with the high charge cost and low availability is enough. Additionally, it (intentionally) uses `throw_at`, meaning if you use it in a hardsuit with low armor, you'll take damage from slamming into walls.

If it's still too good for pulling people in, I can make it only drag people 1-2 tiles. If it's too good as a mobility tool, I can bump up the cooldown and also restrict it from mounting weapons.


cargo clamp is basically a ripley cargo clamp, but in a hardsuit. It can cube scrap piles, load unanchored structures and such. Can't load mobs or items, can't do damage, can't force airlocks.

**Comment by BigBadPossum** [comment]
I think most of its good to go except the cargo clamp, that is absurdly powerful as a player could load a ton of storage with it. Hard limit it to only be able to load 1 crate/dumpster/locker/whatever and it'll be good to go, as that might actually get some people to use a hardsuit without being too good.

**Comment by lolman360** [comment]
> I think most of its good to go except the cargo clamp, that is absurdly powerful as a player could load a ton of storage with it. Hard limit it to only be able to load 1 crate/dumpster/locker/whatever and it'll be good to go, as that might actually get some people to use a hardsuit without being too good.

done, LS clamp can now hold 3 for moving ore drills around easier. Regular clamp can only hold one.

**Pull request merged**
