### PR TITLE
Removes Dogborgs (As requested)

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
People asked in dev-discussion to remove dogborgs. So here.

lore approved
image

this pr is within possums vision 👍
image

## Changelog
:cl:
removes: dog borgs
/:cl:

### CODE REVIEW

**Comment by ApplePlastic** [comment]
this will be terrible for the cyborg economy.

**Comment by hex37** [comment]
won't fix the core problem; we'll still have furries once it's all over

**Comment by Stutternov** [comment]
> won't fix the core problem; we'll still have furries once it's all over

can solve this with a second pr if requested

**Comment by Trilbyspaceclone** [comment]
The issue its addressing is on request, thus it does properly handle the task its trying to achieve.
Meaning: Wont Fix, as a tag is not applicable to this pr
Invalid, is not applicable to this pr
 Salt/Skill issue maybe

**Comment by Thegreatspidernonbinary** [comment]
Firstly there is absolutely no reason for this to be spawning, secondly it will screw up loot and make all these items more common, thirdly, this is possibly a direct violation to contributing guidelines, I should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by MLGTASTICa** [comment]
Vore fetish content being removed ? i thought id never see the day coming.

**Comment by faaaay** [comment]
> Firstly there is absolutely no reason for this to be spawning, secondly it will screw up loot and make all these items more common, thirdly, this is possibly a direct violation to contributing guidelines, I should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

I think you posted this on the wrong PR

**Comment by Dongels** [comment]
@Stutternov Do confirm that your game runs with these changes made. Your pr lacks any info for anyone to confirm apart from this just being a meme pr...that it works at all.

**Comment by Stutternov** [comment]
> Firstly there is absolutely no reason for this to be spawning, secondly it will screw up loot and make all these items more common, thirdly, this is possibly a direct violation to contributing guidelines, I should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

Your copypaste fails, funny man.........
- A furry content without any erotic or sexual context will attract people who will demand such content. If you need a proof for that you probably started using Internet yesterday.

I can port them to Eris for u doe (:

**Comment by cdb-is-not-good** [comment]
As stated before I'd rather we replace them with something more setting appropriate rather than completely nix them

**Comment by Stutternov** [comment]
> As stated before I'd rather we replace them with something more setting appropriate rather than completely nix them

wyci

**Comment by cdb-is-not-good** [comment]
> > As stated before I'd rather we replace them with something more setting appropriate rather than completely nix them
> 
> wyci

:(

**Pull request merged**
