### PR TITLE
Blob Spawning Rework #1

### PR DESCRIPTION
**Pull request by ApplePlastic**
## About The Pull Request
<details>
<summary>
	Prevents blob from spawning in the main R&D lab and Robotics, which are both critical areas. 
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Why are they critical areas?

**Comment by ApplePlastic** [comment]
The blob can delete everything in the R&D lab (autolathe, circuit printer and consoles included) and make it a hinderance for the rest of the round. Most things would have already been eaten due to the blob announcement's delay, since it only alarms when it is of considerable mass.

**Comment by cdb-is-not-good** [comment]
Doesn't the cro have a disk with all the stuff to make a new lab?

**Comment by ApplePlastic** [comment]
I am not entirely sure on that, honestly. This only prevents the blob from spawning directly inside these areas- anywhere around it is free game, if it spreads there fast enough. 

You could spend an hour or two gaining materials for the department, just for them to be deleted instantly by the blob happening to spawn right next to the autolathe (which is what happened in a very recent round).

**Comment by cdb-is-not-good** [comment]
Fair and reasonable

**Pull request merged**
