### PR TITLE
disk storage fix

### PR DESCRIPTION
**Pull request by benj8560**
Did a minor fuckup. Fixes disk storage fridge icon disappearing. Hopefully.

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
>:T

**Comment by benj8560** [comment]
fridge venders CURRSED I think I finally figured out a fix

**Comment by benj8560** [comment]
well I'd suggest test merging this for now to keep it open until I come up with a better fix. For now its about 90% working. The only issue that happens is when after inserting disks if you remove all disks from the disk storage the disk storage become invis. Given these are meant to store and organize disks...well a bit counterproductive to not have at least a single disk in them at all times.

**Comment by benj8560** [comment]
Trilby approved code. I think we good for full merge with this

**Pull request merged**
