### PR TITLE
Hydro nerfs*

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Hydropanics now has xeno bio and additional mapping work around - requested

Plants for chemical have a get a 25% reduction when are able to be repeatedly harvested, adding the trait juicy makes it 15% then level 2 juicy will be an additional +10% reduction then adding the new plant gene chem-maker makes it -25% reduced. 
(Aka adding them both gives a 1.25 mult compared to old + other stacking chem stuff) 

Plant maker chem can be found in the cargo trade beacon or randomly in random seeds if *extremely* lucky
As well as placed one in Xenobio
Allows for failing to harvest plants if you are unable to get a yield

Poppies chem rate lowered
Harm intent now instantly kill on hydrotrays if said item has attack force (no harm intent with like paper to instant kill every plant)
Pumpkins are now pumpkin looking and coloured to be yellow
Bees now only can give a max addition to the extra yeild  of 1.5 (I.e yield 10 means max extra yeild is 5 for bees to contribute to) 

PERK_GREENTHUMB now along with its healing of sanity will give a +1 to yield amount on harvest

Plant scanners give slightly more feedback on chemical mults and a few extra traits, as well as prints 10x faster

plants internal age now lowers extra yield, this
120 aged plants now tell you that your plant is old and being negatively impacted by age. This does not mean that plants below this age are being negatively affected. 

Increases base yields of the following plants:
berry bush, blueberry bush, tomato plant, eggplant, grapevines, cacao tree

Fixes a few kitchen tags being missing 

Potency mod from chemcials now only affects the tray it was added to, this resets pre removal of dead plants. - This is to stop every plant omni-sharing globally the edit to the trait. Helps make potency 100 rarer and more valued.
```
Why is this a good thing for the server? What problems were present that are solved by this? (We really should add this question to the template for PRs)

1. it improves feedback in terms of expected reagents
2. Actually brings upsides and downsides, better plants need investment.
3. Helps reduce over-all AFKing as you have more to work on.
4. Incentives departmental trading
5. buzz word
6. Fixes bugs, as well as adds qol (plant scanner stuff)
```

Ports over:
https://github.com/discordia-space/CEV-Eris/pull/8126

### CODE REVIEW

**Comment by Guidesu** [comment]
I would prefer 80 instead of 60. I don't know why 30 potency of nerf seems too harsh.

**Comment by cdb-is-not-good** [comment]
> I would prefer 80 instead of 60. I don't know why 30 potency of nerf seems too harsh.

50% is the standard we generally go by as a max nerf/buff. This is fine.

**Comment by Trilbyspaceclone** [comment]
> I would prefer 80 instead of 60. I don't know why 30 potency of nerf seems too harsh.

Addressed

**Comment by Dimasw99** [comment]
50% is pretty huge. I am not sure why this was even needed. I think it would be better to modify and adjust chem outputs in the seed.dm file instead of doing another jump in another file, it just adds confusion later.

**Comment by SingingSpock** [comment]
Why is this a good thing for the server? What problems were present that are solved by this? (We really should add this question to the template for PRs)

**Comment by SkinkHunt** [comment]
> Why is this a good thing for the server? What problems were present that are solved by this? (We really should add this question to the template for PRs)

good idea, tbh.

**Comment by cdb-is-not-good** [comment]
> Why is this a good thing for the server? What problems were present that are solved by this? (We really should add this question to the template for PRs)

Unmerging this for now till these questions are answered.

**Comment by cdb-is-not-good** [comment]
> > > Why is this a good thing for the server? What problems were present that are solved by this? (We really should add this question to the template for PRs)
> 
> 
>  it improves feedback in terms of expected reagents
> Actually brings upsides and downsides, better plants need investment.
> Helps reduce over-all AFKing as you have more to work on.
> Incentives departmental trading
> buzz word
> Fixes bugs, as well as adds qol (plant scanner stuff)
> 
> 
> 

How does giving Lonestar access to SI plant tech incentivize departmental trading

**Comment by cdb-is-not-good** [comment]
I have a question for all the people who are concerned about soteria being pushed out of their Monopoly How many of you actually made extensive use of xenoflora

**Pull request merged**
