### PR TITLE
Tonkette : Greece Edition

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Gives ability for guild and church together to finally realize their dream of owning their very own ""Tank"", sprites by Nayu / Monochrome#9090
	
<hr>
</details>

## Changelog
:cl:
add: Tankette
/:cl:

### CODE REVIEW

**Comment by DorfGuy1** [comment]
mechanized blackshield when.

**Comment by cdb-is-not-good** [comment]
Exact same problem as before with this. 

Why does the church need a tank? 

Why does the sprite use inconsistent perspective? left/right sprites are isometric, north is top-down. I said it on the last PR and I said it again, stick with one perspective. Neverminding that, jamming a tank into 32x32 is ALWAYS going to look janky and cartoony.

**Comment by Catalaria** [comment]
I'm not surprised that you once again came back with the same answered questions of previously, so I shall answer them differently.
First and foremost:
1.: Why the Church needs a tank?
Response: 
Better asked: "Why the Guild **AND** Church should not create competition with Soteria over their complete domain over the production of Mecha-types of combative units?"
First half of the answer: To consider the tankette as Church-only is shameful at best, considering the theme I'm going to provide for the following guild sprites have boundaries to dieselpunk and this is the first welcoming sight of such theme, but in Church colours. It is more of an Guild tank than it is an Church tank - it just happens to have these colours because code-wise, what covers the Guild's chassis comes from an litany. 
Second half of the answer: 
Complete monopoly over ballistic/para-military resources sticks as a sore thumb to me, considering how there's an clear competition/armsrace between certain departments over laser and plasma weaponry, what stops the competition of metallic structures made by an ACTUAL department focused on engineering, hardwares and the production of marvel-of-steel together with an faction that is getting their lore reworked with deep roots on surviving an complete onslaught that broke their society to dust? Plus, there's an good reason for the presence of the tank that is well answered in the description, if you dare to even look at it briefly for a second.

2. What the **fuck** you are talking about, Jessie? 
It's rather amusing to read the terms "inconsistent perspective" while I'm fully aware the perspective of my current sprite is more consistent than the toblerone/slanted walls people so much licks the balls about. Fully enough, you pointed out the WRONG errors of my sprites, what makes me wonder if this criticism is genuine or just spite of some ill-mannered degree. I hope not. We are all adults here.
The Frontal perspective is correct. the Continuous track is kept with the frontal platings enlarged for the player's view, with the back plating - that is larger, mind you - is slimmer, to portray distance. The reinforcements of the platings on the north have inclinations of 3/4 (Not top down. Look at the sprites correctly. If it was top-down it would be the stupid /tg/ walls.) and there's a "pull" of the steel backwards towards the tank's turrethead - again, 3/4, and the turret inclinates down instead of being just a slank ball aiming directly at the player - AGAIN, NOT TOP DOWN LIKE YOU SAID. (Now you understand why I think you said that for spite? There's NOTHING top-down here. It unironically feels like you are trolling, I'm not even trying to be disrespectful with you - please examine the sprite better if you want to criticize it) and the metal reflection of the turrethead gives direction of inclinations and ensures the player to be barely be able to see the overall circular inclinations of the back of the turrethead - WHAT. TOP. DOWN. WOULD. BE. SHOWING.
The Sideways sprites follows the same degree with an plausible inclination of the turrethead sideways while keeping the track's reinforcements with proper inclination in the frontal and backside sprite - showing the difference in size between the frontal plating and back plating. 
The only error I can see about my sprite is the BACK sprite - what you said it was isometric. But what gives it away is the presence of the HATCHET. it's an circular thing and reflects differently. But that can be improved with time - but as of now, this can be safely put aside, even more when we consider how ugly some of our mechas and sprites are, and are still kept. It isn't because of an slight little inconsistency everything should be scrapped off and threw in the trash bin.
Again, one of the reason I start to think you are against me on this idea entirely out of spite rather than genuine intention of criticism.
 
 


Do you even know what Isometric even means?

**Comment by Catalaria** [comment]
Spriting references.
https://cdn.discordapp.com/attachments/567023102257659914/1086466263917789294/9601.gif
https://cdn.discordapp.com/attachments/567023102257659914/1086466264253354054/9623.gif

**Comment by Catalaria** [comment]
Besides, if for you - 32x32 tanks always will look "janky and cartoony" then start changing the entire walls and armor sprites of Eris, since it all looks like plastic or gum, and change it to IS12 sprites. Go ahead, what side of sprite-style are you on?

**Comment by Catalaria** [comment]
I'm not surprised that you once again came back with the same answered questions of previously, so I shall answer them differently.
First and foremost:
1.: Why the Church needs a tank?
Response:
Better asked: "Why the Guild AND Church should not create competition with Soteria over their complete domain over the production of Mecha-types of combative units?"
First half of the answer: To consider the tankette as Church-only is shameful at best, considering the theme I'm going to provide for the following guild sprites have boundaries to dieselpunk and this is the first welcoming sight of such theme, but in Church colours. It is more of an Guild tank than it is an Church tank - it just happens to have these colours because code-wise, what covers the Guild's chassis comes from an litany.
Second half of the answer:
Complete monopoly over ballistic/para-military resources sticks as a sore thumb to me, considering how there's an clear competition/armsrace between certain departments over laser and plasma weaponry, what stops the competition of metallic structures made by an ACTUAL department focused on engineering, hardwares and the production of marvel-of-steel together with an faction that is getting their lore reworked with deep roots on surviving an complete onslaught that broke their society to dust?

Inconsistent perspective? Not at all.
Well- Let's talk about "inconsistent perspective" while I'm fully aware the perspective of my current sprite is more consistent than the toblerone/slanted walls people so much licks the balls about. Fully enough, you pointed out the WRONG errors of my sprites, what makes me wonder if this criticism is genuine or just spite of some ill-mannered degree. I really hope that's not the case - since you pointed out the goods as bad, while the "bad" wasn't criticed.
The Frontal perspective is correct. the Continuous track is kept with the frontal platings enlarged for the player's view, with the back plating - that is larger, mind you - is slimmer, to portray distance. The reinforcements of the platings on the north have inclinations of 3/4 (Not top down. Look at the sprites correctly. If it was top-down it would be the plain /tg/ walls.) and there's a "pull" of the steel backwards towards the tank's turrethead - again, 3/4, and the turret inclinates down instead of being just a slank ball aiming directly at the player - against, not top down. (Now you understand why I think you said that for spite? There's NOTHING top-down here. It unironically feels like you are trolling, I'm not even trying to be disrespectful with you - please examine the sprite better if you want to criticize it) and the metal reflection of the turrethead gives direction of inclinations and ensures the player to be barely be able to see the overall circular inclinations of the back of the turrethead - Topdowns would show it.
The Sideways sprites follows the same degree with an plausible inclination of the turrethead sideways while keeping the track's reinforcements with proper inclination in the frontal and backside sprite - showing the difference in size between the frontal plating and back plating.
The only error I can see about my sprite is the BACK sprite - what you said it was isometric. But what gives it away is the presence of the HATCHET. it's an circular thing and reflects differently. But that can be improved with time - but as of now, this can be safely put aside, even more when we consider how ugly some of our mechas and sprites are, and are still kept. It isn't because of an slight little inconsistency everything should be scrapped off and threw in the trash bin.

**Comment by cdb-is-not-good** [comment]
> Besides, if for you - 32x32 tanks always will look "janky and cartoony" 

It's almost like I already said exactly this as a reason to not make it a tank and to make perhaps literally any other shape. It is perhaps the reason why no one uses tanks? Because you force them into a shape they don't want to be- working AGAINST the limited canvas that's offered by a 32x32 sprite.

**Comment by DorfGuy1** [comment]
after this make an apc style metal box on wheels for BS. Two or three guys piling out of a short bus is just great style for BS

**Comment by Catalaria** [comment]
CDB. 
I still fail to see the "Light" on why this argument of yours even matters as an issue to the current PR. 
Using the argument "No one uses tanks" is an failure of argument, since many other servers have their own different types of tanks and many other vehicles. The lack of styles on their tanks, however, comes to another reason entirely: Spriting Capacity. I am sure you are FULLY aware that many tank sprites has been made in the past and currently in servers, from the CM top-down sprites to Civilizations's "wall-tanks." The reason Sojourn does not have any tank falls entirely to two reasons: There was no Sojourn/Eris spriter working on this project, and because Eris focuses on Retro-Futurism based on Star Trek just like how /tg/ does, **something we do not follow.**
You are literally throwing "Reverse Soul" argument on me - and "soul-safety" is as shallow as the surface of the human's skin, and I will tell you something, bud. I love eating souls out of sprites and I will continue doing that. Sprites are to be improved, sprites are to be advanced and rival actual games unrelated to byond or SS13. 
But CDB. What you said.
"Because you force them into a shape they don't want to be- working AGAINST the limited canvas that's offered by a 32x32 sprite."
I'm going to be honest, are you reading what you are writting...? "Working against the limited canvas?"... What the hell this means? 
You are trying to say "You are using everything the limited canvas provides you! You totally shouldn't use every single pixel of the sprite! You shouldn't work with dimensions! You are to be limited by my desires over your creative phenomenas for some stupid reason!"
That's the same argument of before that is extremely shallow and absolutely means nothing, the canvas is a tool and the limits must be followed to be suitable for the tile - and I will not increase it - and like a tool, I will use what it provides to the climax of my opportunities, because that's how a spriter is supposed to do it, an spriter that denies the opportunities for the sake of "I don't know" is just limiting themselves from actually providing art, but you'd be surprised to know I did not pushed the limits of the canvas, if that was the case, it would be enlarging it with coding, making an 46x32 sprite, or I don't know? Overlay? 
Look, CDB. I have a lot of respect for you - and I may understand your intentions of keeping Sojourn from having tanks, but with all honesty all your arguments until now makes absolutely no sense, it's like you are asking me to limit the spritingwork because of... I don't know, autism? It just makes no sense.
The sprite is there in it's clean shape, and people that got to see it up to this point absolutely loves the sprite and are hyped to see it around, minus the argument of yours and an misunderstanding coming from The Overfluff#3902 that thought that these Guild-church tanks were Ezoken's Blackshield *oval* tanks. 
CDB, please. Stop this, it seems that **you are just trying to find reasons to deny this PR for some other reason entirely unrelated to the spriting work, it can't be otherwise.** I might understand if you told me that's all because Sojourn should be more retrofuturistic, but for that I'd expect this argument from an actual headmin of the lore or something related to that to provide further informations, because if that was the case, many things that I made for the Church as of previously should've removed since these were meant to be Candlepunk, completely unrelated to Retrofuturism, what would end up "so... why are you blaming the tanks?"
I don't know if you are saying this because you can't see tanks being small - then RESEARCH about TANKETTES. These are SURPRISINGLY small - sometimes just slightly bigger or SMALLER than an human. check this out: https://cdn.discordapp.com/attachments/567023102257659914/1087896024170901606/images_-_2023-03-21T202705.837.jpg

Saying this again. The "reason" no one does a tank falls entirely to the fact that producing 3/4 sprites is very, very complicated - and no wonder people didn't made any highlight work before, and since you seemingly does not know - spriting in SS13 is only getting professional as it is recently, so please, stop being an barrier for development and allow others to perceive the presence of these tanks and make things out of it, so "up/down" tanks of other servers improves with us, that's how spriting works. With that said, all my words absolutely destroyed your shallow arguments. 
If you want to continue this, please, contact me directly on discord and allow our discussion to increase properly, and please, provide ACTUAL arguments against this PR instead of some sick prejudice.

**Comment by Dorodomki** [comment]
The tank is fucking good and is an Advance for a VEHICLE CODE we don't have polished, it looks good sprite wise, in lore wise adds an Advance for the colony technology and opens us a door for a new base for the development of new vehicles 

I love this why say no to a good idea?

**Comment by StarDustFoxFox** [comment]
I look at this tank and even so being compact still looks very good, visually appealing too, and fitting for church and guild, I don't understand what the fuss is all about, it is far easier to add new ideas than to remove em from code and this does look like a good idea, at least it gives the colony a new tool to work with, I can easily see it being used in events where colony has to break in somewhere, and for sure it would be badass for everyone involved to see the tank exploding/crushing a wall to allow the people afoot to rush in blaming fire, I just like the idea and potential it can bring both mechanical and RP wise

Why not just give it a try and see how it operates in game before letting any criticism and doubt be atop the table?, Maybe it works, maybe it doesn't, still testing it would be amazing for anyone involved, as well it adds more depth for colony, they have a tank, this is the closest we have to a proper combat vehicle that isn't a mech

**Comment by cdb-is-not-good** [comment]
>I still fail to see the "Light" on why this argument of yours even matters as an issue to the current PR.

I'm not reading all this mess. My complaint about the tank is the aesthetic of it first and the fact that you're giving a combat mech to a faction that really kinda doesn't need it and legally isnt even allowed to have such materiel. Is this just going to turn into the plasmaguns, where it is a curiosity that can never be used because the creator didn't actually stop to consider current IC policy?

>Why not just give it a try and see how it operates in game before letting any criticism and doubt be atop the table?,

because as you said, it's easier to add than remove. Concerns with a PR should be raised WHEN the pr is made not after, and this serves as a better forum for discussion than the discord

**Comment by Dissentbay** [comment]
> after this make an apc style metal box on wheels for BS. Two or three guys piling out of a short bus is just great style for BS

considering it would all fit on square, BS clown car? I'm not opposed, the only issue is like 4 BS coming out of a small car 🤣, just need the bike horn honk

>I'm not reading all this mess.

neither am I, guild having mechs was already proposed, plus technically it's not a mech, it's a vehicle, who happens to have a weapon? what next? can't use guns while on the cargo tug? can't hack the loaders to fit people, all of them holding guns and shooting at any threat?

**Comment by Catalaria** [comment]
"I'm not reading all this mess. My complaint about the tank is the aesthetic of it first " 
The argument about the aesthetic has already been settled. If the aesthestic is still an issue, you are either ignoring my arguments or trolling. Perhaps both.

"You're giving a combat mech to a faction that really kinda doesn't need it and legally isnt even allowed to have such materiel."
This ensures that you are indeed ignoring me as I did answer what you said about the idea of the tank and competition with Soteria. Also, put in your mind that this isn't JUST an church tank - since for some reason you tend to use the "a faction" in singular all this time. This is a Guild AND Church tank. While you are against the PR - Soteria is taking complete control of mechatronics. Besides, the tank is to set up an different theme.

Soteria can make the mecha alone as long as they have materials.
With the Guild and Church, it is mandatory to have an proper degree of faction interactions to make the tank. 

"Is this just going to turn into the plasmaguns"
Come again? If you mean the competition/arms race, what is wrong with it?

"you just hate me and dont want it added 🥺🥺🥺" when we should both know by now it has nothing to do with you."

Dear God, no. You got my words all wrong, I am not saying you have spite on me - but spite on the Church department as a whole. It is well know this is the most hated department there is - and the fault mostly falls to the dreadful ways that the department was directed by Possum, leading an really bad example accross the old playerbase - and now the new playerbase suffers from the shackles of old. I'm willing to make that different lore-wise, while talking with coders to make the church less of an chore and a deserving scapegoat with none of Kazkin's kinks/fetishes/warhammer stupidbabble and copying Eris NT lore.

 "so does that mean it conveniently bypasses the rules on combat mechs?"
Laws are flexible and can change accordingly. The guild provides the hardware, the church provides the software. Do have in mind that the church are allowed to make grenades, so what is the "step-wall?"

Please, don't get me to tell you again that the tank is not solely under the Church's ownership. This is only making that "spite" more obvious when you literally don't see the Guild existence.

**Comment by cdb-is-not-good** [comment]
>Soteria can make the mecha alone as long as they have materials.

And they cant take such a mech outside their department for anything other than testing. You do realize this, yes? They can only have a mech because their department has special rules for contraband within their walls.

>Come again? If you mean the competition/arms race, what is wrong with it?

literally never used because it's illegal. Plasma guns are explosives, which means owning or using them adds a bunch of issues that no one wants to deal with.

>Laws are flexible and can change accordingly. The guild provides the hardware, the church provides the software. Do have in mind that the church are allowed to make grenades, so what is the "step-wall?"

So change them yourself, offer some solution to the law issue currently posed rather than going "it COULD be fixed."

>Please, don't get me to tell you again that the tank is not solely under the Church's ownership. This is only making that "spite" more obvious when you literally don't see the Guild existence.

The arguments are the exact same for both factions since neither faction is allowed combat mechs, and the church is only allowed explosives under very specific circumstances.  I will repeat again, quit crying 'oh woe is me poor victim to CDBs apparent bias against the church'. My complaints were the exact same when Dromkii was trying to give the shield a Tank as well.

**Comment by ActuallyALovelyGrave** [comment]
I don't see a problem adding it into the game, since usual SOPs and admin/marshals ~~bitchery~~ about the laws and how they are important will make any usage of mechs and explosives barely real. As well as the standard combat-antag policy, this will be used more likely as a statue, rather as a proper mech.

**Comment by DorfGuy1** [comment]
> > after this make an apc style metal box on wheels for BS. Two or three guys piling out of a short bus is just great style for BS
> 
> considering it would all fit on square, BS clown car? I'm not opposed, the only issue is like 4 BS coming out of a small car 🤣, just need the bike horn honk
> 
> > I'm not reading all this mess.
> 
> neither am I, guild having mechs was already proposed, plus technically it's not a mech, it's a vehicle, who happens to have a weapon? what next? can't use guns while on the cargo tug? can't hack the loaders to fit people, all of them holding guns and shooting at any threat?

idk if mutiple people shoooting guns from one entiity would cause everything to have a stroke, but I'd assume it'd be a nightmare, so maybe no portholes on the BS clowncar/apc

**Comment by cdb-is-not-good** [comment]
> As well as the standard combat-antag policy, this will be used more likely as a statue, rather as a proper mech.

This is part of my issue with it. Why add the thing if it will never be used, like the plasmaguns?

**Comment by DorfGuy1** [comment]
anyway, this is a great idea. Having the guild be able to be essentially truck nuts adds a new facet for rp. I think they should get an exception in the SOP as well. BS should also get an APC. The church should get a tractor. And lonestar a forklift. As you can see, the meme potential of each of these vehicles should be maxed. This is entirely biased but I just like tractors. And if we give BS an apc we can have an event character give the "METAL BAWKSES" Speach from DoW. Having marshals give traffic citations would be funny. And taking a lonestar(tm) forklift certification course is a great RP opportunity. As a nod to some crackhead military 'reformer' on the internet, we should name the APC 'Gavin'. The apc would prevent people who know the forest less from getting lost, and let people haul shit out the next time something dumb happens and we all have to go out to the swamp to fight Kriosans, excel, ect

**Comment by ActuallyALovelyGrave** [comment]
@cdb-is-not-good Let the people have their own stuff for shit-and-giggles with no actual use. One day, in one day with some event that allows combat, it might be useful, or not...(Not really)
@DorfGuy1 
>I think they should get an exception in the SOP as well.

1)No, since this exception will just insult basically every other faction that can't have combat mech. Church already has a plenty of exceptions and exclusive stuff.
>As you can see, the meme potential of each of these vehicles should be maxed.

2)No, you can't have memes on soj, 'high-rp', even some far-away references were removed, as i recall correctly.

**Comment by DorfGuy1** [comment]
> 1)No, since this exception will just insult basically every other faction tha1t can't have combat mech on legal terms. Church already has a plenty of exceptions and exclusive stuff.
Fair enough. It is a tankette afterall. If any other factions get any vehicles. Like an APC, as long as someone isnt driving it round the colony, should be a bit looser, especially if it has no integrated weapons mountable. Forklift goes without saying.

**Comment by Guidesu** [comment]
Jesus christ it's just a tank on mecha code chill.

Sheep head approved this

**Comment by ChefDoggo** [comment]
> 

big fat stinky necro post but soj is still riddled with memes and shitposts, we literally have not one but TWO neco arc fumos and more than likely a few funny hahas drawn around the map that you can only see when editing the map

**Comment by ThePainkiller** [comment]
Burenyaa

**Comment by Lamasmaster** [comment]
Burenyaa

**Comment by cdb-is-not-good** [comment]
@king5327 Can i untestmerge this yet

**Comment by Dorodomki** [comment]
haha developed tank goes brrr

**Comment by Lamasmaster** [comment]
How is this still open ong fr fr 
203mm

**Comment by cdb-is-not-good** [comment]
Unmerging this again. I can let go of *most* of my other complaints if the sprite is changed to something less....goofy. Balance can be handled separately.

**Comment by Dorodomki** [comment]
> Unmerging this again. I can let go of _most_ of my other complaints if the sprite is changed to something less....goofy. Balance can be handled separately.

the pr contains code and spritework done and ready to be used, the sprite quality isn't "goofy" and is fairly better than almost all non catalaria/copy pasted eris/bay/tg sprite content on sojourn dude what yo even talking about grown man 😆  try to sprite something in a near quality

**Comment by Lamasmaster** [comment]
https://tenor.com/view/itsover-wojack-gif-4367840179675491690

**Comment by Lamasmaster** [comment]
https://tenor.com/view/chudbob-soypants-chudbobsoypants-chudbob-soypants-gif-11950911749488548032

**Comment by cdb-is-not-good** [comment]
https://media.tenor.com/393SodJjoOUAAAAC/fsq.gif

**Comment by Lamasmaster** [comment]
image

**Comment by Lamasmaster** [comment]
image

**Comment by Lamasmaster** [comment]
image

**Comment by Lamasmaster** [comment]
image

**Comment by cdb-is-not-good** [comment]
I'm going to kill you.

**Comment by Lamasmaster** [comment]
> I'm going to kill you.

image

**Comment by cdb-is-not-good** [comment]
image

**Pull request closed without merging**
