### PR TITLE
Vape and Command Role Age Requirements Salt PR

### PR DESCRIPTION
**Pull request by Obeycap**
## About The Pull Request
Updates: Child smoking
	
Tweaks cigarette vendors a bit and lets younger colonists take up higher positions, except in R&D and Medical, where they still need to be old enough to have a doctorate. Overly young characters should probably still be given shit for taking up command positions, it's just better to have that be an SOP and RP thing than a "you literally cannot do it" thing.

## Changelog

- Adds mint vape cartriges to the cigarette vendor.
- Removes cigar nicotine (nicotineplus) from Lonestar cigarettes.
- Lowers the minimum age on Guild Master, Blackshield Commander, Marshal Warrant Officer and Lonestar CEO to 0. (Foreman never had age requirements, Lodge master doesn't even ask for playtime.)
- Lowers the minimum age on Premier, CBO and CRO by 5.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
**WILSON CEO WILL BE CANON**

**Comment by Stutternov** [comment]
18 year old Blackshield Commander time.

“My mom owns the militia!!!!”

**Comment by cdb-is-not-good** [comment]
Not a fan tbh! Like - would it be good if we had a way to dynamically allow people to bypass agelocks? sure! Should EVERYONE just automatically be able to play a 18 year old WO? Fuck no! Should we REALLY make this the problem of people playing the game to apply peer pressure to people who want to play councilors despite being young as fuck? No!

Also very funny that Premier/CRO/CBO are the only roles that kept most of their timelocks. Premier sure, but cbo/cro? they're hardly the most disruptive positions.

**Comment by Obeycap** [comment]
> Also very funny that Premier/CRO/CBO are the only roles that kept most of their timelocks. Premier sure, but cbo/cro? they're hardly the most disruptive positions.

The only thing this changes is that now, the number in character creation can be lower than 30. People still play their 53 year old war vets like 20-somethings, so it's not like this is changing anything in terms of keeping people from being "disruptive".

**Comment by Obeycap** [comment]
I also feel like I should reinstate that Foreman never had any age requirements _at all_ and defaults to having no minimum age and no one ever cared or noticed and all of the regular Foremen are still appropriately aged.

**Comment by ThePainkiller** [comment]
I don't know about 25 year old CBO's and CRO's tbh...To me, they should be of older age out of not only the time it takes to complete their studies, but also an actual profession track.
And 18y/o WO's and CO's? Far, far worse

**Comment by Stutternov** [comment]
My personal input is that the ages should be adjusted but - not limitless.

Oddly, I would recommend a system similar to Bay's for once.

A CBO and CRO would require a doctorate. Which means they'd likely be at LEAST 28, if not way more likely 30.

A warrant officer or CO (Used to hold some weird officer rank via pins of like LT or Captain) which places them usually between 25-28 as the 'lower-average' age for them due to the college education requirement and the officer school. Warrant Officers are - weird but I look at them like a Police LT in a city. They usually range 28+.

CEO however and possibly Steward I could easily picture at the lower end of the spectrum at, say, 24+. CEOs can be young, I forget who the youngest technically is, but most of those who are do not become CEO of a corp at 20, they _found_ their own companies which is not the case here. So, 24 seems more likely - given they prob have some education (not much really required, but it helps) and roughly at least 4-6 years of work experience if they started working at LS at 18-20. (Steward is just an accountant. Prove me wrong.....)

**Comment by Obeycap** [comment]
> A CBO and CRO would require a doctorate. Which means they'd likely be at LEAST 28, if not way more likely 30.

A medical doctorate takes 8 years on average. If you go into college immediately at 18, 26 is the minimum for a fresh out of college doctor. In non-medical fields, like physics, for CROs, this is 4-6 years. 25 is a fine age.

> A warrant officer or CO (Used to hold some weird officer rank via pins of like LT or Captain) which places them usually between 25-28 as the 'lower-average' age for them due to the college education requirement and the officer school. Warrant Officers are - weird but I look at them like a Police LT in a city. They usually range 28+.

This is fine. I could change it to 25 and 28, respectively.

> CEO however and possibly Steward I could easily picture at the lower end of the spectrum at, say, 24+. CEOs can be young, I forget who the youngest technically is, but most of those who are do not become CEO of a corp at 20, they _found_ their own companies which is not the case here. So, 24 seems more likely - given they prob have some education (not much really required, but it helps) and roughly at least 4-6 years of work experience if they started working at LS at 18-20. (Steward is just an accountant. Prove me wrong.....)

CEO here is like... mismatched with the job title. LSS CEO's aren't really Chief Executive Officers, or even executives, most of the time. They're like, regional managers, or something. They really don't need an age restriction.

> Premiers are the - silly one. Because all they are is a 'diplomat' of sorts. They don't objectively even need a degree, but due to finance I'd imagine they'd need some education. It's more likely they'd be at least 30 due to the fact the HC has to _unanimously_ appoint them, so they're going to want someone mature, trustworthy, and a smooth speaker with some education.

Premier is the only one I didn't go too far in terms of messing with the age requirements because it's very clear the "intended" premier is like, some old fuck, so I don't mind this either.

**Comment by REDLAERT88** [comment]
Premier - 30
CEO - 25
CBO - 30
CRO - 30
WO - 30
CO - 30
PRIME - 25
GM - 25
FOREMAN - 18

Thats my bare minimums for now, I might look at lowering them in the future, but this I'm willing to agree to, give the idea a try and all that, see how it goes.

**Comment by ThePainkiller** [comment]
> Premier - 30 CEO - 25 CBO - 30 CRO - 30 WO - 30 CO - 30 PRIME - 25 GM - 25 FOREMAN - 18
> 

Very fair, very realistic, bit iffy on GM's being young but this should totally be the bare minimum age for these jobs

> A medical doctorate takes 8 years on average. If you go into college immediately at 18, 26 is the minimum for a fresh out of college doctor. In non-medical fields, like physics, for CROs, this is 4-6 years. 25 is a fine age.

A recently graduated doctor ain't cut enough yet for CBO, unless nepotism is at hand (and we all know how well RP'd characters introduced by nepotism are...) there's no way they will be granted full control over a medbay. 30 should at least give them 4 years of experience which is a bare minimum barring excellency on the field.

**Comment by cdb-is-not-good** [comment]
> I also feel like I should reinstate that Foreman never had any age requirements _at all_ and defaults to having no minimum age and no one ever cared or noticed and all of the regular Foremen are still appropriately aged.

yes and there's a reason he was the only one without age requirements. It doesn't really make sense that someone would be trusted essentially with running their entire factions day-to-day on the surface level without actually having extensive experience in the field. 

>Thats my bare minimums for now, I might look at lowering them in the future, but this I'm willing to agree to, give the idea a try and all that, see how it goes.

Yea that's mostly fine, i guess.

**Comment by faaaay** [comment]
I think that if you can't trust someone to responsibly set their character's age, can you trust them to play these roles in the first place?

I'd definitely be in favour of, as Cora said, looking at lowering them in future - but it seems like a reasonable compromise to lower them **a little** for now.

**Comment by Obeycap** [comment]
> Premier - 30 CEO - 25 CBO - 30 CRO - 30 WO - 30 CO - 30 PRIME - 25 GM - 25 FOREMAN - 18
> 
> Thats my bare minimums for now, I might look at lowering them in the future, but this I'm willing to agree to, give the idea a try and all that, see how it goes.

Updated files to be in accordance to this; still think looking at lowering them further is a good idea. We've gotten too caught up discussing this from a lore and reasoning angle (that the hiring practices of the colony don't really follow mechanically or narratively) rather than a gameplay angle.

There are a series of ludonarrative gaps in terms of how employment _wants to be handled_ in "lore", and how it is actually handled in practice, to the point where the age requirements stick out, to me at least, as notably out of place. Either Command roles are actually expected to live up to some kind of standard, and are scrutinized with some degree of attention or care, or you let it float in the miasma of endlessly changing, conflicting job canons created as a result of normal gameplay.

It's not really something you can half ass, really. In strict gameplay terms, simply letting people have the freedom to play whatever job they want is a big boost in player enjoyment, but is bad for the roleplay.

Making jobs very restricted, on the other hand, is good for the roleplay but can lead to significantly unfun situations where you want to try out new mechanics, but are forced to choose between making a new character or creating a narrative break and retconning things. Or just simply not being allowed to play certain characters in certain positions.

We're in the weird in between where characters can work in two departments simoultaneously and are wildly different people depending on what position they're occupying. People with recent criminal records get into positions where clean records would be expected, Foremen will be janitors on off days, engineers will not know how to work machines when they're on break. Continued employment, in Nadezhda, just flat out doesn't make sense, and I don't see a use in pretending that it does.

I mean, just consider that, people can arrive, play 4 rounds, and so long as their character was born before 2531, they qualify for a Command position. And a lot of them, do, play 4 rounds, and then start playing heads. A lot of them do this before they _read their SOP_. And that's **canon** and **allowed*, and can ruin department dynamics for extended periods of time, mechanically and narratively. Compare that with the other side of the coin: If you started playing a 20 year old character when the server was first made, you might be the most experienced, and senior player in your department; but you'd need to wait **8 real life years** to be able to play that character as a head.

For these reasons, I just think age restrictions should be done away with entirely, and instead judged in a case by case basis where characters with significantly mismatched ages/experience are called out by players and admins, rather than a hard, arbitrary minimum age.

**Pull request merged**
