### PR TITLE
TALLY HO EEPY TIME TO GO

### PR DESCRIPTION
**Pull request by ChefDoggo**
## About The Pull Request
<details>
<summary>
brings back the SST format bound and system cost as well as readds the soporific 7.65 bullet to the code. compiled but didn't host to test it (my PC is too shit today for some reason)
</summary>
<hr>
i miss my sopo guns
<hr>
</details>

## Changelog
:cl:

add: readded the 7.65 sopo round to code (who gutted it? dunno but its back now)
code: reenabled the format bound and system cost 
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
I assume you tested this, right

**Comment by ChefDoggo** [comment]
finally managed to get my local host running (PC fucking bluescreened) and its still not in the list despite all the files being supposedly correct, back to the malding board

**Comment by ChefDoggo** [comment]
right TIL compile and host is different than just hosting, the guns exist but have fucked up sprite sizes and im not sure how to fix it, they function but just look a bit janky

**Comment by ChefDoggo** [comment]
would preesh help with figuring out why the sprites are massive though

**Comment by ChefDoggo** [comment]
nevermind pathing for the abnegate seems fucky now, i'll look at it when my pc isn't on fire

**Comment by ChefDoggo** [comment]
i love code

**Comment by ChefDoggo** [comment]
AAAALRIGHT turns out its fine! i think my on fire pc is the issue, for some reason it wasn't selecting it for spawn and i am now mildly upset with having to reopen this a second time, same issue as before with the sprite sizes with the format bound and system cost being fucky, all is well besides that. i have bluescreened and am reopening this through my phone, my copium huffing is next level

**Comment by ChefDoggo** [comment]
the seethe

**Comment by cdb-is-not-good** [comment]
So it is infact tested and works?

**Comment by cdb-is-not-good** [comment]
also the sprites are large because they aren't 32x32 iirc, and whoever coded them didn't bother to... dunno, maybe use the existing code we have to downscale them.

**Comment by cdb-is-not-good** [comment]
```
/obj/item/gun/energy/sst/add_initial_transforms()
	. = ..()

	add_new_transformation(/datum/transform_type/modular, list(0.65, 0.65, flag = SST_INITIAL_SCALE_TRANSFORM, priority = SST_INITIAL_SCALE_TRANSFORM_PRIORITY))
```

For some reason, Trilby removed the code to shrink it down to a normal size. This is the removed code.

**Comment by ChefDoggo** [comment]
> So it is infact tested and works?

yeah besides the janky sprites they're back and working, it was mostly disabled code anyways

**Comment by ChefDoggo** [comment]
> ```
> /obj/item/gun/energy/sst/add_initial_transforms()
> 	. = ..()
> 
> 	add_new_transformation(/datum/transform_type/modular, list(0.65, 0.65, flag = SST_INITIAL_SCALE_TRANSFORM, priority = SST_INITIAL_SCALE_TRANSFORM_PRIORITY))
> ```

> For some reason, Trilby removed the code to shrink it down to a normal size. This is the removed code.

i have aboslutely no fucking clue where this goes

**Comment by cdb-is-not-good** [comment]
``/obj/item/gun/energy/sst/add_initial_transforms()``

Something like this, where it's /path/of/item/youre/affecting + proc-usually-ending-in-() is usually placed directly below the original path, So it'd go after the last line of say....the stats for whichever SST is last in the list.

**Comment by cdb-is-not-good** [comment]
This can probably just get fully merged. It's fine.

**Pull request merged**
