### PR TITLE
Addon - Excel Fortress (Fixed maybe)

### PR DESCRIPTION
**Pull request by CactusMouth**
Erases a sad attempt at a dungeon and replaces it with this Excelsior Fortress.

UPDATE: Found the issue, that's on me. #4791 

## About The Pull Request
So earlier today I found this... thing in the Deep Forest underground.
image
This was going to be removed in a few hours because it was a disgusting carcass. Which is why I attempted to revamp it into a fully fledged dungeon for you all to enjoy.

	About The Pull Request
The dungeon is consisting of Excelsior troops, one big OKB-01 boss and a load of goodies for players to enjoy. This is mainly for mid/late game prospies and outsiders to have a pry at due to it's inhabitant's ability to sweep ass.

There are some slight additions to some items/mobs which are basically the same one with different flavour text and health. For instance, the 'Communist Manifesto' can be found at the end of the dungeon. There's also Greg attached onto the build.
image
Other than that, just the dungeon.

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by CactusMouth** [comment]
THANK FUCK

**Comment by cdb-is-not-good** [comment]
If you would, post a screenshot of the whole dungeon(with hte area overlay off)

**Comment by CactusMouth** [comment]
image
Best Image I could get just cause of the size.

**Comment by cdb-is-not-good** [comment]
image
image
image

**Comment by CactusMouth** [comment]
Alright, ready to go.

**Comment by benj8560** [comment]
dreamseeker_ceB1gQSzG5


This APC seems a little wonky needs to be on the wall. 
Aside from that I like this lotta desirable loot at the end. But still likely not worth all the effort more of a flex (again don't mind it more of a for fun thing)

**Comment by CactusMouth** [comment]
> dreamseeker_ceB1gQSzG5
> 
> This APC seems a little wonky needs to be on the wall. Aside from that I like this lotta desirable loot at the end. But still likely not worth all the effort more of a flex (again don't mind it more of a for fun thing)

APC should be fixed now, and future updates should bring more additional loot such as armour and so on.

**Pull request merged**
