### PR TITLE
Adds a var to shield generators that controls if it will report it's damage or not.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
I want to use one of these in an event at some point abut I can't if they'll constantly scream about their damage status.

## Changelog
:cl:
tweak: Added a var to shield gens that allows them to not report it's damage.
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Is this variable controllable from the shield interface?

**Comment by nikothedude** [comment]
> Is this variable controllable from the shield interface?

No actually, good idea, I'll do that when I get a chance

**Comment by nikothedude** [comment]
g o d n o .

**Comment by cdb-is-not-good** [comment]
>g o d n o .

lmao

**Pull request merged**
