### PR TITLE
Borg love

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Fixes borgs thinking they are still on the ship
Makes each borg type have an emag type
Makes the hound engi borg have the correct scanner
Gives medical and engi borgs beakers
New upgrade for engi borgs - an arc welder that should work off its the borg's cell, if not it has an atomic cell.
Fixes outdata stats for the hound borgs
Fixes the outdata headset data for the sec borgs
Corrects some gun robo guns for fluff, no longer using lightfall for a "laser gun" but the Cog as thats for sec forces.

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by KathyRyals** [comment]
Needs testing and some tweaks.

**Comment by KathyRyals** [comment]
I would also argue that considering the Sojourn HEAVY PVE environment, security borgs really needs some type of lethal weapon for the fauna.

**Comment by Kazkin** [comment]
While this for the most part alright, aside from some Renglish errors, I don't have time to test this just yet. Let me finish with my existing major projects as this one will require extensive testing before approval.

**Comment by Trilbyspaceclone** [comment]
Sec-borgs have a taser, the single most powerful weapon in the game for both PvE and PvP. Taser even runs off internal cell giving it like 9999 shots or something crazy

**Pull request merged**
