### PR TITLE
Make Service Department get paid by Service Account

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
Make the Service Department get paid by Service Account instead of the main Lonestar Account.

### CODE REVIEW

**Review by Trilbyspaceclone — CHANGES_REQUESTED** [review]
Do not do this, this account isnt meant to be used like this, cant be checked and no one has access to it. Keep it with LSS

**Comment by r4d6** [comment]
Talked with Trilby on discord, as far as I could understand, Trilby's main objection is that there's no one that will receive an email if the people can't get payed.

**Comment by Trilbyspaceclone** [comment]
Thats not all what was decussed and R4 is eather lieing or drastically wrong to the point of not understanding basic points made
1) email errors, thats correct
2) cant be checked
3) cant be accessed
4) they are same department should use same account
5) they get tips and are required in sop to give the money back to LSS not servest account

**Comment by r4d6** [comment]
Here's my perspective : 
>Service Jobs drain the Main Lonestar Account when there's no one working Cargo.
>Have Service Jobs get paid by the Service Account that's already there so that they don't drain the Main Lonestar Account.
>Trilby say it won't work because no one will be able to access the account.
>Why do we care about that? All we want is to prevent Service from draining Cargo, we don't care if no one can manually remove or add money to that account.
>Being paid by a different account doesn't mean that they're automatically a different faction.

**Comment by Trilbyspaceclone** [comment]
Still bad

**Comment by r4d6** [comment]
Just tested it in a test server by playing a janitor and waiting for a paycheck : It does seems to work just fine.

**Comment by MSieghardt** [comment]
Interesting as heck change, which doesn't look like it would break. However, I think they should still come from the Lonestar one, they are technically still provided by them.

**Comment by r4d6** [comment]
> Interesting as heck change, which doesn't look like it would break. However, I think they should still come from the Lonestar one, they are technically still provided by them.

That's fair, but the main reason I did this PR was because I was told there were rounds where Service Jobs were present to drain Lonestar's account, but no one to refill it, so eventually it became empty and people no longer got paid.

**Comment by Kazkin** [comment]
This can be fixed by setting up proper crediting, so the account gets the amount that is removed to pay people.

**Pull request closed without merging**
