### PR TITLE
misc map fixes

### PR DESCRIPTION
**Pull request by benj8560**
notes: I'd consider everything in this PR a bugfix _however_ this is my first major mapping PR and I've mostly learned from trial and error so I'd suggest a test merge regardless encase I somehow broke everything but I tested pretty thoroughly

Changelog: 

Fixes the engineering turbine burn chamber. Adds a gas sensor, high volume vent, and correctly links the vent to the computer.

Adds to atmos a hard storage of sorts. Has most kinds of gas canisters, spare pumps and scrubbers as well as 3 emitters. Back are the days of engi using these on blobs I hope.

Adds 2 boxes of the unique disks needed for old genetics to the old genetics lab. 

 Adds normal plating to all low walls I could find missing it. This was not funny! It was inconsistent what ones had underplating and what ones had normal plating and makes no real sense to trip on plating under what you are standing on. _okay it was kinda funny_ 

Adds smoking signs around some of the hangout areas near dorms. The spots with tables, chairs, etc

StrongDMM_IOmqaVNXrf

## About The Pull Request
<details>

<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
While you're tweaking atmos are you up to replace the high-pressure hell room with a regular cold loop like what's on the mountains?

**Comment by benj8560** [comment]
> While you're tweaking atmos are you up to replace the high-pressure hell room with a regular cold loop like what's on the mountains?

well....the way its setup it filters the burnt gas back into atmos thus the super high pressure room. It's needed to get that superheated gas back down to tempt quick enough that it does not massively change the temps inside the tanks.  With a T4 cooler and that crazy room its barely even enough. Maybe better off just adding some blast doors to that room so foke stop wandering into it?

**Comment by benj8560** [comment]
what im getting at is heat pipes in space wont provided remotely the same cooling capacity as that room unless it's excessively large

**Comment by cdb-is-not-good** [comment]
I mean we do have the entirety of the space out there but I guess i see your ppoint. putting a button that's properly labeled owuld help

**Comment by Trilbyspaceclone** [comment]
photo in the desc needs a camera in that room, a scrubber, vent (sus) and an atmos alarm

**Comment by benj8560** [comment]
so it does. Will make it happen when I do more shit at some point soon

**Comment by Trilbyspaceclone** [comment]
kk

**Comment by benj8560** [comment]
more minor fixes! Small mistake on the  changelog fixed: 

Relocates Ian's dinner so it's not hiding away inside a closet where he can't enjoy it assumed unintended. Also returns Runtimes food to her from the old map.

Corrects the micromeds in dorms to using offsets rather then being lodged insdie a wall.

Relocates the Turbine cooling chamber blast door button to the GMs storage room and gives it a engine room ID lock for good measure. Should keep those trainees away from the funny room.

Adds a sec cam I forgot to the new atmos hard storage room.

Moves poly into the GMs breakroom and gives him a few crackers to eat/grab. The stamp is finally free!

**Comment by SingingSpock** [comment]
A suggestion for another minor fix: These shutters don't have a button controlling them, making them just block the way unless removed.
image

**Comment by cdb-is-not-good** [comment]
bless.

**Pull request merged**
