### PR TITLE
WAIT IT COMPLIED?

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Adds in a likely not working Crypo Miner, aka a way to turn your useless ded pda into a money printing!

### CODE REVIEW

**Comment by Kazkin** [comment]
Not merging this until its been tested.

**Comment by Kazkin** [comment]
Has this been tested?

**Comment by Trilbyspaceclone** [comment]
>: no...

**Comment by MSieghardt** [comment]
Worked with Trillby to hash out the small bugs it had. Tested it and it works as intended now. Ready to merge and all that jazz.

**Pull request merged**
