### PR TITLE
Changes Dsay to less cancer color

### PR DESCRIPTION
**Pull request by Honto335**
## About The Pull Request
Changes Dsay to #499c42
<summary>
	As described, it changes Dsay to #499c42, making it easier to read on light and dark mode.
</summary>
<hr>

	
<hr>
</details>

## Changelog

code: changed Dsay hex code to #499c42

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Interesting choice of color. Pls post pics showing how it looks in light/dark modes

**Comment by Honto335** [comment]
Screenshot_644
Screenshot_645

**Comment by cdb-is-not-good** [comment]
👍

**Comment by Trilbyspaceclone** [comment]
Why a green veris a sorta brighter current verson?

**Comment by Honto335** [comment]
> Why a green veris a sorta brighter current verson?

Because brighter of the current color gets washed out in light mode pretty quickly. Thats the first thing I tried. Can't really get a good balance between being readable in dark mode and light mode without one of the two being painfully hard to read.

**Comment by Trilbyspaceclone** [comment]
not the biggest fan of *another* green, but if cdb is ok with it then its fine

**Comment by Honto335** [comment]
> not the biggest fan of _another_ green, but if cdb is ok with it then its fine

Im willing to experiment around and run other colors by you and cdb, but just getting it changed would be nice.

**Comment by Honto335** [comment]
Going to experiment a bit to see if I can get two colors to work and resubmit so we have like dark grey for light mode and a pumpkin orange for dark mode per trilby request.

**Pull request closed without merging**
