### PR TITLE
Adds in two clothing items by ErisMeleeEnjoyer

### PR DESCRIPTION
**Pull request by BoblinTheGoblin2**
adds both boxer jacket ((Mother russia bleeds reference)) and white tank top ((disco elysium referen- nah it's just a generic tank top.)

Testing: Hosted it and was able to pick and wear both the jacket and tank top from the loadout.

Performance: It's two sprites so, nothing noticeable.

### CODE REVIEW

**Review by Trilbyspaceclone — APPROVED** [review]
it should be good to merge if linterchan agrees

**Comment by TheSleepyCatmom** [comment]
Why're we adding a tank top uniform when undershirts exist?

**Comment by cdb-is-not-good** [comment]
> Why're we adding a tank top uniform when undershirts exist?

One is customizable and the other is designer as a piece of wear with different aesthetics.

**Comment by TheSleepyCatmom** [comment]
Oh. Fair. My stupidity didn't actually check the fucking sprite and just assumed 'just a tank top.'

**Pull request merged**
