### PR TITLE
Fixes some Gauss rifle issues

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Reverts sojourn-13/sojourn-station#3085

This at basic look was an incorrect assumtion, the ARM does 90 damage 180 pen, this cant even take good upgrades

Also fixes the cells dusting by misstake
Fixes inconstants with materal

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
The gun state is objectively ***WORSE*** then a railrifle do to its blacklisted parts

**Comment by Dark1Star3s** [comment]
> So the gauss rifle would be better than the Anti-Material Rifle!

Yeah except the Gauss Rifle cannot have mods that make it amazing stupid OP. The AMR can, and the reductor can too.

**Comment by SouthyOsmanli** [comment]
> > Reverts #3085
> > This at basic look was an incorrect assumtion, the ARM does 90 damage 180 pen, this cant even take good upgrades
> > The gun state is objectively WORSE then a railrifle do to its blacklisted parts
> 
> The [projectile](https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/projectiles/projectile/plasma.dm#L155) this gun shoot deal 54 burn damage and has 50 AP. 54 * 1.6 = 86.4 burn damage. 50 * 2 = 100 AP.
> 
> This gun would deal 86 burn damage and ignore _**A L L**_ armor!
> 
> As a comparison, the Reductor Rail Rifle fire [this](https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/projectiles/projectile/bullettypes.dm#L571) projectile, with a damage multiplier of 1.2 This mean that a shot from the Reductor deal 54 * 1.2 = 64.8 Brute Damage, and only has 25 AP.
> 
> In other words, the Gauss Rifle ignore all armor and deal 86 damage per shot, while the Reductor Rifle deal ~65 damage per shot and ignore 25 armor.
> 
> Meanwhile, the AMR fire [these](https://github.com/sojourn-13/sojourn-station/blob/master/code/modules/projectiles/projectile/bullettypes.dm#L451) rounds, with a 0.9 damage multiplier and 100 AP. So it deal 90 * 0.9 = 81 damage with 100 AP.
> 
> So the gauss rifle would be _**better**_ than the Anti-Material Rifle!

The AMR does not have 100 AP, it has 180 - doing more damage to mobs and extra damage to mechs. The reductor can take a battery shunt allowing its damage to be 100 damage when kitted well with roughly ~20 pen and 28 rounds per cell, compared to a high recoil, venting mechanic (2 shots, fire the 3rd and you can burn your arm off), double the production cost and so forth. The Gauss cannot gain extra damage that well, I can blacklist **all** attachments if preferred to make it unimprovable.

Also this is ignoring the Abdicator doing roughly 200 damage with a low pen if you modify it as guild to nearly 1 shot a player depending on armor values.

**Comment by Trilbyspaceclone** [comment]
Burn damage dosnt ingore all armor.
Thats a fundamental miss-understanding on how armor works in pvp
Also cuz its burn damage many many many more mobs have inherent burn restant
Also 90 BRUTE damage is **MUCH BETTER** then 86 Burn do to brute having more affects and dqueling blood well burn dosnt
This in its current state is worse then any gun in the game cuz it kills its user

**Comment by r4d6** [comment]
> The AMR does not have 100 AP, it has 180

Where does the 80 extra AP coming from?
The bullet itself has 100 AP, but the only bonus to any kind of penetrative bonus that I can see apply to the ability of the bullet to go through _**walls**_, not armor.

**Comment by SouthyOsmanli** [comment]
> > The AMR does not have 100 AP, it has 180
> 
> Where does the 80 extra AP coming from? The bullet itself has 100 AP, but the only bonus to any kind of penetrative bonus that I can see apply to the ability of the bullet to go through _**walls**_, not armor.

I've used the gun. It has 180 AP due to its 6x pen modifier roughly. It also pens 6 walls and does bonus damage to things like mechs due to its AP. Atop of that you can modify it heavily. Once this is merged I can do more code changes actually to make it unable to take any damage/pen mods besides maybe a plasma injector.

**Comment by r4d6** [comment]
>I've used the gun. It has 180 AP due to its 6x pen modifier roughly. It also pens 6 walls and does bonus damage to things like mechs due to its AP. Atop of that you can modify it heavily. Once this is merged I can do more code changes actually to make it unable to take any damage/pen mods besides maybe a plasma injector.

The fuck are you saying?
First of all, the 6x pen modifier is **_additive_**, so it add +6 to the bullet's +5 wall penetration.
The actual variable that change the bullet's armor penetration is `penetration_multiplier`, which the AMR doesn't have set anywhere. What it _does_ have set is the `pierce_multiplier` variable, which, again is **additive** and only affect the number of walls the bullet can go through.

**Comment by Dark1Star3s** [comment]
Either way, without the revert to its damage, nobody is going to use this. People will just use a Reductor instead, or any other weapon that can be modified to have the power of a AMR.

**Comment by SouthyOsmanli** [comment]
> > I've used the gun. It has 180 AP due to its 6x pen modifier roughly. It also pens 6 walls and does bonus damage to things like mechs due to its AP. Atop of that you can modify it heavily. Once this is merged I can do more code changes actually to make it unable to take any damage/pen mods besides maybe a plasma injector.
> 
> The fuck are you saying? First of all, the 6x pen modifier is **_additive_**, so it add +6 to the bullet's +5 wall penetration. The actual variable that change the bullet's armor penetration is `penetration_multiplier`, which the AMR doesn't have set anywhere. What it _does_ have set is the `pierce_multiplier` variable, which, again is **additive** and only affect the number of walls the bullet can go through.
> 
> Beside, if it was a 6x multiplier, the AP would be 600, not 180. And if it was a 1.6 multiplier, it would be 160 AP, not 180.

When using it in game it tells you its AP modifier is 6.0, it may be set as a pierce but that is not what it calls it as when inspecting it in-game. Maybe it's due to mods or something I'm getting that number. This gun is still not more powerful than the AMR due to the fact armor still reduces the damage dealt. Unlike the AMR it doesn't 1 shot blow off limbs in testing, requiring 3-5 to do so, and the 3rd shot is usually a killing one with armors. 2 shots without. Which is weaker than the Abdicator modded out or the AMR itself which is a 1-2 tap due to a mix of shrapnel, bleed and so forth.

If it's needed, AP can be reduced. Reducing it to 50 damage 50 pen is terrible since why tf would you use it when you can just get a 90 damage rail rifle with 15 pen that one-shot breaks people's chest even if it's AP is low. I've one-shot a trooper before into crit using it while he was in ballistic armor and undamaged due to the fact of its high damage.

**Comment by ThePainkiller** [comment]
> The gun state is objectively _**WORSE**_ then a railrifle do to its blacklisted parts

Lilly does have a point here, considering the fact the rifle has drawbacks like the need to vent itself every two shots or so, and the fact it can't take a shunt.

> Burn damage dosnt ingore all armor. Thats a fundamental miss-understanding on how armor works in pvp Also cuz its burn damage many many many more mobs have inherent burn restant

While I know what you're trying to say (100 AP doesn't mean "100% of armor ignored), strong enough burn damage with armor penetration included **CAN** vaporize limbs and it's **extremely** efficient in PVP situations due to the fact it also bumps up pain harder than brute ever did, leading to stamcrit. Also, to remind you, burn damage has had a history of being completely ignored by armor types for some reason, making mobs that fire lasers (Greyson drones et al) utterly lethal in the past, don't know how true that holds still.

>Also 90 BRUTE damage is **MUCH BETTER** then 86 Burn do to brute having more affects and dqueling blood well burn dosnt This in its current state is worse then any gun in the game cuz it kills its user

Again, debatable depending on the armor pen values of the projectile, but since we're talking about the AMR with 180 pen, it's true, this literally breaks bones AND can embed since no 60-06 bullet variant has the `embed` flag set to FALSE and by default parent it's always TRUE, plus bloodloss becoming more and more fatal lately. But like the description of the AMR says, it's a gun meant to be used **against mechs** due to its penetration being the strongest factor above all.

> Either way, without the revert to its damage, nobody is going to use this. People will just use a Reductor instead, or any other weapon that can be modified to have the power of a AMR.

> If it's needed, AP can be reduced. Reducing it to 50 damage 50 pen is terrible since why tf would you use it when you can just get a 90 damage rail rifle with 15 pen that one-shot breaks people's chest even if it's AP is low. I've one-shot a trooper before into crit using it while he was in ballistic armor and undamaged due to the fact of its high damage.

I second these two. Why would you craft a rifle that needs more materials than a Reductor when it can be modded enough to be not only equal, but better than it?

**Comment by Trilbyspaceclone** [comment]
> > Burn damage dosnt ingore all armor. Thats a fundamental miss-understanding on how armor works in pvp Also cuz its burn damage many many many more mobs have inherent burn restant
> 
> While I know what you're trying to say (100 AP doesn't mean "100% of armor ignored), strong enough burn damage with armor penetration included **CAN** vaporize limbs and it's **extremely** efficient in PVP situations due to the fact it also bumps up pain harder than brute ever did, leading to stamcrit. Also, to remind you, burn damage has had a history of being completely ignored by armor types for some reason, making mobs that fire lasers (Greyson drones et al) utterly lethal in the past, don't know how true that holds still.


Nope this takes 2 shots to burn down a lim, its always 2 well a bullet is 1

**Comment by ThePainkiller** [comment]
@Trilbyspaceclone and speaking of materials to craft, can you please modify line 172 so that the gun is made of the proper materials required to make it?

`matter = list(MATERIAL_PLASTEEL = 40, MATERIAL_STEEL = 15, MATERIAL_SILVER = 10, MATERIAL_GOLD = 6)`

should be

`matter = list(MATERIAL_PLASTEEL = 40, MATERIAL_SILVER = 10, MATERIAL_GOLD = 8, MATERIAL_PLATINUM = 4)`

**Comment by Trilbyspaceclone** [comment]
Sure

**Comment by Yawet330** [comment]
Reductor will always be superior to this due to how toolmods work.

This was a kneejerk nerf considering the gauss rifle couldn't have any mods put onto it, was expensive to make, and was generally less than ideal due to it requiring two types of ammo.

This needs to be merged, or we're going to have another guild weapon which nobody has any reason to make.

**Comment by cdb-is-not-good** [comment]
> > The AMR does not have 100 AP, it has 180
> 
> Where does the 80 extra AP coming from? The bullet itself has 100 AP, but the only bonus to any kind of penetrative bonus that I can see apply to the ability of the bullet to go through _**walls**_, not armor.

What the fuck are you talking about, R4? Why are you talking about things of which you have zero knowledge?
image
You have said yourself many times that you do not understand balance, check your numbers before you go hopping down someone's throat.

**Comment by cdb-is-not-good** [comment]
image
>


> > I've used the gun. It has 180 AP due to its 6x pen modifier roughly. It also pens 6 walls and does bonus damage to things like mechs due to its AP. Atop of that you can modify it heavily. Once this is merged I can do more code changes actually to make it unable to take any damage/pen mods besides maybe a plasma injector.
> 
> The fuck are you saying? First of all, the 6x pen modifier is **_additive_**, so it add +6 to the bullet's +5 wall penetration. The actual variable that change the bullet's armor penetration is `penetration_multiplier`, which the AMR doesn't have set anywhere. What it _does_ have set is the `pierce_multiplier` variable, which, again is **additive** and only affect the number of walls the bullet can go through.
> 
> Beside, if it was a 6x multiplier, the AP would be 600, not 180. And if it was a 1.6 multiplier, it would be 160 AP, not 180.

What exactly are you talking about and where are you getting these numbers from? The above picture is with zero  vigilance for the sake of simplicity, with basic bullets. an extra 30 was likely the result of relatively high vigilance but it's still a lot closer than 100.

**Comment by r4d6** [comment]
> What exactly are you talking about and where are you getting these numbers from? The above picture is with zero vigilance for the sake of simplicity, with basic bullets. an extra 30 was likely the result of relatively high vigilance but it's still a lot closer than 100.

I got those numbers from looking at the code of the AMR.
I just went and checked something, and turns out that Boltguns have, by default, a 1.5x AP multiplier, which the AMR doesn't change.

**Comment by Kazkin** [comment]
Damage 86.4, armor pen 100. Kiiiiiiiiinda of an issue in terms of weapons given the rifles base damage is 54 with its bullet type, multiply it by the 1.6 damage mod it had gave it 86.4, its base armor pen was 50 but the rifle gave it x2. That is absurdly powerful and makes it a rival, if not outright better, than the AMR.

**Comment by cdb-is-not-good** [comment]
> Damage 86.4, armor pen 100. Kiiiiiiiiinda of an issue in terms of weapons given the rifles base damage is 54 with its bullet type, multiply it by the 1.6 damage mod it had gave it 86.4, its base armor pen was 50 but the rifle gave it x2. That is absurdly powerful and makes it a rival, if not outright better, than the AMR.

I'd say the downsides more than makeup for it - the AMR as it exists has...relatively few. It slows you down, has to be loaded after each shot - but it has perfect accuracy, no need to vent heat, the rounds are relatively small and portable(can hold stacks of them in one hand, fire, rack bolt, load, fire, etc) and because it's sharp can take off limbs. Maybe the damage mod needs to be dialed back but it does look like the nerfhammer hit this way too soon and too hard imo

**Comment by Kazkin** [comment]
This is being merged *for now* pending balance changes done directly by me. I'm currently looking at a potential nerf for the reductor *as is*, so we'll see after I have time to test it. My new job has cut back on my coding time.

**Pull request merged**
