### PR TITLE
Title Addition: Lodge Hunt Master

### PR DESCRIPTION
**Pull request by OliOliOnsiPree**
## About The Pull Request
So now you can see who is at the gate instead of waiting for like a two hours playing league of legends plus its the lodge "leadership" and you know whos in charge for the shift. 
Yes Trilby you can call this a cope PR if you are doing tags.
image

## Changelog
:cl:
add: Title broadcast for lodge hunt master
/:cl:

### CODE REVIEW

**Comment by benj8560** [comment]
; hey LC? This ''hunt master'' guy needs in the gate we need a vote. :D

**Comment by OliOliOnsiPree** [comment]
> ; hey LC? This ''hunt master'' guy needs in the gate we need a vote. :D

That has happened multiple times enough to make me PR this up LOL cause I sat there for thirty minutes playing league cause they dont understand

**Comment by cdb-is-not-good** [comment]
Id almost be tempted to argue that the hunt master should have gate access.

**Comment by OliOliOnsiPree** [comment]
> Id almost be tempted to argue that the hunt master should have gate access.

Im going to be 1000% real I dont know access code and that seems to be a issue that is more on the lines of lore/heads people to do that if they want it. :nod:

**Comment by OliOliOnsiPree** [comment]
Whoops.

**Pull request merged**
