### PR TITLE
Staircase-Church remap

### PR DESCRIPTION
**Pull request by Evie7056**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>
So, I played a few rounds as churchie, and I felt that reactor room feels off to me. The mere fact that you can't make you you business without proper protection against biomatter, which was spilled by god knows whom, irritated me enough to make a remap. 
Firstly, Reacto and Generator are moved to a separate rooms, so they won't intoxicate you, if you want to go to the EOTP. 
EOTP along with a bioprinter also got it's own room to feel a bit more "divine". Invisible light ontop of obelisk included 🙏 

And, since I thought it would be an interesting idea, I made an extra exit at the bottom level of the church and extended hallway with few fluff and functional corners such as church's cohort vendor or aux toolstorage. Because of that Guild's reception moved a bit west, to the other side of workshop's entrance. Same for the piping to the underground, since I needed that space for the hallway. That means that Guild has their exit downstairs closer to the Cargo, rather than SI.
	
<hr>

### Screenies (SDMM view)

<spoiler>

image
image
image
image
</spoiler>
<hr>

### Screenies (ingame view)

</spoiler>

image
image
image
image
image
image

</spoiler>
</details>

## Changelog
:cl:
add: Added new things
tweak: Shuffles few things in the Reactor.
add: Extends staircases hallway to the church, giving them an extra exit to the colony.
tweak: Shuffles rooms in the Guild.
/:cl:

### CODE REVIEW

**Comment by Evie7056** [comment]
Running a few tests, will undraft after I make sure everything looks fine.

**Comment by Evie7056** [comment]
Looks good for me. I walked to from church to the old warehouse under the guild and no one died. Undrafring and open to look at.

**Comment by Evie7056** [comment]
Drafting to make changes. Bye-bye funny window.

**Comment by Evie7056** [comment]
Updated with a new screenshots

**Comment by Evie7056** [comment]
Shoving a diff image to see how tech room dimensions have changed. Ugly as fuck, yeah, but oh well
image

**Comment by Evie7056** [comment]
image
image

Hallway is killed. It's maints now. And you also can move downstairs. Kinda cool

**Comment by Medizeal22** [comment]
Draw down on the number of spawns, put in a few tables or other appropriate objects for maint then approved.

**Comment by Trilbyspaceclone** [comment]
For sake of merging it for the updoot this will do untill myself or others edit it

**Pull request merged**
