### PR TITLE
Add anti-EMP augment.

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
Add an admin-only (for now) augment that render any limb it is installed on, and the organs of said limb, completely immune to any and all EMPs.

### CODE REVIEW

**Comment by r4d6** [comment]
It is literally an _**admin-only**_ augment that **_only_** affect the limb it is installed on.

It is only game-breaking if the admins use it that way.

**Comment by Trilbyspaceclone** [comment]
Here ya go so we dont have cheats

**Comment by Trilbyspaceclone** [comment]
I think this is bad for the game

**Comment by DerFlammenwerfer** [comment]
> I think this is bad for the game

Being perma KO in two shots no matter what because lol 30 organ damage on 60 HP internal organs, without there being any method of damage mitigation other than 'lol don't get shot at by ions then' is even worse for the game.

**Pull request closed without merging**
