### PR TITLE
New-New Bar

### PR DESCRIPTION
**Pull request by Bamhalazam**
## About The Pull Request
Adds a new layout to the bar! The Customer (platonic, abstract, not a certain person) is right when it comes to matters of taste, after all!
Also changes the bar's area lighting color to a pleasant blue hue to match the aesthetic.
Also adds a sub-variety of area for easier tracking via sensor consoles (and to avoid having the dining area be lit in blue) _(see image 2)_

	
<hr>

IMAGE 1: BAR AREAS
areas

IMAGE 2: BAR SUB-AREA (dining area :3)
diningarea

IMAGE 3: CURRENT LAYOUT OF THE BAR (the current version that I wish to merge w/ all of the slot machines and jukebox)
wholebarunlit

IMAGE 4: SLIGHTLY OUTDATED LAYOUT OF THE BAR (It's taken on a test server I didn't bother to re-launch after seeing the lighting worked, lacks minor details such as benches being fixed and slotmachines being added)
bar1

IMAGE 5: CLOSER LOOK AT THE DINING AREA (also a tad bit outdated, I added a stool and bucket behind the chef's counter)
bar2

## Changelog
:cl:
add: Added a new area variation
code: changed some area lighting code 
/:cl:

### CODE REVIEW

**Comment by Bamhalazam** [comment]
Also, in image 4, yes, I see that blue sofa over there. That, too, is fixed.

**Comment by Trilbyspaceclone** [comment]
image

needs piping

**Comment by Trilbyspaceclone** [comment]
linters failed legitmently do to APCs

**Comment by Bamhalazam** [comment]
> linters failed legitmently do to APCs

what the fuck is a linter and how do i fix the APCs, im pretty sure i copied the exact way apcs were set up in the old bar

**Comment by Trilbyspaceclone** [comment]
image

**Comment by cdb-is-not-good** [comment]
Every "area"(place with unique area coverage) needs its own APC and only one or it'll fail. It's part of why we generally don't subdivide areas that are essentially the same area

**Comment by Bamhalazam** [comment]
@Trilbyspaceclone @cdb-is-not-good 

image

Fixed the disposals and fixed ther APC, should be ready for a testmerge :3

**Comment by Bamhalazam** [comment]
So due to the recent PRs fucking with everything I'm going to have to redo this from scratch

**Pull request closed without merging**
