### PR TITLE
Revert "Minor Blackshield and Marshal additions"

### PR DESCRIPTION
**Pull request by Yawet330**
We do not support powercreeping or the addition of teleporter weapons to both the blackshield commander and WO

As radiantmittens put succinctly "I was not asked or informed of this and I still haven't been told by Moon why."

No lore consultation and was approved and speedmerged without any community or lore input

Plus it just doesn't make sense.

Refer to general as to why this PR was made.

### CODE REVIEW

**Comment by TheSleepyCatmom** [comment]
I'd appreciate my comments not being used to add fuel to your fire here. I'm confused why I wasn't spoken to on it, not upset that it was added. Since giving Bluespace equipment to people is generally something I felt should be brought to me. Thx.

**Comment by Trilbyspaceclone** [comment]
Just a bot kick

**Comment by Trilbyspaceclone** [comment]
Side note, lasers never did organ damage, they mean bullets*

**Comment by cdb-is-not-good** [comment]
>which currently, pose an threat to the colony - and an incredible one at that

It's not a 'bluespace sword'. It's a rules of nature gimmick weapon. See bellow. 
https://youtu.be/Yc0VchzMaxM

>I just want an explanation to this buff

CO had no artifact hence why it was originally suggested to give it to him. A second one was made as a 'twin' to the first and Nightmare gave that to the WO - does the WO need it? Eh. Does it matter? No. Will most WOs even carry it? Probably not. 

>What I'm trying to outline is the fact Sojourn has lost direction and has begun doing a /tg/.

' ^ '

**Comment by cdb-is-not-good** [comment]
Above comment partially retracted as I was unaware of the portal function of the sword.

**Comment by Spoopy11** [comment]
Clearly power creep is fine if it got merged in the first place /s

**Comment by cdb-is-not-good** [comment]
The more i read into this PR the more it seems like you have an axe to grind against the direction of the server as a whole rather than the actual swords themselves which are, at the end of the day - gimmicky items that are no more 'lore breaking' than the hand teleporter that the Premier to this day still has. If you want to argue for balance and adjustment to the PRs that made the game harder then do so on their own PRs OR make a PR with adjustments - this trend of throwing up a revert for each PR you dislike rather than playing with it in game and actually seeing what needs changing and how leaves a sour taste in my mouth.

**Comment by Trilbyspaceclone** [comment]
I dont think you have accully now used the sword. As a majority of what you say the sword can do, is not possable.

**Comment by cdb-is-not-good** [comment]
The 'pause' lasts a few seconds, severely limiting this """"ranges""""" capabilities. It's also incredibly obvious when you're doing this.

**Comment by cdb-is-not-good** [comment]
That would make it a 'niche' item. If it needs to be nerfed/removed then it'll be so- and we'll determine that after having it in play for a bit.

**Pull request closed without merging**
