### PR TITLE
Buffs marshals for Pneumo. Nerfs marshals for Meeeeeee also some bugfixes i guess

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Adds the wind(ostwind + Nordwind) frame to the Marshal disk.

Raises the price of the wind frame to include diamond owing to the high quality of the weapons it produces- ditto for the omni frame. In the future I may want to find an alternative resource for these higher quality weapon frames

fixes [#4767](https://github.com/sojourn-13/sojourn-station/issues/4767) probably. Adds a check to prevent bleeding once blood has reached a certain volume.

fixes [#4763](https://github.com/sojourn-13/sojourn-station/issues/4763) , im not sure how this ever worked but should be fine now.

Probably fixes [#4740](https://github.com/sojourn-13/sojourn-station/issues/4740), there was a pathing issue.

First two were all trilby :)

oops forgot to make a new fork so i guess this is also a bugfi x pr now

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Not gonna merge this for now as I h aven't actually tested any of this code B)

**Comment by Trilbyspaceclone** [comment]
To be fair the good to merge was added when  it was just a gun frame and i had confmered via a quick scroll in code files it work

**Comment by PvtStupidhead** [comment]
Hey, I don't normally write out on PRs but I felt like it'd be best to come out now and do it. While I haven't mined for a long while, I have done it on the occassion when required to feed the colony, and personally Osmium seems like a huge increase in cost - because it's not a material you can just find in scrap-piles, and it's not a material you just stumble upon while mining, but rather something you have to actively hunt down to get ahold of, the raw platinum itself that you must then compress using a smelter.

Only 2 departments have any access to an area rich with ores and potentially materials (and the equipment to mine it from roundstart), and only 1 that can refine the materials without the aid of the Guild making a spare board. 

This'll add an unreasonable cost to producing these weaponry, so even though a buff has been given to balance out the increased cost, the increased cost will make the weaponry non-viable for production to the point that the buff will be a non-factor. While I personally don't use the 8.6mm weaponry because I dislike the recoil, I know a few people that do.

This only leaves one viable option for those that still want to produce it, but there's no miner around or a savvy Soteria worker who decides to do a side-business of gathering materials instead of healing or research; finding the frames out in maints, relying on luck you'll get it. While Prospectors may prosper, the Marshals that actually make the guns won't, and given current population size, the chance of a Miner trickling through isn't that high.

I'd propose instead adding a cost increase with gold or sillicon since those materials can still be found around in piles or with savvy ghetto chemists can grind them out from other materials while still explaining the increased cost of the weaponry due to their electrical components or recoil-compensating systems, while still leaving the door open just enough that it isn't impossible for a Marshal to make the weapon legally without the aid of Lonestar.

It was also super neat of you to look into and potentially fix #4740 as that confused me for a long time, so thank you for that.

**Comment by cdb-is-not-good** [comment]
You walked right beside the point then stepped over it. These weapons are the absolute top tier of what is available to find casually, they're quite good and not horribly common- replacing that requirement with something that's trivial to find completely defeats the purpose of even adding another material to the cost

**Comment by PvtStupidhead** [comment]
> You walked right beside the point then stepped over it. These weapons are the absolute top tier of what is available to find casually, they're quite good and not horribly common- replacing that requirement with something that's trivial to find completely defeats the purpose of even adding another material to the cost
> 
> Edit; These rare materials won't see more use if they aren't used more - but they are as you say also not included in basically anything so finding them is, yes- tedious. To that end i've followed the good ol' ss13 classic of just making it be diamond like the old research SMG. This way, it'll be a rare material but not so rare that finding enough is functionally impossible without mining.

Yeah, I just wasnt sure what other material to use instead. However using diamonds I think is the best possible thing you could have done. I agree the rarer materials should inevitably find some use, high end stuff, just then some map changes should be done to allow for mining outside or some such that someone without giga-mine could scrap together atleast some.

**Comment by cdb-is-not-good** [comment]
Or adding those rare materials to rare stuff that spawns naturally would be nice. But that's something for another time

**Pull request merged**
