### PR TITLE
Runechat 

### PR DESCRIPTION
**Pull request by Dangerlurking**
## About The Pull Request
Implements Runechat into Sojourn. NONE OF THIS CODE WAS MADE BY ME, ALL CREDIT GOES TO STUTTERNOV WHERE APPLICABLE.

## Changelog
:cl:
add: Adds Runechat from Stutternov's old PR.
server: Preferences for Runechat are also included in this PR.
:cl:

### CODE REVIEW

**Comment by Xaytan** [comment]
Woe, Trilby be upon ye.

**Comment by nikothedude** [comment]
runechat's upsides massively outweigh the downsides. good pr

**Comment by Trilbyspaceclone** [comment]
On the bright side, did infact test it. The code somehow works
On the downside. Im closing the pr.

**Comment by nikothedude** [comment]
why do you do these things

**Comment by cdb-is-not-good** [comment]
Why did you add discussion needed and then close it without discussion?

**Comment by benj8560** [comment]
The only thing I can truly agree on you with Trilby is this ''It encourages memes and LRP'' maybe being a problem. Such could easily be tested via the wonders of a test merge for a week to see how are players handle it.

**Pull request closed without merging**
