### PR TITLE
Marshal Jackeeto

### PR DESCRIPTION
**Pull request by Dorodomki**
## About The Pull Request

Adds a new jacket for the Marshals, Ranger, WO, Supply Specialist, Commisioned by pneumo/husky.

## Changelog
:cl:
add: Added new Jacket For Marshals
/:cl:

Captura de pantalla (1001)

-----
Captura de pantalla (1002)

### CODE REVIEW

**Comment by SingingSpock** [comment]
I don't think pure-blue sprites should be used for the only sprite of an object. This would work better as an alternative sprite of the Marshal Greatcoat.

**Comment by Trilbyspaceclone** [comment]
Apparently its commissioned to be like this.

**Comment by cdb-is-not-good** [comment]
You've made a small mistake. Please look at files changed.

**Comment by cdb-is-not-good** [comment]
Closing since you have another version up.

**Pull request closed without merging**
