### PR TITLE
Painmaker fixers

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Proj pain mult now properly increase halloss damage bullets do
Painmaker and hornet now flat add 20 halloss damage to bullets they shoot
Painmaker and hornet have been rebalanced to adjust for this change

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
>Painmaker and hornet now flat add 20 halloss damage to bullets they shoot

Uh....is the painmaker able to be attached to shotguns? Because if so this means you can add ....what, 100 pain damage to buckshot if it's PB?

**Comment by cdb-is-not-good** [comment]
So for buckshot you.lose 70% damage and each pellet goes down to....like what, 5 or 6 damage plus 20 halloss?

**Comment by Trilbyspaceclone** [comment]
> So for buckshot you.lose 70% damage and each pellet goes down to....like what, 5 or 6 damage plus 20 halloss?

Damage isnt per pellet anymore (or shouldnt)
20 damage halloss is flat, nothing really modifes it

**Comment by cdb-is-not-good** [comment]
If it's just 20 that's fine but pls test buckshot with this

**Comment by Trilbyspaceclone** [comment]
> If it's just 20 that's fine but pls test buckshot with this

Seems to hit twice meaning its 40 halloss tested with gladstone and swat

**Pull request merged**
