### PR TITLE
Reduces pouch prices.

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
## About The Pull Request
<details>
<summary>
	Reduces the cost of church/leather pouches. As of now they were REALLY fucking expensive for how easy they were to produce. they still are worth a good amount, but no more 1000 for 15 biomass.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I disogree with the learther pouches being changed as that requires hunters

**Comment by cdb-is-not-good** [comment]
only the large ones do i thought?

**Comment by cdb-is-not-good** [comment]
Mkay, raised the price of the leather ones and adjusted the others just a tad.

**Comment by Kazkin** [comment]
Adjust to be far less damning, originally I was going to deny this pr but upon looking closer discovered a coding error from eris which made modular pouches (baton, tool, etc. etc.) worth a stupidly high amount of credits. The small reduction should normalize the prices but far from prevent the pouch lonestar sell strategy.

As I was telling Rin last night, we want to promote profitable ventures between departments and the constant nerfing on viable strats is not fun. This change is more to make pouches reasonably priced, but not making it not still more than viable for a church/lonestar production cut.

**Comment by cdb-is-not-good** [comment]
That was my original intent. Not to make pouches worthless - but to do away with a really wonky conversion. Two pieces of roach meat, or three ambrosia branches - are worth one large pouch(1k initially.). Which is just a little silly.

**Comment by Kazkin** [comment]
New strat is soteria/lonestar pouches of holding.

**Comment by cdb-is-not-good** [comment]
Valid. those take hella materials and research.

**Pull request merged**
