### PR TITLE
Anti-Ghost Subtle

### PR DESCRIPTION
**Pull request by AysheDaArtist**
## About The Pull Request
<details>
<summary>
	Ports over Anti-Ghost Subtles that allow admins to see, but blocks view from ghosts

        Port of: https://github.com/Liberty-Landing/Liberty-Station-13/pull/144
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
adds: "Subtle verb (Anti-ghost)" to IC tab
fixes: Subtle anti-ghost emotes no longer can be abused; 7 tile range added to the visibility of the emote.
fixes: Admins can see subtle anti-ghost emotes. This is kept for policing any issues noticed.
/:cl:

Credit to https://github.com/Stutternov for original code

### CODE REVIEW

**Comment by AysheDaArtist** [comment]
Tested with @LongSleeves  it should be working

Admins are able to see anti-ghost subtles

Normal ghosts cannot see anti-ghost subtles

**Comment by benj8560** [comment]
7 tile range meaning it can't be used to screw your friend in the bar without anyone noticing? Pretty much everything I wanted from a subtle verb. Keeps ghosts out can't be abused. Is plus 1 from me

**Comment by cdb-is-not-good** [comment]
K5 has expressly vetoed this PR.

**Comment by Trilbyspaceclone** [comment]
image

**Pull request closed without merging**
