### PR TITLE
Minor Lodge map edit

### PR DESCRIPTION
**Pull request by Dangerlurking**
## About The Pull Request
<details>
<summary>
</summary>
<hr>

Adds some cooking utensils for the Lodge kitchen since they were lacking them and removes a few out of place objects.
	
<hr>
</details>

## Changelog
:cl:
add: Cooking utensils, a shelf to store plates on, a cutting board, and some bowls on the serving window for the dining area.
del: Removed a wine bottle in the cooking area, a random knife spawn where the cooking board is now located, a random potted plant behind the door of the crafting area, and a random scythe that was located in the middle of the farm.
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Tested and working?

**Comment by Dangerlurking** [comment]
> Tested and working?

Did a test host on my branch and I can confirm it's working.

**Comment by Dangerlurking** [comment]
New commit adds a spatula where the pan is located.

**Comment by Dangerlurking** [comment]
> New commit adds a spatula where the pan is located.

Aw fuck something went wrong after making the change, dealing with it.

**Comment by Dangerlurking** [comment]
> > New commit adds a spatula where the pan is located.
> 
> Aw fuck something went wrong after making the change, dealing with it.

Compiled and ran the game with the changes locally and there were no issues present and Github didn't show any changes made. Going to assume that the integration test isn't working properly.

**Comment by SkinkHunt** [comment]
>Add spatula
>Breaks PR

Ahhh the fun

**Comment by king5327** [comment]
There are a lot of... unrelated commits here. Can you git squash them down or something? A lot of them end up getting reverted.

**Comment by cdb-is-not-good** [comment]
won't it all get disappeared when we squash & Merge?

**Comment by cdb-is-not-good** [comment]
fuck it we ball.

**Pull request merged**
