### PR TITLE
Makes carbons no longer spill their organs during bioreactor procesing and give too much biomatter

### PR DESCRIPTION
**Pull request by SingingSpock**
## About The Pull Request
<details>
<summary>
	Comments out the code that ejects the organs from carbons and dissolves them separately so they don't get absurd amounts of biomass for their size
</summary>
<hr>

Exactly what it says on the tin. Humans no longer have more biomass than Empress spiders, they've got 100
	
<hr>
</details>

## Changelog
:cl:
tweak: Humans give a reasonable amount of biomass now rather than an absurd amount
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
hahahaha ahhhhh the end of a fuckiing era

**Comment by Trilbyspaceclone** [comment]
people will still organ spill folks, dosnt change all that much but extra steps

**Comment by cdb-is-not-good** [comment]
Also won't it be maybe a good idea to reduce the biomass from organs in general? does this stop someone from just chopping the body up into pieces and removing all organs?

**Comment by SingingSpock** [comment]
> Also won't it be maybe a good idea to reduce the biomass from organs in general? does this stop someone from just chopping the body up into pieces and removing all organs?

I think that would at the same time reduce the biomass needed to print them, since it's just the biomatter variable on the object itself. And yeah, someone could go full kidney harvester but that's more grotesque (and could be prohibited by IC policy more reasonably)

**Comment by cdb-is-not-good** [comment]
> > Also won't it be maybe a good idea to reduce the biomass from organs in general? does this stop someone from just chopping the body up into pieces and removing all organs?
> 
> I think that would at the same time reduce the biomass needed to print them, since it's just the biomatter variable on the object itself. And yeah, someone could go full kidney harvester but that's more grotesque (and could be prohibited by IC policy more reasonably)

Suppose that's fair

**Comment by SingingSpock** [comment]
> I'd really rather we just remove all the carbon human bodies around the map as I suggested before. They have other issues involving psionics and probably an incredibly minor performance hit. It's also really not AS good as everyone makes it out to be. You get around 700 per body and most large mobs can offer upwards of 500. I often hit nightmare cave for quick biomatter theres 2k in there alone.

Removing the hard spawns won't stop people from using monkey cubes, which I have seen players do. Also, this isn't _only_ a balance issue, it's also a verisimilitude issue: why is a human or a monkey giving more than a large mob?

**Comment by benj8560** [comment]
> Removing the hard spawns won't stop people from using monkey cubes, which I have seen players do. Also, this isn't _only_ a balance issue, it's also a verisimilitude issue: why is a human or a monkey giving more than a large mob?

if we are are gonna talk monkey cubes theres no legal downside to using them. As long as the monkey is handled humanely and it would not fix THAT issue. Just make it more steps like Trilby said.

**Comment by cdb-is-not-good** [comment]
> > Removing the hard spawns won't stop people from using monkey cubes, which I have seen players do. Also, this isn't _only_ a balance issue, it's also a verisimilitude issue: why is a human or a monkey giving more than a large mob?
> 
> if we are are gonna talk monkey cubes theres no legal downside to using them. As long as the monkey is handled humanely and it would not fix THAT issue. Just make it more steps like Trilby said.

This *is* a good poiint. Perhaps the fix is simply to add a var to organs that the biogenerator process checks for which negatively affects the math rather than simply changiing the total cost of the things.

**Comment by SingingSpock** [comment]
> > Removing the hard spawns won't stop people from using monkey cubes, which I have seen players do. Also, this isn't _only_ a balance issue, it's also a verisimilitude issue: why is a human or a monkey giving more than a large mob?
> 
> if we are are gonna talk monkey cubes theres no legal downside to using them. As long as the monkey is handled humanely and it would not fix THAT issue. Just make it more steps like Trilby said.

If there becomes a meta of regularly grabbing monkeys and harvesting their organs for biomatter, then we can handle it. That's not currently an issue, because that's effort.

**Comment by SingingSpock** [comment]
> > > Removing the hard spawns won't stop people from using monkey cubes, which I have seen players do. Also, this isn't _only_ a balance issue, it's also a verisimilitude issue: why is a human or a monkey giving more than a large mob?
> > 
> > 
> > if we are are gonna talk monkey cubes theres no legal downside to using them. As long as the monkey is handled humanely and it would not fix THAT issue. Just make it more steps like Trilby said.
> 
> This _is_ a good poiint. Perhaps the fix is simply to add a var to organs that the biogenerator process checks for which negatively affects the math rather than simply changiing the total cost of the things.

That would work, but then we're again having a verisimilitude issue of "everything else dissolves into its normal material's worth of biomatter, why don't organs?"

One solution _would_ be to just make organs much cheaper and lower the capacity and starting stock of the organ printer commensurately, but that's a lot of effort for minor gain.

**Comment by cdb-is-not-good** [comment]
ehh...well, either way for now this is probably fine. WE'll cross the monkey bridge when we get to it, i guess.

**Pull request merged**
