### PR TITLE
Nerfs oddities """A bit"""

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Oddities will now lose their stats upon being reflected upon. This change is hoped to A. be a first minor stab at reducing inflation in the stats economy and B. making valuable oddities a little more valuable.

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
"""A bit"""

**Comment by cdb-is-not-good** [comment]
Real.

**Comment by ChefDoggo** [comment]
church will never see the seal ever again 😭 🙏

**Comment by benj8560** [comment]
thanks I hate it

**Comment by lizhurd** [comment]
pointless nerf aimed at only making the game slower (and therefore less enjoyable) for players
don't be like helldivers 2 devs!

**Comment by cdb-is-not-good** [comment]
> pointless nerf aimed at only making the game slower (and therefore less enjoyable) for players
> don't be like helldivers 2 devs!

Aimed more so at curbing the very high amount of stats that you can trivially obtain due to how inspiration works. It's worth noting that super high stats aren't by any means required to play or enjoy the game.

**Comment by cdb-is-not-good** [comment]
Stat raising values that were inflated by changes made quite a while ago

**Comment by cdb-is-not-good** [comment]
as funny as this would be to keep, it doesn't *really* fix the problem and can pretty reliably be subverted by powergamers. Oh well.

**Pull request closed without merging**
