### PR TITLE
BS armerments

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
New blackshield auto shotgun that holds 8 shots, sprite and sound by Churro
2 New blackshield guns, a SMG replacing the grease gun and a DMR. - sprited and mostly stated by Quill
Adds markrovs to both marshals and blackshields vouchers
Adds in the makrov to the marshals and blackshield vouchers
adds missing boxes to the vendors
fixes colt box being misslabled
Fixes the greasegun smg having more recoil then a shotgun

### CODE REVIEW

**Comment by r4d6** [comment]
While this look awesome, I feel like an automatic shotgun should be an upgrade that Blackshield has to get, and not start with it.

**Comment by Trilbyspaceclone** [comment]
its worse then the state damage pvp wise

**Comment by cdb-is-not-good** [comment]
I'll point out that the shotgun they start with, the Grizzly - is among the best shotguns for sheer numbers. This isn't directly an upgrade, imho. It's a sidegrade that trades pure firepower for utility.

**Comment by Trilbyspaceclone** [comment]
No in hands yet

**Pull request merged**
