### PR TITLE
Ameridain redo

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Ameridain spread endlessly being more easy to contain

Ameridain spreading is now controled by the spires, and to activate the spires you must use a core on said spire, this increases its spawn range by 1 per, looking at the spire now tells you how many cores it has thus its range
You can also for a steep costs make your own ameridain spires, using 1 core and 60 shards, for more domestic farms in case you get bad roles or want to move your outpost closer home 

Ameridain from a spire will also now allow 1 extra spred meaning its 4x4~ as a basic default rather then 3x3

Greatly speeds up Ameridian size growth and links how bright a Ameridian glow is to the size, meaning in caves they should be much brigher lit to avoid golem ambushes 

Golems now randomly spawn in the mines -> Meaning the ameridain tiles no longer spawn them
To clearife more, golems no longer passively spawn but when a new shard is made (other then the fake spier in the crafting menu).

Golems spawn when the Ameridain spreads onto ground, this is to make it less of a constant pushing back threat and more of a wave kinda deal were you can out drain the numbers and then clean up the mess.

You can no longer craft new ameridain shards
removes the non-funcition? ameridain tenders
Ameridain cores now are worth 1k rather then 10k
Ameridain processers now are way better on coverts as Ameridain now limited much greater
Ameridaian is no longer radioactive unless you drink the liquid, or get shot by a shard

Ameridaian spirer is now radioactive but only when you activate it with a Ameridain core, much more so then before increased:
Radition from 0.5 -> 4
Radiation range 2 -> 3

Ameridaian now shows up on ore sonar
Ameridaian spire now can be mined and to give 60 Ameridain shards
Infests the mines with rather the random spiders, roaches and stalkers with golems

## Ameridian no longer can grow outside of non-dirt tiles

Mining now has a randomizer for open tiles to add-
Area outside the mining doc cant spawn any of the mining randimizer stuff
Ore(as in the rock of ore) now randomly spawns in mines
as well as rubble
Ameridian now randomly spawns in the miners

Map stuff was approved by liched

The Ameridian field in mining area has had its  sonic walls removed as they are unneeded power draw atm in this interaction of the ameridaian 
Added 3 more rad suit containers to the mining area

Testing: Ran a complie and see if they were spawning properly minor amounts of balancing based on feel.
Tested Ameridain crafting, cores and general balance of it as well as tweaked timers for it to be a bit more fair well still a hard fight to maintain.
Testing: Two made sure all changes are working as best I can

Performance: Techinnally improves?

### CODE REVIEW

**Comment by Guidesu** [comment]
I see this as completely unnecessary as an Ameridian player that plays and messes with it.
Why?

Ameridain no longer grow or spread
RESPONSE: Ameridian growth is LITERALLY fine. Like. It grows alrighty in a steady motion not so fast in a way. Even the synthetical one the red one is EVEN slower which I think it need its speed a little more buffed.


Ameridian now randomly spawns in the miners
RESPONSE: Why? Like. Create a subtype and leave the ameridian at the same place there's no need to remove it.,

Golems now randomly spawn in the mines ^
RESPONSE: I am alright with it along you don't touch or move the place. Make it an subtype that does not deals radiation damage and we are even.

Ore(as in the rock of ore) now randomly spawns in mines
RESPONSE: Eh its alright

You can no longer craft new ameridain shards
RESPONSE: N o. There's again no need to remove an entirely functional system due to a small issue.

removes the sonic fields for ameridain
RESPONSE: There's no need to remove an entirely functional system due to a small issue.


removes the non-funcition? ameridain tenders
RESPONSE: Fix it


Ameridain cores now are worth 1k rather then 10k
RESPONSE: The price is fine for what is it worth. You can't mass-produce it and it really takes an really long painstakingly to get an core

Ameridain processers now are way better on coverts as Ameridain now limited


Ameridaian is no longer radioactive unless you drink the liquid
Make it an subtype and leave the Ameridian at the place it is. The ones that grow in the caves make it non-radioactive.

**Comment by Trilbyspaceclone** [comment]
> I see this as completely unnecessary as an Ameridian player that plays and messes with it. Why?
> 

Laggy, and player requested, no one maintaining it in

> Ameridain no longer grow or spread RESPONSE: Ameridian growth is LITERALLY fine. Like. It grows alrighty in a steady motion not so fast in a way. Even the synthetical one the red one is EVEN slower which I think it need its speed a little more buffed.
> 

Aware and its being axed do to how it spreads being laggy and unmaintained

> Ameridian now randomly spawns in the miners RESPONSE: Why? Like. Create a subtype and leave the ameridian at the same place there's no need to remove it.,
> 

Thats not within the goal of pr

> Golems now randomly spawn in the mines ^ RESPONSE: I am alright with it along you don't touch or move the place. Make it an subtype that does not deals radiation damage and we are even.
> 
> Ore(as in the rock of ore) now randomly spawns in mines RESPONSE: Eh its alright
> 
> You can no longer craft new ameridain shards RESPONSE: N o. There's again no need to remove an entirely functional system due to a small issue.
> 

Cut do to no longer spreading, so making new ones would do nothing

> removes the sonic fields for ameridain RESPONSE: There's no need to remove an entirely functional system due to a small issue.
> 

Cut do to no longer spreading, so making new ones would do nothing

> removes the non-funcition? ameridain tenders RESPONSE: Fix it
> 

Please refure to https://sojourn13.space/wiki/Contributor_Guide

> Ameridain cores now are worth 1k rather then 10k RESPONSE: The price is fine for what is it worth. You can't mass-produce it and it really takes an really long painstakingly to get an core
> 

If you look it was made way cheaper, to make and now can be found in the mines via the sprial. Fair that I forgot to put that in the changelog will fix that

> Ameridain processers now are way better on coverts as Ameridain now limited
> 
> Ameridaian is no longer radioactive unless you drink the liquid Make it an subtype and leave the Ameridian at the place it is. The ones that grow in the caves make it non-radioactive.

Radioactive bad tho. Its the main complain I hear about it

**Comment by nikothedude** [comment]
this pr needs a "why this pr was made" section

**Comment by r4d6** [comment]
Right, it's a major no from me.

First thing first : While it is true that I don't actively maintain the ameridian stuff anymore, there is no game-breaking bugs related to it. The only real thing left to do is balancing it in response to what the player do, and balancing is something I am bad at.

- Ameridain no longer grow or spread
That's the **main feature** of ameridian!

- Ameridian now randomly spawns in the miners
It's supposed to be something that you cultivate, not a bonus item that appear randomly.

- Golems now randomly spawn in the mines -> Meaning the ameridain tiles no longer spawn them
I don't mind this, but the reason why the ameridian spawned golems was to make it more dangerous.

- You can no longer craft new ameridain shards
So it was implemented before Liquid Ameridian, but I still kept it because it gave a way of making new fields without access to an Ameridian Refinery.

- removes the sonic fields for ameridain
_**WHY?!**_ It was working just fine before! There's no need to completely remove them from the code!

- removes the non-funcition? ameridain tenders
The tenders works just fine. We just never figured out how to introduce them/decide how they should be made.

- Ameridain cores now are worth 1k rather then 10k
The main reason ameridian cores were worth 10k was to justify the raw ameridian cost of them.

- Ameridain processers now are way better on coverts as Ameridain now limited
That's just a side effect of the way you "reworked" ameridian.

- Ameridaian is no longer radioactive unless you drink the liquid
... why? It doesn't do that much radiation damage on its own anyway, and it was intended to give an environmental hazard to ameridian, in addition of the physical hazards of the golem. Ameridian Crystals are also the only real source of radiation in the entire game, baring the SM.


In my opinion, _**axing 75% of the content and spreading the remains over the mines is not a rework.**_ Hard no.

**Comment by Guidesu** [comment]
> Right, it's a major no from me.
> 
> First thing first : While it is true that I don't actively maintain the ameridian stuff anymore, there is no game-breaking bugs related to it. The only real thing left to do is balancing it in response to what the player do, and balancing is something I am bad at.
> 
> * Ameridain no longer grow or spread
>   That's the **main feature** of ameridian!
> * Ameridian now randomly spawns in the miners
>   It's supposed to be something that you cultivate, not a bonus item that appear randomly.
> * Golems now randomly spawn in the mines -> Meaning the ameridain tiles no longer spawn them
>   I don't mind this, but the reason why the ameridian spawned golems was to make it more dangerous.
> * You can no longer craft new ameridain shards
>   So it was implemented before Liquid Ameridian, but I still kept it because it gave a way of making new fields without access to an Ameridian Refinery.
> * removes the sonic fields for ameridain
>   _**WHY?!**_ It was working just fine before! There's no need to completely remove them from the code!
> * removes the non-funcition? ameridain tenders
>   The tenders works just fine. We just never figured out how to introduce them/decide how they should be made.
> * Ameridain cores now are worth 1k rather then 10k
>   The main reason ameridian cores were worth 10k was to justify the raw ameridian cost of them.
> * Ameridain processers now are way better on coverts as Ameridain now limited
>   That's just a side effect of the way you "reworked" ameridian.
> * Ameridaian is no longer radioactive unless you drink the liquid
>   ... why? It doesn't do that much radiation damage on its own anyway, and it was intended to give an environmental hazard to ameridian, in addition of the physical hazards of the golem. Ameridian Crystals are also the only real source of radiation in the entire game, baring the SM.
> 
> In my opinion, _**axing 75% of the content and spreading the remains over the mines is not a rework.**_ Hard no.

Agreed

**Comment by Trilbyspaceclone** [comment]
Its not a rework
its a redo, i didnt use the word rework as its not reworking whats present.

**Comment by hex37** [comment]
Hard disagree. I'll spare everyone the wall of text- If we can't fix Ameridian to fit the server better, it shouldn't be reduced to some random thing out in the mines.

Worst case remove it. Best case, make it into a proper SI department for making wierd, high-tech gear a la bluespace or hydrogen tech.

**Comment by Stutternov** [comment]
> Worst case remove it.
Based

**Comment by Stutternov** [comment]
> The tenders works just fine. We just never figured out how to introduce them/decide how they should be made.

Why was it PRed incomplete? It's never received any development past it.

**Comment by MSieghardt** [comment]
PR changes a broken system up and makes it potentially fresh and fun.

**Comment by r4d6** [comment]
> > The tenders works just fine. We just never figured out how to introduce them/decide how they should be made.
> 
> Why was it PRed incomplete? It's never received any development past it.

Well first I decided to stop waiting on a sprite. Then I got a sprite that worked and made a PR to put it in. Then I have 2 other PRs fixing issues about the ameridian tender.

It was mostly just a lore/event issue.
I was planning on letting Possum handle the reveal & stuff, like I always did, but then he got kicked out...

**Comment by r4d6** [comment]
> PR changes a broken system up and makes it potentially fresh and fun.

1. It ain't broken.
2. How is searching for crystals in an almost empty mine fun?

**Comment by MSieghardt** [comment]
I'll add the ability to see ameridian clusters on the sonar.

**Comment by Dimasw99** [comment]
While I think ameridian in its current state has some pretty noticeable balance and tedium issues. The approach to fixing it here is very robbing of the identity that ameridian has, that being an active risk management that can be rewarding. Having an ameridian field means you have a passive income that can escape the moment something like a power outage appears which leads to conflict and can contribute to roleplay.

The current approach taken just turns it into a jack of all traits material, though I don't see a reason why people would bother doing it if they can just buy the stacks of materials instead. The cores are then too are a little bit strange. Lonestar never really sees a reason to sell them to Soteria since that would just give them unnecessary competition which often is a reason enough to forbid the trade

**Comment by cdb-is-not-good** [comment]
> While I think ameridian in its current state has some pretty noticeable balance and tedium issues. The approach to fixing it here is very robbing of the identity that ameridian has, that being an active risk management that can be rewarding. Having an ameridian field means you have a passive income that can escape the moment something like a power outage appears which leads to conflict and can contribute to roleplay.
> 
> The current approach taken just turns it into a jack of all traits material, though I don't see a reason why people would bother doing it if they can just buy the stacks of materials instead. The cores are then too are a little bit strange. Lonestar never really sees a reason to sell them to Soteria since that would just give them unnecessary competition which often is a reason enough to forbid the trade

Agree. Im not really a fan of this PR for a variety of reasons. It feels like gutting a system that while flawed, certainly doesn't cause many issues - the performance however could stand to be looked at if it is as bad as said, but I really am not sure how major said impact is given the...utterly puny size of the field and its generally limited area.

Part of the issue with LSS refusing to sell them to SI comes down to a failure to properly detail the 'deal' made by Lonestar with Soteria that says they MUST provide them to SI, i've spoken to Dasfox and asked her to detail this so that such an event doesn't occur - similarly, i'd honestly look at removing the ability of SI to process it. Lonestar is SUPPOSED to have exclusive rights to do so.

**Comment by Dimasw99** [comment]
> Agree. Im not really a fan of this PR for a variety of reasons. It feels like gutting a system that while flawed, certainly doesn't cause many issues - the performance however could stand to be looked at if it is as bad as said, but I really am not sure how major said impact is given the...utterly puny size of the field and its generally limited area.
> 
> Part of the issue with LSS refusing to sell them to SI comes down to a failure to properly detail the 'deal' made by Lonestar with Soteria that says they MUST provide them to SI, i've spoken to Dasfox and asked her to detail this so that such an event doesn't occur - similarly, i'd honestly look at removing the ability of SI to process it. Lonestar is SUPPOSED to have exclusive rights to do so.

Main issue rn is that lonestar sees three main reasons to sometimes refuse service: 1: They are too lazy to harvest and process ameridian which I can understand, it is a tedious and boring process. 2: They simply don't like you and yes that happens quite a bit with how often you make deals and have to deny them sometimes. 3: They are afraid of you making materials with the cores and thus become "independant".

Though with all that, Soteria can't work or even research ameridian without cores. The ameridian analyzer requires a core, the power gamer suit requires a core, the cell requires a core. Which in essence locks you out of everything ameridian has to offer for Soteria

**Comment by r4d6** [comment]
> Though with all that, Soteria can't work or even research ameridian without cores. The ameridian analyzer requires a core, the power gamer suit requires a core, the cell requires a core. Which in essence locks you out of everything ameridian has to offer for Soteria

So, first of all, the ameridian cell only require a core for its self-recharge function. Otherwise it work just like a regular rechargable 20k L-cell.

Second, the main reason why everything require a core is because at the time one of the objective was to promote "Inter-department cooperation", AKA to make people from different departments have to rely on each other.
That and I didn't want Soteria to be able to be independent material-wise that easily.

**Comment by Thegreatspidernonbinary** [comment]
Firstly there is absolutely no reason for this to be spawning, secondly it will screw up loot and make all these items more common, thirdly, this is possibly a direct violation to contributing guidelines, I should try reading them. https://wiki.cev-eris.com/Content_GuidelinesEn

**Comment by Guidesu** [comment]
Hot take:

Ameridain spread endlessly being more easy to contain
Response: Actually alright with it its fine. It means that it still retains the original concept of ameridian of being an sorta of dangerous bio-hazard thought still not being a hassle to play with it.

Ameridain spreading is now controled by the spires, and to activate the spires you must use a core on said spire, this increases its spawn range by 1 per, looking at the spire now tells you how many cores it has thus its range
You can also for a steep costs make your own ameridain spires, using 1 core and 60 shards, for more domestic farms in case you get bad roles or want to move your outpost closer home

If lonestar gets an round-start core then its fair without taking away the capacity of creating ameridian.

Ameridain from a spire will also now allow 1 extra spred meaning its 4x4~ as a basic default rather then 3x3
👍 

Greatly speeds up Ameridian size growth and links how bright a Ameridian glow is to the size, meaning in caves they should be much brigher lit to avoid golem ambushes
👍 

Golems now randomly spawn in the mines -> Meaning the ameridain tiles no longer spawn them
That means that the Ameridian spire does not spawn golems anymore?

You can no longer craft new ameridain shards
Er... Why?

removes the non-funcition? ameridain tenders
I think it was working as far as I am aware

Ameridain cores now are worth 1k rather then 10k
I would not do it I would make the price around 3k to 5k so it gives miner an reason to mess with it and sell reliably.

Ameridain processers now are way better on coverts as Ameridain now limited much greater
👍 

Ameridaian is no longer radioactive unless you drink the liquid, or get shot by a shard
👎.... Ameridian being radioactive was an key part of it.... at very least make that the radiation is so low-wise that means that in enough contact with it for like maybe hours you get the usual symptoms. Enough to a human to handle in nearby of one for hours even without needing to go to medical or giving miners or putting radiation medicine around......
If you can't do that at least make some way to get irandiated since there's need to be an key part of danger of messing with something like that.

Ameridaian now shows up on ore sonar
👍 

Ameridaian spire now can be mined and to give 60 Ameridain shards
👍 Would recommend 75 shards.

Infests the mines with rather the random spiders, roaches and stalkers with golems
👍 

Ameridian no longer can grow outside of non-dirt tiles
Eh I am biased towards it but I would say let them have control on SOME sort of terrain like grass and such. So it can impose  an bigger threat if someone for whatever reason leaves and brings them outisde

Ameridian now randomly spawns in the miners
👍  make them spawn with some consitancy

Map stuff was approved by liched

The Ameridian field in mining area has had its sonic walls removed as they are unneeded power draw atm in this interaction of the ameridaian

I would  wish to not have it removed or very least make it so the power drain is lower than 10kw

**Comment by Trilbyspaceclone** [comment]
60 was picked as it had good scaling with anti-douping messers so sadly we should keep it 60 😔

**Comment by Guidesu** [comment]
> 60 was picked as it had good scaling with anti-douping messers so sadly we should keep it 60 😔

Damn

**Comment by Trilbyspaceclone** [comment]
To clearife more, golems no longer passively spawn but when a new shard is made (other then the fake spier in the crafting menu).

Golems when the shard on the ground is spawned is when they spawn, this is to make it less of a constant pushing back threat and more of a wave kinda deal were you can out drain the numbers and then clean up the mess.

**Comment by Guidesu** [comment]
> To clearife more, golems no longer passively spawn but when a new shard is made (other then the fake spier in the crafting menu).
> 
> Golems when the shard on the ground is spawned is when they spawn, this is to make it less of a constant pushing back threat and more of a wave kinda deal were you can out drain the numbers and then clean up the mess.

👍

**Comment by Trilbyspaceclone** [comment]
as for core prices, i wish to see how they are in game and maybe tweak it based on values and some game testing for a simple price tag. :~:

**Comment by Karlov357** [comment]
Yeah, I'd upvote this rework.

As someone that has been a miner main for the last three-ish months and been dealing with ameridian since it's first event I do agree with this change, albeit not fully. I do have an issue with all of the other mobs like spiders and roaches being removed save for some select nightmare spawns so they can be changed out for crystals and golems, which could be fixed if there were to be other variations of golems to be added. The only other issue that I would have for this change is the removal of the static radiation from the crystals, but that is in reality a small issue as all it does is remove the worry of rad poisoning which is already eliminated fully as we are provided radiation suits and sonic emitters.

Now coming from a personal stance from my time in mining it became apparent very quickly that ameridian is a wholly inefficient way of making money in cargo unless you fully dedicate to only that, and even then you cannot use the liquid to make up for any potential material orders since you are loosing hundreds of credits in that endeavor for any near stack sized orders. Crystals may have all these neat things they can be changed into but at the end of the day it is nothing but a money sink to use them that way, the only real way to use the crystals effectively, in the sense of LS, is to just mine the crystals and sell them since that is the best way to make money off of them, the issue with that is they are slow to grow currently and in mining the most effective way to make money and materials is still hand/exo mining. Crystals and even fully modded big drill will be outclassed. If this change were to go through however I could see how hand miners would naturally run across the crystals, and with them being a threat with the golems their most effective way to deal with it would be to kill the golems and mine up the spires and crystals, which means that the miners would effectively passively collect ameridian while doing standard mining and if I had to do math in my head based off my experiences that would mean miners would be walking away with ~100 ameridian crystals if they dealt with a 3x3 formation with a spire in the middle and no golems. 

Lastly as a fully personal belief, I think that the way that ameridian is set up currently it costs too much to set up an ameridian grow to hoist up LS with. Ameridian at this point is only good for those that get interested in it for a couple rounds as a pet project, I was like this and past that I have only seen one other miner, who's player had serious experience in guild, try to make a large ameridian farm and they were still struggling to make as much that standard mining can and it was very time consuming. In regards to Soteria, I think it would be unfair to add anything ameridian related, their own grow farm and ability to make ameridian processers included,  since this was supposed to be an LS only venture. But on top of that I think they should be barred as they added through mapping their own potted ameridian plants that they could use to make their own farm, circumventing the need for LS for any reason other than the need of a core from LS. 

Sorry if this is disjointed or hard to understand, I didn't write this in one sitting

**Comment by Trilbyspaceclone** [comment]
image
adding it to the spirer

**Comment by cdb-is-not-good** [comment]
So to clarify, do spires now spawn naturally or are they always a product of player intervention?

**Comment by cdb-is-not-good** [comment]
also pls give tl;dr of the changes made

**Comment by Trilbyspaceclone** [comment]
> also pls give tl;dr of the changes made

the TL:DR
Green rock no longer normally endlessly spreads
No longer endlessly makes golems
Rads are more and only on spire 
People activate spire with cores making them rad active to spread and have the above rads

golems now when a ameridian is made spawn to protect it

prices on ameridian are cheaper to make people accully want to use it
crafting ameridain is removed but now you can make spires at a heavy cost

**Comment by cdb-is-not-good** [comment]
> > also pls give tl;dr of the changes made
> 
> the TL:DR Green rock no longer normally endlessly spreads No longer endlessly makes golems Rads are more and only on spire People activate spire with cores making them rad active to spread and have the above rads Mines spawn ameridaian golems, spires and ameridaian itself as well as rocks and rubbel
> 
> golems now when a ameridian is made spawn to protect it
> 
> prices on ameridian are cheaper to make people accully want to use it crafting ameridain is removed but now you can make spires at a heavy cost

I'll merge this for now as it seems to be in line with the changes that were requested by folks and seems to be a good change to a system that's largely been sidelined, if someone wants to make changes/revert this down the line that bridge can be crossed by the lead-dev at that time

**Pull request merged**
