### PR TITLE
(DNR)(WIP) Omni-PR

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>

	
<hr>
</details>

**###_From Lamas:
Framework on how it should operate is done just needs way more professions which you can leave in comments on what it should be
What this PR does which is the biggest change that actually comes from here https://github.com/Eclipse-Station/NEV-Northern-Light/pull/1689 in essence it limits stats from ever going in their version 150 I reduced it further to 120
Furthermore removes planets from background selections and changes career ethnicity and upbringing to origin (where you came from) childhood (decides your perks) and profession (what gives you the most skill points)
The point of this change is so that certain races/backgrounds aren't clearly meta over the other but rather complement a certain playstyle since the current system has the issue of "Just pick scavenger and rough life lol lmao" which is pretty sad
Most jobs got stats changed mainly buff to janitor back to his glory days since players no longer seem to have issues with being prospector+, on the topic of prospector they are now the only ones with sure step._**

This is a omni-PR that will change several kinds of stuff regarding the game due to my vision and additions that I felt that would be reasonable to do:

#define STAT_LEVEL_GOD		300 
You cannot go past this... as I think it is really reasonable as a value. 300 should be the value that nothing should really break. As far as I know lore-wise all council members should have between 100 to 300 so any bigger value should be quite prevalent. Or non-game breaking as the value should not break anything.

_Changes to Steward Quarters_
image
image
_I decided that the Steward should have changed regarding is new duty:
Aiding/Rescuing and helping council members. They get a paramedic helmet (I can sprite a new one with worse values). Tracking helmet. Surgery Kit (Normal Kit. Why? Well to be fair Stewards should ABSOLUTELY as known do any type of surgery if we have a medical on duty, but in just instances where surgery could save lives or shrapnel removal, they don't even get things to properly heal organs afaik. If people think that's too far that's okay I going to remove it). Combat Medical Kit. A roller bed so they don't need to steal Soteria. New changes to the map alongside a + 4 nanopastes to healing synthetical council members and tools. Shield/Baton/Armours at the armory aswell as emergency fire axe on the council armory._

WIP to BE MADE:
image
New Blackshield (Maybe Marshal?) gun.

- [ ] WIP: Give CBO a unique tool
- [ ] WIP to DO: Give Steward a unique self-defense weapon.
- [ ] WIP to DO: Give Church new alternatives armor sprites
- [ ] WIP to DO: Give TWO new types of background that essentially gives a genetic base that gives round start genes depending on the race (Humans/Abhumans get a specific set of gene packs: Canine / Feline / Caprine. ETC and each one of those gene packs has different types of mutations that gives their character uniqueness)
- [ ] WIP to DO: Create the other system to give round start "implants" (Depending on the race ethnicity / and race itself). An example is a canine implant set that gives you two organic claws implants at each hand, weaker compared to prosthetic, un-moddable, un-EMPeable, small NV eyes that gives them really minor NV to being weaker to flashes. Felines get another type. )

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Just as a reminder, since I forgot to coment it on Lamas' PR.

This means that every single and I do mean **EVERY SINGLE** skill check on the game will have to be readjusted in consideration of:

1. A stat cap now existing, making stats impossible to accumulate past a godlike state and thereby stablishing a minimum-maximum threshold for stat checks
2. Pre-existing hard and soft stat caps for certain checks (80 BIO for tissue restoration surgery, 100 ROB for throwing weapons, psionic summons, etc)
3. **Massive** nerf in starting stats for every single player
4. Profession stat gain rebalance, meaning their minimum thresholds to do their jobs effectively will have to be met somehow by default

Take this into consideration when making and merging this PR, please, lest we have through another "testmerge without calling it a testmerge and fix our fuck ups on the future" like we're still doing with weapon fire delay.

**Comment by elgeonmb** [comment]
please don't make one PR for multiple unrelated changes some of which are highly contraversial, it makes it harder to go through and review the contraversial changes

**Comment by ThePainkiller** [comment]
What the fuck has this PR become.
Who the everliving fuck ever said "Steward should be able to do surgery"???????????

**Comment by faaaay** [comment]
Aside from the point that's already been raised about rolling multiple completely unrelated PRs into one:

The Steward is, ultimately, no more of a surgeon than a Corpsman or Salvager. They _can_ potentially have that much BIO, but it's not their role. **At most** Steward should be equipped for emergency medical aid. 

> WIP to DO: Give Marshals a new machine that helps officers/rangers to create ammo and arguably sell and make for themselves when there's no SS or WO.

This is fulfilled by ammo disks in the autolathe.

**Comment by cdb-is-not-good** [comment]
>WIP to DO: Give Steward a unique self-defense sword\

please don't do this. Just give them a gun or something that's actually useful. Swords are a meme.

> WIP to DO: Give Marshals a new machine that helps officers/rangers to create ammo and arguably sell and make for themselves when there's no SS or WO.

We have that, we have that and it's called our public lathe.

**Comment by ThePainkiller** [comment]
> WIP: Give CBO a unique self-defense gun

They already have the white-paintjob Clarissa with snowflake soporific bullets that's just a glorified slaughtomatic. CBO could use any kind of gadget that isn't necessarily just a cooler gun, something that would benefit medical greatly in some way or another. ~~Give me my hypersleeper board, Kriosan scum.~~

> The Steward is, ultimately, no more of a surgeon than a Corpsman or Salvager. They _can_ potentially have that much BIO, but it's not their role. **At most** Steward should be equipped for emergency medical aid.

Corpsmen are **at least mentioned in SoP** as the very least option available when it comes to performing surgery, when has a **STEWARD** have ever been seen as a surgically-capable job??? Their goal is to **PROTECT** not to **FIX** the harm done to other heads of staff. The comparison with Salvager **does** work as they're never intended, not even as a last ditch effort, only in the extreme necessity of no one with a bigger BIO stat than them, but **Steward**?! Please no, by no means.
 
> WIP to DO: Give Marshals a new machine that helps officers/rangers to create ammo and arguably sell and make for themselves when there's no SS or WO.

They are given a plethora of ammo disks, an autolathe, and STARTING MATS for this. I even threw in the caseless ammo box so that Rangers that pick the Spec Ops doesn't get gimped on ammo if there's no SS/WO on duty.

**Comment by Thegreatspidernonbinary** [comment]
why are these all in one PR? some of these additions are cool but some of them aren't

**Comment by Guidesu** [comment]
Eh....  not in the mood anymore tbh

**Pull request closed without merging**
