### PR TITLE
Greyson Offices Map Rework

### PR DESCRIPTION
**Pull request by Rat-Time**
## About The Pull Request
A rework of the Greyson Offices map.
Changes-
The map itself has been cut down to 130x150 from the original 200x150.
Areas that were never touched have been cut, this includes: northern parking lot, central dorms, office spaces, large air fuel cloud filled roach/food trash room.
Areas with valuable loot that were rarely touched have been revamped to have additional access or condensed.
Full use of the area lighting.
Removal of large amounts of mobs that are never engaged by players.
Addition of a central office tower containing additional routes and the re-arranged prototype storage loot rooms.
Only a few turrets were removed, most were repositioned in hopes of making them more interesting to their areas.

StrongDMM_0aDX00d7Wm
StrongDMM_wmDu051Wb9

My goal for this re-work was to cut down on unused space and mobs, making the remaining space interesting in order to get people visiting areas that were going completely untouched.  I've focused the map down into a central north to south strip rather than the more sprawling previous setup.  Two sets of inactive teleporter pads are within the central office complex for events or future building projects.  I had plans for a mini-dungeon but life unfortunately got in the way.
As always changes can be made pending feedback.

Areas filled out as per request.
Vasiliy landing location added.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
This bathroom having 2 doors is a little odd
Also could this storage area have a few extra basic melee things like the FPB looking ones?
image

**Comment by Trilbyspaceclone** [comment]
image
The light sky area both layers should have some inviz lights under the windows to help smooth out lighting from it

**Comment by Trilbyspaceclone** [comment]
image
If you could check if the map data in this location is still present that is required as in my version it is not

**Comment by Trilbyspaceclone** [comment]
image
Adding in a wall in the bottom top roof section is an odd choice I dont understand

The top section feels rather enemty, maybe a rooftop garden could be added? Unsure

Bottom section feels a little enemy too, maybe a second material crate drop off? I.e a cargo crate already opened and moved into other storage areas

**Comment by Trilbyspaceclone** [comment]
image
Its a little odd theirs no workers in this small area as  well as the lockers having no loot makes it seem just odd? Unfitting?
Perhaps some engi borgs and medical/tool lockers in the room in the image

**Comment by FoxBopGaming** [comment]
quick question, was the use of the old, outdated Greyson turret sprite, over the newer Greyson Laser Turret Sprite here intentional, it looks out of place? 
image

**Comment by Rat-Time** [comment]
Intentional, as they're a different sort of area denial.

**Comment by Rat-Time** [comment]
Turrets replaced.

**Pull request merged**
