### PR TITLE
fixing map troubles (copypasting)

### PR DESCRIPTION
**Pull request by GlitchySoftware**
Copy and pastes a couple other of my pull requests totalling it together, since i am a big dumb and cant use github properly

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Pic plox

**Comment by GlitchySoftware** [comment]
> Pic plox

no new content added, everything same fr fr no cap

**Comment by GlitchySoftware** [comment]
just the PRs i had jammed into one to avoid map bugs

**Comment by GlitchySoftware** [comment]
for some reason i cant upload strongdmm screenshots

**Comment by cdb-is-not-good** [comment]
So just copy paste the pics from the other PRs u goober

**Comment by GlitchySoftware** [comment]
image
image
image
image
image

**Comment by GlitchySoftware** [comment]
@cdb-is-not-good yippee

**Pull request merged**
