### PR TITLE
Nothing to see here.

### PR DESCRIPTION
**Pull request by benj8560**
A small PR I came up with in bed then made a reality. Direct quote from CDB ''Can we make it even smaller'' Thus clearly already approved by a lead maintainer! 

Jokes aside test merge this for 1 or 2 rounds then send it back to hell where it belongs and merged the REAL shuttle PR

intentionally vague changelog: 
The Vasiliy was in need of a overhaul. A replacement ''shuttle'' has been provided for the marshals hanger in the meantime.

''art'':
StrongDMM_LgLScOGWXj

### CODE REVIEW

**Comment by benj8560** [comment]
and yes i do hate that it looks kinda cool honestly

**Comment by benj8560** [comment]
whatever bots proly whining about nothing works fine in testing

**Comment by AysheDaArtist** [comment]
"We're updating the Vasiliy!"
"We've provided you a shuttle in the meantime"

Solid gold, I love this server

**Comment by Noobetski** [comment]
The Pill 2: The Electric Boogaloo edition

**Comment by benj8560** [comment]
You'll be missed my lil pod....never got the respect you deserved ;-;

**Pull request closed without merging**
