### PR TITLE
More QOL for borgs and minor AI bugfix

### PR DESCRIPTION
**Pull request by benj8560**
More QOL nothing massive. Don't think there should be much debate as to why.

Changelog: 

Adds 2 more beakers to the medical borg for a total of 4.
Makes the medical borg defib a SI advanced defib.
Adds a large syringe to the medical borg replacing their old one.
Adds a mini welder to the janitor borg as all other modules get one.
Adds the sec borgs holowarrent projector back now that it has print functionality it can be used correctly.
Tweaks the desc on sec borg handcuffs to convey that they can collect used handcuffs with it.

Disables speaking Jive for AI for obvious reasons.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I think their was issues with hollow warrents with borgs, can you test it out?

**Comment by benj8560** [comment]
they cant use show held item thus they cant show the projector itself. However since Spock added printing to the projector's they can just use that

**Comment by benj8560** [comment]
and yes I tested that the printing works fine for them

**Comment by king5327** [comment]
When you say 'speak' jive, are we insinuating that, at least in person, the AI wouldn't be able to replicate the gestures on its screen?

Maybe an idea for a later PR, but allow the AI to 'speak' jive through the telescreens instead of the radio.

**Comment by benj8560** [comment]
> When you say 'speak' jive, are we insinuating that, at least in person, the AI wouldn't be able to replicate the gestures on its screen?
> 
> Maybe an idea for a later PR, but allow the AI to 'speak' jive through the telescreens instead of the radio.

I suppose it likely could? But they're usually on comms regardless. Ideally we would just get languages actually working on holopads some fine day.

**Comment by benj8560** [comment]
confirmed borgs defib is working as a advanced defib now

**Pull request merged**
