### PR TITLE
Makes mobs randomly retarget, adds framework for custom mob targetting, moves superior mob vars into their own file, among other changes.

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
Title.

I made them randomly retarget because I noticed mobs got really tunnel visiony. I didn't like that.

You may ask, why did you make new procs for finding the nearest objects in the list? Put simply I literally had no idea how the other proc worked like at all.

I moved it into it's own file because it was honestly getting really cluttered.

## Changelog
:cl:
add: Mobs will now randomly retarget.
code: Moved mob vars and declaration into superior_defines.dm
/:cl:

### CODE REVIEW

**Comment by nikothedude** [comment]
DAMN IT

**Comment by nikothedude** [comment]
come on baby give me the conflict so i can resolve it already

**Comment by nikothedude** [comment]
btw, i didnt test this much as i usually do for something with this size, so if you want to not merge it on that basis, thats totally fine

gonna do some extra testing anyway, but testing did show targetting seemed to work, there were no runtimes, etc

**Comment by cdb-is-not-good** [comment]
yes pls, test

**Comment by nikothedude** [comment]
found a few bugs and fixed em, im done testing

**Pull request merged**
