### PR TITLE
New optimized NV goggles sprites and more

### PR DESCRIPTION
**Pull request by ThePainkiller**
## Drafted pending approval of map changes

- "Converted" NV goggles renamed to "Optimized" ones as that's what they are in the end
- New sprites for the guild NV courtesy of Dromkii!
image
- Fixes bad reagent filling overlay on droppers
- Fixes reagent_filling not working properly on spray bottles
- Adds a black trenchcoat to the suit jacket selection, with female alt mode
image
- Fixes wall lockers not having a proper opened state (FINALLY)
- Adds a recharger to the organ lab, moves the organ storage to the adjacent table
image
- Corrects disposals positioning on genetics lab to not block access to a table with the chem cannon
image
- Repositions the light switch on the Prime's office to not be awkwardly floating on top of the library
image
- EDIT: Marshal armory windoors now with proper armory access, adds a windoor with armory access to the Takeshi machinegun, and an extra row of reinforced metal walls to the Marshal armory on request of CDB
image
- Most pre-filled pill bottles now come appropiately colored for ease of distinction

## Changelog
:cl:
add: Black trenchcoat to suit jacket selection, for all your film noir needs
fix: Fixes a few bad chem overlays on droppers and spray bottles
tweak: Converted NV goggles renamed to Optimized NV goggles
tweak: Most pre-filled pill bottles now come appropiately colored for ease of distinction
imageadd: New Optimized NV goggles courtesy of #Ezoken5894
map: Recharger added to organ lab. Fixed positioning of disposals chute on Genetics. Prime office light switch fix. Granted armory access to Marshal Armory's windoors. Adds an extra row of reinforced walling to the Marshal armory.
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
the sprites a little unusual. It doesn't quite look like it was made from a pair of mesons

**Comment by TheSleepyCatmom** [comment]
They are in fact meant to be made from a pair of Mesons, so they should be using mesons as a base.

**Comment by ThePainkiller** [comment]
Changed the Optimized Nightvision Goggles' sprite to an accepted version now (at least by Das), updated the screenshots on the PR

Still waiting for Lich approval to be merge ready.

**Comment by Medizeal22** [comment]
Map approved.

**Pull request merged**
