### PR TITLE
Bone gel, a proper way to fix bones

### PR DESCRIPTION
**Pull request by ThePainkiller**
## About The Pull Request

- Adds Bone Gel, a tool with bone grafting quality that now comes on every surgical kit on the colony. Instead of using Advanced Trauma Kits or Bruise Packs to fix bones as if they were organs, there's a new surgical procedure that uses this consumable item to repair bone damage (but not mend fractures), replacing trauma kit use.
- Makes Bone Gel craftable through science on the basic medical node, in case you somehow need to print more of them.
- **New Retractor and Bonesetter sprites!** Courtesy of @Dongels , so that now you won't confuse Bonesetter with Hemostat due to how similar they always were!
- New Autopsy Scanner sprite, animated, that fits a better color palette for surgical tools.
- Surgical drills removed from surgical kits and as a "surgical" tool. Now renamed to "Hand drills", you may still find them on piles of trash or build them from an autolathe (just not from a soteria medical disk anymore), they can still be used to craft anything that requires drilling quality, as cavity surgery is a heavily discontinued surgical procedure only ever used on `old_surgery`.
- Same as with implantation, a proper sound is now played every time you finish mending bones or fixing an organ through surgery. ~There are **so** many sounds unused in code for some reason...~
- Superglue now has bone grafting capabilities to act as a ghetto replacement for Bone Gel, also costs plastic instead of biomatter because autolathes can't accept biomatter and thus it's a wasted design otherwise.

<hr>

</details>

## Changelog
:cl:DimmaDunk
add: Added Bone Gel, a tool used to repair damage to the bones through surgery.
add: Added bone grafting quality, used to fix bones. Currently, only Superglue and Bone Gel 
tweak: Surgical drills are now named Hand Drills and no longer classify as a surgical tool.
soundadd: Added sounds for succesful organ repair and bone repair surgeries.
imageadd: Added new sprites for the Retractor and Bonesetter (by @Dongels), for the Bone Gel, and a new Autopsy Scanner sprite.
/:cl:

### CODE REVIEW

**Comment by Kazkin** [comment]
Make bone gel consumable with 5 charges, 1 per use. A non-consumable property makes it far too simple to fix heavily broken bones otherwise.

**Comment by Kazkin** [comment]
As an addition to the above statement, nanopaste has 5 charges and heals 200 toxins per 1 use. If nanites are not infinite, gel shouldn't be either.

**Comment by Trilbyspaceclone** [comment]
> As an addition to the above statement, nanopaste has 5 charges and heals 200 toxins per 1 use. If nanites are not infinite, gel shouldn't be either.

No they dont, nanopaste heals 40 per 1 use, 1 full stack is 200 toxin damage.

**Comment by ThePainkiller** [comment]
@Kazkin Fair points, let me clarify:


> Make bone gel consumable with 5 charges, 1 per use. A non-consumable property makes it far too simple to fix heavily broken bones otherwise.

1. On any other codebase in wich I have played, Bone Gel was **never** a consumable, but I agree that conditions here are different since bones have health bars, and thus leads me to my second point,
2. I have never, in my experience on this server as solely medic, ever seen a bone go below 10-20 damage only. Justifying **one** use of Bone Gel out of **five** for such minimal damage (specially now that Ossisine has become the only chem that fixes it as per my previous PR #872 ) is literally **wasting** a charge. You might think this is a non-issue for medical, who can mix Ossisine on the fly, but this **utterly** fucks up Corpsmen who need to deal with multiple bone fractures on the field and don't have the luxury of a chem dispenser, or ideal conditions for restocking.

> As an addition to the above statement, nanopaste has 5 charges and heals 200 toxins per 1 use. If nanites are not infinite, gel shouldn't be either.

3. This comparison holds terribly. Nanopaste not only fixes 200 damage on a **full five stack use** (not on 1 use, god I wish), it also fixes neural degeneration due to the corpse being dead for more than 1 hour, and is currently the only way to fix toxins accumulation on a dead body (and the very niche case of neural degradation). The nanopaste "1 charge use" is still tied **ONLY** to doctors (and the CBO) and it's not a universal thing, narrowing the efficacy even more, not to mention it now takes plasteel and raw nanobots to make. making it a pain in the ass to obtain for such benefits in wich it gets consumed entirely if not used by a doctor.

My aim is to give an alternative that takes both ideal and non-ideal situations in wich bone repair is required, while cutting off the massive biogel (trauma kit) use problem that medbay has, seeing as how up until not long ago it was a universal fix.

While I can agree you have a solid point on non-consumability, this needs a charge system, so I propose doing the following:

1. Change the crafting materials to both plastic **and** biomatter, to justify what it does.
2. Instead of mere 5 charges, I'm going to make it stack-based like tape (max number of stacks pending, might be 20/30/100 depending on balance), and adjust the time spent doing this surgical procedure to a skill/perk check, using `consume_resources` as a measurement of stacks consumed per seconds spent like tapes do, probably with a 1 stack soft cap as well (instead of the regular tape's 0.5 uses since it's terrible for balance).

**Comment by Kazkin** [comment]
I can see a 100 scale for a 1:1 for bone healing, making it a biomatter and plastic base is also a functional alternative.

**Comment by ThePainkiller** [comment]
Why the hell do I keep getting icon merge conflicts, I don't want to make so many commits to doccument my stupidity please help

**Comment by ThePainkiller** [comment]
Okay that solved it, compiles and everything, yadda yadda. Testing pending.

**Comment by Kazkin** [comment]
More merge conflicts :D

**Comment by Kazkin** [comment]
Ping me when its up and I'll make sure to make it a priority merge.

**Comment by Kazkin** [comment]
Once I get the clear for it being tested I'll merge this.

**Pull request merged**
