### PR TITLE
Add microwave recipe for hawaiian pizza

### PR DESCRIPTION
**Pull request by du-top**
## About The Pull Request
<details>
<summary>
	Add missing pizza recipe to microwave.
</summary>
<hr>

	Added missing pizza microwave recipe, enabling the chef to cook all the pizzas that are also in an ordered pizza crate. The pizza itself was already there, it was just not possible to create it.
<hr>
</details>

## Changelog
:cl:dutop
add: Added missing pizza recipe to microwave

/:cl:

### CODE REVIEW

**Comment by Rat-Time** [comment]
This should have a non-zero chance of summoning deep maintenance creatures.

**Comment by cdb-is-not-good** [comment]
Also the recipe is a little off. Hawaiian Pizza has canadian bacon/ham , i know the other one is ALSO only pineapple but now is a good time to remedy this :)

**Comment by ThePainkiller** [comment]
I will metagrudge whoever cooks this until I get banned. I'm not joking.

**Comment by du-top** [comment]
Well, the pizza was already there and contained no taste of anything meaty and not much protein. It's quite similar to the mushroom pizza, so I took that as base and replaced the five mushrooms with one pineapples (a little hint to the fact that someone thought it would be nice to have the pineapple's kitchen-id in plural, costing me about an hour to figure that out), because pineapples are bigger.
Sure, one could change the pizza and the recipe to include meat. I'm torn here between realism and changing as less as possible (especially without approval from the lore guys).

**Pull request merged**
