### PR TITLE
Buffs psion point regen

### PR DESCRIPTION
**Pull request by Ghostcoffeee**
## About The Pull Request
<details>
<summary>
	>>:)
</summary>
<hr>
Made psions regenerate all of their points at once.
Endorsed by Solvult.

https://cdn.discordapp.com/attachments/387651131645362211/1125512591960178869/image.png

	
<hr>
</details>

## Changelog
:cl:
balance: Psions now regenerate all their psi points at once.
/:cl:

### CODE REVIEW

**Comment by AysheDaArtist** [comment]
As a psion user/coder I highly recommend **against** this PR

Why have Psion's regenerate all of their psi points at once when we have code to give it back on a timed regen?
It is better to balance with **COG** on a time scaled regen if you wish to speed up psi point regen.

**Comment by cdb-is-not-good** [comment]
Bad change, unnecessary. If you want to buff the regen, sure. Make it take less time. Have you already forgotten our standard for this kind of thing? A buff or nerf should be 50% at best/worst, don't jump suddenly into a massive change.

**Comment by Ghostcoffeee** [comment]
Had a nap and sobered up

**Comment by AysheDaArtist** [comment]
A variation of psion regen to assist has been PR'd https://github.com/sojourn-13/sojourn-station/pull/4684

**Pull request closed without merging**
