### PR TITLE
Tries to improve a little pixel scaling

### PR DESCRIPTION
**Pull request by Guidesu**
I just added a few flags to icon lines, and accessories which should help further in making visual clarity better on big and small sprites. Tested in game, for me there were a slight improvement

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
pics pls

**Comment by cdb-is-not-good** [comment]
PICS PLS

**Comment by Guidesu** [comment]
Doing it

**Comment by cdb-is-not-good** [comment]
Is this still being worked on or no?

**Comment by Guidesu** [comment]
Nope.

**Pull request closed without merging**
