### PR TITLE
fixes rook speed

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Rooks are no longer to fast

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by king5327** [comment]
Probably late since this isn't the right PR for it, but the rook deals the exact same amount of damage as any other, just with tweaked probabilities.

**Comment by Trilbyspaceclone** [comment]
Thats intented, rook deals 20 damage

**Comment by king5327** [comment]
I mean, so do the others. The only difference is the others deal randomly between 15 and 25, and the rook deals 20 every time.

**Comment by king5327** [comment]
Yeah, no, this one has 20 times the health of a regular roomba and twice the damage. OP.

**Comment by Kazkin** [comment]
This makes them even shittier. Gonna close because they're already quite terrible in regards of player pet mobs.

**Pull request closed without merging**
