### PR TITLE
Return of Sudtle (Not antighost)

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
based?

Subtle (not antighost) is like a small emote thats kinda like a whisper that works in a small area. Useful for hostages and sneaky cases of antagery!

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
tested?

**Comment by Trilbyspaceclone** [comment]
> tested?

It hasnt changed in legit years

**Comment by cdb-is-not-good** [comment]
Tested???

**Comment by Trilbyspaceclone** [comment]
> Tested???

It was last tested years ago when we had it

**Comment by benj8560** [comment]
dunnnooo still not crazy about this people always just used it to stealth fuck in the bar :P guess we see if that starts again

**Comment by Trilbyspaceclone** [comment]
> dunnnooo still not crazy about this people always just used it to stealth fuck in the bar :P guess we see if that starts again

oh hey isnt that why this was removed?

**Pull request merged**
