### PR TITLE
Fractals are invited

### PR DESCRIPTION
**Pull request by benj8560**
Makes some changes to fractal rosaries. After a gander at are updated lore (that I wont explain here go read it **especially** if you want to take one all of a sudden) I felt they where deserving of being able to open public church doors. Round start being just the commons. copying the way the tau cross neckless handles this. (partly)

Updates its desc to convey this.

Removes it from the church vender as it should have been awhile ago honestly. Church can print them now anyways.

### CODE REVIEW

**Comment by benj8560** [comment]
idk why it decided to grab the last ALREADY merged PR I did and cram it in here I'm using new shit for pushing PRs and its giving me trouble I guess. I don't think its really a problem but drafted just incase

**Comment by benj8560** [comment]
I guess its likely not really a problem just let me know if it is and what I should do about it.

**Comment by benj8560** [comment]
problems fix yey

**Comment by SingingSpock** [comment]
Don't write a whole new access proc for the public doors. Better to write another line into the general holy access proc for "if you've got the Rosary and the door access level is 0, you shall pass"

**Comment by benj8560** [comment]
I assumed I was doing very lazily ye figured there would be a cleaner way

**Comment by benj8560** [comment]
I'll look into it later

**Comment by benj8560** [comment]
Cleaner code made and tested

**Pull request merged**
