### PR TITLE
Revert "Medical kit storage rebalance" and buff the medical hardcase instead

### PR DESCRIPTION
**Pull request by r4d6**
- Reverts sojourn-13/sojourn-station#2751
- Augment the medical hardcase storage from 15 to 25
- Augment the scrap medical hardcase storage from 13 to 20

From what I could gather/figure out, Trilby heard some complaints that the Medical Hardcase was useless because it held the same amount as regular first aid kits, despite being harder to use than the kits.

So instead of just... buffing the hardcase, Trilby decided to make all the aid kits hold less stuff _and_ start with less stuff, so that in the end the hardcase would have "more" storage.
So it was basically just a server-wide nerf to medkits, since they no longer hold as much supplies and start with half as much.
And the Large Bruise/Burn Kits aren't used in the code anywhere, so they might as well not exist.

So this PR revert Trilby's PR **and** buff the medical hardcase storage to be bigger, so that it is worth to fiddle with it.

### CODE REVIEW

**Comment by r4d6** [comment]
> This dosnt address the issues at all and power creeps storae

The power creep is something _**you**_ coded in : [This](https://github.com/sojourn-13/sojourn-station/commit/e2d2a2af8a3e2573dd4fb668b30d395a94dd78c0) is you setting the medkit's storage capacity to 15.

**Comment by Trilbyspaceclone** [comment]
Correct, cuz they were printing for 0 storage before, when done via enemty do to being set as "exsand to fit"

**Comment by Trilbyspaceclone** [comment]
the DNM tag is so possum reviews it closer

**Comment by Trilbyspaceclone** [comment]
The entire pr statements on my intent and the story behind it is legitmently wrong

**Comment by r4d6** [comment]
> The entire pr statements on my intent and the story behind it is legitmently wrong

Well my impression of your intent during our discord discussion was that someone complained to you about the Medical Hardcase's additional finagling not being worth it since the First Aid Kits had the same amount of space and didn't require any finagling, and that you decided to nerf First Aid Kits as a whole by making them hold **less** than actual boxes while also making them start with less medical supplies. As a whole, FAKs lost 33% of their brute healing and 50% of their burn healing.

**Comment by Trilbyspaceclone** [comment]
The o.g pr buffed healing, the og idea was nothing to do with hardcases, I actively stated its *not* about hardcases

**Pull request closed without merging**
