### PR TITLE
/tg/ statpanel

### PR DESCRIPTION
**Pull request by ShadowLarkens**
## About The Pull Request
Ports /tg/'s latest stat panel.

This is fully functional.

preview

## Changelog
:cl:
add: /tg/'s stat panel replaces the upper right corner
add: Fullscreen mode
tweak: Chatbar is now on the right pane only
tweak: Status bar is a cute little grey thing in the bottom left
add: Added tooltips to actions
tweak: Perks are now actions 
add: Added action palette button with custom sprite... but all it does is hide buttons rn
fix: Horrible verb lag
/:cl:

### CODE REVIEW

**Comment by benj8560** [comment]
HOLY SHIT ITS HAPPENING

**Comment by king5327** [comment]
I personally would prefer it if the chatbar stayed full-width.

On the one hand, halving it when people are typing emotes into the thing is quite the inconvenience. On the other hand, me and like... two other people use it.

**Comment by Dimasw99** [comment]
grafik
Another minor issue of being unable to tell which bottle is what, even if they are named

**Comment by benj8560** [comment]
you need to manually click off the window _every_ single time you wanna hit the drop/throw hotkey when sorting loot. This. Is. awful. Please if you can find a way around this. Also yes the window saving or perhaps defaulting to a 4x4 or 5x5 would be very nice. Usually if I'm using this window theres gonna be a LOT of crap.

**Comment by ShadowLarkens** [comment]
> grafik Another minor issue of being unable to tell which bottle is what, even if they are named

Hover over them to see the full name

**Comment by ShadowLarkens** [comment]
> Is it possible for the loot panel to memorise its size? 3x3 is often quite small. Another minor thing is that alt clicking makes the search bar automatically selected.

Can make it bigger, search automatically selected is intended for quickly sorting through

**Pull request merged**
