### PR TITLE
Revert "Hides Crafting Menus of Unknown Categories"

### PR DESCRIPTION
**Pull request by Yawet330**
Reverts sojourn-13/sojourn-station#2835

was not tested. Broke the game.

### CODE REVIEW

**Comment by Yawet330** [comment]
Creator is apparently fixing it, but until its confirmed to work, leaving this up.

**Comment by Risikio** [comment]
"It breaks the game."

How? I'm vaguely aware of an issue with the storage tab, but "break the game" and "Missing storage tab" are different things.

**Comment by Yawet330** [comment]
> "It breaks the game."
> 
> How? I'm vaguely aware of an issue with the storage tab, but "break the game" and "Missing storage tab" are different things.

Read what was discussed in dev-general. Your PR can effect far more than just the storage tab. This is only what we were aware of.

**Comment by r4d6** [comment]
> > "It breaks the game."
> > How? I'm vaguely aware of an issue with the storage tab, but "break the game" and "Missing storage tab" are different things.
> 
> Read what was discussed in dev-general. Your PR can effect far more than just the storage tab. This is only what we were aware of.

Riskio's PR was merged 12 hours ago, so it was merged at 9 PM (At least for me). His PR was also made 14 hours ago, so at 7 PM.
This PR was opened 6 hours ago, or at 3 AM.

And the last post in the Development-General channel was me, at 8 PM (So an hour after Risikio's PR was opened, and an hour before it was merged) saying that the Hydrogen Generator doesn't have an UI.

So, I am _**very**_ curious as to what discussion in Dev-General you are talking about, because I don't see anything.

**Pull request closed without merging**
