### PR TITLE
fixes guild clothes sprites + typos + whoops

### PR DESCRIPTION
**Pull request by Dissentbay**
## About The Pull Request
<details>
<summary>
	read title
</summary>
<hr>
I tried also to fix the overlay issue on clothings being affected by contaminate(), but it seems the overlay is written as null for some fucking reason and the only solution to remove the overlay is var editing currently 😔 since decontaminate() can make the item safe, but not handle the overlay

	
<hr>
</details>

## Changelog
:cl:
fix: typos in guild clothing
fix: east sprite issues on guild clothing
fix: wiring of the soteria outpost is now supposed to work as it should (my bad)

/:cl:

### CODE REVIEW

**Comment by Dissentbay** [comment]
i love how it keeps giving errors unrelated to my code 💢

**Comment by Dissentbay** [comment]
added a wiring fix that may have been caused by me

**Comment by REDLAERT88** [comment]
No issues here as far as my screen burnt eyes can see. Good to go.

**Comment by Guidesu** [comment]
Go wild!
No issues

**Pull request merged**
