### PR TITLE
Atmos tweaks (piping and related procs)

### PR DESCRIPTION
**Pull request by Dissentbay**
## About The Pull Request
<details>
<summary>

- fixes some issues with procs returning negative values instead of zero or positive values
- vents now sleep for up to 90 seconds if they aren't doing anything
- scrubbers sleep for up to 30 seconds if they aren't doing anything
- prepares vent_scrubber.dm in case someone wants to unbind it from SSmachines (every scrubber might be assigning himself one too many times to it without proper care of the var/currently_processing and the complete lack of a TRUE state in the entire code)

</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
this tested?

**Comment by Dissentbay** [comment]
yes, more than I would like to admit
but the scrubbers assigning themselves one too many times to SSmachines persists
but that is also on live so....

**Comment by Dissentbay** [comment]
actually give me some time, I will see if aurora and eris managed to fix that

**Comment by Dissentbay** [comment]
Eris did
https://github.com/discordia-space/CEV-Eris/pull/7493/files#top
but it's part of a bigger fix
you may can commit this now, I will look into copy pasting eris atmos here, if it is feasible to just adjust the ins and outs

**Comment by Dissentbay** [comment]
nevermind, I managed to port eris ATMOSPHERICS folder just fine
just need to fix the piping colors and the firedoors
this PR just became obsolete

**Pull request closed without merging**
