### PR TITLE
Ammo Fab access for the people(the security people)

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Removes the perk check on the bullet fab.

Why? The bullet fab is a great tool for security as a whole, but the fab being locked was something originally done because people would frequently break into the guild to use it when they weren't around where they'd likely suffer 0 consequence due to the guild being a low sec area. 

the fab is not in the guild anymore. It's in the Marshals. Breaking into the armory is a capital crime that carries extremely severe consequences. This change will empower those with access to use the thing when a Spec/WO isnt available which is a fairly frequent case. 

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
No. Play supply specialist or use the funny shootout disk.

**Comment by cdb-is-not-good** [comment]
the bullet fab goes unused more rounds than not these days, and the fab being unusable by officers/rangers when no spec/wo is on is also a not tiny issue

**Comment by Stutternov** [comment]
> the bullet fab goes unused more rounds than not these days, and the fab being unusable by officers/rangers when no spec/wo is on is also a not tiny issue

That's not a reason to change it. And this will not change that at all.

**Comment by cdb-is-not-good** [comment]
How  do you figure it's taking it away from them? They still hold absolute and executive authority over the entire armory, higher than any single person on the colony.

**Comment by Stutternov** [comment]
> How do you figure it's taking it away from them? They still hold absolute and executive authority over the entire armory, higher than any single person on the colony.

Stop encouraging other people to do their job. It has a:
- Stat mechanical bypass
- Guild perk check
- Gunsmith perk check

There are 3 ways to use the thing. Again, if you really want to make it Marshal exclusive, just remove the Guild perk and leave the mech and gunsmith. The mech check still works on this machine, just not the Nanoforge.

**Comment by Trilbyspaceclone** [comment]
Guild can use it in code red or what not,
It has a basic stat bypass
and its in the armory, somewere that if allowed by anyone to print will be flooded with non-specs/wos to get free tm ammo
Their other options for people to get basic ammo, by making the *best ammo printer in the game* easyer to use you are directly making all other options of ammo less viable.

**Comment by cdb-is-not-good** [comment]
didn't you JUST tell me that the mech bypass didn't work?

**Comment by Stutternov** [comment]
> didn't you JUST tell me that the mech bypass didn't work?

On the Nanoforage. I said this - directly - you told me to skill-lock the NANOFORGE.

**Pull request closed without merging**
