### PR TITLE
voidsuits (barring SCAF) now upgradeable

### PR DESCRIPTION
**Pull request by lolman360**
## About The Pull Request

voidsuits can now mount armor upgrades (plates etc)

this is probably an oversight given that voidsuit helmets can be upgraded, but it's still a straight buff

## Changelog
:cl:
balance: buffs voidsuits significantly by giving them 1 modular armor part space
balance: SCAF and other assorted high-armor (>65) voidsuits no longer plateable
tweak: voidsuit parts are now removable with a wrench not a screwdriver
/:cl:

### CODE REVIEW

**Comment by Kazkin** [comment]
Has this been tested? I remember there being issues with upgrading void suits.

**Comment by lolman360** [comment]
not yet

**Comment by ThePainkiller** [comment]
Does this mean we can attach cloak accesories again to voidsuits? I miss the outsider cape on SCAF combo.....

**Comment by Yawet330** [comment]
> Does this mean we can attach cloak accesories again to voidsuits? I miss the outsider cape on SCAF combo.....

I am far more concerned about people putting melee plates on SCAF suits

**Comment by lolman360** [comment]
> I am far more concerned about people putting melee plates on SCAF suits

you can already plate SCAF voidsuit *helmets*, but not the voidsuits proper

tbh it's too overpowered i can probably prevent them from getting plating at all since 90 melee resist is massive on anything player-obtainable

**Pull request merged**
