### PR TITLE
Drippening II: I Fucking Hate Accessory Code

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Time for another loadout expansion. This makes some additions, and refactors loadout code a bit so that the preview shows accessories properly.

The shirt, tie and turtleneck sprites in this PR are ported from Aurora.
	
<hr>
</details>

## Changelog
:cl:
add: recolorable shirt/turtleneck/tie accessories, ported from Aurora
refactor: tweaked preference code a bit so that accessories show up in the loadout
/:cl:

### CODE REVIEW

**Comment by faaaay** [comment]
hold off on merging, forgot something.

**Comment by faaaay** [comment]
Realised that my commits hadn't uploaded properly and couldn't get 'em through. **Ready to merge.**

**Comment by faaaay** [comment]
No idea what's up with the build failing. It works on my machine.

**Comment by Trilbyspaceclone** [comment]
Please do a few local tests to make sure this one isnt making massive lag on character making stuff

**Comment by faaaay** [comment]
> Please do a few local tests to make sure this one isnt making massive lag on character making stuff

I'm not seeing the lag in local tests. Was it lagging during the testmerge? Was it lag during startup, or when changing stuff in the character creation menu?

I just tested it with a shit-ton of accessories. The lag between clicking a loadout item and the preview updating was a fraction of a second, as it always is.

**Pull request merged**
