### PR TITLE
Adds a funky new tool for mappers and events: Entity spawners, objects that endlessly churn out any given entity, to a limit

### PR DESCRIPTION
**Pull request by nikothedude**
## About The Pull Request
This started as a meme, of a roomba dispenser, and very quickly became something I'm stupidly proud of.

Adds mob/entity spawners. Key to the functionality of this thing is a pair of lists, to_spawn and default_spawn, formatted as list(list(maximum, typepath, probability for prob()), ...), and list(list(maximum, typepath), ...) respectively. Maximum is the max of this entity the machine can spawn, typepath is typepath of the entity, probability is how likely, in percent, it is to be spawned on every spawn attempt. You can control how many are spawned per tick, how many ticks of delay it has, the probability of it actually firing on a given spawn tick, and many more things. 

I have successfully made a roomba dispenser that dispenses a random type of melee roomba every 6 ticks up to a max of 15, and let me say, it works GLORIOUSLY.

It works, no runtimes, but as always, there might be some bugs in it that I haven't found yet.

https://cdn.discordapp.com/attachments/859890910027841618/992658657626046494/2022-07-02_01-09-53.mp4

## Changelog
:cl:
add: Mob dispensers, that can spawn any given entity with a given chance and limit up to a total limit.
/:cl:

### CODE REVIEW

**Comment by hex37** [comment]
This'll probably be useful for drills...

**Comment by Spoopy11** [comment]
I wonder if it's worth putting something in so that the spawner is linked to what it spawns, and instead of spawning x amount of entities on a successful spawn roll it checks what's alive, what's not, and uses that delta as how many entities to spawn.

**Comment by nikothedude** [comment]
probably going to repath this to /obj/ or /obj/structure and use objss instead

**Comment by nikothedude** [comment]
> I wonder if it's worth putting something in so that the spawner is linked to what it spawns, and instead of spawning x amount of entities on a successful spawn roll it checks what's alive, what's not, and uses that delta as how many entities to spawn.

Already does this. Both the mob and the spawner hold a ref to their spawned mobs.

**Comment by nikothedude** [comment]
calling it, ready to merge

**Comment by nikothedude** [comment]
> I'd recommend making boombas a restricted/1 spawn only type of mob since trying to destroy these may lead to one spawning, instantly aggroing, and then blowing up in the same second. (or add a specific restriction/spawn type check that can be configged in vars (e.g 1 'boss' enemy, and then the rest will spawn as defined)

The boomba spawner is intentionally annoying, thats why I added //fuck you as a comment

Also, what do you mean by boss enemy? If you want only one instance of a mob to exist, you can set it's maximum to 1. If you want it to always spawn, you can also set it's prob to 100.

If you only want one instance of something to spawn, ever, thats fair, and I might do that

PR is still ready to merge though, any changes I make can be done in other prs

**Comment by nikothedude** [comment]
> > I'd recommend making boombas a restricted/1 spawn only type of mob since trying to destroy these may lead to one spawning, instantly aggroing, and then blowing up in the same second. (or add a specific restriction/spawn type check that can be configged in vars (e.g 1 'boss' enemy, and then the rest will spawn as defined)
> 
> The boomba spawner is intentionally annoying, thats why I added //fuck you as a comment
> 
> Also, what do you mean by boss enemy? If you want only one instance of a mob to exist, you can set it's maximum to 1. If you want it to always spawn, you can also set it's prob to 100.
> 
> If you only want one instance of something to spawn, ever, thats fair, and I might do that
> 
> PR is still ready to merge though, any changes I make can be done in other prs

ACTUALLY

If you want only one instance of something to ever exist, just spawn it in initialize()

**Pull request merged**
