### PR TITLE
HexCookFixAdd

### PR DESCRIPTION
**Pull request by AysheDaArtist**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Fixes broken recipes in Hex-Cooking / VIKA and adds new recipes

-Change: Cake recipes are easier to bake
-Fix: Glaze can be made for future recipes, raw meatball/chocolate bar recipe fix to stop foods with protein spontaneously spawning them 
-Add: Taco, Tortilla, Sausage, Hotdog, Flat Dough Slice 
-Remove: Raw meatball chem mix, Chocolate bar chem mix
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Not sure why your removing them form the microwave also please show proof that this is working in a test server do to fear of simular hex cooking overriding one a other

**Comment by cdb-is-not-good** [comment]
Big fan, the old way of creating these ingredients by mixing reagents was always fussy.

**Comment by du-top** [comment]
Please delete converted recipes from code/modules/cooking_with_jane/recipes/recipes_to_covert.dm 

I don't see anything removed from the microwave? Just mixing shit won't make a chocolate bar or meatball anymore. I understand the bar, but what is a meatball more than protein and flour? Nah, this is cleaner, like it.

**Comment by AysheDaArtist** [comment]
Was tested, but will test again and provide proof.

I'll clean up the code/modules/cooking_with_jane/recipes/recipes_to_covert.dm of recipes converted.
PR made to clean up the VIRK so all recipes work, and don't conflict; Old taco recipe would spawn meatballs due to protein.

**Comment by AysheDaArtist** [comment]
Video proof, please enjoy:
https://www.youtube.com/watch?v=mBjtdOAi-Oc

**Comment by AysheDaArtist** [comment]
The only question I have now, is what are we doing with **Food Quality**?  Does it _do anything_?

**Comment by Trilbyspaceclone** [comment]
well if carret cake works the rest should to so it should be fine?

**Comment by AysheDaArtist** [comment]
all the cakes use the same base recipe
cheesecake = add cheese slice instead of carrot
cocoa = add cocoa powder instead of carrot
plain = don't add anything, just bake it as is

The old way of making these cakes led to issues with Cheesecake spawning meatballs due to the meatball protein mix, and also being strange that you had to make a plain cake first and then add to it which doesn't feel too good when cooking purely through Hexcooking.

**Pull request merged**
