### PR TITLE
Blackshield HARD Nerf!!!! (Prospector gang rise up kill em' all 1984)

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
Prospectors won the last Colony Games. Their reward still hasn't even been decided so I'm moving the trophy pre-emptively instead of waiting longer.

## Changelog
:cl:
balances: NERFS BALACKSHIELD!!!! (prospectors beat you in the event, it's theirs now)
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
i know this change is very controversial............

**Comment by Trilbyspaceclone** [comment]
Has this been approved by Lich and pinkest?

**Comment by cdb-is-not-good** [comment]
Yea this is fine. The reward they were going to get if you feel like taking a crack at it was basically a jaws of life like tool that would be used for ripping open lockers. I started on it then got busy w/ work :')

**Comment by ThePainkiller** [comment]
The thing I'm salty about is that I was fucking editing the omni map already on a previous PR.

**Comment by Trilbyspaceclone** [comment]
Bits over

**Comment by Stutternov** [comment]
> The thing I'm salty about is that I was fucking editing the omni map already on a previous PR.

It won't conflict unless you are editing the same area as me. Not even the same map file itself. If it conflicts, I can literally just merge it.

Blame the event runners for not doing this themselves.

**Comment by cdb-is-not-good** [comment]
> The thing I'm salty about is that I was fucking editing the omni map already on a previous PR.

ur PR is STILL NOT READY FUCKER

**Pull request merged**
