### PR TITLE
Makes volume not increase text size.

### PR DESCRIPTION
**Pull request by LiteralMushroom**
## About The Pull Request
genuinely can't believe I didn't think of just doing this sooner
you can now say things with ACTUAL EMOTION and not have people interpret it as yelling

objectively better than the previous PR

## Changelog
:cl:

### CODE REVIEW

**Comment by Dimasw99** [comment]
You could just move it to !! instead of straight up kneecaping the whole feature. You can take an example of `var/ending = copytext(message, length(message))` and after the first ! true if statement do a second copytext proc but instead with `var/ending_loud = copytext(message, length(message)-1)`. Though I am unsure if it will runtime if you just write "!" or the proc itself is smart enough to avoid that.

**Comment by elgeonmb** [comment]
removing this might have the fun knock-on effect of allowing you to actually change your UI's text size without that change failing to work on all dialogue

**Comment by LiteralMushroom** [comment]
> You could just move it to !! instead of straight up kneecaping the whole feature. You can take an example of `var/ending = copytext(message, length(message))` and after the first ! true if statement do a second copytext proc but instead with `var/ending_loud = copytext(message, length(message)-1)`. Though I am unsure if it will runtime if you just write "!" or the proc itself is smart enough to avoid that.
> 
> You can find more documentation about the copytext proc in Dream maker

please understand that I have no knowledge of how to untangle SS13 spaghetti

**Comment by Dimasw99** [comment]
> please understand that I have no knowledge of how to untangle SS13 spaghetti

That is alright. You can use Visual Studio Code for very quick searching of keywords and trying to track what everything does. Writing just proc/copytext will either reveal to you of how it works or like in this case show you no results which means it is a proc made by byond itself which you can look up on its official documentation

**Comment by cdb-is-not-good** [comment]
Stance remains the same, essentially as Elgeon says + Gutting a feature that does have a use without adequate replacement is meh.

**Comment by LiteralMushroom** [comment]
> > please understand that I have no knowledge of how to untangle SS13 spaghetti
> 
> That is alright. You can use Visual Studio Code for very quick searching of keywords and trying to track what everything does. Writing just proc/copytext will either reveal to you of how it works or like in this case show you no results which means it is a proc made by byond itself which you can look up on its official documentation

I still have to find all the files though???? The fact that a feature is often controlled by a bunch of different files in different places is my main problem here.

**Comment by cdb-is-not-good** [comment]
> > Stance remains the same, essentially as Elgeon says + Gutting a feature that does have a use without adequate replacement is meh.
> 
> it's either this or I try to find some convoluted way to make it so you can make text big in a different way
> 
> also, I specifically commented out the volume stuff instead of outright deleting it because this is just a band-aid fix that still lets someone who actually knows how to code repurpose the volume code to make something **else** make text big
> 
> ALSO ALSO, all this changes is that volume no longer affects text size. It still does whatever else volume does.

Or. Alternatively. Just don't mess with it.

**Comment by TheSleepyCatmom** [comment]
> Or. Alternatively. Just don't mess with it.

Agreed.

**Comment by LiteralMushroom** [comment]
> > > Stance remains the same, essentially as Elgeon says + Gutting a feature that does have a use without adequate replacement is meh.
> > 
> > 
> > it's either this or I try to find some convoluted way to make it so you can make text big in a different way
> > also, I specifically commented out the volume stuff instead of outright deleting it because this is just a band-aid fix that still lets someone who actually knows how to code repurpose the volume code to make something **else** make text big
> > ALSO ALSO, all this changes is that volume no longer affects text size. It still does whatever else volume does.
> 
> Or. Alternatively. Just don't mess with it.

I will literally try to get the "haha text go big when exclamation point" thing removed for all eternity, I need the ability to SAY THINGS WITH EMOTION without FLOODING THE CHAT LOG.
**AAAAAAAAAAAAAAAAAAAAAAAAAAA**

**Comment by LiteralMushroom** [comment]
> You could just move it to !! instead of straight up kneecaping the whole feature. You can take an example of `var/ending = copytext(message, length(message))` and after the first ! true if statement do a second copytext proc but instead with `var/ending_loud = copytext(message, length(message)-1)`. Though I am unsure if it will runtime if you just write "!" or the proc itself is smart enough to avoid that.
> 
> You can find more documentation about the copytext proc in Dream maker

```
	if(ending == "!")
		var/ending_loud = copytext(message, length(message)-1)
		if(ending_loud == "!")
			volume ++
```
tried this in localhost, it does Not work because I am dumb

**Comment by LiteralMushroom** [comment]
> > > > > Stance remains the same, essentially as Elgeon says + Gutting a feature that does have a use without adequate replacement is meh.
> > > > 
> > > > 
> > > > it's either this or I try to find some convoluted way to make it so you can make text big in a different way
> > > > also, I specifically commented out the volume stuff instead of outright deleting it because this is just a band-aid fix that still lets someone who actually knows how to code repurpose the volume code to make something **else** make text big
> > > > ALSO ALSO, all this changes is that volume no longer affects text size. It still does whatever else volume does.
> > > 
> > > 
> > > Or. Alternatively. Just don't mess with it.
> > 
> > 
> > I will literally try to get the "haha text go big when exclamation point" thing removed for all eternity, I need the ability to SAY THINGS WITH EMOTION without FLOODING THE CHAT LOG. **AAAAAAAAAAAAAAAAAAAAAAAAAAA**
> 
> The entire reason it does this, from baycode to eriscode, to now sojourncode was the fact larger text = eye catching.
> 
> All this does is make it harder to follow the flow of fast-moving conversations, and the fact is; people may end up missing statements they should have otherwise seen.
> 
> E.g Four blackshield yelling different things over a currently occupied radio/area.
> 
> "GET ON THE GROUND" versus **"GET ON THE GROUND"**, or similar.
> 
> Can be applied to marshals too but its w/e

Consider: Ending a sentence with a period makes it sound soulless and I like not having to make a choice between that and having people tell me to "stop yelling" over comms.

**Comment by LiteralMushroom** [comment]
> You can mitigate this by adding an invisible itallics/bold to the end of your sentences, or on the ! itself, which should entirely prevent the issue.

pretty sure bolding something makes the automatic period thing happen????

**Comment by ThePainkiller** [comment]
> I will literally try to get the "haha text go big when exclamation point" thing removed for all eternity, I need the ability to SAY THINGS WITH EMOTION without FLOODING THE CHAT LOG. **AAAAAAAAAAAAAAAAAAAAAAAAAAA**

**First**, gutting Eris-downstreamed features because "I don't like this and I want it to be like how I want it it be" is never a valid reason, specially when you're given fair criticism by players and coders alike that it's a bad idea. It's also a very much needed feature during chaotic events with tons of players talking at the same time, coupled with prompts from mobs that now print alerts when they're targetting/shooting you, and some other printed messages (tact reload, throwing mags, buckling people to roller beds, etc) flooding chat to the point you need a distinction **beyond** merely bolding your sentences. That's why the big text is needed and why it exists, it's used to **call attention** to the rest of the people, for a good reason.

**Secondly.** Like Yaweth said, just type a fucking period after your final exclamation mark and the text won't bet big, or bold at least your last exclamation point (since bolding automatically adds a period). It's that easy. It does not matter if it's "soulless", what you wanted it was to not flood the chat and it that way, you don't. No need to even make a PR **commenting out** a feature entirely for the rest of the playerbase because you want to exclaim without yelling. Just use a workaround in game with what the code already allows you to. Like using /me's to `profusely exclaims, "I want to yell without big text!"` if freedom of expression through roleplay is what you care about.

**Thirdly**, if you do not truly understand a particular aspect of code, **please do not touch said code**. Or at least consult either dreammaker docs or other coders on Discord for guidance so you may better understand it beyond merely commenting something out praying that it works and doesn't break everything. Specially with _say_ code, since it's pretty convoluted and it handles a lot of operations, including emoting and the entirety of how comms handle messages through the radio. Having a lot of cross references across multiple files is innate to most "spaghetti" code you'll find across even the most well maintained ss13 servers and is not an excuse to just push a _"bandaid fix"_ that is **not** a fix at all, but rather the removal of a feature you disagree with. It's hard to take it seriously if you try to push it in this way, and very unlikely it'll be well received as well.

**Comment by LiteralMushroom** [comment]
> just type a fucking period after your final exclamation mark and the text won't bet big, or bold at least your last exclamation point (since bolding automatically adds a period)

I would do this if the PERIOD WASN'T **VISIBLE.** Having a second dot after the one at the bottom of the exclamation point looks weird.

**Comment by LiteralMushroom** [comment]
look this is literally just a salt PR I made in response to getting told something along the lines of "stop yelling" over comms

**Comment by Trilbyspaceclone** [comment]
If you can get a version that works then I see no reason unless hex or CDB can provide one to not merge it.

**Comment by LiteralMushroom** [comment]
> If you can get a version that works then I see no reason unless hex or CDB can provide one to not merge it.

this works BUT people are angry at it and will just revert it immediately instead of
making the big text a choice instead of "it always goes big" or "it never goes big"
which I have no idea how to do myself

**Comment by nikothedude** [comment]
don't blame other people for not doing something you don't know how to do yourself

**Pull request closed without merging**
