### PR TITLE
Hivemind - per emojiocracy vote.

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Reduces total 'combat related' players required to spawn either blob or Hivemind.

Hiveminds now require 7 players.
Blob now requires 4 players.

See below for the list of jobs that count for this requirement. Why does Premier count??

``#define JOBS_ANTI_HIVEMIND "Blackshield Commander","Warrant Officer","Supply Specialist","Ranger","Corpsman","Blackshield Trooper","Marshal Officer","Sergeant","Prime","Vector","Foreman","Salvager","Prospector","Premier","Steward","AI","Janitor","Soteria Lifeline Technician","Soteria Roboticist","Lonestar Miner" ``

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by ChefDoggo** [comment]
>AI

**Comment by DustanHache** [comment]
just like questioning why premier is on that list, why is *janitor* there too? they’re not exactly the types to be involved in major threats like this unless another faction seriously bolsters their kit.

**Comment by cdb-is-not-good** [comment]
Janitor does however have blob resistant armor and tend to be armed.

**Comment by DustanHache** [comment]
> Janitor does however have blob resistant armor and tend to be armed.

i would agree, except my boots keep getting melted off while fighting the blob. its coverage is not full in spite of having maximum bio resistance, and they lack appropriate weaponry for fighting the blob unless they burn all their kudzu grenades. this is exacerbated by the fact they also count towards hivemind triggers, which janitors have next to nothing appropriate for dealing with.

**Comment by cdb-is-not-good** [comment]
Seems to be fine, havent heard any complaints.

**Pull request merged**
