### PR TITLE
True and Factual

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Disables outsider slots, admins can still open new ones but prevents them from spawning naturally and draining already low pop from the colony.
	
<hr>
</details>

## Changelog
:cl:
del: Outsider slots
/:cl:

### CODE REVIEW

**Comment by BurpleBineapple** [comment]
https://github.com/user-attachments/assets/350337fa-0b59-49bf-a4dc-967392865884

**Comment by Lamasmaster** [comment]
https://github.com/user-attachments/assets/338d6426-2ade-4481-a555-ba84d92d1aad

**Comment by Trilbyspaceclone** [comment]
Is this a joke pr?

**Comment by Lamasmaster** [comment]
No, I am serious

**Comment by Ryan180602** [comment]
inshallah

**Comment by Lamasmaster** [comment]
> inshallah


https://github.com/user-attachments/assets/57239385-7eef-4a6a-ba0f-c67246317b2e

**Comment by ChefDoggo** [comment]
blackbeard-blackbeard-writing

**Comment by AMcilraith** [comment]
https://media.discordapp.net/attachments/859890910027841618/1310083842710704268/huh.mp4?ex=6743ee28&is=67429ca8&hm=e9fdc8a0c2e4f6f5f89335a72b0c1afbbf9417bf5176a074f147e65e5e8433af&

**Comment by AMcilraith** [comment]
https://github.com/user-attachments/assets/eed0f538-eab1-43c2-b5df-240331c35aeb

**Comment by AMcilraith** [comment]
this is single-handedly the greatest (and funniest) Pr in sojourn history.

+1 for the funny

**Comment by AMcilraith** [comment]
however, on a more serious note.

it might be better to make slots open up once a threshold of colonists are reached
say an outsider slot only opens when 6-8+ colonists are on the manifest actively

that way it incentivises players to join.

this could also apply to readies, and the slots would close when colonists leave
like how bay/hestia handled offship - it could be linked to a deuteragonist antag role

**Comment by Smokingsquirrel** [comment]
Opening up outsiders only when certain slots are filled is good

**Comment by Stutternov** [comment]
Correcting histories wrongs, one PR at a time.....

**Comment by Smokingsquirrel** [comment]
In addition: instead of simply deleting the job, make it so it opens up when there’s like 5 colonists or somethign

**Comment by Trilbyspaceclone** [comment]
Outsider slots should be added based on a new system if set to 0 rather then admins opening slots

**Pull request closed without merging**
