### PR TITLE
Fruit volume fix

### PR DESCRIPTION
**Pull request by Dimasw99**
## About The Pull Request
Fruits now adpativly change their maximum volume depending on how much they produce.
Fix a flossisine pathing.

### CODE REVIEW

**Comment by DustanHache** [comment]
Okay, so, as someone who **REALLY** wants this change... No. just no. Not the way you are doing it. Why? Because all other fruits will scale 2x harder, especially basic ones like sun tear, vale bush, mercy's hand, ambrosia, and god forbid /wheat/. Adaptive max volume is good on paper, but hell in practice. a single harvest after they are finally brought up to speed will be capable of putting medical out of business instantaneously even before factoring in how robust harvest and the like act upon harvest quantity.

**Comment by DustanHache** [comment]
> > Okay, so, as someone who **REALLY** wants this change... No. just no. Not the way you are doing it. Why? Because all other fruits will scale 2x harder, especially basic ones like sun tear, vale bush, mercy's hand, ambrosia, and god forbid /wheat/. Adaptive max volume is good on paper, but hell in practice. a single harvest after they are finally brought up to speed will be capable of putting medical out of business instantaneously even before factoring in how robust harvest and the like act upon harvest quantity.
> 
> Sun tear, vale bush, mercy's hand and so on are not affected by this since their math goes like this: Wheat has the following stats, chems = list("nutriment" = list(1,25), "flour" = list(15,15)) The first number in the list is the the garentuee, the second is a division of the current potency. Even with 100 potency you would get 1 + 4 nutrients and 15 + 100/15 = 6.6 Flour and as a total it would 26.6 units of reagents total. Now lets look at Mercy's hand, chems = list("bicaridine" = list(1,10), "anti_toxin" = list(1,10)) 1 + 10 bicaridine and 1 + 10 dylovene, total 22.
> 
> In both cases it is below 50 units which is the current max limit that is definied not in the plants tree but rather two trees up the parrent up in snacks, that being just 50 units. What this PR fixes are the niche cases where Panacea produces more than 50 units, a plant that is science exclusive since it requires machinery and a florasoma ray. To say that everything will scale x2 harder is a blatant lie and if you are worried about the number balance then look at seed_datums.dm but not through a hack job that is the maximum volume limitations. Again, maximum volume is how much a container can have and not will have.

this is distinctly false if you look at vale bush at maximum potency currently. It produces so much dexalin and paracetemol that it’s nutrient content is removed, which would produce a minimum of 70 medical regents and 20 nutrients according to the math given. you are essentially doubling it’s effectiveness in producing medicine AND returning its lost nutrient value (which is not to be understated, since nutrients help when it comes to bloodloss and cryo.
a bunch of the plants scale similarly aggressively, and you would have to go through and check ALL of them to make sure there are no outliers in production. Also, lets not forget that you can literally copy production genes from plant to plant, which will invariably make those “low production” plants absurdly strong regardless.

**Comment by Dimasw99** [comment]
> this is distinctly false if you look at vale bush at maximum potency currently. It produces so much dexalin and paracetemol that it’s nutrient content is removed, which would produce a minimum of 70 medical regents and 20 nutrients according to the math given. you are essentially adding another half a fruit it’s effectiveness in producing medicine AND returning its lost nutrient value (which is not to be understated, since nutrients help when it comes to bloodloss and cryo. a bunch of the plants scale similarly aggressively, and you would have to go through and check ALL of them to make sure there are no outliers in to production. Also, lets not forget that you can literally copy production genes from plant to plant, which will invariably make those “low production” plants absurdly strong regardless.

Yeah I see the issue with Vale bush now having the following stats:
chems = list("paracetamol" = list(1,5),"dexalin" = list(1,2),"nutriment"= list(1,5))
1 + 20 paracetamol, 1 + 50 dexalin and 1 + 20 nutriment, total of 93 units.
Again, the math is the first number in the list is a garentueed amount. The second number is (Potency/divisor) for the amount. You can easily change the 2 to a 5 and reduce the production amount from 51 units to 21. 

But again, this is not an issue you solve by having a random max volume cap two tress up. If you think Vale is unbalanced, go and make a PR in seed_datums.dm. You can easilly adjust those numbers yourself. Same thing with the biochemistry stacking being a seperate issue and needs its own solution, not a spagheti code solution.

**Comment by Trilbyspaceclone** [comment]
Max volume growing with size is something that i do want.

**Pull request merged**
