### PR TITLE
UI's that you desire

### PR DESCRIPTION
**Pull request by Moltovz**
## About The Pull Request
This PR does a lot, but I was told I didn't need to atomize this PR into smaller PR so here goes:
Brings all of the funny TGUI stuff over from Eris, this includes the stats and perks screen, ore box UI, and a modified version of the disposals unit and sanity UI.

This PR also brings back the old desires system, where foods and drinks have "Taste tags", instead of your character suddenly having a pregnancy craving after you kill enough stuff.

**DO NOT MERGE UNTIL ALL OF THESE BUGS ARE FIXED:**

- [X] Fix the ore box UI thinking a stack of ore is a single item (This is probably an "us" issue because our ores stack and Eris's doesnt)
- [x] Fix some vendors printing their entire DMI file in place of some items (IDK)
- [x] Fix Perks only showing the "vagabond" Icon
- [x] Fix the ore box listing multiple stacks independently.  See below
<details>
<summary>The Silly In Question</summary>

image

</details>
**FOR CBD**

- [x] Add taste_tags to everything so I can make sure taste tags work... lol.
<br>
<br>
<details>
<summary>Sanity+Skill UI</summary>

image

image

Hovering over them provides a description.

image

</details>
<br>
<details>
<summary>Vendor UI</summary>

image

</details>
<br>
<details>
<summary>disposals UI</summary>

image

</details>
<br>
<details>
<summary>Ore Box</summary>

image

</details>

## CREDITS:
Props to the crew who worked on this over at Eris for me to steal later. @hyperioo @intercepti0n , you guys are wild :)

## Changelog
:cl:
add: UI's for a bunch of stuff.
tweak: Desires now follow the old desires system. Foods and drinks will have a taste associated with them
:cl:

### CODE REVIEW

**Comment by benj8560** [comment]
I assume this fixes issue #4727 ?

**Comment by benj8560** [comment]
all disposal units seem to be defaulting to off now. I assume due to this.

**Comment by Trilbyspaceclone** [comment]
admin ghosts cant intract with things that are this new tgui

**Comment by cdb-is-not-good** [comment]
> admin ghosts cant intract with things that are this new tgui

What? I haven't had this issue.

**Comment by benj8560** [comment]
I dont think that admins can interact with things as a ghost with are older TGUI stuff as well.

**Comment by cdb-is-not-good** [comment]
> I dont think that admins can interact with things as a ghost with are older TGUI stuff as well.

I just tested, at least with the new UI I am able to go to say...a seed vendor, and make it dispense a seed as a ghost.

**Comment by cdb-is-not-good** [comment]
removin g the DNM tag as it's a bit null given that this is already TM'd and I need some like....further info to consider unmerging it.

**Comment by cdb-is-not-good** [comment]
image
image
Rolling back the testmerge from the server to a point before obscuration was re-implimented.

**Comment by benj8560** [comment]
YSOzBHSbw1

OMG venders are just totally screwed rn

**Comment by cdb-is-not-good** [comment]
I believe the above post was made when I accidentally updated the server to the latest problematic build of your PR.

**Pull request merged**
