### PR TITLE
New church maping

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Massively reworks the church map to be better trade mark
Moves the church/guild """recycler""" (aka the thing that eats every item ever and gives nothing but refined scrap) into the guilds atmos storage
Removes 1 doble stacked trash cart in scavs
turns the old recycler room that into a table/shelf/trashcart storge room
Fixes the missing landing zone in the river forest
Added more sofa's

Testing: Tested every wire line that I remember to, ever pipe I remember to and the new stairs to make sure it all works
Performance: less wall oblistics but not sure if its good or bad in net

### CODE REVIEW

**Comment by Stutternov** [comment]
image

**Comment by Medizeal22** [comment]
Make sure we consult some churchies with this stuff since this is some radical changing to the overall dynamics to the department, especially with how the Prime's office is moved plus the bio room.

Otherwise, I have no issue with it personally save for the landing pad being a tad awkward but I don't know how to personally fix that at this time.

**Comment by Trilbyspaceclone** [comment]
Endorced player names Eonoc/Alistair Sturnholde, Calyst Morfrom/Insane Factorial, Luxyleatherhat

**Comment by Eonoc** [comment]
Yeah, Trilby consulted with Churchies in our discord channel extensively. Think a good chunk of the active Church players saw and approved.

**Pull request merged**
