### PR TITLE
Creating ERT Ready Room

### PR DESCRIPTION
**Pull request by Pawoverlord**
## About The Pull Request
<details>
This creates and adds an ERT Ready Room.
<summary>
	This creates and adds an ERT Ready Room that will allow admins and mods to access and prepare ERT characters quicker and without needing the ADMIN+ or SPAWN+ perms. This is exclusively for the times that we do need and use ERT when applicable. 
</summary>
<hr>

The room, seen below comes with the capacity of five units. Three Marshal Units and two Corpsman Units. Images of the loadout are provided with this. For ammo, they are given an ammo printer with six stacks of refined scrap which should be more than enough scrap for any of the loadouts. They come with WO headsets, Marshal IDs, and ammo pouches for each type of weapon. 

There's four boxes of gun parts for all the attachments for any of the guns, ten medium super cells, ten small super cells for the respective guns. Three medium and three small atom cells. 

image

image

image

The gun choices for the ERT team is designed with the idea of low-tier threats towards high-tier threats, left to right accordingly. Grenades are also provided as a tactical resource. Though, I excluded adding anything like RPGs as I felt that ERT should not need to resort to RPGS, as they would just be Death Squad. I additionally included a sectech for any security items such as handcuffs, maglights, or flashes. 

image

image

image

image

	
<hr>
</details>

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Very good, though I'd suggest a few additions. Marshal/Shield wardrobes and loadout vendors- toss in a locker with a variety of armor/weapon vouchers so as to allow the standard selection of marshal/shield weaponry/armor in addition to the more advanced kit that you've arrayed here.

**Comment by cdb-is-not-good** [comment]
Gonna testmerge this for now(mostly because n0 reason not to even if it's in production)- be sure to document each commit since they'll ultimately get pushed to the server when we update with it still testmerged.

**Comment by Pawoverlord** [comment]
Gonna leave images here for the updates to the Ready Room. 


<body> 
    <details> 
        <summary>Photo Update</summary> 
        
image
image
image
image


</body> 
</html>

**Comment by Pawoverlord** [comment]
Sorry to spam that. . . 

image

Photo update for the floor so it wasn't about to be a MASSIVE FREAKING EYESORE. I wasn't aware that the Centcom tiles actually made patterns until JUST NOW. That would have been AWFUL for EVERYONE. 😭 😭 😭

**Comment by cdb-is-not-good** [comment]
👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍👍

**Comment by Pawoverlord** [comment]
image

image


Changes have been made. (I also am using this moment to finalize my flooring patterns for the room, which I think will look decent enough.

**Comment by cdb-is-not-good** [comment]
👍

**Pull request merged**
