### PR TITLE
Literally 1984

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Slight map adjustment! Evidence storage has been moved to the top right corner of the 'investigation block' in the central Marshals, in its place is the E.Y.E Pods storage room, locked to Ranger access(All Marshals will have access thusly.)
To use it, simply put on the provided equipment in the room, turn on the provided internals and climb in before clicking the pod.
It functions similarly to the AIs eye, allowing you to pan through the camera network in a highly efficient fashion. Credit goes to @KIROV#6255 for the actual code of the thing! 
image

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
incredibly based, time to main marshals

**Comment by ThePainkiller** [comment]
Jesus fucking christ this is the most dystopic thing I've ever seen coded on SS13, the title fits like a glove :joy:

**Comment by cdb-is-not-good** [comment]
> Jesus fucking christ this is the most dystopic thing I've ever seen coded on SS13, the title fits like a glove 😂

To be fair, we already have full camera access at all times. The camera console program works on the tablet, so most Marshals ALWAYS have access to cameras .

**Comment by AysheDaArtist** [comment]
Hell yea, this is one heavy metal solution to our defunct camera system.
**Cyberpunk intensifies**

**Comment by cdb-is-not-good** [comment]
>map merge conflicts
fuck you.

**Pull request closed without merging**
