### PR TITLE
The Soteria™ Psychological Treatment Centre (AKA The "Looney Room")

### PR DESCRIPTION
**Pull request by GlitchySoftware**
image

## About The Pull Request
<details>
<summary>
	Adds a psych ward on downstairs soteria level, near the morgue. The morgue itself was moved a little bit to the side. Now you can throw in people into the room and forget about them. Will add padded walls eventually once its possible.
</summary>
<hr>

	
<hr>
</details>

## Changelog
<cl>

</cl>

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
looks like it needs the cryo terminal storage consoles in that one room.
Or for that cryo room to be removed...

**Comment by cdb-is-not-good** [comment]
as trilby says, yep.

**Comment by GlitchySoftware** [comment]
image

**Comment by GlitchySoftware** [comment]
@Trilbyspaceclone removed the pod room since it felt out of place and put down a janitorial closet there instead, heard people wanted stuff to clean med too

**Comment by Trilbyspaceclone** [comment]
image
Why is the fire b gone area like that? Second fire b gone locker needs a decal ahead of it
and the light is off centered?

**Comment by GlitchySoftware** [comment]
> image Why is the fire b gone area like that? Second fire b gone locker needs a decal ahead of it and the light is off centered? Also the layered camera with a large light is a bit messy looking

okay so that fire extinguisher is in fact the one in morgue, its just a 1 layer wall so they look like they're in the same room, gonna fix the off-centered light and move the table to add a decal for the extinguishers

**Comment by GlitchySoftware** [comment]
image
@Trilbyspaceclone

**Comment by Trilbyspaceclone** [comment]
This pr was commpressed into #5440

**Pull request closed without merging**
