### PR TITLE
The most unpopular pr in all time

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Massively increases time and differentially on surgery
Makes ADVDANCED trauma and burn kits perk locked, but church and hunters are not to increase trade
Removes all advanced kits spawns other then surgery kits as those need it for surgery
Needles now need a 15bio or 30 cog to use, and of course medical perks bypass
Makes robotic surgery not as hard as normal surgery
You can now refill hypoinjectors, only with a needle tho

### CODE REVIEW

**Comment by hex37** [comment]
Slow down there satan.

**Comment by r4d6** [comment]
I don't mind the rest, but I think that the brute & burn kit being *obligatory* perk-locked is too much. Especially since there is no skill bypass.
But even if there was I would still say that it's too much.

**Comment by ThePainkiller** [comment]
Locking ATK use behind perk with no BIO bypass? Syringes using COG for some reason??? Increased surgery time why????
Lilly what are you even thinking? What compelled you to do this?

**Comment by Trilbyspaceclone** [comment]
> Locking ATK use behind perk with no BIO bypass? Syringes using COG for some reason??? Increased surgery time why???? Lilly what are you even thinking? What compelled you to do this?

These are lighter changes then what were discussed and planned.

**Comment by ThePainkiller** [comment]
> Possum wanted to make surgery need a perk to even do
I've been suggesting this for almost a year and you know it. It would make sense so that medical job is justified but only if NOT outright locking entirely things like shrapnel extraction which I see is now possible to attempt without even having the proper BIO for diagnosis, and even as a doctor with high BIO (due to background) I tried using that option and it failed more than it worked so you might wanna get that code tidbit checked.

> and have it so hunters kits worked with the perk maste burtcher
This is half bad half good. Hunters kits are good, but locking their use by virtue of a perk is horrible practice and bad faith plus limits the ammount of goods they can barter for with others. Who's gonna trade for an ATK that no one but hunters can use? *Why make an item which was previously universally available limited in use to one job only?* This question goes more for ATK's than hunter's tongues and stuff.

> Ontop of that this still keeps the Ru's globs useable by all
Cht'mant players are as rare as hunters nowadays, even moreso the Ru kind save for like two or three staple characters, still a highly conditional option.

> The cog check on the needle is a bypass if you dont have perks/bio needed
I see you're still trying to justify reasons for leveling COG but it doesn't make mechanical sense whatsoever that because you know how to use a computer you know how to use a syringe. The BIO is sensitive enough at 15 (I'd still lower it at 10), but using COG as a "bypass" stat makes no sense.

> Surgery time was increased as well at the request of medical mains
Speaking as a medical main across many years and three different medical codebases, no medical main worth their salt would ever ask for **SLOWER SURGICAL PROCEDURES** (extra surgical steps or tools are a different matter entirely though) when surgery is a literal lifesaving procedure in which **_speed is of the essence_**, hence the existance of **ADVANCED SURGICAL TOOLS** to cut on the speed or even circumvent the clamp bleeders step (laser scalpel, incision management system in bay comes to mind as well) because your patient would **DIE** if unattended. Surgery is no mere autopsy to fix organs and defib someone, it must be done precisely to **AVOID** death (**SPECIALLY HERE WHERE YOU PERMANENTLY LOSE STATS UPON DEATH AND GET CRIPPLING DEBUFFS UPON REVIVAL**), which is quite literally the core of medicine itself. I call utter bullshit on this _"medical mains asked for it"_ justification, this sounds like overly complicating simple enough procedures for the sake of making things take more time on no particular beneficial returns, which is **horrible** practice when it comes to game balance.

**Pull request closed without merging**
