### PR TITLE
knight -> hussar

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Reskins the knight rig to hussar, sprites by both Gundam Tanaka#9565 and Polyushko#0323

### CODE REVIEW

**Comment by Dongels** [comment]
My only recommendation: Slow the interval between each full cycle of the animation. it's way too distracting and fast.

**Comment by cdb-is-not-good** [comment]
Semi agree, but seeing a full size .gif or such would probably help to get an idea. I've no objections with the change though i do ask 'why'? I suspect some people will miss the old one if we change

**Comment by Trilbyspaceclone** [comment]
Better sprite is better
BOS armor looks goofy

**Comment by Polyushko1** [comment]
Answering prior questions.
First, the older armor was essentially the knight_cydonia.dmi from /tg/ modified with some Church of Absolutism symbols. Second, as far I know, keeping Sojourn sprite-style as close as possible of Eris standards (even if you guys are way more relaxed on this aspect) is important. The older knight sprite looked absurdly off compared to everything else, without proper highlights, palletes - anything. 
About the animation, yes. It is necessary to be fast - it's lightening and smoke of burning incense afterall - unless you guys wants to make it faster. Tried it myself and it looked off.
Still, my intention on making this sprite was exactly to be an gift for the server because I made that armor for a medieval server that I'm working on, yet it looked more close to an power armor rather than a actual 14th century medieval armor. So yeah, it'd make more sense here than there.

**Comment by cdb-is-not-good** [comment]
I can dig it.

**Pull request merged**
