### PR TITLE
Turns dusters into accessories

### PR DESCRIPTION
**Pull request by faaaay**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Makes dusters (specifically, the non-armoured ones in the loadout) into accessories that can be worn in the suit slot. Now you can have drip _and_ protection by draping a coat over your armour! 

_Why is this good for the game?_
It allows a greater degree of cosmetic customisation.
	
<hr>
</details>

## Changelog
:cl:
tweak: Dusters can now be attached to armour as an accessory.
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
All these items you're turning into accesories are storage (have pockets) items. This is a heavy nerf for their use, so at least reduce their price on the vending machine.

**Comment by faaaay** [comment]
> All these items you're turning into accesories are storage (have pockets) items. This is a heavy nerf for their use, so at least reduce their price on the vending machine.

Fair enough, I can do that. Think 40 is fair?

**Comment by ThePainkiller** [comment]
> Fair enough, I can do that. Think 40 is fair?

For attachable accesories, yeah that's fair

**Comment by cdb-is-not-good** [comment]
suuuure

**Pull request merged**
