### PR TITLE
Tweak/setup solars at round start

### PR DESCRIPTION
**Pull request by Hydroxyapatite**
## About The Pull Request
THIS PR IS A PROPOSAL. Please discuss before merging.

* Connects the wires to the solar panels and starts their auto-tracking at the beginning of the round.
The intent behind this change is to make restarting less painful for our low pop. Because power is such an issue without consistent Guild players, restarting is often avoided due to power being problematic at round starts. 

I believe that this change does not take much away from the Guild, as: 1) Not having power at the start of rounds has not made people play Guild more often, and 2) Managing RCON, snipping wire splices on the array, and opening the hydroelectric dam are more involved and/or repeatable jobs for the Guild to handle. 

As such, I believe that not having any solar power set up at the beginning of the round is causing a bigger problem than it solves at the moment.
	
<hr>

## Changelog
:cl:
tweak: Solars are now set up at the beginning of a round.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I disogree with the removal of round start requirements, it already takes 16 people to be counted as "Normal" crew. Making it so we dont need an engi or command with theirs 16 people is kinda silly. Imo we should also enforce some in Sec at the 16 mark

**Comment by Hydroxyapatite** [comment]
> 
> 
> I disogree with the removal of round start requirements, it already takes 16 people to be counted as "Normal" crew. Making it so we dont need an engi or command with theirs 16 people is kinda silly. Imo we should also enforce some in Sec at the 16 mark

I mostly did this because I've seen rounds get stuck at the start because of nobody playing Guild even with 16 players on. I also suspect that this count includes players who don't intend to play.

**Comment by Trilbyspaceclone** [comment]
It as well as events that story tells role/story teller points looks at server pop not ready pop

**Comment by Hydroxyapatite** [comment]
Well, I'll drop it for now. We can see how it plays out when we see rounds with enough people.

**Comment by Kazkin** [comment]
We'll bookmark this but for now it can remain how it is.

**Pull request closed without merging**
