### PR TITLE
Oddity double barrel now holds two shells instead of a single one

### PR DESCRIPTION
**Pull request by Chevalt**
This double barrel shotgun, that could fire two shells at once, had only a capacity of a single shell. Wtf? Anyway, this change is so that this gun makes sense at all.

### CODE REVIEW

**Comment by benj8560** [comment]
I believe it fires two shells out of one? That's what I was always told it's what makes it a bluecross

**Comment by benj8560** [comment]
ye short look believe this is it. It should fire two rounds on it's other firemode even if it only has a single shell loaded.

 list(mode_name="August Presence", mode_desc="Fires two of the king's decrees at the same time.", burst=2, icon="semi")

**Comment by Trilbyspaceclone** [comment]
its based off a game ref, not intended for 2 shells at start

**Comment by cdb-is-not-good** [comment]
In light of that I'd say 'no' to this PR, no need to fuss with it.

**Comment by cdb-is-not-good** [comment]
> just did some toying around with this weapon...gotta agree its pretty meh. I think for buffing it? Give it auto eject and reduce the recoil abit. At the moment the duel fire is pretty much useless even heavily modded

I'm not averse to buffing it. That said, it's a bluecross gimmick gun and is meant to be a gimmick that references a game - rather than strictly a 'great gun'. This has sat open for long enough so for now we'll say 'nah'.

**Pull request closed without merging**
