### PR TITLE
CMO Rigsuit

### PR DESCRIPTION
**Pull request by AysheDaArtist**
## About The Pull Request
<details>
<summary>
	Gives the CMO their own designed rigsuit to replace the Hacker Suit
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Add: CMO Rigsuit sprites
Change: CMO rigsuit replaced from Hacker Rigsuit to CMO Rigsuit; Hacker Rigsuit still in code and usable
:cl:

### CODE REVIEW

**Comment by AysheDaArtist** [comment]
OPERATE

**Comment by Trilbyspaceclone** [comment]
Some icons seem to have been deleted
is this intented?

**Comment by AysheDaArtist** [comment]
No icons should be deleted

I've added in a cmo_rig for sprites and attached that to the 'SI Medtek' suit

I don't think any rig icons have been touched for the last few days, but some files under head/feet/suit might have been updated and when I slipped my files back in after a sync

I'm not sure which icons got deleted, but I can redo the PR and manually load in the files... urrrrggrgrghrhghghhh

**Comment by AysheDaArtist** [comment]
pain

**Comment by Trilbyspaceclone** [comment]
I can fix it if you want :~:

**Pull request closed without merging**
