### PR TITLE
Centurio nerf + code cleaning

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Cleans up files for laser guns to refect more so what are gun files are rather then massive files with guns thrown in

Centurio hardstun projectile that is only other found in a church weapon has been replaced with an Ion shot. This might be a buff tbh as ion can be insainly good agianst hivemind, robotic combatives and drainning the cells on mechs/laser guns that others might use. Rather then `ahah i clicked on you with 1 hit hardstun lock gun`

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
This is terrible, you're butchering the only good weapon Science has for self defense in lieu of something useful against an antagonist only seen on events  or mechs, and this is still another indirect buff to church by virtue of being the only ones with the hard stun projectile on their guns
And no, the Zeus sucks ass and it's not a "hard" stun as you'd think since you can still crawl your way out of being handcuffed

**Comment by Trilbyspaceclone** [comment]
Buff church? Buff church.
Also didnt say anything about the Zeus.
Also also, the normal fire mode is still good.

**Comment by CormanQuewye** [comment]
> This is terrible, you're butchering the only good weapon Science has for self defense in lieu of something useful against an antagonist only seen on events or mechs, and this is still another indirect buff to church by virtue of being the only ones with the hard stun projectile on their guns
> And no, the Zeus sucks ass and it's not a "hard" stun as you'd think since you can still crawl your way out of being handcuffed

Ah yes, 'self-defense'. As well all know, non-combatant faction should have access to one of the strongest weapons in the game relative to accessibility. And it's strongest not considering the stun factor.

The .35 is a self-defense weapon. The centurio is a self-charging hand cannon that has a "I'd like my enemy to be incapable of fighting back" option.

**Comment by MSieghardt** [comment]
The centurio does need this nerf, it was far too good of a weapon with a stun like that which would work on mobs too. The ion shot brings it up to a more standard level rather than having it be king.

**Pull request merged**
