### PR TITLE
blunderbuss

### PR DESCRIPTION
**Pull request by lolman360**
dnm

loads trash items for ammo, uses welding fuel as the modern-day blackpowder (it's a low explosive ok)
cheaper than the makeshift shotgun at the price of requiring 2 different ammo sources + lower damage as your ammo goes down

### CODE REVIEW

**Comment by TheSleepyCatmom** [comment]
I'm really not a fan of the aspect that this weapon looks like it literally just came out of a museum of history. We're generally trying to move away from the olden-modern aesthetic for weaponry. :c

**Comment by Dongels** [comment]
DeWalt Tools:tm: look would probably fit for a sprite change

**Comment by Dongels** [comment]
Why is this still open? it's been 3 months with no changes.

**Comment by Trilbyspaceclone** [comment]
Do to inactivity this is being closed, when you get the sprite please do let me know and ill reopen it

**Pull request closed without merging**
