### PR TITLE
Blackshield loadout

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
adds the blackshield cap and blackshield beret to loadout options. This time without breaking something!

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by r4d6** [comment]
Can you try and add the skirt to the loadout too?

**Comment by Kazkin** [comment]
Skirt pl0x :D

**Comment by cdb-is-not-good** [comment]
mdsmfg fine ill also add the shield cadet uniform while i'm at it because it probb should've already been there.

**Comment by Kazkin** [comment]
yaaaaaaaaaay

**Pull request merged**
