### PR TITLE
Creates Hunter Fangs necklace

### PR DESCRIPTION
**Pull request by Memedoktor**
Hunters now can make a Fang tooth necklace with a bit of leather 5 pristine animal fangs. 
This has the benefit of being worth 5 pristine fangs in one item since carrying them is a hassle.
Plus hunter drip to sell to the colony to appeal to wannabe surfer nerds
## Changelog
:cl:
add: Adds the Fang Tooth Necklace, an expensive craftable accessory for hunters, made with three leather sheets and five fangs
/:cl:

### CODE REVIEW

**Review by Trilbyspaceclone — CHANGES_REQUESTED** [review]
Please test making it in a privet server, this looks wrong to me

**Comment by Memedoktor** [comment]
@Trilbyspaceclone 

I'd already tested crafting it, wearing it on both face and accessory, and checked its value on an export scanner

**Review by Memedoktor — COMMENTED** [review]
Double checked again and still worked for me

**Comment by Memedoktor** [comment]
Screenshot_4

**Review by Trilbyspaceclone — APPROVED** [review]
looks good then

**Review by cdb-is-not-good — APPROVED** [review]
Looks good! The only thing that may come up later is if we want to add a trade offer to the beacon, but that can probably wait :p

**Review by hex37 — APPROVED** [review]

**Comment by hex37** [comment]
Looks good to me. Approved.

**Pull request merged**
