### PR TITLE
WotP Revamp

### PR DESCRIPTION
**Pull request by Kazkin**
@Kazkin
[Will of the Protector Revamp](https://github.com/sojourn-13/sojourn-station/pull/2996/commits/89532158bd86cf5da9485e37fe078168bae39cc4)
[8953215](https://github.com/sojourn-13/sojourn-station/pull/2996/commits/89532158bd86cf5da9485e37fe078168bae39cc4)

-Added 20 license point disks to the church vendor that are copies of their utility disks for 400 credits.
-Replaced the limited license disk in the biogenerator room with its formerly infinite disk.
-A massive revamp to the Will of the Protector has been done. It now functions as a combination between a shrine and church merchant machine. It now sells only disks and medkits, allowing disciples to more readily obtain church disks beyond asking the prime.
-Offerings expanded, detailing what each offering requires and what it does. Offerings effect the WotP's global blessing, weighting which one happens when power hits 100.
-Offerings grant 5 armanent points per offering to give a reason to actually do them and what to do with excess biomass.
-Armanent points rebalanced to 100, all items bought balanced in this same scale.
-Removed annoying global message every time the WotP releases its power, instead limiting it to only when a power directly effects you while also explaning how.
-Remove the WotP ability to give materials, finished guns, the nt oddity, and other stuff as it was unbalanced.
-Gave it a slightly customized sprite, more of a place holder really but its an obelisk with a blue cruciform instead of gold.

### CODE REVIEW

**Comment by Dongels** [comment]
I told yah I was making a church variant you heck, I thought this was going to be used for something else...not church. **FROWN**

**Comment by cdb-is-not-good** [comment]
For a suit of armor that is competitive with assault armor, excel armor and specialized variants(bulletproof/riot) the cost of this seems awfully low

**Comment by Kazkin** [comment]
I thought this was the church variant? I'll hold off on merging it for now.

**Comment by r4d6** [comment]
Aren't those almost the same bullet/melee as the crusader armor?

**Comment by Trilbyspaceclone** [comment]
1. Heavy armor only has 0.9 slowdown (space suits have 1+)

2. Fortress is already used in spiders so "Temple" or "Palace" would fit better

3. Merge conflicts

4. These are the same stats for bullet and melee as jugernought suit and can fit 2 upgrades making 80/80. Or placing it in the energy armor to get that upto 40 (Really op)

5. Conflict error

6. The helmet is the one of the best helmet in the game baring crusader armor or admin spawn gear. Its flat out the best armor stats also has 0 downsides to waring, unlike lets say jugernought armor that also has slowdown with it, 0 tradeoff with anything. Also the light is **brighter** then even the guilds Enviro suits. Way to cheap for what can be spam clicked off and on free 60s armors.

**Pull request merged**
