### PR TITLE
Gun Fixes & Misc Stuff

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
<details>
<summary>
	basically all just stuff I got asked to port. TL;DR list here.
	
	- gave Longarm and Osprey a very small 0.2 damage bonus since Ostwind and other guns have it for scoped rifles. They're 'dmrs', so idk why they don't have any.
	- Bat'ko lowered price-cost to make and way more charges due to new damage capacity and changes to armor divisor.
	- abdicator fire delay /slightly/ reduced, as requested by guild player and raptor when he tested it. 
	- also, related to abdicator: upped buckshot projectiles lasting 1 tile longer before pellets fall off. this includes tile stood on, its base was 2 and was changed to 1 for whatever reason. this fixes all buckshot projectiles a tad; needs more touching up but it's a start i guess.
	- Lamas forgor to add a blacklist on the Sunrise to stop expansion ports from fitting on it. added expansion port ro blacklist, but added 1 extra slot for 2 total. (no more 4 slot sunrise, only 2 now. plus got rid of 0.05 pen to standardize, i geuss. add it back if you like but figured would be ok to do due to attachments)
	- reduced commonality of Church oddity spawn on requested, it now spawns less often than a gun thus will spawn more rarely. (they're artifacts anyway.)
	- Odio asked their cool new chem dispenser be added so i added it, it was a cool Freeport sprite i found laying around.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
fixes: Buckshot pellet falloff
tweak: adjusts Sunrise attachment slots
tweak: adjusts abdicator firedelay
tweak: adjusts bat'ko cost to make and cell charge
tweak: church oddity bluecross spawn
add: new dispenser sprite made by Odio
/:cl:

### CODE REVIEW

**Comment by Stutternov** [comment]
example of the dispenser sprite:
https://cdn.discordapp.com/attachments/859890910027841618/1296904842685452388/image.png?ex=6713fc41&is=6712aac1&hm=3550c6dc9204b885441e381c689f10d7440c2962ee4951220d7ce06399f9db7c&

**Comment by Trilbyspaceclone** [comment]
Keep the old sprite, i dont mind the new sprite being used for something like a "make shift chem dispencer" or something like that but it does not match current SI-med pallets or sprites

**Comment by Stutternov** [comment]
Dispenser sprite returned to og one as requested; chemical dmi changes should Just now be moved around sprites and the new sprite set as unused.

**Comment by Trilbyspaceclone** [comment]
Industeral chem dispencers are invisables

**Comment by Stutternov** [comment]
Made a new PR without the chemistry issue, too lazy to fix this one properly.

**Pull request closed without merging**
