### PR TITLE
Guts and Glory Re-Work

### PR DESCRIPTION
**Pull request by MSieghardt**
OORAH

Guts and Glory is now reworked to give a buff. +17 to all combat stats for 2 minutes for you and everyone around you and it **STACKS**

You're a human, this is "guts and glory" not "rest and recuperate". It's your moment of glory.

### CODE REVIEW

**Comment by Kazkin** [comment]
Has this been tested? If so I'll merge it, seems like a good rework.

**Comment by ThePainkiller** [comment]
This is a massive nerf in actual human survivality, stat boots are terrible in general and don't make much of a noticeable difference in combat (not even +17) to even justify butchering a decently balanced self-healing mechanic. If I wanted stat boots I'd play an Akula or Kriosan.

**Comment by MSieghardt** [comment]
This was tested and it works, forgot to put that in the description. It uses the same baseline of asynchronous calls to kill the stat boost as litanies do. 

And on the topic of nerf, this change was based on feedback from the human players I know and talk to. 

It's called "Guts and Glory", it's your heroic moment rise to power not power-nap time. Also, humans are more known for, both in our setting and standard universal settings, working together and rising to the ocassion to overcome things.

The reasoning behind it being +17 is that it applies it to everyone in view and it *stacks*. This means that if 3 humans do their OOORAH moment together, everyone around them, including themselves, gets a +51 to their combat stats. That's absolutely nothing to scoff at. 

Don't let the fact that the new insight lets you get to 100 ROB in an hour or two cloud your judgement regarding combat stats. When compared to other boost perks, it's up there.

**Comment by Trilbyspaceclone** [comment]
I dislike this nerf to gag and wish to see it  be a new perk rather then removing GaG

**Comment by Kazkin** [comment]
This will require some discussion, as I can see merits to both.

**Pull request closed without merging**
