### PR TITLE
Aberrant Organs - tweaks and a little bit of content

### PR DESCRIPTION
**Pull request by Pink-Chink**
## Changelog
:cl:
add: Added dependent and enigmatic teratomas to the loot drop pool
add: Added parenchymal membrane
balance: Organoids no longer have a chance to be destroyed on failed removal
balance: Added lipzoine, lime juice, orange juice, tomato juice, tea, and iced tea to edible pool
balance: Standard reagent outputs increased to 2u
balance: Durable membrane and biostructure gel size mod reduced to 0.25
balance: Hormone blood-clotting effect increased to 0.25
balance: Hormone blood regen effect increased to 0.4
balance: Hormone painkiller effect increased to 20
balance: Hormone speed boost effect increased to 0.25
tweak: Sci goggles allow user to see organoid information
tweak: Organs don't rot in vending machines
fix: Adds stomach to the organ fab
/:cl:

### CODE REVIEW

**Comment by LiteralMushroom** [comment]
Can ALL the hormones please get buffed? They're pretty much all useless right now because 0.1 is basically nothing and they only get secreted in tiny amounts.

**Comment by ThePainkiller** [comment]
> 0.2 is probably useless too but I obviously can't say for sure because this isn't merged yet.

From personal experience and lag testing on IV drips (via my roller beds PR), 0.2 is literally `REM`, normal metabolization of a chemical, anything below that is so small it won't even get properly processed, IF barely affecting the user

**Comment by Pink-Chink** [comment]
Gonna try these numbers for a hormone buff.

**Comment by LiteralMushroom** [comment]
> Gonna try these numbers for a hormone buff.

The anti-toxin and oxygenation ones need a buff too, I've tested them and they either do nothing or heal a negligible amount of damage.

**Comment by Pink-Chink** [comment]
Anti-tox and oxygenation are weak chem effects in general. The effects themselves need a buff, not the numbers.

**Review by Trilbyspaceclone — APPROVED** [review]

**Pull request merged**
