### PR TITLE
psionic harvester port

### PR DESCRIPTION
**Pull request by LongSleeves**
Ports the psionic harvester fix

is a 1:1 port so shouldn't mess anything up.

### CODE REVIEW

**Comment by r4d6** [comment]
I got two questions : 
1. Can you link to the original fix PR?
2. You do know that the machine is completely useless due to how rare procedural artifacts are, right?

**Comment by Trilbyspaceclone** [comment]
> I got two questions :
> 
> 1. Can you link to the original fix PR?

It was requested by SoJ staff to not show the o.g link pr for some reason

**Comment by ActuallyALovelyGrave** [comment]
>For some reason.
So, now soj staff doesn't even want to give the credit to other people at coding.
Why?

**Comment by r4d6** [comment]
> > For some reason.
> 
> So, now soj staff doesn't even want to give the credit to other people at coding. Why?
I got no idea, but I managed to find the PR anyway. It's by the same guy : https://github.com/Liberty-Landing/Liberty-Station-13/pull/7

**Comment by ActuallyALovelyGrave** [comment]
@r4d6 Thanks for you contribution, it helped a lot. And explained as well, now this all makes sense.

**Comment by AysheDaArtist** [comment]
> > I got two questions :
> > 
> > 1. Can you link to the original fix PR?
> 
> It was requested by SoJ staff to not show the o.g link pr for some reason

If this is about https://github.com/Liberty-Landing/Liberty-Station-13/pull/7 it's because we did not want to advertise on Sojourn side of the code

This was fixed on Liberty Landing side then ported over, this was always r4's code, it's been tweaked, given a sprite, and anomalies have been modified to allow for it to function

**Pull request merged**
