### PR TITLE
Quality of Life-changing and drink-mixing Patch: "Bartender, Shake that drink!" edition

### PR DESCRIPTION
**Pull request by ThePainkiller**
## About The Pull Request

- Reworks the bartending shaker to become a `NO_REACT` container (akin to a cryostasis beaker). Now, to properly mix drinks, you have to fill it with the reagents of choice, and use in-hand to give the shaker a cursory shake, in excellent bartending style (sound and animated sprite included!) to mix the drink inside of it. No longer Bartenders will resort to quick, dull mixing! RP it up for extra spice!

shakeshake

- Reverts Soteria non-lethal weaponry sprite centering attempt as it only worsened the sprite's display. As they're odd dimensions of 60x32 or 40x32 they are impossible to properly center and will always offset the in-hand sprite to the right.
- Minor typo fixes on deep maint creature's descriptions and the things they say
- Gibbers now play a proper sound when gibbing something, and the old "blender" sound when activated without anything inside it to match the "metallic" sound and "squelching" sounds on the messages.
- Fixes microwave and burrows messages adding an extra "the" (the the microwave)
- Nullifies oldification and ID locking chances on deployed Body Bags and Stasis Bags as it was horrendously hilarious and hilariously horrendous, no longer will you take a bag from Soteria/Blackshield Triage only to deploy it and become an irrecoverable, unhackable ID-locked stasis bag!
- Fixes Leisure Outfit's bad `icon_state` and `item_state` pathing
- Gives Overcoats small pockets, changes loadout selection categories to split between Overcoat and Greatcoat (Greatcoats do not have pockets)
- Ports Overcoat sprites from Eris, adds updated Blackshield Armored Overcoat and Commander's Greatcoat variants
EDIT: Does the same for marshal drip because heck, why not?

image

image

image

<hr>

## Changelog
:cl:
add: Bartending shaker is now a NO_REACT container. To mix drinks inside of it, use it in-hand to give it a shake (with sound and animated sprite included!) to mix whatever's inside of it into a poured drink!
del: Reverts "sprite centering" on Soteria soporific guns, as they're oddly big sprites that can't be properly centered in-hand
tweak: All gibber type machines now play a proper sound when activated with and without proper mobs inside of them
tweak: All Overcoats have pockets now
fix: Fixes "the the microwave" and burrow interaction extra "the" 's
fix: Leisure suit now has a proper sprite path
fix: Stasis Bags and Body Bags will no longer have a chance to become ID locked on deployment, paramedics rejoice!
spellcheck: Fixed a few typos on deep maint creatures' descriptions and the things they yell
imageadd: Ports better greatcoat sprites from Eris, adds Blackshield Armored Overcoat and Commander's Greatcoat variants
/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
> For the `the` issues. `[src]` already handle adding them, so you can just remove them entirely from the descriptions to fix the issue.

I know, I'd just rather leave the [src] in case anything gets added without a prefix out of a lack of need to add the "the" prefix to it. The only other thing was just outright replacing [src] with the parent object name (when applicable) like just "The microwave turns on", which I considered a lazy fix :P

**Comment by r4d6** [comment]
> 

I didn't meant to say to remove the `[src]`, I meant to say to remove the `\the` in _front_ of the `[src]`.
[Also](http://www.byond.com/docs/ref/#/proc/var/src), when you put [src] in the output, BYOND already put a `the` in front of it if it is appropriate.

**Comment by ThePainkiller** [comment]
Oof, something broke master, can't compile anymore

image

**Comment by Trilbyspaceclone** [comment]
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm:5081:error: undefined type: /obj/item/clothing/suit/greatcoat/general/overcoatblack/brown
maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm:5085:error: unknown type

Fix that

**Comment by Trilbyspaceclone** [comment]
Masters not broken, this pr breaks it :P

**Comment by ThePainkiller** [comment]
> maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm:5081:error: undefined type: /obj/item/clothing/suit/greatcoat/general/overcoatblack/brown maps/__Nadezhda/map/_Nadezhda_Colony_Omni_STU.dmm:5085:error: unknown type
> 
> Fix that

How did you manage to see that? It wouldn't let me compile past the one I screenshotted to see what went wrong

**Comment by ThePainkiller** [comment]
Hold on on merging this, for some reason the commander's coat is a bit broken

**Comment by ThePainkiller** [comment]
Turns out merging with master had the `xenobio.dm` unticked from dream maker. Should be good to go now.

**Pull request merged**
