### PR TITLE
Revert "borg port"

### PR DESCRIPTION
**Pull request by Kazkin**
Reverts sojourn-13/sojourn-station#3035

Might have issues according to Aerith, unmerging temporarily.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Mind waiting on this a few shifts for testing?

**Comment by Kazkin** [comment]
Sure

**Comment by r4d6** [comment]
> Mind waiting on this a few shifts for testing?

The fix is only to define the bitflags correctly.
0x1, 0x2, 0x4, 0x8, 0x10, 0x20, 0x40, 0x80...

**Comment by r4d6** [comment]
https://github.com/sojourn-13/sojourn-station/pull/3040

**Comment by Trilbyspaceclone** [comment]
The flags works and theirs even a pr to make them more consentient, no need to revert.

**Pull request closed without merging**
