### PR TITLE
[lore] Cruciforms for Councilors

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
Allows all low councilors other than VBO and CRO to be faithful and select the cruciform. Hallelujah.

This PR may be fucked up as.im testing if I can make PRs.on mobile.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Can't figure.out how to draft this on mobile. DNM pending some stuff from lorehead.

**Comment by cdb-is-not-good** [comment]
Why did you change the tags?

**Comment by Trilbyspaceclone** [comment]
you cant merge a draft so DNM isnt needed
and your commit said `needs approveal from lorehead`

**Comment by cdb-is-not-good** [comment]
the lorehead gave approval it's waiting for him to do some writing not for approval.

**Comment by cdb-is-not-good** [comment]
@SingingSpock

**Pull request merged**
