### PR TITLE
toggles ooc at round end and at round start

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
OOC toggles off at round start, if not already muted
OOC toggles on at round end, if not already unmuted

### CODE REVIEW

**Comment by Lamasmaster** [comment]
https://tenor.com/view/better-call-saul-ss13-ooc-tgstation-tg-gif-25540502

**Comment by Stutternov** [comment]
https://media.discordapp.net/attachments/838502643492061206/1085203063725367458/doug.mov

**Comment by Dissentbay** [comment]
this is the type of pr that makes me wonder wtf happened for it to be made

**Comment by Stutternov** [comment]
> this is the type of pr that makes me wonder wtf happened for it to be made

Constant ic-oocing and salting in OOC channels; atop of general spam.

**Comment by Trilbyspaceclone** [comment]
This was not needed as it turns out

**Pull request closed without merging**
