### PR TITLE
Adds armored overcoat to blackshield militia

### PR DESCRIPTION
**Pull request by Smokingsquirrel**
## About The Pull Request
Adds a blackshield milita overcoat. It is currently not implemented in itemlists but is spawnable.

## Changelog
:cl: 
<!--add: Added new things
add: Blackshield Milita Overcoat
code: Added Overcoat to Armor.dm
/:cl:

### CODE REVIEW

**Comment by Smokingsquirrel** [comment]
no clue why this suddenly has an X when it had a check before. Code works

**Comment by Smokingsquirrel** [comment]
how's it looking on this?

**Comment by Kazkin** [comment]
Pretty simple test, just merge it, check it to verify working and we're good to go.

**Comment by Smokingsquirrel** [comment]
Yeah i dont get the problem. It works fine on my test, it compiles and runs without any errors and even is wearable, found in the locker and has no conflicts whatsoever.

**Pull request merged**
