### PR TITLE
Revert "Makes the subtle verb hidden to ghosts"

### PR DESCRIPTION
**Pull request by king5327**
Reverts sojourn-13/sojourn-station#467
I'm annoyed that this slipped my watch, after all those times I'd explicitly rejected this idea.
Also didn't appear on the changelog.

Caught it by accident while trying to figure out why whispers weren't being logged, of all things.

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Wasn't this basically intended for people who didn't want their (impure) actions literally be seen by ghosts? The description even said so. The vars were defined for it to work this way. Why do you want to revert this, if it was intended all along?

**Comment by king5327** [comment]
Intended... by whom? Subtle was for short range emoting like whispers, not for eroticism.
t. guy who ported subtle years ago

**Review by Trilbyspaceclone — CHANGES_REQUESTED** [review]
This is a bad change, anti-subtle verson is for ERP without annoying ghosts

**Comment by king5327** [comment]
I can assure you that if I wanted subtle to be antighost, I would have done that when I first ported it.

**Comment by Kazkin** [comment]
Request from the host himself, k5 rarely asks for things and often allows alot of things he wants to pass by unused/undone. I'm more than willing to accept this as its a minor change.

**Pull request merged**
