### PR TITLE
[Apparently works] Client FPS re-enabling.

### PR DESCRIPTION
**Pull request by Yawet330**
## About The Pull Request
<details>
<summary>
	Uhhhhhhhhhhhhhhhhhhhhhhhh I don't know why this was disabled
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
add: Re-adds client FPS?
/:cl:

### CODE REVIEW

**Comment by Yawet330** [comment]
still a WIP

**Comment by Yawet330** [comment]
Now fully compiles. Needs testing

**Comment by Trilbyspaceclone** [comment]
Blank #1438

**Comment by Kazkin** [comment]
Who wants to bite the bullet and test this?

**Comment by MSieghardt** [comment]
@Kazkin Went through and ran a few tests on this. Not much that can break and it is barely noticeable from what I can tell. I'm curious how it'll be on live. On my own server, 60 FPS is the same as sync-ing up to the server FPS, so no change there. We'll see what happens on live, shouldn't crash or affect anything because it affects clientside view.

**Pull request merged**
