### PR TITLE
more consistent overwear

### LINKED ISSUE #4728: Universal slings are not universal
Universal slings seem to be pretty inconsistent in what they can carry. Guns? Always but melee weapons/tools can be very inconsistent for example the new getto spears we got awhile back. There's many things they can't hold that jackets/vests can. Not really sure why it is this way or if it's a intended nerf why given usually jackets have armor already making slings a direct downgrade mechanically.

### PR DESCRIPTION
**Pull request by benj8560**
Removes unique allowed items list for slings and Expedition suits. This making it default to what all overwear use (vests, jackets, etc). This was just....odd and unnecessary.

Also technically fixes a small bug allowing it to hold /obj/item/storage/box it being able to do so made some very odd sprite related things involving becoming a massive cardboard box. Switches the sling to use a extra_allowed list to retain it's niche use cases on the bases that it has no armor values.

Flat out buff to the Expedition suit but needs it....it's easily one of the worst bits of ''armor'' in the game.

Fixes #4728

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
why are you so heavilly nerfing the sling

**Comment by benj8560** [comment]
they can't hold tools and many other very weird things normal vests can hold. I drives me nuts no one uses them for holding briefcases and other odd things cos no one KNOWS they do that. I just want it to be able ot hold melee weapons and things like that.

**Comment by benj8560** [comment]
I would not use the word heavy nerf. I'm removing their custom allowed list. They will default to the same every /obj/item/clothing/suit uses

**Comment by benj8560** [comment]
that being a much longer list: 

	allowed = list(
		/obj/item/clipboard,
		/obj/item/pen,
		/obj/item/paper,
		/obj/item/device/flash,
		/obj/item/storage/pouch,
		/obj/item/storage/sheath,
		/obj/item/gun,
		/obj/item/melee,
		/obj/item/material,
		/obj/item/ammo_magazine,
		/obj/item/ammo_casing,
		/obj/item/handcuffs,
		/obj/item/tank,
		/obj/item/tool, //People are going to so abuse this
		/obj/item/device/suit_cooling_unit,
		/obj/item/cell,
		/obj/item/storage/fancy,
		/obj/item/flamethrower,
		/obj/item/device/lighting,
		/obj/item/device/scanner,
		/obj/item/reagent_containers/spray,
		/obj/item/device/lighting/toggleable/flashlight,
		/obj/item/storage/box/matches,
		/obj/item/reagent_containers/food/drinks/flask,
		/obj/item/device/radio,
		/obj/item/clothing/mask,
		/obj/item/storage/backpack/guncase,
		/obj/item/implant/carrion_spider/holographic)

**Comment by benj8560** [comment]
but I'd be more then happy going the route of just adding their unique uses to a extra_allowed list I just figured I'd get more debate trying to buff them.

**Comment by cdb-is-not-good** [comment]
I'd be fine with the sling having an extra long list of things it can hold. Give up your suit slot in exchange for more versatility. DO take the box off that list, though.

**Comment by Trilbyspaceclone** [comment]
Its now way less harsh of a nerf to the point of being a bug-fix

**Pull request merged**
