### PR TITLE
Gives outsider a lil farm

### PR DESCRIPTION
**Pull request by Guidesu**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>
Honestly theres NO other place on the deep forest that has any sorta of farm and the outsiders already have a chem dispenser..... i mostly want to give it to them so there might be alternative to heal (which is good.... because plants take time... no analyzer so people need to trust on their wits....) that takes more skill than to press some buttons. (also a reason to outsiders to make tea that CDB coded :) )

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
pics

**Comment by Guidesu** [comment]
image

**Comment by cdb-is-not-good** [comment]
Not rly in favor of this, personally. Outsiders already have so much help and other farms ALREADY exist.

**Comment by Guidesu** [comment]
Fair enough.

**Comment by cdb-is-not-good** [comment]
Leaving this open for now in the event anyone has anything else to add. It'll be closed in a few days otherwise.

**Pull request closed without merging**
