### PR TITLE
Final Patchasy VI (actually porting from Eris)

### PR DESCRIPTION
**Pull request by ThePainkiller**
## About The Pull Request
- Ports the Burn Barrel from Eris, functions as a ghetto microwave on the fly.

firebarrel

- Adds different audio files and descriptions to the burn barrel because I'm just **THAT** extra.
- Also fixes Iron Lock hat not having a sprite, placeholder red Security hat for now.
- Adds new sprite for the Mouse plushie, to distinguish it from an actual dead mouse. Although you swear you could see it breathing...
- Ports .40 mags sprites from Eris
- Finally corrects the horribly body-innacurate Magnitka Officer suit
-  Removes small cell requirement from makeshift multitool since it didn't spawn with one when crafted
- Ports full body armors from Eris, as well as making a few local touches for lore adaptation.
- Makes all 15 of the full body armors craftable through the Clothing tab with their respective parent armors, any article of clothing (jumpsuit), four sheets of steel and a quality 15 adhesive tool.

image

<hr>

## Changelog
:cl:
add: Adds Burn Barrel to crafting under Furniture, works as a ghetto microwave and bonfire (emits light)
add: Ported Full Body Armors from Eris, all 15(!) are craftable on the Clothing section with their respective armors, a piece of clothing and 4 sheets of steel along with some tape.
tweak: Removed small cell requirement from makeshift multitool since it didn't spawn with one when crafted
fix: Finished fixing the Magnitka officer jumpsuit, it should now be pixel cohesive with human mobs
soundadd: Added new ambiental sounds for the Burn Barrel, planning on making it do a permanent loop of campfire noises for immersion
imageadd: Adds new mouse plushie icon. Adds custom server based full body armors based on faction colors.
code: minor fixes to descriptions, missing slashes and such
refactor: Refactored microwave code to accomodate for the Burn Barrel and not have it get "microwave" messages.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
All the crafting should have more steps in them for getting so much more armor, more coil/tools used/plastic and more metal for some of them.

**Comment by ThePainkiller** [comment]
> All the crafting should have more steps in them for getting so much more armor, more coil/tools used/plastic and more metal for some of them.

It has the same armor values, it's just additional body parts covered which are still pretty prone to rng targetting (almost 80% of mob attacks go for the chest, with the odd projectile sometimes targetting the arms), does it really justify more metal/plastic?
I wanted to make it accessible and easy more for the drip than actual combat functionality but if it truly is as imbalanced...

**Comment by Trilbyspaceclone** [comment]
Your armor level 4x itself do to covering more, it should prob take more materals for balance, maybe cutting or something?

**Comment by ThePainkiller** [comment]
> Your armor level 4x itself do to covering more, it should prob take more materals for balance, maybe cutting or something?

Alright, I'll adjust the recipes according to the armor values and leave the very basic steps with the handmade ones then

**Pull request merged**
