### PR TITLE
Church General Litany Rebalance

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
-Makes litanies cost an amount of nutrition with every cast
-Using one without proper nutrition gives slight toxins
-Shortens the power cost for the entreaty litany from 50 to 25

## Changelog
:cl:
/:cl:

### CODE REVIEW

**Comment by intense-skies** [comment]
How dare you lie about your PR. Shame on you.

**Comment by Trilbyspaceclone** [comment]
> How dare you lie about your PR. Shame on you.

WHAT LIES?

**Comment by intense-skies** [comment]
> WHAT LIES?
Only adjusted it after I said something...

**Comment by Kazkin** [comment]
Require testing before merging.

**Comment by Chaoyote** [comment]
Cruciforms literally have a prayer to cure hunger, and cahors is plentiful. There are more pressing issues with litanies than this.

**Comment by intense-skies** [comment]
> Cruciforms literally have a prayer to cure hunger, and cahors is plentiful. There are more pressing issues with litanies than this.

I agree. Personally I plan to change this, after it gets merged, so you can cast litanies while not having the nutrition and instead it takes blood from you (basically consuming your body at that point).
Nutrition cost will be balanced overtime.
They do have a litany to cure hunger. But that is fairly costly energy-wise and makes the individual have to manage a lot more then previously.

**Comment by intense-skies** [comment]
Made a slightly different version of this PR.
https://github.com/sojourn-13/sojourn-station/pull/1480

**Pull request closed without merging**
