### PR TITLE
examination room to upper soteria medical

### PR DESCRIPTION
**Pull request by GlitchySoftware**
Adds an examination room to upper soteria medical, for all the examination needs there are.
image

By Trilby:
Fixes up the medical ward to function better
Fixes some misc area stuff that dosnt matter

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
No atmos?
Also your removing a lot of strechers/blood
Also also this remove some maints loot

**Comment by GlitchySoftware** [comment]
> No atmos? Also your removing a lot of strechers/blood Also also this remove some maints loot

i reverted the changes and pasted the area over

**Comment by GlitchySoftware** [comment]
are you sure the problem still persists?

**Comment by GlitchySoftware** [comment]
i forgot the pipes.......

**Comment by Dimasw99** [comment]
I salut the old exam room I once made but got lost in the map change o7
grafik

**Comment by GlitchySoftware** [comment]
> I salut the old exam room I once made but got lost in the map change o7 grafik

o7 to all the fallen warriors

**Comment by GlitchySoftware** [comment]
@Trilbyspaceclone catto should be pleased things have been fixed

**Pull request merged**
