### PR TITLE
Ranger Vouchers & Guns

### PR DESCRIPTION
**Pull request by SouthyOsmanli**
## About The Pull Request
<details>
<summary>
	This PR adds a unique primary voucher to the Ranger, allowing a selection of three primary weapons - the Thompson, the Armstrong and the new Peacekeeper break action E-shotgun. A new secondary voucher was added to rangers as well, allowing a selection between the Deckard, the new 7.5 revolver, or the new Zwang energy revolver. Sprites for all the new firearms made by Kaverick.
</summary>
<hr>

<hr>
</details>

## Changelog
:cl:
add: Two new Ranger-specific revolvers - the Zwang and the Judge.
add: New Peacekeeper break-action E-shotgun; similar to the Abdicator but, granted, worse cell cost and AP wise since it is round start gear.
add: New primary and secondary selection voucher for Rangers.
/:cl:

### CODE REVIEW

**Comment by lolman360** [comment]
while you're adding it armstrong might need a buff, it has negative damage mult and is actually weaker than most .40 pistols

**Comment by SouthyOsmanli** [comment]
> while you're adding it armstrong might need a buff, it has negative damage mult and is actually weaker than most .40 pistols

See the buff it got before you commented. It does bonus now.

**Comment by ThePainkiller** [comment]
Ranger starting with a free .50 Kurtz sounds a bit OP imo...

**Comment by SouthyOsmanli** [comment]
> Ranger starting with a free .50 Kurtz sounds a bit OP imo...

...But - they literally do **already**. The Dekcard is in their locker default. I just moved it to the voucher.

**Comment by cdb-is-not-good** [comment]
Looks good overall, just give it a full test

**Comment by Lamasmaster** [comment]
Why add thompson back after the entire they can't get more ammo for it ?

**Comment by cdb-is-not-good** [comment]
> Why add thompson back after the entire they can't get more ammo for it ?

I mean marshal lathe has disks for .40 large boxes now

**Comment by cdb-is-not-good** [comment]
My brain is empty so forgive me if i'm repeating stuff. No inhand sprites for either Zwang/Peacekeeper seem to work, nor wielded. there's the overlay thing but frankly that can be fixed at a later date - so can these as well, frankly. But worth noting!

**Comment by MichaelMaCleod007** [comment]
Can confirm that the Peacekeeper has no in hand or wielded sprites, otherwise the gun seems to have all the other sprites and is visible.

**Pull request merged**
