### PR TITLE
Changes One Star Vendor to Greyson Positronic Vendor

### PR DESCRIPTION
**Pull request by ThatGuyFromThatPlace**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Changes the "One Star Vendor" name to "Greyson Positronic Vendor" to match with our lore. The name "One Star" is what is used by Eris. Also altered the description to match, and minorly altered the wording
	
<hr>
</details>

## Changelog
:cl:
fix: Changed One Star Vendor to Greyson Positronic Vendor to match with Sojourn's lore 
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Reason why it kept with onestar is when I coded it, i thought GP would make a shell corp to make the venders under a different name.

Thats the only reason why it kept "Onestar"

**Comment by king5327** [comment]
Lore Concern, I'll get someone to review it.

**Comment by Guidesu** [comment]
I want to keep it as one star.
Personally the idea of subsidiaries from greyson is a idea that is already on lore like nanotrasen and such would think its better to let this way.

No from sheep head min

**Comment by REDLAERT88** [comment]
This is a bit of a weird one? If one star was intended to be existent, to be honest I haven't heard of that before. Im more inclined to follow the precedent that Greyson is the existing. Company. If anything it should be nano-trasen vendor due to nano-trasen being the office supplies side of greyson positronics. I dont think we need another shell company name just for this vending machine.

**Comment by Guidesu** [comment]
Well okay makes sense.
Honestly since the vendors sells varieties of stuffs and nanoteasen still exist and is on the colony it's kinda an okay of a detail

**Pull request merged**
