### PR TITLE
slowdown!

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Massively reduces stacking speed ups from drugs, musle (implant), and a few perks as well as higher the cap on musle (organ) speed gain

testing: made sure it complied
performance: no change

### CODE REVIEW

**Comment by Guidesu** [comment]
Hi Trilbo.
I have a suggestion.
I think this change might be good but I think that you lowered the value so much, Yeah, speed stacking is kinda bad as you can go mac-5 in the whole colony if you have like nanites/muscles and such. But I don't think it should be nerfed that hard.
I feel that it would need a speed cap in general with other factors as well but my hot take is:
Exalt's in general needs a general buff about their organ's efficiency mostly speaking the muscles.
As far as I am aware the cap or something that I heard makes exalts supposed buffs and advantages not that good.
So I wish you could buff or make exalts organs, in general, more viable without nerfing them (I don't know if you are nerfing them, but as far as I read correctly ou making the cap higher. So that means the exalts are not using their full potential)

Yeah. I think these changes are good I just think that you don't need to lower the value that much or in cases of the perks, since you removing their speed bonus could you at least give them some better stats or like bonus

**Comment by Thegreatspidernonbinary** [comment]
this looks amazing. now storage rework

**Comment by ThePainkiller** [comment]
I've implanted additional muscles in someone's legs the other day and they no longer give any significant speed up, are muscles even working properly?

**Review by TheSleepyCatmom — APPROVED** [review]

**Comment by Stutternov** [comment]
make it so it also removes storage when your speed goes up (:

**Comment by Trilbyspaceclone** [comment]
### _**APPARENTLY THIS IS POPULAR???**_

**Pull request merged**
