### PR TITLE
Creates a barefoot shoes that does not have a mob icon so people can walk around "barefoot"

### PR DESCRIPTION
**Pull request by Guidesu**
<summary>
	About The Pull Request
</summary>
<hr>
The title says all. I just made a subtype of a jackboot, someone asked to me do it for them, i probably will use it too.  Nothing really changed aside of that.

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
why is it a subtype of jackboot instead of a subtype of any other type of shoes, like the cloth wraps

**Comment by Guidesu** [comment]
UGGGGH

**Comment by Guidesu** [comment]
its not that jackboots are the most available type of footgear... *mumbles*

**Comment by ChefDoggo** [comment]
the foot fetish stocks are about to go up

**Pull request merged**
