### PR TITLE
Cloth psych ward walls

### PR DESCRIPTION
**Pull request by benj8560**
Was messing around and HOH figured out you can make cloth walls. perfect for are psych ward! I was crazy once.....

dreamseeker_75tkLLykUk

Changelog:

Adds cloth walls to the psych ward rooms

### CODE REVIEW

**Comment by hex37** [comment]
On one hand I think that the psych ward may not be long for this world.

On the other, this is very non-intrusive and on-point. So if I'm not going to remove it any time soon, why not?

**Comment by cdb-is-not-good** [comment]
Question; if these don't stop injury when you leap into them, what is the point?

**Comment by benj8560** [comment]
> Question; if these don't stop injury when you leap into them, what is the point?

looks nice? Does there need to be a point. 



> On one hand I think that the psych ward may not be long for this world.
> 
> On the other, this is very non-intrusive and on-point. So if I'm not going to remove it any time soon, why not?

Why remove?

**Comment by benj8560** [comment]
also I highly doubt someone _could_ go beyond midly hurting themselfs with diving. Once your at 40 or something brute it does the ''to hurt to dive'' thing. What you should be thinking about is someone smashing the light with their shoes and you knowwww

**Comment by benj8560** [comment]
diving into walls does not hurt you at all as is. Stawp gaslighting me ;-;

**Pull request merged**
