### PR TITLE
We need to cooka da mets jedse

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Drug PR, nowhere near done I just want it here causse uhh yeah
	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by ThePainkiller** [comment]
Hope these become high contraband as well

**Comment by Hlscientist** [comment]
Heisenborg

**Comment by AysheDaArtist** [comment]
"Hope these become high contraband as well"
Agreed, unlike normal Space Drugs, these drugs have some serious backlash to them and could lead to uneducated colonist harm, it would be nice to have these on a Contraband list

**Comment by Hlscientist** [comment]
I am the synthetic that cooks

**Comment by DorfGuy1** [comment]
will this have actual meth in it. Asking for a freind.

**Comment by Lamasmaster** [comment]
Closing for now as I need to actually make a spreadsheet first to make this properly work how I want.

**Pull request closed without merging**
