### PR TITLE
Low FPS for Wilson

### PR DESCRIPTION
**Pull request by Stutternov**
## About The Pull Request
Simulates lag (:
image

## Changelog
:cl:
add: adds lag.
/:cl:

### CODE REVIEW

**Comment by JohnWilsonDeez** [comment]
very good pr you're very good cod r

**Comment by Trilbyspaceclone** [comment]
This dosnt accully do anything

**Comment by Stutternov** [comment]
i have proven myself to coder cat that this pr is truly good for the game and makes all players fight on an equal playing field

**Comment by nikothedude** [comment]
this will surely put us on the same playing field as games such as fortnite

**Comment by Dimasw99** [comment]
HOLY SHIT! THIS IS WHAT WE NEEDED!

**Comment by ThePainkiller** [comment]
Actually, the human eye cannot perceive anything faster than 30fps so it shouldn't be a problem!! :D

**Comment by cdb-is-not-good** [comment]
🤨

**Pull request closed without merging**
