### PR TITLE
Old Data (10% reduction)

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Printing items on an autolathen is worth 10% less on cargo shuttle, dosnt affect beacons

### CODE REVIEW

**Comment by Kazkin** [comment]
No.

**Comment by Trilbyspaceclone** [comment]
Its being tweaked to be less extream

**Comment by r4d6** [comment]
We really don't need for lathe-printed items to be cheaper.

It is intended for Cargo to be able to sell printed items for higher than the cost of the mats.
And we're fixing the items with a disproportionate mats-price ratio.

There's no need for this.

**Comment by Trilbyspaceclone** [comment]
> We really don't need for lathe-printed items to be worth less.
> 
> It is intended for Cargo to be able to sell printed items for higher than the cost of the mats. And we're fixing the items with a disproportionate mats-price ratio.
> 
> There's no need for this.

Issue is they cant compete with trade beacons, so its always better even when a trade beacon *wants* an item to sell it on the shuttle rather then trade ship

**Comment by Kazkin** [comment]
Why not just make trade ships pay more for bounties?

**Comment by Trilbyspaceclone** [comment]
> Why not just make trade ships pay more for bounties?

Other way around, bounites take 15->30 mins to refresh (not bad they are REALLY good but limited)
Selling items back to the trade ship is the issue, i plan on adding WAY more things to trade ships, more food items just more things so its viable to see to a trade ship

**Comment by Kazkin** [comment]
Still no.

**Comment by Trilbyspaceclone** [comment]
Ill make more supporting prs for this

**Comment by r4d6** [comment]
Trilby, there is no need to have autolathes reduce the worth of the items they produce, when the _explicit_ goal is to allow Lonestar to print slightly more expensive items with cheap mats.

The problem was always a few random items having a ridiculous sell price for the materials used.

**Comment by Trilbyspaceclone** [comment]
@r4d6 Prices are an afterthought thats not the point of this pr.

**Comment by Kazkin** [comment]
My opinion still has not changed >:V

**Comment by Trilbyspaceclone** [comment]
The Factio shuttles were made, so they have an alteritive to the shuttle, but currently its always better to make the items and do main shuttle

**Comment by r4d6** [comment]
> The Factio shuttles were made, so they have an alteritive to the shuttle, but currently its always better to make the items and do main shuttle

For fuck's sake Trilby, Possum refused this PR 3 times in a row. What make you think that he won't refuse a fourth time?

**Comment by Trilbyspaceclone** [comment]
> For fuck's sake Trilby, Possum refused this PR 3 times in a row. What make you think that he won't refuse a fourth time?

No swaring!
Also now that its ready

**Comment by Trilbyspaceclone** [comment]
image
A graft to better show the intent/reasoning of the pr

**Comment by Trilbyspaceclone** [comment]
linter test

**Comment by Trilbyspaceclone** [comment]
Linter testing again

**Pull request closed without merging**
