### PR TITLE
Gives Scavs, scav step

### PR DESCRIPTION
**Pull request by Spoopy11**
## About The Pull Request
<details>
<summary>
	Minor buff to Scavengers  by giving them scav-step.  Stop falling over you buffoons.
</summary>
<hr>

	
<hr>
</details>

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
image

**Comment by Spoopy11** [comment]
> image

It was a joke >:(

**Comment by cdb-is-not-good** [comment]
pf, im not so sure about this one, chief.

**Comment by Stutternov** [comment]
I dont particularly agree with this since they can just choose the background. If they get sure-step as a perk as well they can just power-game by choosing a different background perk for another bonus.

Could just boost their cognition since cog also determines if you fall on your face n' all on underplating.

**Comment by cdb-is-not-good** [comment]
ahhhhhhh- Nah.

**Pull request closed without merging**
