### PR TITLE
Ports a few updated icons from Eris + New Medhud

### PR DESCRIPTION
**Pull request by Guidesu**
https://github.com/discordia-space/CEV-Eris/pull/8380
https://github.com/discordia-space/CEV-Eris/pull/8379
^ Sprites of a few mobs and objects

The pulse-styled medhud was made by me. Its even animated. Inspired by Baystation Brainmed system to look less gamey.
 
(Moon does not include this only this)
add: A new type of medhud inspired by baystation brainmed system, made by me, Guidesa.
add: New sprites for power station, splints and etc. Morgue and Crematorium aswell.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
credit the o.g pr and the artists if possable

**Comment by Shirumic** [comment]
Not the biggest fan of these medkit sprites, I think our current ones are better.

Health analyzer is a much needed improvement though

**Comment by Guidesu** [comment]
Did you even looked the icon bot?

**Comment by ChefDoggo** [comment]
this update things like the SI ointment and bandages as well or just the baseline ones?

**Comment by cdb-is-not-good** [comment]
I like the medical sprites, Im not a huge fan of the mobsprites. Eris uses HIGHLY stylized animal sprites that really stand out when put side-side with non Eris sprites. Which, obviously, is an issue for Us.

**Comment by ChefDoggo** [comment]
agree on the mob sprites, they'd look super out of place considering we have a load of noneris style animals. if the ointment and bandages cover  the soteria handmade fancy ones then it would be def a good PR to make

**Pull request merged**
