### PR TITLE
the space leakening

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
New bluespace event that leads to leaking in traps of space!
Walking into it will deal clone damage as well as to everyone around the leak as well
The leak can be fixed with space cleaner, some types of soap (church and bluespace) and a vaccum.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
...space cleaner?

**Comment by cdb-is-not-good** [comment]
Why space cleaner?

**Comment by Trilbyspaceclone** [comment]
Its a blue*space*
that needs to be cleaned up
**space** cleaner is the job for it.

**Comment by cdb-is-not-good** [comment]
That's a little goofy

**Pull request merged**
