### PR TITLE
Makes adding an exclamation point to the end of a sentence not flood the chat.

### PR DESCRIPTION
**Pull request by LiteralMushroom**
**## About The Pull Request**
hello yes I'd like to be able to say things with some amount of emotion without it being interpreted as yelling
if you DO want to yell, just bold the sentence instead

## Changelog
:cl:
removes: No more big text.
/:cl:

### CODE REVIEW

**Comment by CocaColaTastesGood** [comment]
proc probably doesn't have support for more than one character

**Comment by cdb-is-not-good** [comment]
Could use the uhbhhh- ‼ Unicode marking but LOL no one will ever use it then

**Comment by UntoldTactics** [comment]
yespls

**Comment by cdb-is-not-good** [comment]
IMO just don't.

**Comment by hex37** [comment]
Has my +1. Approved.

**Review by hex37 — APPROVED** [review]

**Comment by LiteralMushroom** [comment]
hey so uuUUHHHHHHHHHHHHH would people be fine with me just removing the big text thing entirely?

it would be significantly easier than finding a workaround for the whole "only recognizes 1 character" thing

**Comment by LiteralMushroom** [comment]
whatever I'm taking the complete and utter silence as a yes

**Comment by cdb-is-not-good** [comment]
Not a fan, personally. It has its use.

**Comment by LiteralMushroom** [comment]
> Not a fan, personally. It has its use.

okay so just bold the sentence
might consider finding a way to make bolded sentences big instead of exclamation points making text big

being able to say things with actual emotion without flooding the chat is more important than the ability to Yell At People

**Comment by TheSleepyCatmom** [comment]
Yells do more than just 'big text.' It carries the voice further mechanically (or at least is intended to, just like the Ranger's perk is supposed to let them hear shit from further away. Whether it actually works is a separate issue.)

**Comment by cdb-is-not-good** [comment]
Correct. I'd rather just ...not. Either change it to a different character or don't fuss with it.

**Comment by LiteralMushroom** [comment]
doesn't work, backup plan: just make volume not make text any bigger

**Pull request closed without merging**
