### PR TITLE
Termite hell

### PR DESCRIPTION
**Pull request by KitchiFox**
Adds a Termite POI underground on the Deep Forest map. complete with termites, food piles and loot. includes a hidden safe and bluecross/redcross/super rare oddity spawn.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Neat, please add pics

**Comment by KitchiFox** [comment]
Screenshot 2024-03-16 080203
Screenshot 2024-03-16 080148
Screenshot 2024-03-16 080145
Screenshot 2024-03-16 080140
Screenshot 2024-03-16 080132

Screenshot 2024-03-15 214203

**Comment by KitchiFox** [comment]
Screenshots added!

**Comment by cdb-is-not-good** [comment]
Based

**Comment by AysheDaArtist** [comment]
Helldivers, you know what to do.

**Comment by KitchiFox** [comment]
After the test and gathering opinions. will need to rework the POI to make it worthy of risking termite wrath without making it lag the server.
Plan is:
-Removing the majority of swarm spawns
-Adding tougher termites going deeper within that will take far more punishment. they will be coloured differently to reflect this
-Add a Boss termite in the middle with two guard type termites. tougher like the tougher termites and pack extra hurty pincers
-Adding a static rare firearm or two. with accompanying ammo
-Add a giant gem for prospectors/colonists/outsiders to fight eachother for. the treasure of the boss termite.
-Replacing food piles with scrap and armament piles. Was informed Termites eat ores and metals

**Comment by cdb-is-not-good** [comment]
veto on the giant gem, those are worth way too much.

**Comment by cdb-is-not-good** [comment]
Is this still being worked on?

**Comment by KitchiFox** [comment]
Map is essentially done. issue is getting the sprites for the alternative, tougher termites. going to poke people in the spriting section later today

**Comment by Trilbyspaceclone** [comment]
This pr is **not** rejected
Closed to do conflict merges and seemingly stale

**Pull request closed without merging**
