### PR TITLE
saving xenobotany from itself

### PR DESCRIPTION
**Pull request by hex37**
- adds low-grade antitoxin chem, which heals tox like dylo but slower
- adds monocaridine chem, which heals brute like bicard but slower
- adds moon water chem, which heals burn like kelo but slower
- adds quintalin, which heals oxy like dexalin but slower
- added chemical reactions that prevent chem stacking the new healing chems
- adds moon tear plant, which has moon water. It mutates into sun tear.
- adds space alocasia, which has monocaridine and low grade antitoxin. It mutates into mercy's hand
- adds curtain weed, which has quintalin and paracetemol. It mutates into vale bush.
- changed poppies to contain Monocaridine and space drugs instead of its previous reagents
- changed ambrosia vulgaris to contain just monocaridine instead of kelotane and bicaridine
- changed potatoes to mutate into blood root
- Moon Tear added to seed vendors
- Space Alocasia added to seed vendors
- Curtain Weed added to seed vendors
- Blood root, Mercy's hand, Sun tear, vale bush and Jurlmah removed from Seedmaster & Megaseed servitor.

## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by SingingSpock** [comment]
> Do not merge yet - It is very early I need to do testing on this when I have time later today. PR is open for now to discuss changes.

You can use a draft PR for that purpose (should be a link to convert to draft on the right hand side)

**Comment by cdb-is-not-good** [comment]
This is good and I strongly support this change

**Comment by cdb-is-not-good** [comment]
I might suggest making poppies have a weaker version of oxy that still has all the negatives but less pain killing effects(to be analogous to the opiates jn actual poppies) but thats just my first thought.

**Comment by cdb-is-not-good** [comment]
...ah yea the chem stacking might be an issue in terms of power creep. A simple bandaid could nclide making it so that the simple version of a chem and superior metabolize together, maybe just into the simple version or maybe something in-between. If you wanted to be extra mean could make it so that stacking both metabolizes into something bad

**Comment by Vex8tion** [comment]
Probably should have it that stronger chemicals take precedence, not weaker chemicals. If chem stacking is a concern, we could add removal terms to bicaridine and keloderm, etc. like what's in moonwater to remove the respective weaker chemicals.

**Comment by cdb-is-not-good** [comment]
Not an awful solution. In general it might be preferable if chems gave only the best effect so you couldn't make god mixes with like....meralyn bicard tricord and varceptol.

**Comment by WilsonWeave** [comment]
Yeah I can get behind this change, always was odd to me that herbs and plants could easily and reliably procure refined medicinal products. Which, ended up getting them nerfed somewhere down the line anyways.

It'll lock the garden out of doing Cad favors roundstart, which is an agreeable change, makes Lonestar as a whole more reliant on Soteria to fulfill that niche of the station tree via chemistry, which is an arguably positive change to overall balance.

**Comment by SkinkHunt** [comment]
Ghetto chem, delicious.

**Comment by hex37** [comment]
I switched up how the new chems interact with better alternatives- they react with eachother and create nutriment instead

**Comment by hex37** [comment]
I consider this ready for a merge- be mindful that I added the curtain weed to the list, and gave vale bush the same treatment as other good-healing seeds.

**Comment by cdb-is-not-good** [comment]
Thumbs up. We can TM for however long and make sure there's no weirdness

**Pull request merged**
