### PR TITLE
Aberrant Organs - Mostly bug fixes and balancing

### PR DESCRIPTION
**Pull request by Pink-Chink**
### New Stuff

- Almost all organoids can be adjusted with a laser cutting tool to change their inputs/outputs. Reagent-based inputs can only be adjusted based on the pool they spawned with (e.g. roach toxins can only be swapped with other roach toxins). Other organoids are almost fully customizable. Overall, there should be less RNG nonsense involved.
- Teratomas are separated by type. You shouldn't need to print a bunch and hope you get the kind you want anymore. If you do need to reroll, teratomas will recycle for their full cost as long as you don't remove the organoid inside.
- Hormones. The names may change in the future to be more fictional, but these are reagents that add the removed chemical effects at similar magnitude. They are removed and re-added when the scaffold triggers to prevent build-up.
  - Thrombopoietin - 0.1 blood clotting
  - Aldosterone - 0.1 blood restoration
  - Enkephalin - 10 painkilling
  - Osteocalcin - 0.1 speed boost
  - Leukotrienes - 0.5 anti-toxin, a slight buff from the original.
  - Dexterone - 1 oxygenation, a new addition

### Fixes

- Organ fabricator has 360 starting biomatter again. This should be enough for 4 completed organs after recycling the ruined teratomas.
- Organ fabricator can recycle organs and organoids again, but only those item types. This is temporary until the organ resource machine is finished.
- Aberrant organ designs (scaffolds, teratomas, etc.) now cost base biomatter, which means they will fully refund when recycled. Note: teratomas lose 15 biomatter when the organoid is removed.
- Chemical effects (endocrinal) were replaced with new hormone reagents since the chemical effects weren't actually working.
- Eyes were removed from the efficiency pool since it was the cause of a massive amount of runtimes.
- Stat buffs (intracrinal) were fixed and will properly stack.

### Balance Adjustments

- Deep maintenance Oh My Guts! vendor disks are free. You just need to hack the vendor.
- Stat-based (intracrinal) organoids and membranes give 3 stat points instead of 5. It was too easy to stack them and get massive bonuses.
- As a consequence of the changes to chemical effect (endocrinal) organoids, chemical effects from the same hormone won't stack.
- Output-boosting (enzymal) teratomas can only be found in deep maintenance disks/vendors. Tubular teratomas have replaced it on the organ fabricator.
- Organ stat modifiers (efficiency, size, blood requirements, etc.) had their pool reduced from 5%, 10%, and 25% to 4%, 8%, and 16%.
- Organ scaffold base size increased to 0.4 to account for the above change. Aberrant organs should still be the roughly same size on average, though. 
- Organoid reagent pools. Paracetamol was removed from the basic medicine pool. Synaptizine, hyperzine, and bicaridine were moved to the intermediate medicine pool. Polystem was added to the simple medicine pool. Base toxin reagent type was removed from the toxin pool. As more hormones are added, the medicines may be removed entirely since it doesn't make a ton of sense to have them, anyway.

### Testing

Assembled and inserted the following organs into a monkey. All outputs observed and no runtimes over 10 minutes.

    This is a kidnessel. 
    It is a normal-sized item.
    A collagen-based biostructure.
    Organ size: 0.52
    Requirements: 0.06/0.42/0.24
    Organoid grafts present (3/3). Use a laser cutting tool to remove.
    Average organ process duration: 10 seconds
    Organ tissues present (efficiency): kidneys (2), blood vessel (16)
    Functional information (input): drains held power sources
    Sources accepted: medium power cell
    Functional information (processing): condenses inputs into a single output
    Functional information (output): augments physical/mental affinity
    Affinities: Mechanical (3)

    This is a stomessel. 
    It is a normal-sized item.
    A collagen-based biostructure.
    Organ size: 0.52
    Requirements: 0.2/0.52/0.16
    Organoid grafts present (3/3). Use a laser cutting tool to remove.
    Average organ process duration: 10 seconds
    Organ tissues present (efficiency): stomach (4), blood vessel (16)
    Functional information (input): metabolizes reagents
    Source: stomach
    Reagents metabolized: Nicotine
    Functional information (processing): connects inputs to outputs
    Mode: normal
    Functional information (output): produces reagents in stomach
    Reagents produced: Seligitillin (0.5u)

    This is a musidney. 
    It is a normal-sized item.
    A collagen-based biostructure.
    Organ size: 0.64
    Requirements: 0.32/0.4/0.4
    Organoid grafts present (3/3). Use a laser cutting tool to remove.
    Average organ process duration: 10 seconds
    Organ tissues present (efficiency): muscle (16), kidneys (8)
    Functional information (input): injury response
    Damage types: brute
    Functional information (processing): connects inputs to outputs
    Mode: normal
    Functional information (output): secretes hormones
    Effects produced: augmented agility

    This is a neressel. 
    It is a normal-sized item.
    A collagen-based biostructure.
    Organ size: 0.42
    Requirements: 0.04/0.08/0.08
    Organoid grafts present (3/3). Use a laser cutting tool to remove.
    Average organ process duration: 10 seconds
    Organ tissues present (efficiency): nerve (8), blood vessel (4)
    Functional information (input): drains held power sources
    Sources accepted: medium power cell
    Functional information (processing): condenses inputs into a single output
    Functional information (output): produces reagents in bloodstream
    Reagents produced: Inaprovaline (0.5u)

## Changelog
:cl:
add: Added the ability to adjust organoid behavior for almost all organoids with a laser cutting tool
add: Added hormone base reagent type and hormones thrombopoietin, aldosterone, enkephalin, osteocalcin, leukotrienes, and dexterone
tweak: Process teratomas are now separated by type
fix: Organ fabricator starts with 360 biomatter again and can recycle organs and organoids
fix Aberrant organ designs print at base cost
fix: Replaced chemical effect organoid behavior with hormone behavior
fix: Removed eyes from the organ stat pool due to massive amounts of runtimes
fix: Stat buffing organoids apply stat mods correctly and stack with other organoids
balance: deep maint OMG! vendors no longer charge for the disk in the contraband menu
balance: Stat buffing organoids now only apply a 3 point mod instead of 5 points
balance: Output-boosting organoids moved to deep maint loot, replaced with regular input/output mapping organoid
balance: Organ stat modifier pool reduced to 4%, 8%, and 16%
balance: Organ scaffold size increased to 0.4
balance: Paracetamol was removed from the basic medicine pool. Synaptizine, hyperzine, and bicaridine were moved to the intermediate medicine pool. Polystem was added to the simple medicine pool. Base toxin reagent type was removed from the toxin pool.
/:cl:

### CODE REVIEW

**Comment by LiteralMushroom** [comment]
Hey so uuuuhhhhh why do these require 60 biology when the maximum for a scientist is usually something close to 40?

**Comment by Pink-Chink** [comment]
Aberrant organs are medical content, not genetics/sci. You're not playing with DNA or any genetic information. It's all organ tissues, which is within the purview of a doctor. The 60 BIO for non-doctors is intended to be a steep requirement because it represents a specialization in biological sciences. You can get away with 40 BIO because examining an organoid only requires 40 BIO (60 when it's inside of an organ) and extracting an organoid from an organ/teratoma has a 0% fail chance at 20 BIO. As far as obtaining the 60 BIO at roundstart, FBP characters can easily meet the requirement and carbon-based characters are able to reach 59.

**Comment by LiteralMushroom** [comment]
> Aberrant organs are medical content, not genetics/sci. You're not playing with DNA or any genetic information. It's all organ tissues, which is within the purview of a doctor. The 60 BIO for non-doctors is intended to be a steep requirement because it represents a specialization in biological sciences. You can get away with 40 BIO because examining an organoid only requires 40 BIO (60 when it's inside of an organ) and extracting an organoid from an organ/teratoma has a 0% fail chance at 20 BIO. As far as obtaining the 60 BIO at roundstart, FBP characters can easily meet the requirement and carbon-based characters are able to reach 59.

So why is the actual machine in the genetics lab...?

**Comment by Pink-Chink** [comment]
It’s in the hallway across from the med locker room now. It’s where the devs decided it should go during their partial remap of Soteria.

**Comment by LiteralMushroom** [comment]
> It’s in the hallway across from the med locker room now. It’s where the devs decided it should go during their partial remap of Soteria.

oh, huh

**Pull request merged**
