### PR TITLE
Small tweaks

### PR DESCRIPTION
**Pull request by hex37**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Makes all medical staff able to use genetics lab, regardless of role. (Previously locked to Doctor/CBO only)

Adds hyperion mutation back to wendigo (and other tengolo big guys)

Removes biomatter requirement from soteria medical void armor

Removes biomatter requirement from rig suits

Removes Chemist perk from the Prime
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Not a fan of removing the biomatter needed for the void suits

**Comment by Trilbyspaceclone** [comment]
+ your allowing corpsment do to genetics

**Comment by ThePainkiller** [comment]
> * your allowing corpsmen do to genetics

~~They don't have access to genetics, they'd have to break the doors to do genetics anyways :P ~~

I still concurr, not a great idea to allow even trauma teams to do genetics, doctors I can KIND of understand but TT and Corpsmen? Why???

**Comment by hex37** [comment]
> > * your allowing corpsmen do to genetics
> 
> ~~They don't have access to genetics, they'd have to break the doors to do genetics anyways :P ~~
> 
> I still concurr, not a great idea to allow even trauma teams to do genetics, doctors I can KIND of understand but TT and Corpsmen? Why???

Unintentional.

**Comment by cdb-is-not-good** [comment]
> > > * your allowing corpsmen do to genetics
> > 
> > 
> > ~~They don't have access to genetics, they'd have to break the doors to do genetics anyways :P ~~
> > I still concurr, not a great idea to allow even trauma teams to do genetics, doctors I can KIND of understand but TT and Corpsmen? Why???
> 
> Unintentional.

Is there  an easy fix to negate that? I don't see it being a HUGE issue given the lack of access but I'm not super sure on letting Corpsmen have access to genetics even if it's not SUPER likely to come up

**Comment by ThePainkiller** [comment]
> Is there an easy fix to negate that? I don't see it being a HUGE issue given the lack of access but I'm not super sure on letting Corpsmen have access to genetics even if it's not SUPER likely to come up

Honestly, the whole _"allowing all of medical to do genetics"_ is bad. It has been already fixed by a Trilby PR so that Doctors **actually** have access to the machines, making Trauma Team (and unintentionally Corpsmen due to it being a perk check) having access to it makes no sense.

**Comment by cdb-is-not-good** [comment]
As of now there's a point regarding how little genetics does 'get done' by people across the board which - for a very big, cool, realized system is a bit of a shame. If this DOES get abused too much i would be open to bugging hex and working on it to actually make it a little less 'accessible'.

**Pull request merged**
