### PR TITLE
Marshool

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

Rebalances  Gear (marshal cog) by giving it a lethal mode alongside it's stun mode but giving it higher firedelay and no burst mode, gives tubular pouches to shotgun (except pug) and energy weapon loadouts (alongside 1 cell) and ammo pouches to the rest. Removes unused RCD sprite I left in with one of my PRs
	
<hr>
</details>

## Changelog
:cl:
tweak:  Rebalanced Gear (marshal cog)
balance: Gives marshal loaoduts tubular and ammo pouches alongside 1 cell for energy
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
.40 SMG mags do not belong in the veneder
its scav/guild only

**Comment by Lamasmaster** [comment]
I won't understand why Marshals have a weapon that uses it if it's only those two but removed.

**Comment by SouthyOsmanli** [comment]
This is why I said they shouldn't have the Thompson unless you're going to let them get mags for it.

**Comment by Kazkin** [comment]
Not sure I'm for giving them pouches, the thompson PR was temp denied/not merged due to failing to meet our spriting standards. Will leave this up for similar reasons but I'm against giving marshals ammo pouches. They have security webbings already, an incredibly powerful storage device.

**Comment by Lamasmaster** [comment]
So does blackshield, yet they do spawn with both types of pouches and even more ammo than marshals. There is no easy way to get tubular pouches anywhere unless you scavenge or church exists which makes organizing cells for primaries painful. Not to mention mashals only have 3 entire webbings for department of 8 people where as entire blackshield gets them in a locker.

**Comment by cdb-is-not-good** [comment]
Marshals only have a handful of webbings, not enough for each officer. By design, I believed

**Comment by r4d6** [comment]
> rebalances cog by giving it a lethal mode alongside it's stun mode but giving it higher firedelay and no burst mode

You should phrase that better, you are rebalancing the **Gear**, which is the special stun-cog that the Marshals have access too, not the regular cog that anyone can get.

**Comment by Lamasmaster** [comment]
Fixed the description of the PR. Now is there a still a reason **marshals** can't have spare ammo for their own weapons other than "just use pistol magazines" for a SMG that are meant for ladon. Considering even after being told that it's guild/prospectors only for Blackshield to get the ability to make said ammo too.

So either give them the ability to at least somehow restock the rubber mags or just straight up replace it with either PPV (already can see why this won't happen) or Grease Gun which is at least solid and you can get ammo for it easily.

As for the whole well they got webbings, could just remove them, marshals used to start with 0 webbings and did fine for most part even without them, the pouches allow you to better manage ammo and grenades (at least from my experience).

**Comment by Lamasmaster** [comment]
Removed the 2 webbings from marshals since unknown to me at the time you can just shove most of your equipment into the regular belt unlike the webbing so it's better either way.

PPV replaced the thompson with it now being able to use stick magazines alongside drums (still starts with only sticks) since it's .35 SMG and marshals can actually feasibly get ammo for it unlike the alternative.

**Comment by Dongels** [comment]
My question now is; Why are you deleting the [icons/obj/tools.dmi = rcd_excelsior_mlem] ?

**Comment by Kazkin** [comment]
I'd like a full summary of the changes, nothing stands out as an issue though. Still a bit unsure on giving officers ammo pouches though.

**Comment by cdb-is-not-good** [comment]
i'd call the ammo pouches a whatever but it's also a whatever. We can buy 'em for like 75c from the portable armory(I always do. It's a small cost.)

**Comment by Lamasmaster** [comment]
> My question now is; Why are you deleting the [icons/obj/tools.dmi = rcd_excelsior_mlem] ?

Because it's something that wasn't supposed to even be in files, it was the original excelsior RCD color scheme I kinda forgot to delete it.



> I'd like a full summary of the changes, nothing stands out as an issue though. Still a bit unsure on giving officers ammo pouches though.

Makes 'Gear' lasgun lose burst fire mode and increase it's fire delay by 0.5 but now it has both 'Stun' and 'Lethal' modes.

PPV can take stick magazines alongside drums and replaces thompson for marshals (they don't get drums in the loadout).

Vendor is just rearranged so the pistol mags are on top and longarms at bottom.

'Gear' and 'Sunrise' loadouts get 1 more cell with tubular, State gets tubular too but rest of the loadouts get ammo pouch.

Removed the 2 webbing in marshal prep.

Think that's all  the changes unless I missed something but I don't think I did. The ammo pouches you can just buy from the vendor for almost nothing so it's more matter of convinience at that point and tubular is more just making it equal to the blackshield kit which has it tool.

**Pull request merged**
