### PR TITLE
4x records size increase

### PR DESCRIPTION
**Pull request by Dimasw99**
## About The Pull Request
Requested feature for the HRP nerds

Character description and records length increase from 4096 to 16384

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
YES YES YES

**Comment by Trilbyspaceclone** [comment]
What happends if you print a max langth record?

**Comment by cdb-is-not-good** [comment]
Actually, can you.also.do this for flavor text?

**Comment by Lamasmaster** [comment]
> What happends if you print a max langth record?

This might just print as much as it can then stop if I had to imagine since the paper lenght is way shorter

**Comment by Dimasw99** [comment]
> Actually, can you.also.do this for flavor text?

Pushing commit in a sec

**Comment by cdb-is-not-good** [comment]
Ready to merge imo

**Comment by Trilbyspaceclone** [comment]
What happens if you use a printer to print the records byond what the paper limit is?
Does it bypass that?

**Comment by Dimasw99** [comment]
> What happens if you use a printer to print the records byond what the paper limit is? Does it bypass that?

Digging through the code it seems that printing super long records should be fine since I see no text limit in the print paper proc or that it adjusts the free space of papers, allowing for extra writing. Tho I would still test it locally proper when I have the time

**Comment by Dimasw99** [comment]
> What happens if you use a printer to print the records byond what the paper limit is? Does it bypass that?

Ok yeah, seems like the best solution would be just to edit paper len to be bigger and undo the attempt at making a records define. Are we ok with that?

**Comment by Trilbyspaceclone** [comment]
kinda

**Pull request merged**
