### PR TITLE
SMES -> TGUI (yet another guild buff, trust me)

### PR DESCRIPTION
**Pull request by Dissentbay**
## About The Pull Request
<details>
<summary>

- all SMES now use TGUI
- ghosts can't interact since it's an issue in our TGUI or mob code or onclick...making ghosts have UI_update on interact with TGUI is harder than you'd think
- now all numbers update and show their numbers properly

</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
code: SMES now use TGUI, missing parameters to the UI are now fixed

/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Allow ghosts to see into this tgui, for admins to meddle with it/investigate

**Comment by Dissentbay** [comment]
you know you're asking me to fix something who ported poorly TGUI caused, right?

**Comment by Dissentbay** [comment]
image
also investigate works as intended

**Comment by Dissentbay** [comment]
and from what i've tried so far, we are better rebasing to TG to make it work, our mobcode/_onclick/machine code is a big pileup of jury rigged stuff that long got abandoned by the original creators, because it sucks ass

**Pull request merged**
