### PR TITLE
Psion Regen Increase

### PR DESCRIPTION
**Pull request by AysheDaArtist**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
Increases Psion Regen
Tweak: Changes Psion Regen based on COG from 0.2 to 0.5, and lowers base Regen from 10 minutes to 5 minutes.  Formula has been changed to reflect, and will only allow up to a maximum of 3 minutes removed at high COG. e.g.
Small COG(10): Regen is 5-4.5 minutes per point with about 1-2 psi points Large COG(100): Regen is 2 minutes per point with about 10-12 psi points

QoL
These values can easily be tweaked.  Tested for speed and still feels slow, but more balanced to let a psionic recharge faster if they're focusing Cog.  Allows non-Soteria focused psions to have an easier time regen without Cerebrix.
/:cl:

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
I personally dislike this and would rather it be more linked with progression from equipment or mob drops

**Comment by cdb-is-not-good** [comment]
> I personally dislike this and would rather it be more linked with progression from equipment or mob drops

Suppose one could make it so psions can eat cog oddities to gain extra Regen, but ah- I dunno. I don't mind this pr, it gives more reason to actually care about cog as a psion which many ...still just dump in favor of gaming cog other ways

**Comment by AysheDaArtist** [comment]
This is fine to close, simply made to be a better PR of https://github.com/sojourn-13/sojourn-station/pull/4680 for the sake of a player.

This was tested, and having 10 psi points max with a 2 minute cooldown between them doesn't make it anymore effect than having a havlock with rubbers.

I'm perfectly fine playing Soteria CRO using fireballs and mocking everyone else locked out of such.

**Comment by cdb-is-not-good** [comment]
It is worth pointing out that this pr would be nice for those peasants without infinite cerebrix inhalers more than the real psion aristocracy.

**Pull request merged**
