### PR TITLE
Cleaning buff.

### PR DESCRIPTION
**Pull request by cdb-is-not-good**
## About The Pull Request
<details>
<summary>
Space cleaner now mixes into 3 units of cleaner instead of 2.
When mixing space cleaner + water, as long as there's at least 60 units of cleaner left it'll turn the entire container into space cleaner. 
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:

/:cl:

### CODE REVIEW

**Comment by DustanHache** [comment]
if this is considered a salt PR, then i feel sorry for all the janitor players out there. I’d honestly be more inclined to argue their special no-slip boots need more bio/acid damage resistance (they melted when exposed to a blob, even while wearing custodian armor)

**Comment by cdb-is-not-good** [comment]
Well, it's a salt PR inthat it's the result of salt regarding the change to sinks to not be infinite anymore.

**Comment by cdb-is-not-good** [comment]
Approved by KAzmzo

**Comment by du-top** [comment]
Whats the reasoning? 1+1=3? WTF?
And could you not sneak in a fuckload of other shit that's not even closely related to the topic of the PR?

**Comment by cdb-is-not-good** [comment]
> Whats the reasoning? 1+1=3? WTF?
> And could you not sneak in a fuckload of other shit that's not even closely related to the topic of the PR?

We've other chemicals that do this. But also the shit you think I sneaked in is just old commits because I reused an old fork on accident, that PR was already merged my dude.

**Comment by cdb-is-not-good** [comment]
The reasoning is that folks were complaining about how sinks having low pressure makes it a huge PITA to clean, but making them have infinite again would sorta nullify the need for a janitor. So this is a bit of a compromise that makes space cleaner easier to produce and allows it to be reproduced using that limited supply of water.

**Pull request merged**
