### PR TITLE
Armor surgery difficulty tweaks

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
## About The Pull Request
Requested by Chef_Doggo
Reduces difficulty_adjust to be 1/3rd of what they are. The numbers used before hand where set a little (lot) to high.
------------------
Fixes masks always being allowed

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
probably fine but maybe it should be slashed by half instead of 66%.

**Comment by benj8560** [comment]
I'd agree with CDB as well. Honestly I dont think this is needed at all. I had few issues with it personally. If your a trained doctor? tis no biggy. It's mostly relevant for self surgery. I found the system was pretty forgiving as is. Chef just a whiner

**Comment by Jul-Jul** [comment]
Tbh, I don't see an issue with the system how it is now. It makes sense from an IC perspective that you're not going to fully dressed in dirty/bloody clothing and armor while in surgery.

**Comment by Trilbyspaceclone** [comment]
> probably fine but maybe it should be slashed by half instead of 66%.

1/3 was easyer to do cuz they are all devideable by 3 rather then 2. 
But i dont care about the numbers, i just like the system

**Pull request merged**
