### PR TITLE
Adds axolotl tails and ears

### PR DESCRIPTION
**Pull request by axietheaxolotl**
## About The Pull Request

Port over from Skyrat, axolotls are cool and kino :))

	
<hr>

## Changelog
:cl:
add: Axolotl tails and ears.
/:cl:

### CODE REVIEW

**Comment by axietheaxolotl** [comment]
closing this 'cause I'm making axolotls more indepth

**Comment by axietheaxolotl** [comment]
image

woot axolotl

**Review by Trilbyspaceclone — APPROVED** [review]
Catto approval

**Comment by Kazkin** [comment]
New content from a new developer. Can someone test and verify this? I was going to do it myself today but I only got an hour before I need to spend time with my family.

**Comment by Trilbyspaceclone** [comment]
Its tested by the dev as shown in that screenshot.

**Pull request merged**
