### PR TITLE
Rebalances Text Chat

### PR DESCRIPTION
**Pull request by Trilbyspaceclone**
Hey /SoJ/ Its me again, ya cat back at it with Satan down in hell, plotting against storage some more leads to the greatest ideas 

So Ive noticed that the game is to easy to read and get logs for, this simple can not stand well we have "higher pop" making people accountable, fun to play and keep on station and erp. This is a massive rebalance to not only are LRP shitters but are HRP ERPers being both the best worlds in this matter

The crys for runechat has been heard, and given 0 creedence and will to even allow such LRP text chatting making me choice this better middle ground for people as it adds in Scroll Chat, the much better system for are gameplay, lore and sytle of players we wish to have.

### CODE REVIEW

**Comment by nikothedude** [comment]
do not load this locally you will cry

**Comment by Trilbyspaceclone** [comment]
Ye local cash means the first boot will always fails as it has to re-index iirc

**Comment by Trilbyspaceclone** [comment]
should be fine on main server tho

**Comment by Dongels** [comment]
Huh I actually really enjoy this idea. Great idea Trilby! :+1: The players will <3 it!

**Comment by MSieghardt** [comment]
Looks good to me. Merge and update.

**Comment by cdb-is-not-good** [comment]
>:T

**Pull request closed without merging**
