### PR TITLE
fixes #4690: update icon of mop bucket in cart when it goes empty

### LINKED ISSUE #4690: Mop bucket sprite not updated when empty
When the mop bucket is empty, the sprite will only be updated if you, for example, put the mop back in. It just having 0 contents won't update the sprite.

### PR DESCRIPTION
**Pull request by du-top**
## About The Pull Request
<details>
<summary>
	Updates the icon of the mop bucket in a janitor cart when it goes empty
</summary>
<hr>
When water is removed from a mop bucket while it is attached to a janitorial cart, the icon will be updated. If the bucket is empty, it will show the empty bucket.
A similar fix was done for the mop bucket when it is _not_ attached to a cart.

	
<hr>
</details>

## Changelog
:cl: dutop
fix: Show empty bucket icon when taking the last water from bucket in janitorial cart

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Huh- did I not fix that already

**Comment by du-top** [comment]
@cdb-is-not-good I've added comments to the linked issue. I described the problem wrong (or the wrong problem)

**Comment by cdb-is-not-good** [comment]
Ah, gotcha. Is this all tested and working? In the future if a new thing pops upin a closed issue report just gimme a poke and ill look.

**Comment by du-top** [comment]
Tested by filling the mop bucket with 20 water and attaching it to the janitorial cart. Clicked with mop a few times (4, I guess, 5 per swosh), bucket is displayd as empty.
Didn't want to poke you for something that I worded poorly in the first place.

**Comment by cdb-is-not-good** [comment]
It's okay, I'll take your word for it and go ahead and fix it.

**Pull request merged**
