### PR TITLE
Revert Soul Hunger damage back to toxins to stop burning cultist faces

### PR DESCRIPTION
**Pull request by Shirumic**
## About The Pull Request
<details>
Reverts the 5 burn damage changed unannounced in the Erismed pr back to the 10 toxin damage it was originally.
<summary>
	Changes the fire damage from the Soul Hunger litany back to the toxin damage used previously
This makes it so soul hunger can be healed by Cahors again (run out of food on a pilgrimage? drink in wine and trust in faith) as well and prevents church followers from having a litany that can render their face unrecognizable.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
balance: Changes the fire damage from the Soul Hunger litany back to the toxin damage used previously
This makes it so soul hunger can be healed by Cahors again as well and prevents church followers from having a litany render their face unrecognizable.

/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Toxin damage doesn't work like it used to. This likely essentially nullifies the downside of the litany.

**Comment by benj8560** [comment]
likely rather easy to just have it add 5 or even 2u of basic toxin into your blood and boom a problem. Or perhaps a unique church version of toxin. Then make Cahors remove said toxin from the blood

**Comment by cdb-is-not-good** [comment]
> likely rather easy to just have it add 5 or even 2u of basic toxin into your blood and boom a problem. Or perhaps a unique church version of toxin. Then make Cahors remove said toxin from the blood

That's what I'd recommend, yea. Probably go with the latter. Make a new chem akin to the other church chems but give it CE_TOXIN

**Comment by SingingSpock** [comment]
I'm currently working on a full rework of litanies, it'd be easier for me to just incorporate the intent of this PR than to deal with the conflict that'd happen (or risk me forgetting and overwriting this)

**Comment by Trilbyspaceclone** [comment]
its better if @SingingSpock does their rework and handles the rebalance of this one.

**Pull request closed without merging**
