### PR TITLE
Parry and Bracing

### PR DESCRIPTION
**Pull request by Lamasmaster**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>

So I was wondering why parry isn't really a thing overall and found out that we actually never had that system to begin with other than on shields and swords (even there it didn't really work)

Requires either 40 robustness or a perk (in new background) and to be wielding a weapon that supports it (right now only swords, daggers and tonfa) on harm intent.

Makes bracing only work on harm intent so you can put weapons onto tables like a normal person again.
<hr>
</details>

## Changelog
:cl:
balance: Parry
fix: Bracing
/:cl:

### CODE REVIEW

**Comment by MSieghardt** [comment]
I say we don't merge this. This makes robustness too strong. There would be zero incentive to use a shield when blocking with a shield takes hallos damage where as high enough robustness would mean 100% chance to parry without any detriment.

**Bad**

**Comment by Trilbyspaceclone** [comment]
I disogree with adding in stats to increase flat nullification of attacks.

**Comment by Lamasmaster** [comment]
The plan initially I had was add it so instead of blocking 100% damage and getting hallos damage only parrying 60% and rest letting throught now and/or putting bigger strain on the weapon itself so even if you parry consistently your weapon will kick the bucket pretty fast. Those are still ideas it's why this is a draft not a PR, don't expect it to get merged since most weapons still can't even use the function.
As for it scaling it with robustness, if I removed that I would need to up the base parry chances on the weapons, but the requirement for it should stay at least that's how I see it, not everyone needs to know how to parry.

**Comment by cdb-is-not-good** [comment]
Is this still being worked on or can it be closed? It's been languishing for half a month now

**Comment by Lamasmaster** [comment]
Probably not anytime soon to be honest.

**Pull request closed without merging**
