### PR TITLE
Hard case storage buffing

### PR DESCRIPTION
**Pull request by benj8560**
Pretty much improves the storage the density of specialized hard cases across the board. Generic hard cases untouched cos their already pretty epic. All my own numbers but I did look at Eris's buff to these for vague idea where to start.  Overall much better choice then filling your bag with 10 medium pouches. 

Med hard case can now hold 50% more medical stuffs. Pretty much a combat medkit with some extra room for bandages. It can also now hold _most_ Surgical tools. Become a walking medbay today.

Ammo hard cases now use slot based storage having 14 slots. They can however only hold small items. Good for 12mm enjoyers! Or those stuck using a crafting station.  Higher ammo density then most big ammo boxes just much more annoying about it.

Parts hard cases now use slot based storage. 20 slots! Woh! Can however only hold small items as well. No 20 large power cells thanks. Pretty much a annoying small RPED in terms of capacity. 

Tools hard case given 50% more storage. Pretty much a better toolbox! Just a very annoying toolbox.

Scrap cases no longer have less storage. Their debuff is looking like a hobo and the extra steel cost.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
Probably fine. Hardcases are and have been essentially useless owing to not having any serious advantages over regular storage but carrying pretty serious downsides.

**Comment by Trilbyspaceclone** [comment]
i dislike the heavy nerf to the eletronics hardcase

**Comment by benj8560** [comment]
explain in what way its a heavy nerf? The only thing remotely nerf like is only allowing small items. Their best use case and primary intended use case is parts, computer parts, gun parts. All small items

**Comment by benj8560** [comment]
I did not want to allow medium sized items due to the existence of large cell weapons. Being able to packrat 20 large church power cells is absurd.

**Comment by cdb-is-not-good** [comment]
Why not just keep it at medium size items but exclude large cells?

**Comment by benj8560** [comment]
Because the engi case covers the medium items this used to hold in a more balanced fashion.

**Comment by benj8560** [comment]
List of medium items it could hold from memory: large power cells, welding fuel canisters, welding helmet.

 The other case can hold these as well. I'd rather not see stupid things like someone with 20 fuel canisters stuffed into there hard case. This is intended to hold parts and it does really good job of that

**Comment by Trilbyspaceclone** [comment]
the size change from holding lot more more to 14 is what im against

**Comment by benj8560** [comment]
it used to hold 7 or maybe 8 small parts. It how holds 20

**Comment by benj8560** [comment]
I dont see ur point feline. Explain exactly whats been nerfed please.

**Comment by benj8560** [comment]
ammo case holds 14. Are you talking about the ammo case? Ammo cases used to hold around 7-8 packets as well. 14 puts them more inline with big boxes. Stuff your hardcase with 14 packets and you have more ammo compared to a big box. This is mostly for 12mm/crafting station sufferers.

**Comment by cdb-is-not-good** [comment]
Seems fine tbh. If we wanna nerf this later we can consider that but for now it seems fine in its current state.

**Pull request merged**
