### PR TITLE
Remove the mapped ameridian crystal.

### PR DESCRIPTION
**Pull request by r4d6**
## About The Pull Request
Since apparently, the ameridian crystal field that Lonestar start with is causing so much trouble. I'm removing it.
From now on, _**any**_ ameridian is the fault of a player that started a new field and didn't bother about making sure it didn't go out of control.

### CODE REVIEW

**Comment by Trilbyspaceclone** [comment]
Please be sure to have this approved by Lich and Pinkest

**Comment by nikothedude** [comment]
Can we please not do this? These kinds of PRs made out of bitterness and discourse never go well in literally any codebase.

**Comment by Medizeal22** [comment]
Approved.

**Comment by r4d6** [comment]
> Can we please not do this? These kinds of PRs made out of bitterness and discourse never go well in literally any codebase.

Sure thing, but I would prefer if this PR get merged rather than https://github.com/sojourn-13/sojourn-station/pull/3896
If the other one get closed, then I can close this one too.

**Comment by cdb-is-not-good** [comment]
Technically any failing of the field is already caused by player error. The field can only fail if someone fucks with the SMES or no one sets up power.

**Comment by Dongels** [comment]
> 

Grid checks yah nerd. They get free and break stuff after it happens.

**Comment by r4d6** [comment]
> > 
> 
> Grid checks yah nerd. They get free and break stuff after it happens.

1. I mapped this before we got grid checks back.
2. The Shield Generators are directly wired to the SMES, not remotely powered by an APC.

**Pull request closed without merging**
