### PR TITLE
Gives salvagers combat gloves in their locker

### PR DESCRIPTION
**Pull request by DerFlammenwerfer**
## About The Pull Request
<details>
<summary>
	About The Pull Request
</summary>
<hr>
For some reason, the combat role gets free shock-proof work gloves instead of the role that might actually need them for digging through trash piles. This fixes the problem.

	
<hr>
</details>

## Changelog
:cl:
fix: Salvagers now get combat gloves in their lockers, for safely digging through trash.
/:cl:

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
I might recommend taking the combat gloves away from prospectors to give to Salvagers.

**Comment by DerFlammenwerfer** [comment]
> I might recommend taking the combat gloves away from prospectors to give to Salvagers

And I will refuse your recommendation if you do. Just like the salvaged armor and helmet, these gloves should be considered part of the Prospectors' standard equipment. All other Prospector roles have them, there's no reason for Salvagers to be left out, or to trade one problem for another.

**Comment by king5327** [comment]
I'm gonna peg this as good to merge. Maybe Salvagers shouldn't have combat gloves but is it that big a deal?

**Comment by cdb-is-not-good** [comment]
Its honestly fine, it's whatever. They're just fancy insulated's.

**Pull request merged**
