### PR TITLE
Lamasmaster - Assorted Gun Changes

### PR DESCRIPTION
**Pull request by Ryan180602**
## About The Pull Request
<details>
<summary>
	Lets a few guns have parts for decon and recon, makes the Watchtower be constructable from Strelki, removes the PPV and officiates the PPSH's ability to take stick magazines. Contact Lamasmaster for questions.
</summary>
<hr>

	
<hr>
</details>

## Changelog
:cl:
tweak: Removed PPV
tweak: Watchtower can be made from Strelki parts (needs rubber grip)
tweak: Fixed PPSH description to reflect that it can take stick magazines
tweak: Bulldog/Pitbull have parts now
tweak: Frontier/Cowboy have parts now
/:cl:

### CODE REVIEW

**Comment by Lamasmaster** [comment]
PPV entire niche was A. marshals started with this B. it can take sticks while the base PPSH can't, A got removed in favor of freedom, B is irrelevant since someone added stick mags to base PPSH, in what world would you want to use this thing over simply ekaterina, it's a bloat weapon now sadly

**Comment by benj8560** [comment]
There was a lot of guns removed under the belief of "bloat" people usually just end up complaining why is my favorite gun gone. I'm pretty sure it has better damage stats over the other as well? We generally moved away from gun bloat = bad. There's no real negative to having them

**Comment by benj8560** [comment]
A lot of guns removed that we have been slowly adding back is what I'm getting at

**Comment by Lamasmaster** [comment]
Trust me you lose absolutely nothing removing the PPV, ekaterina barely sees any use as is and that gun is miles better in comparison. Call it confirmation bias but I am yet to see anyone consciously pick up any of the PPSHs and I haven't seen a single complaint about it either.

**Comment by benj8560** [comment]
pretty much what Yatiyaya said. Its okay to just have guns for the sake of having a gun and not much more. It is marginally better then the other. This gun has a more meaningful differences compared to many many other examples of side grades some we have just recently readded for little other reason then one person asking if they could have their fav gun re-added

**Comment by Trilbyspaceclone** [comment]
Handled in a new pr

**Pull request closed without merging**
