### PR TITLE
Everyone's (un)favorite QoL patch number...

### PR DESCRIPTION
**Pull request by ThePainkiller**
## ...Who knows. I lost count!

- **EDIT:** Removes all ranks from the accessory lockers. Adds Blackshield patches, blank and recruit patches (not ranks) to the accessory locker. Adds Trooper and Corpsmen armband to formal attire box.
- Lowers the NSA buildup of Sanguinum as it was impossible to mix with painkillers under dire circumstances, making triage on the field a massive pain. Might still be not enough for those that are Sol Born, but it helps.
- Fixes bad centering on the sprites of the Abnegate, Format Bound, Humility and System Cost guns
- Fixes rogue sprite on black cloak accessory
- Adds Atomic Coffee, a very strong variant of coffee with strong effects but lower overdose threshold and a danger to health if you overdrink. An existing drink yet a homage to a very cataclysmic scenario, perfect for the colony's dark days ahead. Sprites by yours truly as well! It is crafted by combining 1 unit of liquid Uranium with 30 of espresso for a full glass!

atomicoffee

- On high demand, brings back Blattedin purge to Dylovene, extending it to Carthatoline as well, since it was becoming a massive pain for Soteria and Prospectors alike.
- Rezadone overdose lowered to 12 units maximum (REAGENTS_OVERDOSE * 0.4), since it's a chem you should apply on measured doses.
- INAPROVALINE REWORK!!! No longer an incredibly useless and full RP flavor chem due to baycode leftovers (and lack of a proper pulse system affecting heart attacks and the like), Inaprovaline now includes a very weak clotting effect, staving off oxyloss for a while as it's on your system, making it a true stabilizing chemical for emergencies well worth being on your starting survival boxes and useful to buy time while you wait for rescue to come. It retains its pulse stabilizing and painkiller effects for pure flavor issues.
- Changes the NT from the holobadges' sprite to erase NanoTrasen reference into NC (Nadezhda Colony), as well as an "M" for Marshal instead of the Nanotrasen "N"
- Adds alternate cat ears markings that are stylized, combed-back ears to accomodate for better blending with berets and caps (TODO: Make hide tail verb actually work, fix ears overlay over most non-helmet headgears, add propper wagging system to start and stop tail animations)
- All trauma kits variant (including corpsman) can now hold Stasis bags, as initially intended.
- Added dead sprite states for the Robot Chicken and E-N, as they turned invisible once dead due to lack of one.
- Animated capes (Janitor, CBO, Miner) added to their respective lockers

<hr>

## Changelog
:cl:
add: Added Atomic Coffee. Mix 1 units of Uranium + 30 of espresso for a full glass (0.1 + 3). Wakes you up forever and is the perfect sobering drink, just don't overdose or your heart will pay for it! Homage to a certain cataclysmic event. Atomic Coffee Maker not included.
del: Removes all ranks from the accessory lockers. Adds Blackshield patches, blank and recruit patches (not ranks) to the accessory locker. Adds Trooper and Corpsmen armband to formal attire box.
tweak: Rezadone overdose threshold lowered to 12 units maximum (Formula is 30 * 0.4, so Sol Born people will have even less)
tweak: Made espresso a slighter stronger version of coffee effects
tweak: INAPROVALINE REWORKED! Now it truly acts as a stabilizer chem by clotting minor wounds and providing a small artificial window of breathing if you're choking from hypovolemic shock. Don't forget to use yours from your internals box if you're in a dire situation and it might buy enough time for paramedics to save you!
balance: Sanguinum NSA buildup lowered to make it able to combine with at least Tramadol without puking your stomach out.
fix: Due to popular petition, Dylovene purges Blattedin once more. Added (stronger) blattedin purge capabilities to Carthatoline as well, making it a straight upgrade worth mixing.
fix: Forgot to make all trauma kits variants (Large and small, and Corpsman too) to be able to hold stasis bags, so now they do!
imageadd:  Fixes bad centering on the sprites of the Abnegate, Format Bound, Humility and System Cost guns. Adds Atomic Coffee animated sprite. Fixes rogue pixel on black cloak accessory. Adds alternate cat ears sprites. Adds dead state sprites for E-N (the borg corgi) and the Robot Chicken.
/:cl:

### CODE REVIEW

**Comment by Dopiotl** [comment]
How different is your new inaprovaline from dexalin or dexalin-plus now?

**Comment by Dopiotl** [comment]
I ask because, " staving off oxyloss for a while as it's on your system", isn't that's the job of dexalin / dexalin-plus, and a straight corpsman buff?

**Comment by ThePainkiller** [comment]
> How different is your new inaprovaline from dexalin or dexalin-plus now?

The oxyloss heal from it is negligible enough to not justify dosing just to heal it (three times weaker than dexalin) 
Dexalin and Dexplus purge lexorin as well, which causes oxyloss, making it a chem for specific cases of lack of oxygen, rather than being a stabiliser chem. Since we lack a proper pulse system helping blood flow and heart attacks, this is mechanically the closest you can get to a "please just ten more seconds of life until I get medical attention" of a fix you'll get. I'm still partial to remove the heal (which I added with syrettes in mind, mind you, to counteract the initial bloodloss oxyloss spike) and leave the oxygenated trait in, if it staves off oxyloss buildup. 
Dexplus heals muscles as well, and they're both meant to heal oxygenation damage, not outright treat the ailments that cause such conditions, as untreated bloodloss still kills from organ damage.

>straight corpsman buff

How? And why specifically Corpsmen? **Everyone**, even outsiders, come with a 5u syrette of inaprovaline, this is making it an actual helpful thing to have for emergencies on a mere five units until proper medical aid arrives rather than an item most throw away for the sake of inventory space because it's mechanically the same as a less potent paracetamol pill.

**Comment by Dopiotl** [comment]
People above 100 combined damage are in shock, and need inaprov to be stabilized, it's the one thing it doe and it does it very well, it's not a RP chemical, and people discarding it for inventory space are sacrificing something that might just save someone from revival sickness and it's meaningless debuff

I believe it's just fine where it is and should not be powercreep'd into 'dexalin-minus'

It is as if when you really want dexalin, you can already, and really should instead, just trade some :v

**Comment by ThePainkiller** [comment]
> People above 100 combined damage are in shock, and need inaprov to be stabilized, it's the one thing it doe and it does it very well, it's not a RP chemical, and people discarding it for inventory space are sacrificing something that might just save someone from revival sickness and it's meaningless debuff

While `CE_STABLE` will make you not choke (mechanic made to force you into combined damage enough to kill you) while you are in crit, that is the only thing it does so far, the fact remains that untreated bloodloss (which has been the lead cause of death as of late) can and very much **will** start accumulating fixed oxyloss in you due to internal organs not receiving enough blood, an effect shared by both heart **and** lungs, not to mention how this also affects the brain, hence the clotting aid (which mind you is at the same potency as...autohealing very minor wounds still, but I didn't want to make a starter chem so universally good. It'll require further trial to see if it even aids considering fatal bloodletting wounds might not be affected by it), and for this, Inaprovaline does *nothing*. And nobody has easy access to quicklot (despite absurd RNG loot rate on quicklot syrettes here and there), a chem that merely exists as a middle ground clotting agent (already powercrept by peridaxon on fixing veins anyways) when bandaging and tricordazine are a thing that exists.
People at more than -50 health are also on paincrit that inaprovaline does nothing to improve upon with that weak as hell painkilling effect, and cannot self apply that inaprov syrette as well.

> I believe it's just fine where it is and should not be powercreep'd into 'dexalin-minus'

I have never found a situation in which I thought "I gotta get inaprovaline in this dude/myself" (**IN ERISMED**) first and foremost as any non-medical-ready job in all my personal experience, hell with the changes to bloodloss I'd rather rip clothes into bandages to patch those first and foremost and then apply the inaprov syrette only if they start gasping. Bleeding > chemical stabilization in terms of priority. In fact it's more of a _"quicklot-minus powercreep"_ than anything since dexalin still does the job its supposed to do, which is outright treating oxyloss damage (generally the thing I slap on someone who just died to bloodloss and has over 100 oxyloss), a thing not even this PR can dethrone it from (1.5 oxyloss adjustment on dexalin, whereas this gives inaprov a 0.5, it won't outheal bloodloss-induced oxyloss at all). You can consult with most of the medically inclined playerbase and prospectors/outsiders if their inaprov syrettes or syringes found on the field have ever helped them survive enough, or if it wasn't actually their own Human perk or Tricordazine granting blood clotting what saved them from bleeding/choking to death. Like a certain Foreman, whose corpse I had to drag back with 17 inaprovaline (at his time of death) in him, and still accumulated oxyloss enough to get him killed with a mere ~50 brute.

It was either making inaprovaline actually useful, or honestly exchange every survival's box syrette from inaprov into quicklot, because a quick clotting agent will be leagues more useful than a chem that merely lets you "not choke when at -50 HP or less". Decided to give my medical experience a spin rather than taking the lazy route here... :^|

**Comment by cdb-is-not-good** [comment]
>Adds present in code yet unused ranks and patches to all Blackshield formal attire boxes for the sake of drip, including alternate title ones. Don't take it as an excuse for milrp cringe!

these were removed for a reason.

>Adds a box of blank ranks, and blank/volunteer patches to the blackshield wardrobe for the sake of consistency, and to distinguish fresh recruits from the bulk!

kinda neat tho.

**Comment by ThePainkiller** [comment]
> these were removed for a reason.

The "militia" change was ages ago, yet there are (coded and sprited) ranks for alternate titles, which aren't as old as the de-militarization of blackshield, it kinda got me wondering if people just forgot to allocate them anywhere for a reason...
I figured that between that, and the fact there **are** still trooper ranks on the accessory wardrobe, why not do the same for the rest of the ranks :>

**Comment by cdb-is-not-good** [comment]
> > these were removed for a reason.
> 
> The "militia" change was ages ago, yet there are (coded and sprited) ranks for alternate titles, which aren't as old as the de-militarization of blackshield, it kinda got me wondering if people just forgot to allocate them anywhere for a reason... I figured that between that, and the fact there **are** still trooper ranks on the accessory wardrobe, why not do the same for the rest of the ranks :>

No like - the tabs were left after the militia change. I went through and fully removed them later(but it sounds like I missed some.). I don't think adding these back in is a good idea, especially not with this latest influx of Hestia people who historically have been the worst offenders for the milsim OORAH YES SIR stuff.

**Comment by cdb-is-not-good** [comment]
there's another issue i just noticed looking at the code. You...gave...the Brigadier, the faction leader of the shields pips to the CO. That...no. Just no.

**Comment by ThePainkiller** [comment]
> there's another issue i just noticed looking at the code. You...gave...the Brigadier, the faction leader of the shields pips to the CO. That...no. Just no.

I legit just realized that was supposed to be exclusive to, y'know, the literal faction leader and not the commander, my bad, my horrible bad.

**Comment by ThePainkiller** [comment]
>I don't think adding these back in is a good idea, especially not with this latest influx of Hestia people who historically have been the worst offenders for the milsim OORAH YES SIR stuff.

Yep this has finally let me see the light, nope, big nope, I'm also removing the trooper ranks from the locker if you want me to

**Comment by cdb-is-not-good** [comment]
I'd appreciate it - i was going to put it on the list for my next PR. That said, maybe we should figure out something for the shield. Marshals have our funny lil badge, and a symbol of office wouldn't be out of place - just...no...rank boards, please god.

**Comment by ThePainkiller** [comment]
> I'd appreciate it - i was going to put it on the list for my next PR. That said, maybe we should figure out something for the shield. Marshals have our funny lil badge, and a symbol of office wouldn't be out of place - just...no...rank boards, please god.

Would patches at least suffice? I doubt they would induce any kind of military feeling to it, since people can already pick up armbands from loadout and makes almost no difference.

**Comment by cdb-is-not-good** [comment]
Yea i think we actually HAVE some blackshield patches - they have one arm patch and one band for the Corpsmen. something like that could stand out decently well and allow at-glance identification

**Comment by cdb-is-not-good** [comment]
might need some others since we do have some alt titles but i'm sure someone could scare up sprites

**Comment by cdb-is-not-good** [comment]
Spoke to Kavrick a bit and got some little shoulder-mantles as so. Take a peek 
image

**Comment by ThePainkiller** [comment]
> Spoke to Kavrick a bit and got some little shoulder-mantles as so. Take a peek image

These are actually fucking great, even though I'm a bit iffy about pure white being too out-of-tone with the general Blackshield vibe (Much like how the Corpsman cape looks more Soteria than Blackshield...), something more sober with the usual blue cross would be better IMHO
If you can send me the DMI's and their preferred names, I'll add them to this PR to save us all time

**Comment by cdb-is-not-good** [comment]
the white one specifically is for Corpsmen - theyre already included in my PR, i was careful to make sure that one wouldn't cause conflicts with this one tho!

**Comment by ThePainkiller** [comment]
> the white one specifically is for Corpsmen - theyre already included in my PR, i was careful to make sure that one wouldn't cause conflicts with this one tho!

Greatly appreciated, but `wardrobe.dm` is gonna end up conflicting for us since I modified it to remove the ranks and place the patches and box of blanks on `/obj/structure/closet/wardrobe/militia/accessory`, line 262. Maybe it'll be best if I pull back the changes to it and you delete the ranks from `/obj/structure/closet/wardrobe/militia/accessory` on your pr

**Comment by cdb-is-not-good** [comment]
Ah ye, i suppose that could work - my brainless dumbass self thought "Oh ill put them in the individual lockers for each trooper so it wont conflict!" then made changes to the wardrobe.dmi :V i can just remove the pips on my PR, ye

**Comment by Kazkin** [comment]
Conflicts, other than that, good to merge when fixed.

**Comment by ThePainkiller** [comment]
Conflicts solved, should be ready by now

**Comment by Kazkin** [comment]
More conflicts due to people adding more sprites.

**Comment by ThePainkiller** [comment]
Fixed again...

**Comment by ThePainkiller** [comment]
Done for now, not adding more, just hope it doesn't conflict with any other PR now

**Pull request merged**
