### PR TITLE
Soteria+ Cosmetic Upgrade (Not limited)

### PR DESCRIPTION
**Pull request by GlitchySoftware**
image
(The first change as of now, will continue posting in comments)

Giving Soteria more content and some redesigning to areas to make them feel more comfortable.

### CODE REVIEW

**Comment by GlitchySoftware** [comment]
Added blast doors to most entrypoints into soteria research except the ones where its bordering medical wing

**Comment by GlitchySoftware** [comment]
image

**Comment by GlitchySoftware** [comment]
image
image

**Comment by GlitchySoftware** [comment]
image
image
image
image
image
image
(added a few more roach clusters to the hallway)

**Comment by Trilbyspaceclone** [comment]
beds for heads bad

**Comment by GlitchySoftware** [comment]
> beds for heads bad

No more russian sleep experiment on CROs!!!

**Comment by GlitchySoftware** [comment]
image
image
added a canteen and medical section

**Comment by benj8560** [comment]
dreamseeker_d3ZVCo42yG

this is not how offsets work :P

**Pull request merged**
