### PR TITLE
Turrets projectile lim ammo fix

### PR DESCRIPTION
**Pull request by TOBKA4**
## About The Pull Request
<details>
<summary>
	Tested Limited ammo projectile turrets on the main server. They are barely shooting and ignoring some mobs include half or more of the roach faction. Which is most frequent enemy in colony. Now they shoot everything according their settings which is described in code and can't be changed in game by players. Also. Downloaded Master branch and had troubles to compile it due error in mutable_appearance.dm. Fixed that too.

</summary>
<hr>

https://github.com/user-attachments/assets/e5091e52-677a-4440-9b88-0b6ab1e65a29

<hr>
</details>

## Changelog

:cl:
Fix: All projectile turrets (3) with limited ammo now shoots mobs properly 
Fix: Unknown proc trouble on compile from master branch in mutable_appearance.dm file
/:cl:

### CODE REVIEW

**Comment by TOBKA4** [comment]
Good. Some error. Time to try and solve them

**Comment by TOBKA4** [comment]
Strange. Now it fixed.

**Review by TOBKA4 — COMMENTED** [review]
Checked again. Just forgot to close the comment. 
Compile: Successfull
Turrets ingame: Works

**Comment by Trilbyspaceclone** [comment]
This change makes turrets endlessly shoot at walls if they see them as well as does not complie on 514 (thats what the github verson is) meaning that it will not make other pr's post this complie properly eather.

Not against the idea of buffing turrets or making them target more smartly but not with a github version change

**Pull request closed without merging**
