### PR TITLE
French Toast

### PR DESCRIPTION
**Pull request by Luxyleathehat**
Adds in French Toast into available microwavable recipes.

### CODE REVIEW

**Comment by cdb-is-not-good** [comment]
2 questions. 1 is this tested and 2. why microwave  craft instead of regular kitchen?

**Comment by Luxyleathehat** [comment]
> 2 questions. 1 is this tested and 2. why microwave craft instead of regular kitchen?

Yes it is tested

**Comment by cdb-is-not-good** [comment]
im exercising executive jurisdiction to fastmerge this. good PR

**Comment by du-top** [comment]
Despite one of two questions unanswered? Huh.

**Comment by cdb-is-not-good** [comment]
despite it also not compiling because the bastard missed a parenth and i foolishly forgot to run the checks

**Comment by cdb-is-not-good** [comment]
and commas.

**Pull request merged**
